scala_library(
    namelon = "bq_gelonnelonration",
    sourcelons = [
        "**/*.scala",
    ],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "belonam-intelonrnal/src/main/scala/com/twittelonr/belonam/io/dal",
        "belonam-intelonrnal/src/main/scala/com/twittelonr/scio_intelonrnal/job",
        "belonam-intelonrnal/src/main/scala/com/twittelonr/scio_intelonrnal/runnelonr/dataflow",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:offlinelon_twelonelont_reloncommelonndations_from_intelonrelonstelond_in_20M_145K_2020-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:offlinelon_twelonelont_reloncommelonndations_from_intelonrelonstelond_in_20M_145K_2020_HL_0_elonL_15-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:offlinelon_twelonelont_reloncommelonndations_from_intelonrelonstelond_in_20M_145K_2020_HL_2_elonL_15-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:offlinelon_twelonelont_reloncommelonndations_from_intelonrelonstelond_in_20M_145K_2020_HL_2_elonL_50-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:offlinelon_twelonelont_reloncommelonndations_from_intelonrelonstelond_in_20M_145K_2020_HL_8_elonL_50-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:offlinelon_twelonelont_reloncommelonndations_from_mts_consumelonr_elonmbelonddings-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/scio/bq_gelonnelonration/common",
        "src/scala/com/twittelonr/simclustelonrs_v2/scio/bq_gelonnelonration/sql",
        "src/scala/com/twittelonr/wtf/belonam/bq_elonmbelondding_elonxport:bq_elonmbelondding_elonxport_lib",
        "tcdc/bq_blastelonr/src/main/scala/com/twittelonr/tcdc/bqblastelonr/belonam",
    ],
)

jvm_binary(
    namelon = "iikf-twelonelonts-ann-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.twelonelonts_ann.IIKF2020TwelonelontsANNBQAdhocJob",
    platform = "java8",
    delonpelonndelonncielons = [
        ":bq_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "iikf-hl-8-elonl-50-twelonelonts-ann-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.twelonelonts_ann.IIKF2020Hl8elonl50TwelonelontsANNBQAdhocJob",
    platform = "java8",
    delonpelonndelonncielons = [
        ":bq_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "iikf-twelonelonts-ann-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.twelonelonts_ann.IIKF2020TwelonelontsANNBQBatchJob",
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":bq_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "iikf-hl-0-elonl-15-twelonelonts-ann-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.twelonelonts_ann.IIKF2020Hl0elonl15TwelonelontsANNBQBatchJob",
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":bq_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "iikf-hl-2-elonl-15-twelonelonts-ann-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.twelonelonts_ann.IIKF2020Hl2elonl15TwelonelontsANNBQBatchJob",
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":bq_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "iikf-hl-2-elonl-50-twelonelonts-ann-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.twelonelonts_ann.IIKF2020Hl2elonl50TwelonelontsANNBQBatchJob",
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":bq_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "iikf-hl-8-elonl-50-twelonelonts-ann-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.twelonelonts_ann.IIKF2020Hl8elonl50TwelonelontsANNBQBatchJob",
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":bq_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "mts-consumelonr-elonmbelonddings-twelonelonts-ann-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.twelonelonts_ann.MTSConsumelonrelonmbelonddingsTwelonelontsANNBQAdhocJob",
    platform = "java8",
    delonpelonndelonncielons = [
        ":bq_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "mts-consumelonr-elonmbelonddings-twelonelonts-ann-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.twelonelonts_ann.MTSConsumelonrelonmbelonddingsTwelonelontsANNBQBatchJob",
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":bq_gelonnelonration",
    ],
)
