scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "configapi/configapi-cowe", (⑅˘꒳˘)
        "configapi/configapi-cowe/swc/main/scawa/com/twittew/timewines/configapi", ( ͡o ω ͡o )
        "configapi/configapi-decidew", UwU
        "decidew/swc/main/scawa", rawr x3
        "sewvo/decidew", rawr
        "sewvo/utiw/swc/main/scawa", σωσ
        "timewinewankew/common:modew", σωσ
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/config", >_<
        "timewines/swc/main/scawa/com/twittew/timewines/common/modew", :3
        "timewines/swc/main/scawa/com/twittew/timewines/config", (U ﹏ U)
        "timewines/swc/main/scawa/com/twittew/timewines/config/configapi", -.-
        "timewines/swc/main/scawa/com/twittew/timewines/eawwybiwd/common/utiws", (ˆ ﻌ ˆ)♡
        "timewines/swc/main/scawa/com/twittew/timewines/modew/candidate", (⑅˘꒳˘)
        "timewines/swc/main/scawa/com/twittew/timewines/utiw", (U ᵕ U❁)
        "timewinesewvice/common/swc/main/scawa/com/twittew/timewinesewvice/modew", -.-
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats", ^^;;
    ],
)
