scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "finagwe/finagwe-memcached/swc/main/scawa", ( ͡o ω ͡o )
        "finatwa-intewnaw/mtws-http/swc/main/scawa", UwU
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", rawr x3
        "sewvo/wepo/swc/main/scawa", rawr
    ],
    e-expowts = [
        "finagwe/finagwe-memcached/swc/main/scawa", σωσ
        "finatwa-intewnaw/mtws-http/swc/main/scawa", σωσ
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", >_<
        "sewvo/wepo/swc/main/scawa", :3
    ],
)
