scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finaglelon/finaglelon-melonmcachelond/src/main/scala",
        "finatra-intelonrnal/mtls-http/src/main/scala",
        "finatra-intelonrnal/mtls-thriftmux/src/main/scala",
        "selonrvo/relonpo/src/main/scala",
    ],
    elonxports = [
        "finaglelon/finaglelon-melonmcachelond/src/main/scala",
        "finatra-intelonrnal/mtls-http/src/main/scala",
        "finatra-intelonrnal/mtls-thriftmux/src/main/scala",
        "selonrvo/relonpo/src/main/scala",
    ],
)
