scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "finatwa/inject/inject-thwift-cwient", òωó
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/stowe/stwato", o.O
        "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/stowe/common", (U ᵕ U❁)
        "wewevance-pwatfowm/swc/main/scawa/com/twittew/wewevance_pwatfowm/common/weadabwestowe", (⑅˘꒳˘)
        "wepwesentation-managew/cwient/swc/main/scawa/com/twittew/wepwesentation_managew/config", ( ͡o ω ͡o )
        "wepwesentation-managew/sewvew/swc/main/thwift:thwift-scawa", UwU
        "swc/scawa/com/twittew/simcwustews_v2/common", rawr x3
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", rawr
        "stitch/stitch-stowehaus", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", σωσ
    ], >_<
)
