scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "elonmailstoragelon/selonrvelonr/src/main/thrift/com/twittelonr/elonmailstoragelon/api:elonmail-storagelon-selonrvicelon-scala",
        "finatra-intelonrnal/mtls-thriftmux/src/main/scala",
        "finatra/injelonct/injelonct-thrift-clielonnt",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/clielonnts/common",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/modelonls",
        "stitch/stitch-corelon",
    ],
)
