scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/com/github/nscawa_time", (U ᵕ U❁)
        "3wdpawty/jvm/com/googwe/inject:guice", (⑅˘꒳˘)
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", ( ͡o ω ͡o )
        "3wdpawty/jvm/net/codingweww:scawa-guice", UwU
        "3wdpawty/jvm/owg/swf4j:swf4j-api", rawr x3
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/stwato", rawr
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/constants", σωσ
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", σωσ
        "fowwow-wecommendations-sewvice/thwift/swc/main/thwift:thwift-scawa",
        "swc/thwift/com/twittew/onboawding/wewevance/stowe:stowe-scawa", >_<
        "utiw/utiw-cowe:scawa", :3
    ],
)
