scala_library(
    sourcelons = ["*.scala"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/elonschelonrbird:twelonelont-annotation-scala",
        "src/thrift/com/twittelonr/timelonlinelons/contelonnt_felonaturelons:thrift-scala",
        "src/thrift/com/twittelonr/twelonelontypielon:melondia-elonntity-scala",
        "src/thrift/com/twittelonr/twelonelontypielon:twelonelont-scala",
    ],
    elonxports = [
        "src/thrift/com/twittelonr/timelonlinelons/contelonnt_felonaturelons:thrift-scala",
    ],
)
