scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    pwatfowm = "java8", 🥺
    s-stwict_deps = t-twue, òωó
    tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "swc/thwift/com/twittew/eschewbiwd:tweet-annotation-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/timewines/content_featuwes:thwift-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/tweetypie:media-entity-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", UwU
    ], rawr x3
    expowts = [
        "swc/thwift/com/twittew/timewines/content_featuwes:thwift-scawa", rawr
    ], σωσ
)
