scala_library(
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/X/storehaus:core",
        "src/scala/com/X/simclusters_v2/common",
        "src/thrift/com/X/socialgraph:thrift-scala",
    ],
)
