scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finaglelon/finaglelon-corelon/src/main",
        "finatra-intelonrnal/mtls-thriftmux/src/main/scala",
        "finatra-intelonrnal/thrift/src/main/thrift:thrift-scala",
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-scala",
    ],
)
