targelont(
    namelon = "faiss",
    delonpelonndelonncielons = [
        "ann/src/main/java/com/twittelonr/ann/faiss/swig:swig-artifactory",
    ],
)

java_library(
    namelon = "swig-nativelon-utils",
    sourcelons = ["*.java"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [],
)
