tawget(
    nyame = "faiss", (U ᵕ U❁)
    dependencies = [
        "ann/swc/main/java/com/twittew/ann/faiss/swig:swig-awtifactowy", (⑅˘꒳˘)
    ], ( ͡o ω ͡o )
)

j-java_wibwawy(
    n-nyame = "swig-native-utiws", UwU
    s-souwces = ["*.java"], rawr x3
    c-compiwew_option_sets = ["fataw_wawnings"], rawr
    p-pwatfowm = "java8", σωσ
    t-tags = ["bazew-compatibwe"], σωσ
    d-dependencies = [], >_<
)
