scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "ann/src/main/scala/com/twittelonr/ann/common",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/lib",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/lib/onlinelon",
    ],
)
