scala_library(
    sources = ["*.scala"],
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "ann/src/main/scala/com/twitter/ann/common",
        "src/scala/com/twitter/ml/featurestore/lib",
        "src/scala/com/twitter/ml/featurestore/lib/online",
    ],
)
