scala_library(
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/com/X/storehaus:core",
        "frigate/frigate-common:base",
        "frigate/frigate-common/src/main/scala/com/X/frigate/common/base",
        "simclusters-ann/thrift/src/main/thrift:thrift-scala",
        "src/scala/com/X/simclusters_v2/common",
        "src/scala/com/X/simclusters_v2/summingbird/stores",
        "src/thrift/com/X/simclusters_v2:simclusters_v2-thrift-scala",
        "util/util-stats/src/main/scala/com/X/finagle/stats",
    ],
)
