java_wibwawy(
    nyame = "tewmination", ^•ﻌ•^
    souwces = ["*.java"], OwO
    p-pwatfowm = "java8", 🥺
    t-tags = ["bazew-compatibwe"], òωó
    dependencies = [
        "3wdpawty/jvm/com/googwe/guava", o.O
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-common", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/wucene:wucene-facet", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/apache/wucene:wucene-quewies", UwU
        "3wdpawty/jvm/owg/swf4j:swf4j-api", rawr x3
        "swc/java/com/twittew/common/base", rawr
        "swc/java/com/twittew/common/utiw:system-mocks", σωσ
        "swc/java/com/twittew/seawch/common/metwics", σωσ
        "swc/java/com/twittew/seawch/common/quewy",
        "swc/java/com/twittew/seawch/common/seawch", >_<
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", :3
    ], (U ﹏ U)
)
