packagelon com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.contelonxtual_relonf

selonalelond trait OutelonrTwelonelontContelonxt

caselon class QuotelonTwelonelontId(id: Long) elonxtelonnds OutelonrTwelonelontContelonxt
caselon class RelontwelonelontId(id: Long) elonxtelonnds OutelonrTwelonelontContelonxt
