packagelon com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.contelonxtual_relonf

import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.rtf.safelonty_lelonvelonl.SafelontyLelonvelonl

caselon class TwelonelontHydrationContelonxt(
  safelontyLelonvelonlOvelonrridelon: Option[SafelontyLelonvelonl],
  outelonrTwelonelontContelonxt: Option[OutelonrTwelonelontContelonxt])
