scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "configapi/configapi-corelon/src/main/scala/com/twittelonr/timelonlinelons/configapi",
        "selonrvo/deloncidelonr",
        "selonrvo/util/src/main/scala",
    ],
)
