scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", UwU
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject",
        "3wdpawty/jvm/net/codingweww:scawa-guice", rawr x3
        "3wdpawty/jvm/owg/swf4j:swf4j-api", rawr
        "abdecidew", σωσ
        "decidew", σωσ
        "featuweswitches/featuweswitches-cowe/swc/main/scawa/com/twittew/featuweswitches/v2/buiwdew", >_<
        "finatwa-intewnaw/decidew/swc/main/scawa",
        "finatwa-intewnaw/intewnationaw/swc/main/scawa/com/twittew/finatwa/intewnationaw/moduwes", :3
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", (U ﹏ U)
        "finatwa/inject/inject-cowe/swc/main/scawa", -.-
        "finatwa/inject/inject-thwift-cwient/swc/main/scawa",
        "finatwa/jackson/swc/main/scawa/com/twittew/finatwa/jackson/moduwes", (ˆ ﻌ ˆ)♡
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", (⑅˘꒳˘)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/moduwe/pwoduct_mixew_fwags",
        "sewvo/decidew", (U ᵕ U❁)
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", -.-
        "timewines/swc/main/scawa/com/twittew/timewines/featuwes/app", ^^;;
        "utiw-intewnaw/scwibe", >_<
        "utiw/utiw-swf4j-api/swc/main/scawa", mya
    ],
    e-expowts = [
        "3wdpawty/jvm/com/googwe/inject:guice", mya
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", 😳
        "3wdpawty/jvm/net/codingweww:scawa-guice", XD
        "3wdpawty/jvm/owg/swf4j:swf4j-api", :3
        "abdecidew",
        "decidew", 😳😳😳
        "finatwa-intewnaw/decidew/swc/main/scawa", -.-
        "finatwa-intewnaw/intewnationaw/swc/main/scawa/com/twittew/finatwa/intewnationaw/moduwes", ( ͡o ω ͡o )
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", rawr x3
        "finatwa/inject/inject-cowe/swc/main/scawa", nyaa~~
        "finatwa/inject/inject-thwift-cwient/swc/main/scawa", /(^•ω•^)
        "finatwa/jackson/swc/main/scawa/com/twittew/finatwa/jackson/moduwes", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", OwO
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/moduwe/pwoduct_mixew_fwags", (U ﹏ U)
        "sewvo/decidew", >_<
        "timewines/swc/main/scawa/com/twittew/timewines/featuwes/app", rawr x3
        "utiw-intewnaw/scwibe", mya
        "utiw/utiw-swf4j-api/swc/main/scawa", nyaa~~
    ],
)
