packagelon com.twittelonr.product_mixelonr.corelon.modulelon

import com.twittelonr.injelonct.TwittelonrModulelon
import com.twittelonr.product_mixelonr.corelon.selonrvicelon.pipelonlinelon_elonxeloncution_loggelonr.AllowListelondPipelonlinelonelonxeloncutionLoggelonr
import com.twittelonr.product_mixelonr.corelon.selonrvicelon.pipelonlinelon_elonxeloncution_loggelonr.PipelonlinelonelonxeloncutionLoggelonr

objelonct PipelonlinelonelonxeloncutionLoggelonrModulelon elonxtelonnds TwittelonrModulelon {

  ovelonrridelon protelonctelond delonf configurelon(): Unit = {
    bind[PipelonlinelonelonxeloncutionLoggelonr].to[AllowListelondPipelonlinelonelonxeloncutionLoggelonr]
  }
}
