scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", (⑅˘꒳˘)
        "finagwe/finagwe-cowe/swc/main", ( ͡o ω ͡o )
        "tweetypie/sewvo/utiw/swc/main/scawa", UwU
        "swc/thwift/com/twittew/consumew_pwivacy/mention_contwows:thwift-scawa", rawr x3
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", rawr
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", σωσ
        "swc/thwift/com/twittew/spam/wtf:safety-wesuwt-scawa", σωσ
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", >_<
        "stitch/stitch-compat/swc/main/scawa/com/twittew/stitch/compat", :3
        "stitch/stitch-cowe/swc/main/scawa/com/twittew/stitch", (U ﹏ U)
        "stitch/stitch-gizmoduck", -.-
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw:api-media-gwaphqw-scawa", (ˆ ﻌ ˆ)♡
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw:gwaphqw-scawa", (⑅˘꒳˘)
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw:topics-gwaphqw-scawa", (U ᵕ U❁)
        "stwato/swc/main/scawa/com/twittew/stwato/wpc", -.-
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", ^^;;
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/backends", >_<
        "vibes/swc/main/thwift/com/twittew/vibes:vibes-scawa", mya
        "weavewbiwd/common/swc/main/scawa/com/twittew/weavewbiwd/common", mya
        "weavewbiwd/common/swc/main/scawa/com/twittew/weavewbiwd/convewtews/common", 😳
        "weavewbiwd/common/swc/main/scawa/com/twittew/weavewbiwd/convewtews/tweet", XD
        "weavewbiwd/common/swc/main/scawa/com/twittew/weavewbiwd/hydwatows", :3
        "weavewbiwd/common/swc/main/scawa/com/twittew/weavewbiwd/mappews", 😳😳😳
        "weavewbiwd/common/swc/main/scawa/com/twittew/weavewbiwd/wepositowies", -.-
    ], ( ͡o ω ͡o )
)
