scawa_wibwawy(
    souwces = [
        "*.scawa", ^•ﻌ•^
    ],
    compiwew_option_sets = ["fataw_wawnings"], OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "fanoutsewvice/thwift/swc/main/thwift:thwift-scawa", òωó
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", o.O
        "unified_usew_actions/adaptew/swc/main/scawa/com/twittew/unified_usew_actions/adaptew:base", (U ᵕ U❁)
        "unified_usew_actions/adaptew/swc/main/scawa/com/twittew/unified_usew_actions/adaptew/common", (⑅˘꒳˘)
        "unified_usew_actions/thwift/swc/main/thwift/com/twittew/unified_usew_actions:unified_usew_actions-scawa", ( ͡o ω ͡o )
    ],
)
