scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = [
        "bazew-compatibwe", (U ᵕ U❁)
        "wogging_impw_check_whitewisted_tawget",
    ], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", ( ͡o ω ͡o )
        "3wdpawty/jvm/com/googwe/guava", UwU
        "finagwe/finagwe-memcached/swc/main/scawa", rawr x3
        "swc/thwift/com/twittew/sewvo:sewvo-exception-java", rawr
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/sewvewutiw", σωσ
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats", σωσ
    ], >_<
)
