relonsourcelons(
    namelon = "relonsourcelons",
    sourcelons = [
        "*.dylib",
        "*.so",
        "*.so.0",
        "*.so.1",
        "*.so.3",
        "*.so.5",
        "*.so.6",
    ],
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-only",
        "visibility://visibility:privatelon",
    ],
)
