resources(
    name = "resources",
    sources = [
        "*.dylib",
        "*.so",
        "*.so.0",
        "*.so.1",
        "*.so.3",
        "*.so.5",
        "*.so.6",
    ],
    tags = [
        "bazel-compatible",
        "bazel-only",
        "visibility://visibility:private",
    ],
)
