wesouwces(
    nyame = "wesouwces", (ꈍᴗꈍ)
    souwces = [
        "*.dywib", ^•ﻌ•^
        "*.so", OwO
        "*.so.0", 🥺
        "*.so.1", òωó
        "*.so.3", o.O
        "*.so.5", (U ᵕ U❁)
        "*.so.6",
    ], (⑅˘꒳˘)
    t-tags = [
        "bazew-compatibwe", ( ͡o ω ͡o )
        "bazew-onwy", UwU
        "visibiwity://visibiwity:pwivate", rawr x3
    ],
)
