scawa_wibwawy(
    souwces = [
        "*.scawa", 🥺
    ],
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe",
        "3wdpawty/jvm/com/twittew/stowehaus:memcache", (⑅˘꒳˘)
        "3wdpawty/jvm/io/gwpc:gwpc-api",
        "3wdpawty/jvm/io/gwpc:gwpc-auth", ( ͡o ω ͡o )
        "3wdpawty/jvm/io/gwpc:gwpc-cowe", UwU
        "3wdpawty/jvm/io/gwpc:gwpc-netty", rawr x3
        "3wdpawty/jvm/io/gwpc:gwpc-pwotobuf", rawr
        "3wdpawty/jvm/io/gwpc:gwpc-stub", σωσ
        "3wdpawty/jvm/io/opiw:tensowfwow-sewving-cwient", σωσ
        "3wdpawty/jvm/javax/inject:javax.inject", >_<
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", :3
        "ann/swc/main/scawa/com/twittew/ann/hnsw", (U ﹏ U)
        "ann/swc/main/thwift/com/twittew/ann/common:ann-common-scawa", -.-
        "configapi/configapi-cowe", (ˆ ﻌ ˆ)♡
        "content-wecommendew/thwift/swc/main/thwift:thwift-scawa", (⑅˘꒳˘)
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/config", (U ᵕ U❁)
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/exception", -.-
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/modew", ^^;;
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam", >_<
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam/decidew", mya
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/souwce_signaw", mya
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/utiw", 😳
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa", XD
        "decidew/swc/main/scawa", :3
        "finagwe-intewnaw/finagwe-gwpc/swc/main/scawa", 😳😳😳
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/cwient", -.-
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", ( ͡o ω ͡o )
        "finatwa/inject/inject-cowe/swc/main/scawa", rawr x3
        "fowwow-wecommendations-sewvice/thwift/swc/main/thwift:thwift-scawa", nyaa~~
        "fwigate/fwigate-common:base", /(^•ω•^)
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/base", rawr
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/candidate", OwO
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/stowe/stwato", (U ﹏ U)
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/utiw", >_<
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/utiw:stats_utiw", rawr x3
        "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/stowe/common", mya
        "mediasewvices/commons/swc/main/scawa:futuwetwackew",
        "pwoduct-mixew/cowe/swc/main/thwift/com/twittew/pwoduct_mixew/cowe:thwift-scawa", nyaa~~
        "qig-wankew/thwift/swc/main/thwift:thwift-scawa", (⑅˘꒳˘)
        "wewevance-pwatfowm/swc/main/scawa/com/twittew/wewevance_pwatfowm/common/injection", rawr x3
        "wewevance-pwatfowm/swc/main/scawa/com/twittew/wewevance_pwatfowm/simcwustewsann/muwticwustew", (✿oωo)
        "simcwustews-ann/thwift/swc/main/thwift:thwift-scawa", (ˆ ﻌ ˆ)♡
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", (˘ω˘)
        "swc/java/com/twittew/seawch/common/schema/base", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", (///ˬ///✿)
        "swc/java/com/twittew/seawch/quewypawsew/quewy:cowe-quewy-nodes", 😳😳😳
        "swc/java/com/twittew/seawch/quewypawsew/quewy/seawch:seawch-quewy-nodes", 🥺
        "swc/scawa/com/twittew/cowtex/mw/embeddings/common:hewpews",
        "swc/scawa/com/twittew/mw/featuwestowe/wib", mya
        "swc/scawa/com/twittew/simcwustews_v2/common", 🥺
        "swc/thwift/com/twittew/mw/api:embedding-scawa", >_<
        "swc/thwift/com/twittew/wecos:wecos-common-scawa",
        "swc/thwift/com/twittew/wecos/usew_ad_gwaph:usew_ad_gwaph-scawa", >_<
        "swc/thwift/com/twittew/wecos/usew_tweet_entity_gwaph:usew_tweet_entity_gwaph-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/wecos/usew_tweet_gwaph:usew_tweet_gwaph-scawa", /(^•ω•^)
        "swc/thwift/com/twittew/wecos/usew_video_gwaph:usew_video_gwaph-scawa", rawr x3
        "swc/thwift/com/twittew/seawch:eawwybiwd-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/seawch/common:wanking-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/seawch/quewy_intewaction_gwaph/sewvice:qig-sewvice-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", òωó
        "swc/thwift/com/twittew/topic_wecos:topic_wecos-thwift-scawa", ʘwʘ
        "swc/thwift/com/twittew/twends/twip_v1:twip-tweets-thwift-scawa", /(^•ω•^)
        "swc/thwift/com/twittew/twistwy:twistwy-scawa",
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", ʘwʘ
    ], σωσ
)
