scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "cachelon/clielonnt",
        "finaglelon/finaglelon-melonmcachelond/src/main/scala",
        "finatra/injelonct/injelonct-corelon/src/main/scala",
        "finatra/injelonct/injelonct-thrift-clielonnt/src/main/scala",
        "stitch/stitch-corelon",
        "util/util-corelon:scala",
        "util/util-thrift",
    ],
)
