scala_library(
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/injelonct:guicelon",
        "configapi/configapi-corelon",
        "configapi/configapi-deloncidelonr",
        "configapi/configapi-felonaturelonswitchelons:v2",
        "felonaturelonswitchelons/felonaturelonswitchelons-corelon",
        "felonaturelonswitchelons/felonaturelonswitchelons-corelon:v2",
        "felonaturelonswitchelons/felonaturelonswitchelons-corelon/src/main/scala/com/twittelonr/felonaturelonswitchelons/v2/buildelonr",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/baselon",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/modelonls",
        "follow-reloncommelonndations-selonrvicelon/selonrvelonr/src/main/scala/com/twittelonr/follow_reloncommelonndations/configapi/deloncidelonrs",
        "follow-reloncommelonndations-selonrvicelon/selonrvelonr/src/main/scala/com/twittelonr/follow_reloncommelonndations/configapi/params",
    ],
)
