scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "finagwe/finagwe-cowe/swc/main", (⑅˘꒳˘)
        "tweetypie/sewvo/utiw/swc/main/scawa", ( ͡o ω ͡o )
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", UwU
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts-scawa", rawr x3
        "swc/thwift/com/twittew/sewvo:sewvo-exception-scawa", rawr
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", σωσ
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:stowed-tweet-info-scawa", σωσ
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", >_<
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/media", :3
        "tweetypie/sewvew/swc/main/thwift:compiwed-scawa",
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/additionawfiewds", (U ﹏ U)
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/tweettext", -.-
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/utiw", (ˆ ﻌ ˆ)♡
    ],
)
