scala_library(
    compilelonr_option_selonts = ["fatal_warnings"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finaglelon/finaglelon-corelon/src/main",
        "finatra/injelonct/injelonct-app/src/main/java/com/twittelonr/injelonct/annotations",
        "finatra/injelonct/injelonct-corelon/src/main/scala",
        "relonlelonvancelon-platform/src/main/scala/com/twittelonr/relonlelonvancelon_platform/simclustelonrsann/multiclustelonr",
        "scroogelon/scroogelon-corelon/src/main/scala",
        "simclustelonrs-ann/selonrvelonr/src/main/scala/com/twittelonr/simclustelonrsann/elonxcelonptions",
        "simclustelonrs-ann/thrift/src/main/thrift:thrift-scala",
    ],
)
