scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "finagle/finagle-core/src/main",
        "finatra/inject/inject-app/src/main/java/com/twitter/inject/annotations",
        "finatra/inject/inject-core/src/main/scala",
        "relevance-platform/src/main/scala/com/twitter/relevance_platform/simclustersann/multicluster",
        "scrooge/scrooge-core/src/main/scala",
        "simclusters-ann/server/src/main/scala/com/twitter/simclustersann/exceptions",
        "simclusters-ann/thrift/src/main/thrift:thrift-scala",
    ],
)
