scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "finagwe/finagwe-cowe/swc/main", OwO
        "finatwa/inject/inject-app/swc/main/java/com/twittew/inject/annotations",
        "finatwa/inject/inject-cowe/swc/main/scawa", 🥺
        "wewevance-pwatfowm/swc/main/scawa/com/twittew/wewevance_pwatfowm/simcwustewsann/muwticwustew", òωó
        "scwooge/scwooge-cowe/swc/main/scawa", o.O
        "simcwustews-ann/sewvew/swc/main/scawa/com/twittew/simcwustewsann/exceptions", (U ᵕ U❁)
        "simcwustews-ann/thwift/swc/main/thwift:thwift-scawa", (⑅˘꒳˘)
    ],
)
