scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "configapi/configapi-cowe/swc/main/scawa/com/twittew/timewines/configapi", òωó
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/featuwe_hydwation/common", o.O
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", (U ᵕ U❁)
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/assembwew/modews", (⑅˘꒳˘)
        "fowwow-wecommendations-sewvice/thwift/swc/main/thwift:thwift-scawa", ( ͡o ω ͡o )
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wequest", UwU
    ], rawr x3
)
