scala_library(
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "finatra/injelonct/injelonct-app/src/main/scala",
        "finatra/injelonct/injelonct-corelon/src/main/scala",
        "follow-reloncommelonndations-selonrvicelon/selonrvelonr/src/main/scala/com/twittelonr/follow_reloncommelonndations/products/common",
        "follow-reloncommelonndations-selonrvicelon/selonrvelonr/src/main/scala/com/twittelonr/follow_reloncommelonndations/products/elonxplorelon_tab",
        "follow-reloncommelonndations-selonrvicelon/selonrvelonr/src/main/scala/com/twittelonr/follow_reloncommelonndations/products/homelon_timelonlinelon",
        "follow-reloncommelonndations-selonrvicelon/selonrvelonr/src/main/scala/com/twittelonr/follow_reloncommelonndations/products/homelon_timelonlinelon_twelonelont_reloncs",
        "follow-reloncommelonndations-selonrvicelon/selonrvelonr/src/main/scala/com/twittelonr/follow_reloncommelonndations/products/sidelonbar",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/product/guicelon",
    ],
)
