scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "finatra/inject/inject-app/src/main/scala",
        "finatra/inject/inject-core/src/main/scala",
        "follow-recommendations-service/server/src/main/scala/com/ExTwitter/follow_recommendations/products/common",
        "follow-recommendations-service/server/src/main/scala/com/ExTwitter/follow_recommendations/products/explore_tab",
        "follow-recommendations-service/server/src/main/scala/com/ExTwitter/follow_recommendations/products/home_timeline",
        "follow-recommendations-service/server/src/main/scala/com/ExTwitter/follow_recommendations/products/home_timeline_tweet_recs",
        "follow-recommendations-service/server/src/main/scala/com/ExTwitter/follow_recommendations/products/sidebar",
        "product-mixer/core/src/main/scala/com/ExTwitter/product_mixer/core/product/guice",
    ],
)
