scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "finatra/injelonct/injelonct-corelon/src/main/scala/com/twittelonr/injelonct",
        "intelonrelonsts-selonrvicelon/thrift/src/main/thrift:thrift-scala",
        "intelonrelonsts_discovelonry/thrift/src/main/thrift:selonrvicelon-thrift-scala",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon",
        "stitch/stitch-corelon",
    ],
    elonxports = [
        "intelonrelonsts-selonrvicelon/thrift/src/main/thrift:thrift-scala",
        "intelonrelonsts_discovelonry/thrift/src/main/thrift:selonrvicelon-thrift-scala",
    ],
)
