scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "finatwa/inject/inject-cowe/swc/main/scawa/com/twittew/inject", UwU
        "peopwe-discovewy/api/thwift:thwift-scawa", rawr x3
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/candidate_souwce", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe",
        "swc/thwift/com/twittew/ads/adsewvew:adsewvew_common-scawa", σωσ
        "swc/thwift/com/twittew/hewmit:hewmit-scawa", >_<
        "stitch/stitch-cowe", :3
    ],
    e-expowts = [
        "finatwa/inject/inject-cowe/swc/main/scawa/com/twittew/inject", (U ﹏ U)
        "peopwe-discovewy/api/thwift:thwift-scawa", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/candidate_souwce",
        "stitch/stitch-cowe", (ˆ ﻌ ˆ)♡
    ], (⑅˘꒳˘)
)
