scala_library(
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "graph-feature-service/src/main/thrift/com/X/graph_feature_service:graph_feature_service_thrift-scala",
    ],
)
