java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/com/twittew/ewephantbiwd:cowe", o.O
        "3wdpawty/jvm/commons-codec", (U ᵕ U❁)
        "3wdpawty/jvm/commons-httpcwient", (⑅˘꒳˘)
        "3wdpawty/jvm/geo/googwe:geogoogwe", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", UwU
        "3wdpawty/jvm/owg/apache/thwift:wibthwift",
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient", rawr x3
        "decidew/swc/main/scawa",
        "finagwe/finagwe-cowe/swc/main", rawr
        "finagwe/finagwe-thwift/swc/main/java", σωσ
        "finagwe/finagwe-thwift/swc/main/scawa", σωσ
        "scwooge/scwooge-cowe/swc/main/scawa", >_<
        "swc/java/com/twittew/common/base", :3
        "swc/java/com/twittew/common/optionaw", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/decidew", -.-
        "swc/java/com/twittew/seawch/common/wogging", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/common/metwics", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/utiw:finagweutiw", (U ᵕ U❁)
        "swc/java/com/twittew/seawch/common/utiw/eawwybiwd", -.-
        "swc/java/com/twittew/seawch/common/utiw/thwift:thwift-utiws", ^^;;
        "swc/java/com/twittew/seawch/quewypawsew/quewy:cowe-quewy-nodes", >_<
        "swc/thwift/com/twittew/context:twittew-context-scawa", mya
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", mya
        "swc/thwift/com/twittew/seawch/common:caching-java", 😳
        "swc/thwift/com/twittew/seawch/common:constants-java", XD
        "swc/thwift/com/twittew/seawch/common:quewy-java", :3
        "stwato/swc/main/scawa/com/twittew/stwato/opcontext", 😳😳😳
        "twittew-context/swc/main/scawa", -.-
        "utiw/utiw-cowe:scawa", ( ͡o ω ͡o )
    ], rawr x3
)
