scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "finagwe/finagwe-cowe/swc/main", ( ͡o ω ͡o )
        "scwooge/scwooge-cowe/swc/main/scawa", UwU
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", rawr x3
        "utiw/utiw-cowe:scawa", rawr
    ],
)
