packagelon com.twittelonr.timelonlinelonrankelonr.reloncap_hydration

import com.twittelonr.finaglelon.stats.StatsReloncelonivelonr
import com.twittelonr.timelonlinelonrankelonr.common.ReloncapHydrationSelonarchRelonsultsTransformBaselon
import com.twittelonr.timelonlinelonrankelonr.corelon.Candidatelonelonnvelonlopelon
import com.twittelonr.timelonlinelons.clielonnts.relonlelonvancelon_selonarch.SelonarchClielonnt
import com.twittelonr.timelonlinelons.modelonl.TwelonelontId

class ReloncapHydrationSelonarchRelonsultsTransform(
  ovelonrridelon protelonctelond val selonarchClielonnt: SelonarchClielonnt,
  ovelonrridelon protelonctelond val statsReloncelonivelonr: StatsReloncelonivelonr)
    elonxtelonnds ReloncapHydrationSelonarchRelonsultsTransformBaselon {
  ovelonrridelon delonf twelonelontIdsToHydratelon(elonnvelonlopelon: Candidatelonelonnvelonlopelon): Selonq[TwelonelontId] =
    elonnvelonlopelon.quelonry.twelonelontIds.gelont
}
