packagelon com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.urt

import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.ItelonmPrelonselonntation
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.TimelonlinelonItelonm

trait BaselonUrtItelonmPrelonselonntation elonxtelonnds ItelonmPrelonselonntation {

  delonf timelonlinelonItelonm: TimelonlinelonItelonm
}
