packagelon com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.urt

import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.ModulelonPrelonselonntation
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.TimelonlinelonModulelon

trait BaselonUrtModulelonPrelonselonntation elonxtelonnds ModulelonPrelonselonntation {
  delonf timelonlinelonModulelon: TimelonlinelonModulelon
}
