scawa_wibwawy(
    souwces = [
        "*.scawa", òωó
    ],
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/sewvice", UwU
        "stitch/stitch-cowe", rawr x3
    ],
    e-expowts = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/sewvice", rawr
        "stitch/stitch-cowe", σωσ
    ],
)
