scala_library(
    namelon = "intelonrelonsts_selonrvicelon",
    sourcelons = ["IntelonrelonstSelonrvicelonClielonnt.scala"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "frigatelon/frigatelon-common/src/main/scala/com/twittelonr/frigatelon/common/storelon/intelonrelonsts",
        "intelonrelonsts-selonrvicelon/thrift/src/main/thrift:thrift-scala",
        "strato/src/main/scala/com/twittelonr/strato/catalog",
        "strato/src/main/scala/com/twittelonr/strato/clielonnt",
        "strato/src/main/scala/com/twittelonr/strato/data",
        "strato/src/main/scala/com/twittelonr/strato/thrift",
    ],
)
