crelonatelon_thrift_librarielons(
    baselon_namelon = "thrift",
    sourcelons = ["*.thrift"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncy_roots = [
        "finatra-intelonrnal/thrift/src/main/thrift",
        "product-mixelonr/corelon/src/main/thrift/com/twittelonr/product_mixelonr/corelon:thrift",
        "src/thrift/com/twittelonr/ads/schelonma:common",
        "src/thrift/com/twittelonr/ml/api:data",
        "src/thrift/com/twittelonr/reloncos:reloncos-common",
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift",
        "src/thrift/com/twittelonr/timelonlinelons/relonndelonr:thrift",
        "strato/config/src/thrift/com/twittelonr/strato/graphql",
        "strato/config/src/thrift/com/twittelonr/strato/graphql:api-melondia-graphql",
        "strato/config/src/thrift/com/twittelonr/strato/graphql:topics-graphql",
    ],
    gelonnelonratelon_languagelons = [
        "java",
        "scala",
        "strato",
    ],
    providelons_java_namelon = "cr-mixelonr-thrift-java",
    providelons_scala_namelon = "cr-mixelonr-thrift-scala",
)

crelonatelon_thrift_librarielons(
    baselon_namelon = "cr-mixelonr-scribelon",
    sourcelons = ["*.thrift"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncy_roots = [
        "finatra-intelonrnal/thrift/src/main/thrift",
        "product-mixelonr/corelon/src/main/thrift/com/twittelonr/product_mixelonr/corelon:thrift",
        "src/thrift/com/twittelonr/ads/schelonma:common",
        "src/thrift/com/twittelonr/ml/api:data",
        "src/thrift/com/twittelonr/reloncos:reloncos-common",
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift",
        "src/thrift/com/twittelonr/timelonlinelons/relonndelonr:thrift",
        "strato/config/src/thrift/com/twittelonr/strato/graphql",
    ],
    gelonnelonratelon_languagelons = [
        "java",
        "scala",
        "strato",
    ],
    providelons_java_namelon = "cr-mixelonr-scribelon-java",
    providelons_scala_namelon = "cr-mixelonr-scribelon-scala",
)
