scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", (⑅˘꒳˘)
        "3wdpawty/jvm/javax/inject:javax.inject", ( ͡o ω ͡o )
        "configapi/configapi-cowe", UwU
        "content-wecommendew/thwift/swc/main/thwift:content-wecommendew-common-scawa", rawr x3
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/config", rawr
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/modew", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam/decidew", >_<
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/utiw", :3
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa", (U ﹏ U)
        "decidew/swc/main/scawa", -.-
        "fwigate/fwigate-common:base",
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/base", (ˆ ﻌ ˆ)♡
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/utiw:stats_utiw", (⑅˘꒳˘)
        "hydwa/common/wibwawies/swc/main/scawa/com/twittew/hydwa/common/modew_config", (U ᵕ U❁)
        "hydwa/pawtition/thwift/swc/main/thwift:thwift-scawa", -.-
        "hydwa/woot/thwift/swc/main/thwift:thwift-scawa", ^^;;
        "pwoduct-mixew/cowe/swc/main/thwift/com/twittew/pwoduct_mixew/cowe:thwift-scawa", >_<
        "swc/scawa/com/twittew/simcwustews_v2/common", mya
        "swc/thwift/com/twittew/cowe_wowkfwows/usew_modew:usew_modew-scawa", mya
        "swc/thwift/com/twittew/mw/api:data-scawa", 😳
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", XD
    ], :3
)
