scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", ( ͡o ω ͡o )
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/pwomoted", UwU
        "swc/thwift/com/twittew/timewines/wendew:thwift-scawa", rawr x3
    ], rawr
    expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/pwomoted", σωσ
        "swc/thwift/com/twittew/timewines/wendew:thwift-scawa", >_<
    ],
)
ew/cowe/functionaw_component/mawshawwew/wesponse/uwt/metadata", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/timewine_moduwe", >_<
        "swc/thwift/com/twittew/timewines/wendew:thwift-scawa", :3
    ], (U ﹏ U)
)
