java_wibwawy(
    souwces = ["**/*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/com/googwe/inject:guice", o.O
        "3wdpawty/jvm/it/unimi/dsi:fastutiw", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-common", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-smawtcn", UwU
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", rawr x3
        "3wdpawty/jvm/owg/apache/wucene:wucene-facet", rawr
        "3wdpawty/jvm/owg/apache/wucene:wucene-quewies", σωσ
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", σωσ
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient",
        "3wdpawty/jvm/owg/swf4j:swf4j-api", >_<
        "swc/java/com/twittew/common/base", :3
        "swc/java/com/twittew/common/cowwections", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/encoding/docvawues", -.-
        "swc/java/com/twittew/seawch/common/encoding/featuwes", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/common/facets", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/hashtabwe", (U ᵕ U❁)
        "swc/java/com/twittew/seawch/common/metwics", -.-
        "swc/java/com/twittew/seawch/common/wewevance/featuwes",
        "swc/java/com/twittew/seawch/common/schema", ^^;;
        "swc/java/com/twittew/seawch/common/schema/base", >_<
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", mya
        "swc/java/com/twittew/seawch/common/seawch", mya
        "swc/java/com/twittew/seawch/common/utiw:wog_fowmat_utiw", 😳
        "swc/java/com/twittew/seawch/common/utiw/anawysis", XD
        "swc/java/com/twittew/seawch/common/utiw/hash", :3
        "swc/java/com/twittew/seawch/common/utiw/io:fwushabwe", 😳😳😳
        "swc/thwift/com/twittew/seawch/common:constants-java", -.-
        "swc/thwift/com/twittew/seawch/common:facets-java", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/seawch/common:schema-java", rawr x3
    ],
)
