scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject",
        "abdecidew/swc/main/scawa", (⑅˘꒳˘)
        "configapi/configapi-abdecidew", ( ͡o ω ͡o )
        "configapi/configapi-cowe", UwU
        "configapi/configapi-featuweswitches:v2", rawr x3
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/modew", rawr
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa",
        "decidew/swc/main/scawa", σωσ
        "discovewy-common/swc/main/scawa/com/twittew/discovewy/common/configapi", σωσ
        "featuweswitches/featuweswitches-cowe", >_<
        "featuweswitches/featuweswitches-cowe/swc/main/scawa/com/twittew/featuweswitches/v2/buiwdew", :3
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", (U ﹏ U)
        "fowwow-wecommendations-sewvice/thwift/swc/main/thwift:thwift-scawa",
        "pwoduct-mixew/cowe/swc/main/thwift/com/twittew/pwoduct_mixew/cowe:thwift-scawa", -.-
        "scwibewib/mawshawwews/swc/main/scawa/com/twittew/scwibewib/mawshawwews", (ˆ ﻌ ˆ)♡
        "swc/scawa/com/twittew/simcwustews_v2/common", (⑅˘꒳˘)
        "swc/thwift/com/twittew/seawch:eawwybiwd-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", -.-
        "usew-signaw-sewvice/thwift/swc/main/thwift:thwift-scawa", ^^;;
    ], >_<
)
