scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/lihaoyi:pprint",
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "configapi/configapi-corelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/marshallelonr/relonsponselon/urp",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/marshalling/relonsponselon/urp",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon/product",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/product",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/product/relongistry",
        "stitch/stitch-corelon",
        "util/util-corelon:scala",
    ],
)
