java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/com/googwe/inject:guice", o.O
        "3wdpawty/jvm/commons-io", (U ᵕ U❁)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (⑅˘꒳˘)
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", ( ͡o ω ͡o )
        "swc/antww/com/twittew/seawch/quewypawsew/antww:quewypawsew-antww", UwU
        "swc/java/com/googwe/common/utiw/concuwwent",
        "swc/java/com/twittew/common/cowwections", rawr x3
        "swc/java/com/twittew/common/text/wanguage:wocawe-utiw", rawr
        "swc/java/com/twittew/common/utiw:system-mocks", σωσ
        "swc/java/com/twittew/common_intewnaw/text/vewsion", σωσ
        "swc/java/com/twittew/seawch/common/cwientstats", >_<
        "swc/java/com/twittew/seawch/common/decidew", :3
        "swc/java/com/twittew/seawch/common/metwics",
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/woot", -.-
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/common/utiw:finagweutiw", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/utiw/date", (U ᵕ U❁)
        "swc/java/com/twittew/seawch/common/utiw/eawwybiwd", -.-
        "swc/java/com/twittew/seawch/common/utiw/io/pewiodic",
        "swc/java/com/twittew/seawch/common/utiw/wang", ^^;;
        "swc/java/com/twittew/seawch/common/utiw/thwift:text-pwotocow",
        "swc/java/com/twittew/seawch/eawwybiwd/common", >_<
        "swc/java/com/twittew/seawch/eawwybiwd/config",
        "swc/java/com/twittew/seawch/eawwybiwd_woot/common", mya
        "swc/java/com/twittew/seawch/eawwybiwd_woot/quota", mya
        "swc/java/com/twittew/seawch/eawwybiwd_woot/vawidatows", 😳
        "swc/java/com/twittew/seawch/quewypawsew", XD
        "swc/java/com/twittew/seawch/quewypawsew/quewy:cowe-quewy-nodes", :3
        "swc/java/com/twittew/seawch/quewypawsew/quewy/seawch:seawch-quewy-nodes", 😳😳😳
        "swc/thwift/com/twittew/context:twittew-context-scawa", -.-
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", ( ͡o ω ͡o )
    ],
)
