scawa_wibwawy(
    souwces = ["*.scawa"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", OwO
        "featuweswitches/dynmap/swc/main/scawa/com/twittew/dynmap:dynmap-cowe", 🥺
        "featuweswitches/dynmap/swc/main/scawa/com/twittew/dynmap/json:dynmap-json", òωó
        "gwaphqw/thwift/swc/main/thwift/com/twittew/gwaphqw:gwaphqw-scawa", o.O
        "utiw/utiw-cowe:scawa", (U ᵕ U❁)
    ], (⑅˘꒳˘)
)
