scala_library(
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/guava",
        "featureswitches/dynmap/src/main/scala/com/twitter/dynmap:dynmap-core",
        "featureswitches/dynmap/src/main/scala/com/twitter/dynmap/json:dynmap-json",
        "graphql/thrift/src/main/thrift/com/twitter/graphql:graphql-scala",
        "util/util-core:scala",
    ],
)
