packagelon com.twittelonr.product_mixelonr.corelon.selonrvicelon.scoring_pipelonlinelon_elonxeloncutor

import com.twittelonr.product_mixelonr.corelon.modelonl.common.UnivelonrsalNoun
import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.ItelonmCandidatelonWithDelontails
import com.twittelonr.product_mixelonr.corelon.pipelonlinelon.scoring.ScoringPipelonlinelonRelonsult

caselon class ScoringPipelonlinelonelonxeloncutorRelonsult[Candidatelon <: UnivelonrsalNoun[Any]](
  relonsult: Selonq[ItelonmCandidatelonWithDelontails],
  individualPipelonlinelonRelonsults: Selonq[ScoringPipelonlinelonRelonsult[Candidatelon]])
