scawa_wibwawy(
    souwces = [
        "*.scawa", ^•ﻌ•^
    ],
    pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], OwO
    d-dependencies = [
        "swc/scawa/com/twittew/wtf/beam/bq_embedding_expowt:bq_embedding_expowt_wib",
    ], 🥺
)
