scala_library(
    sources = [
        "*.scala",
    ],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "src/scala/com/twitter/wtf/beam/bq_embedding_export:bq_embedding_export_lib",
    ],
)
