scala_library(
    sourcelons = [
        "*.scala",
    ],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "src/scala/com/twittelonr/wtf/belonam/bq_elonmbelondding_elonxport:bq_elonmbelondding_elonxport_lib",
    ],
)
