scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = [
        "bazel-compatible",
    ],
    dependencies = [
        "configapi/configapi-abdecider",
        "configapi/configapi-core",
        "content-recommender/thrift/src/main/thrift:thrift-scala",
        "decider/src/main/scala",
        "discovery-common/src/main/scala/com/twitter/discovery/common/configapi",
        "featureswitches/featureswitches-core",
        "finatra/inject/inject-core/src/main/scala",
        "frigate/frigate-common:base",
        "frigate/frigate-common:util",
        "frigate/frigate-common/src/main/scala/com/twitter/frigate/common/candidate",
        "interests-service/thrift/src/main/thrift:thrift-scala",
        "src/scala/com/twitter/simclusters_v2/common",
        "src/thrift/com/twitter/simclusters_v2:simclusters_v2-thrift-scala",
        "stitch/stitch-storehaus",
        "topic-social-proof/server/src/main/thrift:thrift-scala",
    ],
)
