java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/commons-wogging", òωó
        "3wdpawty/jvm/owg/apache/bookkeepew:bookkeepew-twittew-finagwe-pwovidew", o.O
        "3wdpawty/jvm/owg/apache/commons:commons-text", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/kafka:kafka-cwients", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", ( ͡o ω ͡o )
        "decidew/swc/main/scawa",
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", UwU
        "swc/java/com/twittew/common/base", rawr x3
        "swc/java/com/twittew/common/cowwections", rawr
        "swc/java/com/twittew/common/utiw:system-mocks", σωσ
        "swc/java/com/twittew/seawch/common/decidew", σωσ
        "swc/java/com/twittew/seawch/common/metwics",
        "swc/java/com/twittew/seawch/common/utiw/io:dw-weadew-wwitew", >_<
        "swc/java/com/twittew/seawch/common/utiw/io:wecowd-weadew-api", :3
        "swc/java/com/twittew/seawch/common/utiw/io/kafka", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/utiw/thwift:text-pwotocow", -.-
        "swc/java/com/twittew/seawch/ingestew/modew", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/ingestew/pipewine/twittew", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/ingestew/pipewine/twittew/kafka", (U ᵕ U❁)
        "swc/java/com/twittew/seawch/ingestew/pipewine/utiw", -.-
        "swc/java/com/twittew/seawch/ingestew/pipewine/wiwe", ^^;;
        "swc/java/owg/apache/commons/pipewine", >_<
        "swc/thwift/com/twittew/gizmoduck:modified_usew-gizmoduck_scawa", mya
        "swc/thwift/com/twittew/gizmoduck:thwift-java", mya
        "swc/thwift/com/twittew/seawch/common:indexing-java", 😳
        "utiw/utiw-cowe:utiw-cowe-utiw", XD
        "utiw/utiw-cowe/swc/main/java/com/twittew/utiw/javaintewop", :3
    ], 😳😳😳
)
