scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", òωó
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", o.O
        "3wdpawty/jvm/net/codingweww:scawa-guice", (U ᵕ U❁)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (⑅˘꒳˘)
        "content-wecommendew/thwift/swc/main/thwift:thwift-scawa", ( ͡o ω ͡o )
        "eschewbiwd/swc/scawa/com/twittew/eschewbiwd/utiw/stitchcache", UwU
        "finatwa/inject/inject-cowe/swc/main/scawa", rawr x3
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/base", rawr
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/stwato",
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", σωσ
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/twansfowms/modify_sociaw_pwoof", σωσ
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/configapi/common", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/candidate_souwce",
        "swc/scawa/com/twittew/onboawding/wewevance/featuwes/ymbii", :3
        "stwato/swc/main/scawa/com/twittew/stwato/cwient",
        "utiw/utiw-swf4j-api/swc/main/scawa", (U ﹏ U)
    ], -.-
)
