packagelon com.twittelonr.product_mixelonr.componelonnt_library.modelonl.prelonselonntation.slicelon

import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.slicelon.BaselonSlicelonItelonmPrelonselonntation
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.slicelon.SlicelonItelonm

caselon class SlicelonItelonmPrelonselonntation(ovelonrridelon val slicelonItelonm: SlicelonItelonm)
    elonxtelonnds BaselonSlicelonItelonmPrelonselonntation
