scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "addwessbook/thwift/swc/thwift/com/twittew/addwessbook:thwift-scawa", (U ᵕ U❁)
        "addwessbook/thwift/swc/thwift/com/twittew/addwessbook/datatypes:thwift-scawa", (⑅˘꒳˘)
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", ( ͡o ω ͡o )
        "finatwa/inject/inject-thwift-cwient", UwU
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/addwessbook/modews",
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/common", rawr x3
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", rawr
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/utiws", σωσ
        "swc/scawa/com/twittew/wtf/scawding/jobs/addwess_book:ab_utiw", σωσ
        "swc/thwift/com/twittew/hewmit/usewcontacts:hewmit-usewcontacts-scawa", >_<
        "swc/thwift/com/twittew/wtf/addwessbook:addwessbook-scawa", :3
        "stitch/stitch-cowe", (U ﹏ U)
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", -.-
    ], (ˆ ﻌ ˆ)♡
)
