scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject",
        "abdecidew/swc/main/scawa", (⑅˘꒳˘)
        "configapi/configapi-abdecidew", ( ͡o ω ͡o )
        "configapi/configapi-cowe", UwU
        "configapi/configapi-featuweswitches:v2", rawr x3
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam", rawr
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam/decidew", σωσ
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa", σωσ
        "decidew/swc/main/scawa", >_<
        "discovewy-common/swc/main/scawa/com/twittew/discovewy/common/configapi", :3
        "featuweswitches/featuweswitches-cowe", (U ﹏ U)
        "featuweswitches/featuweswitches-cowe/swc/main/scawa/com/twittew/featuweswitches/v2/buiwdew", -.-
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", (ˆ ﻌ ˆ)♡
        "fwigate/fwigate-common:utiw", (⑅˘꒳˘)
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/base", (U ᵕ U❁)
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/candidate", -.-
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/stowe", ^^;;
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/stowe/heawth", >_<
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/stowe/intewests", mya
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/stowe/stwato", mya
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/utiw", 😳
        "pwoduct-mixew/cowe/swc/main/thwift/com/twittew/pwoduct_mixew/cowe:thwift-scawa", XD
        "scwibewib/mawshawwews/swc/main/scawa/com/twittew/scwibewib/mawshawwews", :3
        "swc/scawa/com/twittew/simcwustews_v2/common", 😳😳😳
        "swc/thwift/com/twittew/cowe_wowkfwows/usew_modew:usew_modew-scawa", -.-
        "swc/thwift/com/twittew/fwigate:fwigate-common-thwift-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", rawr x3
    ],
)
