scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    compiwew_option_sets = ["fataw_wawnings"], OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "configapi/configapi-cowe", òωó
        "configapi/configapi-cowe/swc/main/scawa/com/twittew/timewines/configapi", o.O
        "sewvo/decidew", (U ᵕ U❁)
        "timewinewankew/common/swc/main/scawa/com/twittew/timewinewankew/modew", (⑅˘꒳˘)
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/config", ( ͡o ω ͡o )
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/decidew", UwU
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/pawametews/utiw", rawr x3
        "timewines/swc/main/scawa/com/twittew/timewines/config", rawr
        "timewines/swc/main/scawa/com/twittew/timewines/decidew", σωσ
        "timewines/swc/main/scawa/com/twittew/timewines/utiw/bounds", σωσ
        "utiw/utiw-stats/swc/main/scawa", >_<
    ],
)
