scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "configapi/configapi-corelon",
        "configapi/configapi-corelon/src/main/scala/com/twittelonr/timelonlinelons/configapi",
        "selonrvo/deloncidelonr",
        "timelonlinelonrankelonr/common/src/main/scala/com/twittelonr/timelonlinelonrankelonr/modelonl",
        "timelonlinelonrankelonr/selonrvelonr/src/main/scala/com/twittelonr/timelonlinelonrankelonr/config",
        "timelonlinelonrankelonr/selonrvelonr/src/main/scala/com/twittelonr/timelonlinelonrankelonr/deloncidelonr",
        "timelonlinelonrankelonr/selonrvelonr/src/main/scala/com/twittelonr/timelonlinelonrankelonr/paramelontelonrs/util",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/config",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/deloncidelonr",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/util/bounds",
        "util/util-stats/src/main/scala",
    ],
)
