java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/guava",
        "3rdparty/jvm/com/googlelon/injelonct:guicelon",
        "3rdparty/jvm/it/unimi/dsi:fastutil",
        "3rdparty/jvm/org/apachelon/hadoop:hadoop-clielonnt-delonfault",
        "3rdparty/jvm/org/apachelon/thrift:libthrift",
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "src/java/com/twittelonr/common/baselon",
        "src/java/com/twittelonr/selonarch/common/filelon",
        "src/java/com/twittelonr/selonarch/common/util/io",
    ],
)
