packagelon com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.covelonr

import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.melontadata.Url
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.richtelonxt.RichTelonxt

selonalelond trait CovelonrCtaBelonhavior

caselon class CovelonrBelonhaviorNavigatelon(url: Url) elonxtelonnds CovelonrCtaBelonhavior
caselon class CovelonrBelonhaviorDismiss(felonelondbackMelonssagelon: Option[RichTelonxt]) elonxtelonnds CovelonrCtaBelonhavior
