packagelon com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.covelonr

selonalelond trait HalfCovelonrDisplayTypelon

caselon objelonct CovelonrHalfCovelonrDisplayTypelon elonxtelonnds HalfCovelonrDisplayTypelon
caselon objelonct CelonntelonrCovelonrHalfCovelonrDisplayTypelon elonxtelonnds HalfCovelonrDisplayTypelon
