COURSE_ACTS(COURSE_BOB, _(" 1 BATAILLE DE BOB-OMB"),
       _("ROI BOB-OMB DU SOMMET")         , _("COURSE CONTRE KOOPA-RAPIDO")    , _("CANON VERS L'ILE PERCHEE"),
       _("LES 8 PIECES ROUGES")           , _("VOL DU MARIO AILE")             , _("DERRIERE LA CAGE DE CHOMP"))

COURSE_ACTS(COURSE_WF, _(" 2 FORTERESSE DE WHOMP"),
       _("DESTRUCTION DU GROS WHOMP")     , _("EN HAUT DE LA FORTERESSE")      , _("CANON VERS LES CIEUX"),
       _("PIECES ROUGES DANS LES AIRS")   , _("TOMBEZ DANS LA CAGE PERCHEE")   , _("CANON VERS UN MUR..."))

COURSE_ACTS(COURSE_JRB, _(" 3 BAIE DES PIRATES"),
       _("PILLEZ LE BATEAU COULE")        , _("L'ANGUILLE VEUT FAIRE JOUJOU?") , _("TRESOR DANS LA CAVERNE"),
       _("PIECES ROUGES A BORD!")         , _("CANON VERS LES PILIERS")        , _("DANS LE GEYSER"))

COURSE_ACTS(COURSE_CCM, _(" 4 MONTAGNE GLA-GLA"),
       _("GLISSADE SUR GLACE")            , _("PETIT PINGOUIN PERDU")          , _("COURSE DU PINGOUIN"),
       _("8 PIECES ROUGES GIVREES")       , _("BONHOMME DE NEIGE SANS TETE")   , _("MURS POUR REBONDIR"))

COURSE_ACTS(COURSE_BBH, _(" 5 MANOIR DE BIG BOO"),
       _("CHERCHEZ LE BIG BOO")           , _("MANEGE DES BOOS PAS BEAUX")     , _("SECRET DES LIVRES HANTES"),
       _("TROUVEZ LES 8 PIECES ROUGES")   , _("BALCON DE BIG BOO")             , _("UN OEIL SUR LES SALLES SECRETES"))

COURSE_ACTS(COURSE_HMC, _(" 6 CAVERNE BRUMEUSE"),
       _("GROS BIBI DE LA CAVERNE")       , _("CHARIOT POUR PIECES ROUGES")    , _("COURSE DE METAL MARIO"),
       _("DANS LE LABYRINTHE TOXIQUE")    , _("AU-DESSUS DES GAZ...")          , _("ATTENTION AUX BOULETS"))

COURSE_ACTS(COURSE_LLL, _(" 7 LAVES FATALES"),
       _("CRAMEZ LE GROS MOCHE")          , _("POUSSEZ LES PETITS MOCHES")     , _("PUZZLE DE 8 PIECES ROUGES"),
       _("BALADE SUR LA BUCHE")           , _("CHAUD DANS LE VOLCAN")          , _("ASCENCEUR DANS LE VOLCAN"))

COURSE_ACTS(COURSE_SSL, _(" 8 SABLES TROP MOUVANTS"),
       _("DANS LES GRIFFES DU VAUTOUR")   , _("AU SOMMET DE LA PYRAMIDE")      , _("DANS L'ANCIENNE PYRAMIDE"),
       _("LES QUATRE PILIERS DE LA FOI")  , _("VOL VERS LES PIECES ROUGES")    , _("ENIGME DE LA PYRAMIDE"))

COURSE_ACTS(COURSE_DDD, _(" 9 AFFREUX BASSIN"),
       _("SOUS-MARIN DE BOWSER")          , _("COFFRES DANS LE COURANT")       , _("PERCHES POUR PIECES ROUGES"),
       _("DANS LE GEYSER")                , _("RECOMPENSE DE LA RAIE")         , _("ASSOCIATION DE CASQUETTES..."))

COURSE_ACTS(COURSE_SL, _("10 CHEZ LE ROI DES NEIGES"),
       _("GROSSE TETE DU BONHOMME")       , _("COMBATTEZ LE GROS MOCHE GIVRE") , _("DANS LE GLAÇON"),
       _("VRILLE DEPUIS LE LAC")          , _("CARAPACE POUR PIECES ROUGES")   , _("DANS L'IGLOO"))

COURSE_ACTS(COURSE_WDW, _("11 MONDE TREMPE-SECHE"),
       _("MINI PLATES-FORMES FLECHEES!")  , _("SUR LES TOITS")                 , _("ENIGME DES CHIFFRES CACHES"),
       _("ASCENSEUR EXPRESS!")            , _("PIECES ROUGES: VILLE ENGLOUTIE"), _("COURSE EN VILLE"))

COURSE_ACTS(COURSE_TTM, _("12 TROP HAUTE MONTAGNE"),
       _("ESCALADEZ LA MONTAGNE")         , _("MYSTERE DE LA CAGE DU SINGE")   , _("PIECES ROUGES SUR CHAMPIGNON"),
       _("PAROI MYSTERIEUSE")             , _("PANORAMA DU PONT")              , _("CANON VERS LE CHAMPIGNON"))

COURSE_ACTS(COURSE_THI, _("13 ILE GRANDS-PETITS"),
       _("DETRUISEZ LES MAXI-CARNIVORES") , _("AU SOMMET DE L'ILE DES GEANTS") , _("KOOPA-RAPIDO, LA VENGEANCE"),
       _("CINQ TOUT PETITS SECRETS")      , _("LES PIECES ROUGES DU GIGOTEUR") , _("ENERVEZ LE GIGOTEUR"))

COURSE_ACTS(COURSE_TTC, _("14 HORLOGE TIC-TAC"),
       _("ROULEMENTS DANS LA CAGE")       , _("LES TROUS ET LE PENDULE")       , _("CHEVAUCHEZ L'AIGUILLE"),
       _("L'ECRABOUILLEUR")               , _("SAUTS SYNCHRONISES")            , _("L'HEURE PILE POUR LES PIECES"))

COURSE_ACTS(COURSE_RR, _("15 COURSE ARC-EN-CIEL"),
       _("CROISIERE SUR L'ARC-EN-CIEL")   , _("MANOIR DANS LES AIRS")          , _("LABYRINTHE DES PIECES ROUGES"),
       _("BALANÇOIRE CELESTE")            , _("VICIEUX TRIANGLES!")            , _("L'ARC-EN-CIEL ET AU-DELA"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER DES TENEBRES"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER DES LAVES"))
SECRET_STAR(COURSE_BITS, _("   BOWSER DES CIEUX"))
SECRET_STAR(COURSE_PSS, _("   GLISSADE DE LA PRINCESSE"))
SECRET_STAR(COURSE_COTMC, _("   MINE DES CASQUETTES-METAL"))
SECRET_STAR(COURSE_TOTWC, _("   INTERRUPTEUR DE LA TOUR AILEE"))
SECRET_STAR(COURSE_VCUTM, _("   INVISIBLE SOUS LES DOUVES"))
SECRET_STAR(COURSE_WMOTR, _("   AU-DELA DE L'ARC-EN-CIEL"))
SECRET_STAR(COURSE_SA, _("   AQUARIUM SECRET"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   ETOILES SECRETES"))

EXTRA_TEXT(0, _("UNE ETOILE SECRETE DU CHATEAU"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
