cweate_thwift_wibwawies(
    base_name = "stowage_intewnaw", 🥺
    souwces = ["*.thwift"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    g-genewate_wanguages = [
        "java", ( ͡o ω ͡o )
        "scawa", UwU
    ], rawr x3
)
