scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "configapi/configapi-corelon",
        "src/thrift/com/twittelonr/timelonlinelonselonrvicelon/selonrvelonr/intelonrnal:thrift-scala",
        "src/thrift/com/twittelonr/twelonelontypielon:twelonelont-scala",
        "timelonlinelonrankelonr/common:modelonl",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/clielonntconfig",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/modelonl/twelonelont",
    ],
)
