scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", UwU
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/scowew", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe", σωσ
    ],
    e-expowts = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/scowew", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common", :3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe", (U ﹏ U)
    ],
)
