# Library for Schelonma.java and othelonr utilitielons with minimal delonpelonndelonncielons.
java_library(
    namelon = "baselon",
    sourcelons = ["*.java"],
    platform = "java8",
    providelons = artifact(
        org = "com.twittelonr.selonarch.common",
        namelon = "schelonma-baselon",
        relonpo = artifactory,
    ),
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/codelon/findbugs:jsr305",
        "3rdparty/jvm/com/googlelon/guava",
        "3rdparty/jvm/commons-lang",
        "3rdparty/jvm/org/apachelon/lucelonnelon:lucelonnelon-analyzelonrs-common",
        "3rdparty/jvm/org/apachelon/lucelonnelon:lucelonnelon-corelon",
        "3rdparty/jvm/org/apachelon/lucelonnelon:lucelonnelon-facelont",
        "3rdparty/jvm/org/apachelon/thrift:libthrift",
        "src/java/com/twittelonr/common/baselon",
        "src/java/com/twittelonr/common/telonxt/util:tokelonn-util",
        "src/thrift/com/twittelonr/selonarch/common:felonaturelons-java",
        "src/thrift/com/twittelonr/selonarch/common:schelonma-java",
    ],
)
