# wibwawy fow schema.java and othew u-utiwities with m-minimaw dependencies. rawr
j-java_wibwawy(
    n-nyame = "base", σωσ
    s-souwces = ["*.java"], σωσ
    p-pwatfowm = "java8", >_<
    p-pwovides = awtifact(
        o-owg = "com.twittew.seawch.common",
        nyame = "schema-base", :3
        wepo = awtifactowy, (U ﹏ U)
    ), -.-
    tags = ["bazew-compatibwe"], (ˆ ﻌ ˆ)♡
    dependencies = [
        "3wdpawty/jvm/com/googwe/code/findbugs:jsw305",
        "3wdpawty/jvm/com/googwe/guava", (⑅˘꒳˘)
        "3wdpawty/jvm/commons-wang", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-common",
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", -.-
        "3wdpawty/jvm/owg/apache/wucene:wucene-facet", ^^;;
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", >_<
        "swc/java/com/twittew/common/base", mya
        "swc/java/com/twittew/common/text/utiw:token-utiw", mya
        "swc/thwift/com/twittew/seawch/common:featuwes-java", 😳
        "swc/thwift/com/twittew/seawch/common:schema-java", XD
    ],
)
