# java wibwawy fow docvawues and c-common stwide fiewd e-encoding utiwities. σωσ
j-java_wibwawy(
    s-souwces = ["*.java"], σωσ
    p-pwatfowm = "java8", >_<
    p-pwovides = a-awtifact(
        o-owg = "com.twittew.seawch.common", :3
        nyame = "encoding-docvawues", (U ﹏ U)
        wepo = awtifactowy, -.-
    ), (ˆ ﻌ ˆ)♡
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-common", -.-
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", ^^;;
        "3wdpawty/jvm/owg/apache/wucene:wucene-facet", >_<
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", mya
        "swc/java/com/twittew/seawch/common/schema/base", mya
        "swc/thwift/com/twittew/seawch/common:schema-java", 😳
    ], XD
)
