scawa_wibwawy(
    nyame = "woadtest", ( ͡o ω ͡o )
    souwces = ["*.scawa"], UwU
    c-compiwew_option_sets = ["fataw_wawnings"], rawr x3
    t-tags = ["bazew-compatibwe"], rawr
    d-dependencies = [
        "ann/swc/main/wesouwces", σωσ
        "ann/swc/main/scawa/com/twittew/ann/annoy", σωσ
        "ann/swc/main/scawa/com/twittew/ann/common", >_<
        "ann/swc/main/scawa/com/twittew/ann/faiss", :3
        "ann/swc/main/scawa/com/twittew/ann/hnsw", (U ﹏ U)
        "ann/swc/main/scawa/com/twittew/ann/utiw", -.-
        "ann/swc/main/thwift/com/twittew/ann/common:ann-common-scawa", (ˆ ﻌ ˆ)♡
        "finatwa/inject/inject-sewvew/swc/main/scawa", (⑅˘꒳˘)
        "swc/scawa/com/twittew/cowtex/mw/embeddings/common:hewpews", (U ᵕ U❁)
        "twittew-sewvew-intewnaw/swc/main/scawa", -.-
        "utiw/utiw-wogging/swc/main/scawa", ^^;;
    ],
)

j-jvm_binawy(
    n-nyame = "bin", >_<
    b-basename = "ann-woadtest",
    m-main = "com.twittew.ann.sewvice.woadtest.annwoadtestmain", mya
    w-wuntime_pwatfowm = "java11", mya
    dependencies = [
        ":woadtest", 😳
        "3wdpawty/jvm/owg/swf4j:swf4j-jdk14", XD
        "twittew-sewvew/swf4j-jdk14/swc/main/scawa", :3
    ],
)
