scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/src/jvm/com/twitter/storehaus:core",
        "finagle/finagle-stats",
        "frigate/frigate-common/src/main/scala/com/twitter/frigate/common/store",
        "frigate/frigate-common/src/main/scala/com/twitter/frigate/common/store/strato",
        "hermit/hermit-core/src/main/scala/com/twitter/hermit/store/common",
        "relevance-platform/src/main/scala/com/twitter/relevance_platform/common/injection",
        "src/scala/com/twitter/storehaus_internal/manhattan",
        "src/scala/com/twitter/twistly/common",
        "src/thrift/com/twitter/simclusters_v2:simclusters_v2-thrift-scala",
        "user-signal-service/thrift/src/main/thrift:thrift-scala",
    ],
)
