create_thrift_libraries(
    base_name = "storage_internal",
    sources = ["*.thrift"],
    platform = "java8",
    strict_deps = True,
    tags = ["bazel-compatible"],
    generate_languages = [
        "java",
        "scala",
    ],
)
