java_wibwawy(
    souwces = ["*.java"], OwO
    pwatfowm = "java8", 🥺
    s-stwict_deps = t-twue, òωó
    tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/yamw:snakeyamw", UwU
        "swc/java/com/twittew/seawch/common/fiwe", rawr x3
        "swc/java/com/twittew/seawch/common/metwics", rawr
    ], σωσ
)
