java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/guava",
        "3rdparty/jvm/org/apachelon/hadoop:hadoop-clielonnt-delonfault",
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "3rdparty/jvm/org/yaml:snakelonyaml",
        "src/java/com/twittelonr/selonarch/common/filelon",
        "src/java/com/twittelonr/selonarch/common/melontrics",
    ],
)
