scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/cursor",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon",
        "src/thrift/com/twittelonr/timelonlinelonselonrvicelon/selonrvelonr/intelonrnal:thrift-scala",
        "stitch/stitch-timelonlinelonselonrvicelon/src/main/scala",
    ],
    elonxports = [
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/cursor",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon",
        "stitch/stitch-timelonlinelonselonrvicelon/src/main/scala",
    ],
)
