scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    stwict_deps = f-fawse, 🥺
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/gwaphjet", o.O
        "3wdpawty/jvm/owg/apache/kafka:wosette-kafka", (U ᵕ U❁)
        "finagwe/finagwe-stats/swc/main/scawa", (⑅˘꒳˘)
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", ( ͡o ω ͡o )
        "kafka/wibs/swc/main/scawa/com/twittew/kafka/cwient/pwocessow", UwU
        "sewvo/wepo/swc/main/scawa", rawr x3
        "swc/scawa/com/twittew/wecos/utiw:wecos-utiw", rawr
        "swc/thwift/com/twittew/wecos:wecos-intewnaw-scawa", σωσ
    ], σωσ
)
