scala_library(
    sourcelons = ["*.scala"],
    strict_delonps = Falselon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/graphjelont",
        "3rdparty/jvm/org/apachelon/kafka:roselonttelon-kafka",
        "finaglelon/finaglelon-stats/src/main/scala",
        "kafka/finaglelon-kafka/finatra-kafka/src/main/scala",
        "kafka/libs/src/main/scala/com/twittelonr/kafka/clielonnt/procelonssor",
        "selonrvo/relonpo/src/main/scala",
        "src/scala/com/twittelonr/reloncos/util:reloncos-util",
        "src/thrift/com/twittelonr/reloncos:reloncos-intelonrnal-scala",
    ],
)
