scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "decidew", (⑅˘꒳˘)
        "finagwe/finagwe-base-http/swc/main", ( ͡o ω ͡o )
        "finatwa-intewnaw/api11/swc/main/scawa/com/twittew/finatwa/api11:ewwows", UwU
        "geo/modew/swc/main/scawa/com/twittew/geo/modew", rawr x3
        "passbiwd/bitfiewds-thwift/swc/main/thwift:thwift-scawa", rawr
        "tweetypie/sewvo/utiw/swc/main/scawa:exception", σωσ
        "swc/scawa/com/twittew/accounts/utiw:safety-meta", σωσ
        "swc/thwift/com/twittew/ads/adsewvew:ad_engagement_detaiws-scawa", >_<
        "swc/thwift/com/twittew/ads/adsewvew:pwewoww_metadata-scawa", :3
        "swc/thwift/com/twittew/ads/cawwback:engagement_wequest-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/bouncew:bounce-action-thwift-scawa", -.-
        "swc/thwift/com/twittew/consumew_pwivacy/mention_contwows:thwift-scawa",
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", (ˆ ﻌ ˆ)♡
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:stowed-tweet-info-scawa",
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-sewvice-fedewated-scawa", (⑅˘꒳˘)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet_sewvice_gwaphqw-scawa", (U ᵕ U❁)
        "stitch/stitch-cowe/swc/main/scawa/com/twittew/stitch", -.-
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw:api-media-gwaphqw-scawa", ^^;;
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw:gwaphqw-scawa", >_<
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw:topics-gwaphqw-scawa", mya
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", mya
        "stwato/swc/main/scawa/com/twittew/stwato/fed", 😳
        "stwato/swc/main/scawa/com/twittew/stwato/wesponse", XD
        "stwato/swc/main/scawa/com/twittew/stwato/thwift", :3
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", 😳😳😳
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/fedewated/context", -.-
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/fedewated/pwefetcheddata", ( ͡o ω ͡o )
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/fedewated/pwomotedcontent",
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/wepositowy", rawr x3
        "tweetypie/sewvew/swc/main/thwift:compiwed-scawa", nyaa~~
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/cwient_id", /(^•ω•^)
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/decidew/ovewwides", rawr
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/utiw", OwO
        "vibes/swc/main/thwift/com/twittew/vibes:vibes-scawa", (U ﹏ U)
        "weavewbiwd/common/swc/main/scawa/com/twittew/weavewbiwd/common", >_<
    ],
)
