scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "configapi/configapi-corelon/src/main/scala/com/twittelonr/timelonlinelons/configapi",
        "selonrvo/deloncidelonr/src/main/scala",
        "timelonlinelonrankelonr/selonrvelonr/src/main/scala/com/twittelonr/timelonlinelonrankelonr/deloncidelonr",
        "timelonlinelonrankelonr/selonrvelonr/src/main/scala/com/twittelonr/timelonlinelonrankelonr/paramelontelonrs/util",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/util/bounds",
    ],
)
