scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/com/github/nscawa_time", (U ᵕ U❁)
        "3wdpawty/jvm/com/googwe/inject:guice", (⑅˘꒳˘)
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", ( ͡o ω ͡o )
        "3wdpawty/jvm/net/codingweww:scawa-guice", UwU
        "3wdpawty/jvm/owg/swf4j:swf4j-api", rawr x3
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", rawr
        "finatwa/inject/inject-cowe/swc/main/scawa", σωσ
        "finatwa/inject/inject-thwift-cwient/swc/main/scawa", σωσ
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/common", >_<
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", :3
        "swc/thwift/com/twittew/geoduck:geoduck-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/geoduck:geoduckpawtnewpwaces-thwift-scawa", -.-
        "stitch/stitch-cowe", (ˆ ﻌ ˆ)♡
        "utiw/utiw-cowe:scawa", (⑅˘꒳˘)
    ], (U ᵕ U❁)
)
