scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/candidate_souwce/stwato", (⑅˘꒳˘)
        "stwato/config/cowumns/intewests:intewests-stwato-cwient", ( ͡o ω ͡o )
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", UwU
    ],
)
e", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/timewinesewvice/sewvew/intewnaw:thwift-scawa", UwU
        "stitch/stitch-timewinesewvice/swc/main/scawa", rawr x3
    ], rawr
    expowts = [
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/cuwsow", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/candidate_souwce", σωσ
        "stitch/stitch-timewinesewvice/swc/main/scawa",
    ], >_<
)
