scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "finatwa/inject/inject-app/swc/main/scawa", òωó
        "finatwa/inject/inject-cowe/swc/main/scawa", o.O
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/bwendews", (U ᵕ U❁)
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/fwows/ads", (⑅˘꒳˘)
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/fwows/post_nux_mw", ( ͡o ω ͡o )
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/pwoducts/common", UwU
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/pwoducts/home_timewine/configapi", rawr x3
    ], rawr
)
