scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/marshalling/relonsponselon/urt/relonaction",
        "src/thrift/com/twittelonr/timelonlinelons/relonndelonr:thrift-scala",
    ],
    elonxports = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/marshalling/relonsponselon/urt/relonaction",
        "src/thrift/com/twittelonr/timelonlinelons/relonndelonr:thrift-scala",
    ],
)
