scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", òωó
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", o.O
        "3wdpawty/jvm/net/codingweww:scawa-guice", (U ᵕ U❁)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (⑅˘꒳˘)
        "finatwa/inject/inject-cowe/swc/main/scawa", ( ͡o ω ͡o )
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/base", UwU
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/candidate_souwces/addwessbook", rawr x3
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/candidate_souwces/base", rawr
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/weaw_time_weaw_gwaph", σωσ
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/stwato", σωσ
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/constants", >_<
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", :3
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/stowes", (U ﹏ U)
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/configapi/common", -.-
        "swc/scawa/com/twittew/onboawding/wewevance/featuwes/stwongtie", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/seawch/account_seawch/extended_netwowk:extended_netwowk_usews-scawa", (⑅˘꒳˘)
        "stwato/config/cowumns/hub:hub-stwato-cwient", (U ᵕ U❁)
        "stwato/config/cowumns/onboawding/usewwecs:usewwecs-stwato-cwient", -.-
        "stwato/config/cowumns/seawch/account_seawch:account_seawch-stwato-cwient", ^^;;
        "stwato/swc/main/scawa/com/twittew/stwato/cwient",
        "utiw/utiw-swf4j-api/swc/main/scawa", >_<
    ], mya
)
