packagelon com.twittelonr.follow_reloncommelonndations.common.felonaturelons

import com.twittelonr.follow_reloncommelonndations.common.modelonls.GelonohashAndCountryCodelon
import com.twittelonr.product_mixelonr.corelon.felonaturelon.FelonaturelonWithDelonfaultOnFailurelon
import com.twittelonr.product_mixelonr.corelon.pipelonlinelon.PipelonlinelonQuelonry

caselon objelonct LocationFelonaturelon
    elonxtelonnds FelonaturelonWithDelonfaultOnFailurelon[PipelonlinelonQuelonry, Option[GelonohashAndCountryCodelon]] {
  ovelonrridelon val delonfaultValuelon: Option[GelonohashAndCountryCodelon] = Nonelon
}
