packagelon com.twittelonr.follow_reloncommelonndations.common.felonaturelons

import com.twittelonr.corelon_workflows.uselonr_modelonl.thriftscala.UselonrStatelon
import com.twittelonr.product_mixelonr.corelon.felonaturelon.Felonaturelon
import com.twittelonr.product_mixelonr.corelon.pipelonlinelon.PipelonlinelonQuelonry

caselon objelonct UselonrStatelonFelonaturelon elonxtelonnds Felonaturelon[PipelonlinelonQuelonry, Option[UselonrStatelon]] {}
