common_souwces = ["common/**/*.java"]

config_souwces = ["config/**/*.java"]

toows_souwces = ["toows/**/*.java"]

i-index_souwces = ["index/facets/**/*.java"]

s-segment_buiwdew_souwces = ["awchive/segmentbuiwdew/**/*.java"]

j-java_wibwawy(
    n-nyame = "eawwybiwd-wib", >_<
    s-souwces = ["**/*.java"] + e-excwude_gwobs(common_souwces + c-config_souwces + t-toows_souwces + segment_buiwdew_souwces + index_souwces), mya
    pwatfowm = "java8", mya
    tags = ["bazew-compatibwe"], 😳
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/code/gson", XD
        "3wdpawty/jvm/com/googwe/guava", :3
        "3wdpawty/jvm/com/twittew/distwibutedwog:distwibutedwog-cowe", 😳😳😳
        "3wdpawty/jvm/com/twittew/ewephantbiwd:cowe", -.-
        "3wdpawty/jvm/commons-codec", ( ͡o ω ͡o )
        "3wdpawty/jvm/commons-httpcwient", rawr x3
        "3wdpawty/jvm/commons-io", nyaa~~
        "3wdpawty/jvm/commons-wang", /(^•ω•^)
        "3wdpawty/jvm/geo/googwe:geogoogwe", rawr
        "3wdpawty/jvm/io/netty:netty4-tcnative-bowingssw-static", OwO
        "3wdpawty/jvm/it/unimi/dsi:fastutiw", (U ﹏ U)
        "3wdpawty/jvm/javax/sewvwet:sewvwet-api", >_<
        "3wdpawty/jvm/net/java/dev/jets3t", rawr x3
        "3wdpawty/jvm/owg/apache/bookkeepew:bookkeepew-sewvew", mya
        "3wdpawty/jvm/owg/apache/bookkeepew:bookkeepew-twittew-science-pwovidew", nyaa~~
        "3wdpawty/jvm/owg/apache/commons:commons-wang3", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", rawr x3
        "3wdpawty/jvm/owg/apache/httpcomponents:httpcwient",
        "3wdpawty/jvm/owg/apache/kafka:kafka-cwients", (✿oωo)
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-common", (ˆ ﻌ ˆ)♡
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-smawtcn", (˘ω˘)
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/wucene:wucene-facet", (///ˬ///✿)
        "3wdpawty/jvm/owg/apache/wucene:wucene-quewies", 😳😳😳
        "3wdpawty/jvm/owg/apache/wucene:wucene-quewypawsew", 🥺
        "3wdpawty/jvm/owg/apache/wucene:wucene-spatiaw-extwas", mya
        "3wdpawty/jvm/owg/apache/wucene:wucene-test-fwamewowk", 🥺
        "3wdpawty/jvm/owg/apache/thwift", >_<
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient", >_<
        "3wdpawty/jvm/owg/json", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", /(^•ω•^)
        "3wdpawty/jvm/owg/tensowfwow", rawr x3
        "3wdpawty/jvm/owg/tensowfwow:tensowfwow-hadoop", (U ﹏ U)
        "3wdpawty/jvm/owg/yamw:snakeyamw", (U ﹏ U)
        "cuad/pwojects/new/thwift/swc/main/thwift:thwift-java", (⑅˘꒳˘)
        "decidew/swc/main/scawa", òωó
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", ʘwʘ
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/cwient", /(^•ω•^)
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/sewvew", ʘwʘ
        "finagwe-intewnaw/swo/swc/main/scawa/com/twittew/finagwe/swo",
        "finagwe/finagwe-base-http", σωσ
        "finagwe/finagwe-cowe/swc/main", OwO
        "finagwe/finagwe-http", 😳😳😳
        "finagwe/finagwe-sewvewsets/swc/main/scawa", 😳😳😳
        "finagwe/finagwe-stats/swc/main/scawa", o.O
        "finagwe/finagwe-thwift/swc/main/java", ( ͡o ω ͡o )
        "finagwe/finagwe-thwift/swc/main/scawa", (U ﹏ U)
        "finagwe/finagwe-thwiftmux/swc/main/scawa", (///ˬ///✿)
        "finagwe/finagwe-zipkin-cowe/swc/main/scawa", >w<
        "finagwe/finagwe-zipkin-scwibe/swc/main/scawa", rawr
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", mya
        "pewiscope/api-pwoxy-thwift/thwift/swc/main/thwift:thwift-java", ^^
        "sewvo/decidew", 😳😳😳
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", mya
        "swc/antww/com/twittew/seawch/quewypawsew/antww:quewypawsew-antww", 😳
        "swc/java/com/twittew/common/base", -.-
        "swc/java/com/twittew/common/cowwections", 🥺
        "swc/java/com/twittew/common/net:dynamic-host-set", o.O
        "swc/java/com/twittew/common/quantity", /(^•ω•^)
        "swc/java/com/twittew/common/text/wanguage:wocawe-utiw", nyaa~~
        "swc/java/com/twittew/common/text/token", nyaa~~
        "swc/java/com/twittew/common/text/utiw:token-utiw", :3
        "swc/java/com/twittew/common/utiw", 😳😳😳
        "swc/java/com/twittew/common/utiw:system-mocks", (˘ω˘)
        "swc/java/com/twittew/common/zookeepew:cwient", ^^
        "swc/java/com/twittew/common/zookeepew:gwoup", :3
        "swc/java/com/twittew/common/zookeepew:sewvew-set", -.-
        "swc/java/com/twittew/common_intewnaw/bwoomfiwtew", 😳
        "swc/java/com/twittew/common_intewnaw/cowwections", mya
        "swc/java/com/twittew/common_intewnaw/text:text-penguin7", (˘ω˘)
        "swc/java/com/twittew/common_intewnaw/text/vewsion", >_<
        "swc/java/com/twittew/common_intewnaw/zookeepew", -.-
        "swc/java/com/twittew/mw/api:api-base", 🥺
        "swc/java/com/twittew/seawch/common/auwowa", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/concuwwent", >w<
        "swc/java/com/twittew/seawch/common/config", mya
        "swc/java/com/twittew/seawch/common/constants", >w<
        "swc/java/com/twittew/seawch/common/dawk", nyaa~~
        "swc/java/com/twittew/seawch/common/database", (✿oωo)
        "swc/java/com/twittew/seawch/common/decidew", ʘwʘ
        "swc/java/com/twittew/seawch/common/encoding/docvawues", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/common/encoding/featuwes", 😳😳😳
        "swc/java/com/twittew/seawch/common/featuwes", :3
        "swc/java/com/twittew/seawch/common/fiwe", OwO
        "swc/java/com/twittew/seawch/common/wogging", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/metwics", >w<
        "swc/java/com/twittew/seawch/common/pawtitioning/base", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", 😳
        "swc/java/com/twittew/seawch/common/pawtitioning/zookeepew", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/common/quewy", 😳😳😳
        "swc/java/com/twittew/seawch/common/wewevance:featuwe-update-weadew", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/wewevance:scowews", (///ˬ///✿)
        "swc/java/com/twittew/seawch/common/wewevance:text", 😳
        "swc/java/com/twittew/seawch/common/wewevance/featuwes", 😳
        "swc/java/com/twittew/seawch/common/schema",
        "swc/java/com/twittew/seawch/common/schema/base", σωσ
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", rawr x3
        "swc/java/com/twittew/seawch/common/seawch", OwO
        "swc/java/com/twittew/seawch/common/seawch/tewmination", /(^•ω•^)
        "swc/java/com/twittew/seawch/common/utiw:cwosewesouwceutiw", 😳😳😳
        "swc/java/com/twittew/seawch/common/utiw:finagweutiw", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/utiw:gcutiw", >_<
        "swc/java/com/twittew/seawch/common/utiw:kewbewos", >w<
        "swc/java/com/twittew/seawch/common/utiw:wog_fowmat_utiw", rawr
        "swc/java/com/twittew/seawch/common/utiw:wongintconvewtew",
        "swc/java/com/twittew/seawch/common/utiw:pwatfowm_stats_expowtew", 😳
        "swc/java/com/twittew/seawch/common/utiw:wuwe_based_convewtew", >w<
        "swc/java/com/twittew/seawch/common/utiw/anawysis", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/utiw/date", OwO
        "swc/java/com/twittew/seawch/common/utiw/eawwybiwd", (ꈍᴗꈍ)
        "swc/java/com/twittew/seawch/common/utiw/hash", 😳
        "swc/java/com/twittew/seawch/common/utiw/io", 😳😳😳
        "swc/java/com/twittew/seawch/common/utiw/io:dw-weadew-wwitew", mya
        "swc/java/com/twittew/seawch/common/utiw/io:fwushabwe", mya
        "swc/java/com/twittew/seawch/common/utiw/io:wecowd-weadew-api", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/utiw/io/kafka", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/utiw/wang", mya
        "swc/java/com/twittew/seawch/common/utiw/mw/modews_managew", ʘwʘ
        "swc/java/com/twittew/seawch/common/utiw/mw/pwediction_engine", (˘ω˘)
        "swc/java/com/twittew/seawch/common/utiw/mw/tensowfwow_engine", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/utiw/spatiaw", ^•ﻌ•^
        "swc/java/com/twittew/seawch/common/utiw/text", (˘ω˘)
        "swc/java/com/twittew/seawch/common/utiw/text/wegex", :3
        "swc/java/com/twittew/seawch/common/utiw/thwift:text-pwotocow", ^^;;
        "swc/java/com/twittew/seawch/common/utiw/thwift:thwift-utiws", 🥺
        "swc/java/com/twittew/seawch/common/utiw/uww", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/utiw/zktwywock", nyaa~~
        "swc/java/com/twittew/seawch/common/utiw/zookeepew", :3
        "swc/java/com/twittew/seawch/cowe/eawwybiwd", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/eawwybiwd/common", mya
        "swc/java/com/twittew/seawch/eawwybiwd/common/config", (///ˬ///✿)
        "swc/java/com/twittew/seawch/eawwybiwd/common/usewupdates", (˘ω˘)
        "swc/java/com/twittew/seawch/eawwybiwd/config", ^^;;
        "swc/java/com/twittew/seawch/eawwybiwd/index/facets", (✿oωo)
        "swc/java/com/twittew/seawch/ingestew/pipewine/stwato_fetchews", (U ﹏ U)
        "swc/java/com/twittew/seawch/modewing/common", -.-
        "swc/java/com/twittew/seawch/modewing/tweet_wanking",
        "swc/java/com/twittew/seawch/quewypawsew", ^•ﻌ•^
        "swc/java/com/twittew/seawch/quewypawsew/quewy:cowe-quewy-nodes", rawr
        "swc/java/com/twittew/seawch/quewypawsew/quewy/seawch:seawch-quewy-nodes",
        "swc/wesouwces/com/twittew/seawch/eawwybiwd/com/twittew", (˘ω˘)
        "swc/wesouwces/com/twittew/seawch/eawwybiwd/mw", nyaa~~
        "swc/thwift/com/twittew/seawch:common", UwU
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", :3
        "swc/thwift/com/twittew/seawch/common:featuwes-java", (⑅˘꒳˘)
        "swc/thwift/com/twittew/seawch/common:indexing-java", (///ˬ///✿)
        "swc/thwift/com/twittew/seawch/common:quewy-java", ^^;;
        "swc/thwift/com/twittew/sewvice/spidewduck/gen:metadata-stowe-java", >_<
        "swc/thwift/com/twittew/tweetypie:events-java", rawr x3
        "swc/thwift/owg/apache/auwowa/gen:api", /(^•ω•^)
        "stitch/stitch-cowe/swc/main/scawa/com/twittew/stitch", :3
        "stwato/swc/main/scawa/com/twittew/stwato/catawog", (ꈍᴗꈍ)
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", /(^•ω•^)
        "stwato/swc/main/scawa/com/twittew/stwato/data", (⑅˘꒳˘)
        "stwato/swc/main/scawa/com/twittew/stwato/thwift", ( ͡o ω ͡o )
        "tensowfwow/tfcompute-java/swc/main/java/com/twittew/tfcompute_java", òωó
        "thwift-web-fowms/swc/main/java/com/twittew/thwiftwebfowms", (⑅˘꒳˘)
        "thwift-web-fowms/swc/main/scawa/com/twittew/thwiftwebfowms", XD
        "twittew-sewvew-intewnaw", -.-
        "twittew-sewvew/sewvew/swc/main/scawa", :3
        "ubs/common/swc/main/thwift/com/twittew/ubs:bwoadcast-thwift-java", nyaa~~
        "ubs/common/swc/main/thwift/com/twittew/ubs:events-java", 😳
        "utiw-intewnaw/utiw-evaw/swc/main/scawa", (⑅˘꒳˘)
        "utiw/utiw-app", nyaa~~
        "utiw/utiw-cowe:scawa", OwO
        "utiw/utiw-function", rawr x3
        "utiw/utiw-wint", XD
        "utiw/utiw-swf4j-api/swc/main/scawa", σωσ
        "utiw/utiw-stats/swc/main/scawa", (U ᵕ U❁)
    ], (U ﹏ U)
)

jvm_binawy(
    nyame = "eawwybiwd-binawy", :3
    b-basename = "eawwybiwd", ( ͡o ω ͡o )
    main = "com.twittew.seawch.eawwybiwd.eawwybiwdmain", σωσ
    p-pwatfowm = "java8", >w<
    tags = ["bazew-compatibwe"], 😳😳😳
    dependencies = [
        ":eawwybiwd-wib", OwO
        "wogwens/wogwens-wog4j", 😳
    ],
)

java_wibwawy(
    n-nyame = "toows", 😳😳😳
    souwces = toows_souwces, (˘ω˘)
    tags = [
        "bazew-compatibwe", ʘwʘ
        "bazew-onwy", ( ͡o ω ͡o )
    ],
    d-dependencies = [
        ":eawwybiwd-wib", o.O
        "3wdpawty/jvm/com/googwe/guava", >w<
        "3wdpawty/jvm/com/googwe/guava:guava-testwib", 😳
        "3wdpawty/jvm/commons-codec",
        "3wdpawty/jvm/commons-httpcwient", 🥺
        "3wdpawty/jvm/geo/googwe:geogoogwe", rawr x3
        "3wdpawty/jvm/junit", o.O
        "3wdpawty/jvm/net/java/dev/jets3t", rawr
        "3wdpawty/jvm/owg/apache/bookkeepew:bookkeepew-sewvew", ʘwʘ
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", 😳😳😳
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ^^;;
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", o.O
    ], (///ˬ///✿)
)
