scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", (U ᵕ U❁)
        "ann/swc/main/scawa/com/twittew/ann/common", (⑅˘꒳˘)
        "ann/swc/main/thwift/com/twittew/ann/common:ann-common-scawa", ( ͡o ω ͡o )
        "mediasewvices/commons/swc/main/scawa", UwU
    ], rawr x3
)
