scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/storelonhaus:corelon",
        "ann/src/main/scala/com/twittelonr/ann/common",
        "ann/src/main/thrift/com/twittelonr/ann/common:ann-common-scala",
        "melondiaselonrvicelons/commons/src/main/scala",
    ],
)
