cweate_thwift_wibwawies(
    base_name = "thwift", o.O
    souwces = [
        "cwient_identifiew.thwift", (U ᵕ U❁)
        "sewvice.thwift",
        "signaw.thwift", (⑅˘꒳˘)
    ],
    p-pwatfowm = "java8", ( ͡o ω ͡o )
    t-tags = ["bazew-compatibwe"], UwU
    d-dependency_woots = [
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift", rawr x3
    ], rawr
    g-genewate_wanguages = [
        "java", σωσ
        "scawa", σωσ
        "stwato", >_<
    ],
    p-pwovides_java_name = "uss-thwift-java", :3
    p-pwovides_scawa_name = "uss-thwift-scawa", (U ﹏ U)
)
