scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "strato/src/main/scala/com/X/strato/fed",
        "strato/src/main/scala/com/X/strato/fed/server",
    ],
)
