scala_library(
    sources = ["*.scala"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "decider/src/main/scala",
        "src/scala/com/X/recos/util:recos-util",
    ],
)
