scala_library(
    sourcelons = ["*.scala"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "src/scala/com/twittelonr/scalding_intelonrnal/job/analytics_batch",
    ],
)
