java_wibwawy(
    souwces = ["**/*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/code/findbugs:jsw305", òωó
        "3wdpawty/jvm/com/googwe/guava", o.O
        "3wdpawty/jvm/com/googwe/inject:guice", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/swf4j:swf4j-api", UwU
        "swc/java/com/twittew/common/base", rawr x3
        "swc/java/com/twittew/common/utiw:system-mocks",
        "swc/java/com/twittew/seawch/common/config", rawr
        "swc/java/com/twittew/seawch/common/metwics", σωσ
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", σωσ
        "swc/java/com/twittew/seawch/common/utiw/date", >_<
        "swc/java/com/twittew/seawch/common/utiw/zookeepew", :3
        "swc/java/com/twittew/seawch/eawwybiwd/common/config", (U ﹏ U)
    ], -.-
)
