crelonatelon_thrift_librarielons(
    baselon_namelon = "selonrialization",
    sourcelons = ["*.thrift"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncy_roots = [
        "src/thrift/com/twittelonr/ml/api:elonmbelondding",
    ],
    gelonnelonratelon_languagelons = [
        "java",
        "scala",
    ],
)
