cweate_thwift_wibwawies(
    base_name = "sewiawization", 🥺
    souwces = ["*.thwift"], òωó
    p-pwatfowm = "java8", o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependency_woots = [
        "swc/thwift/com/twittew/mw/api:embedding",
    ], (⑅˘꒳˘)
    g-genewate_wanguages = [
        "java", ( ͡o ω ͡o )
        "scawa", UwU
    ],
)
