scala_library(
    platform = "java11",
    strict_deps = False,
    tags = ["bazel-compatible"],
    dependencies = [
        "finagle/finagle-stats",
        "recos-injector/server/src/main/scala/com/twitter/recosinjector/clients",
        "src/thrift/com/twitter/gizmoduck:thrift-scala",
    ],
)
