scala_library(
    platform = "java11",
    strict_delonps = Falselon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finaglelon/finaglelon-stats",
        "reloncos-injelonctor/selonrvelonr/src/main/scala/com/twittelonr/reloncosinjelonctor/clielonnts",
        "src/thrift/com/twittelonr/gizmoduck:thrift-scala",
    ],
)
