scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "decider/src/main/scala",
        "src/scala/com/twitter/simclusters_v2/common",
    ],
)
