scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "src/java/com/twittelonr/common/telonxt/languagelon:localelon-util",
        "src/thrift/com/twittelonr/selonarch:elonarlybird-scala",
        "src/thrift/com/twittelonr/selonarch/common:felonaturelons-scala",
        "src/thrift/com/twittelonr/timelonlinelonrankelonr/selonrvelonr/modelonl:thrift-scala",
        "timelonlinelons:config-api-baselon",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/common/modelonl",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/elonarlybird/common/options",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/elonarlybird/common/utils",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/modelonl/candidatelon",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/modelonl/twelonelont",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/util",
        "timelonlinelonselonrvicelon/common/src/main/scala/com/twittelonr/timelonlinelonselonrvicelon/modelonl",
    ],
    elonxports = [
        "timelonlinelons:config-api-baselon",
    ],
)
