scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "swc/java/com/twittew/common/text/wanguage:wocawe-utiw", (⑅˘꒳˘)
        "swc/thwift/com/twittew/seawch:eawwybiwd-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/seawch/common:featuwes-scawa", UwU
        "swc/thwift/com/twittew/timewinewankew/sewvew/modew:thwift-scawa",
        "timewines:config-api-base", rawr x3
        "timewines/swc/main/scawa/com/twittew/timewines/common/modew", rawr
        "timewines/swc/main/scawa/com/twittew/timewines/eawwybiwd/common/options", σωσ
        "timewines/swc/main/scawa/com/twittew/timewines/eawwybiwd/common/utiws",
        "timewines/swc/main/scawa/com/twittew/timewines/modew/candidate", σωσ
        "timewines/swc/main/scawa/com/twittew/timewines/modew/tweet",
        "timewines/swc/main/scawa/com/twittew/timewines/utiw", >_<
        "timewinesewvice/common/swc/main/scawa/com/twittew/timewinesewvice/modew", :3
    ],
    e-expowts = [
        "timewines:config-api-base",
    ], (U ﹏ U)
)
