package com.twitter.home_mixer.param

object HomeMixerInjectionNames {
  final val AuthorFeatureRepository = "AuthorFeatureRepository"
  final val CandidateFeaturesScribeEventPublisher = "CandidateFeaturesScribeEventPublisher"
  final val CommonFeaturesScribeEventPublisher = "CommonFeaturesScribeEventPublisher"
  final val EarlybirdRepository = "EarlybirdRepository"
  final val EngagementsReceivedByAuthorCache = "EngagementsReceivedByAuthorCache"
  final val GraphTwoHopRepository = "GraphTwoHopRepository"
  final val HomeAuthorFeaturesCacheClient = "HomeAuthorFeaturesCacheClient"
  final val InterestsThriftServiceClient = "InterestsThriftServiceClient"
  final val BatchedStratoClientWithModerateTimeout = "BatchedStratoClientWithModerateTimeout"
  final val ManhattanApolloClient = "ManhattanApolloClient"
  final val ManhattanAthenaClient = "ManhattanAthenaClient"
  final val ManhattanOmegaClient = "ManhattanOmegaClient"
  final val ManhattanStarbuckClient = "ManhattanStarbuckClient"
  final val MetricCenterUserCountingFeatureRepository = "MetricCenterUserCountingFeatureRepository"
  final val MinimumFeaturesScribeEventPublisher = "MinimumFeaturesScribeEventPublisher"
  final val RealGraphInNetworkScores = "RealGraphInNetworkScores"
  final val RealGraphManhattanEndpoint = "RealGraphFeaturesManhattanEndpoint"
  final val RealGraphFeatureRepository = "RealGraphFeatureRepository"
  final val RealTimeInteractionGraphUserVertexCache = "RealTimeInteractionGraphUserVertexCache"
  final val RealTimeInteractionGraphUserVertexClient = "RealTimeInteractionGraphUserVertexClient"
  final val StaleTweetsCache = "StaleTweetsCache"
  final val TimelineAggregateMetadataRepository = "TimelineAggregateMetadataRepository"
  final val TimelineAggregatePartARepository = "TimelineAggregatePartARepository"
  final val TimelineAggregatePartBRepository = "TimelineAggregatePartBRepository"
  final val TimelinesRealTimeAggregateClient = "TimelinesRealTimeAggregateClient"
  final val TopicCountryEngagementCache = "TopicCountryEngagementCache"
  final val TopicEngagementCache = "TopicEngagementCache"
  final val TweetCountryEngagementCache = "TweetCountryEngagementCache"
  final val TweetEngagementCache = "TweetEngagementCache"
  final val TweetypieContentRepository = "TweetypieContentRepository"
  final val TweetypieStaticEntitiesCache = "TweetypieStaticEntitiesCache"
  final val TwhinAuthorFollowFeatureCacheClient = "TwhinAuthorFollowFeatureCacheClient"
  final val TwhinAuthorFollowFeatureRepository = "TwhinAuthorFollowFeatureRepository"
  final val TwhinUserEngagementFeatureRepository = "TwhinUserEngagementFeatureRepository"
  final val TwhinUserFollowFeatureRepository = "TwhinUserFollowFeatureRepository"
  final val TwitterListEngagementCache = "TwitterListEngagementCache"
  final val UserAuthorEngagementCache = "UserAuthorEngagementCache"
  final val UserEngagementCache = "UserEngagementCache"
  final val UserFollowedTopicIdsRepository = "UserFollowedTopicIdsRepository"
  final val UserLanguagesRepository = "UserLanguagesRepository"
  final val UserTopicEngagementForNewUserCache = "UserTopicEngagementForNewUserCache"
  final val UtegSocialProofRepository = "UtegSocialProofRepository"
}
