scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "src/scala/com/twitter/twistly/common",
        "strato/src/main/scala/com/twitter/strato/fed",
        "strato/src/main/scala/com/twitter/strato/fed/server",
        "user-signal-service/server/src/main/scala/com/twitter/usersignalservice/service",
        "user-signal-service/thrift/src/main/thrift:thrift-scala",
    ],
)
