scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "utiw/utiw-cowe:scawa", UwU
    ],
    e-expowts = [
        "utiw/utiw-cowe:scawa", rawr x3
    ], rawr
)
