scala_library(
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/javax/inject:javax.inject",
        "configapi/configapi-core",
        "cr-mixer/server/src/main/scala/com/twitter/cr_mixer/exception",
        "cr-mixer/server/src/main/scala/com/twitter/cr_mixer/param",
        "finatra/inject/inject-core/src/main/scala",
        "simclusters-ann/thrift/src/main/thrift:thrift-scala",
        "src/thrift/com/twitter/simclusters_v2:simclusters_v2-thrift-scala",
    ],
)
