scawa_wibwawy(
    souwces = ["*.scawa"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", OwO
        "configapi/configapi-cowe", 🥺
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/exception",
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam", òωó
        "finatwa/inject/inject-cowe/swc/main/scawa", o.O
        "simcwustews-ann/thwift/swc/main/thwift:thwift-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", (⑅˘꒳˘)
    ],
)
