scala_library(
    sourcelons = ["*.scala"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "configapi/configapi-corelon",
        "cr-mixelonr/selonrvelonr/src/main/scala/com/twittelonr/cr_mixelonr/elonxcelonption",
        "cr-mixelonr/selonrvelonr/src/main/scala/com/twittelonr/cr_mixelonr/param",
        "finatra/injelonct/injelonct-corelon/src/main/scala",
        "simclustelonrs-ann/thrift/src/main/thrift:thrift-scala",
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-scala",
    ],
)
