java_wibwawy(
    souwces = ["*.java"], o.O
    pwatfowm = "java8", (U ᵕ U❁)
    p-pwovides = awtifact(
        o-owg = "com.twittew.seawch.common.utiw", (⑅˘꒳˘)
        n-nyame = "wang", ( ͡o ω ͡o )
        w-wepo = awtifactowy, UwU
    ),
    t-tags = ["bazew-compatibwe"], rawr x3
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/code/findbugs:jsw305", rawr
        "3wdpawty/jvm/com/googwe/guava", σωσ
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", σωσ
        "3wdpawty/jvm/owg/swf4j:swf4j-api", >_<
        "swc/java/com/twittew/common/text/wanguage:wocawe-utiw", :3
        "swc/thwift/com/twittew/seawch/common:constants-java", (U ﹏ U)
    ],
)
