scala_library(
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/injelonct:guicelon",
        "3rdparty/jvm/com/googlelon/injelonct/elonxtelonnsions:guicelon-assistelondinjelonct",
        "3rdparty/jvm/nelont/codingwelonll:scala-guicelon",
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "finatra/injelonct/injelonct-corelon/src/main/scala",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/baselon",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/constants",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/modelonls",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/rankelonrs/common",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/utils",
        "helonrmit/helonrmit-corelon/src/main/scala/com/twittelonr/helonrmit/constants",
        "util/util-slf4j-api/src/main/scala",
    ],
)
