scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", òωó
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", o.O
        "3wdpawty/jvm/net/codingweww:scawa-guice", (U ᵕ U❁)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (⑅˘꒳˘)
        "configapi/configapi-cowe", ( ͡o ω ͡o )
        "finatwa/inject/inject-cowe/swc/main/scawa", UwU
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/base",
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/gwaph_featuwe_sewvice", rawr x3
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/sociawgwaph", rawr
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/constants", σωσ
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", σωσ
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/utiws", >_<
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/configapi/decidews", :3
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", (U ﹏ U)
        "utiw/utiw-swf4j-api/swc/main/scawa", -.-
    ], (ˆ ﻌ ˆ)♡
)
