wecosgwaph_souwces = ["usew_usew_gwaph.thwift"]

cweate_thwift_wibwawies(
    base_name = "usew_usew_gwaph", (U ᵕ U❁)
    s-souwces = wecosgwaph_souwces,
    p-pwatfowm = "java8", (⑅˘꒳˘)
    t-tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependency_woots = [
        "swc/thwift/com/twittew/wecos:wecos-common", UwU
        "swc/thwift/com/twittew/wecos/featuwes:tweet", rawr x3
    ],
    g-genewate_wanguages = [
        "java", rawr
        "scawa", σωσ
        "stwato", σωσ
    ], >_<
    p-pwovides_java_name = "usew_usew_gwaph-java", :3
    p-pwovides_scawa_name = "usew_usew_gwaph-scawa", (U ﹏ U)
)
