scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon/strato",
        "src/thrift/com/twittelonr/ads/adselonrvelonr:adselonrvelonr_common-scala",
        "src/thrift/com/twittelonr/ads/adselonrvelonr:adselonrvelonr_rpc-scala",
        "strato/config/columns/ads/admixelonr:admixelonr-strato-clielonnt",
    ],
    elonxports = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon/strato",
        "src/thrift/com/twittelonr/ads/adselonrvelonr:adselonrvelonr_common-scala",
        "src/thrift/com/twittelonr/ads/adselonrvelonr:adselonrvelonr_rpc-scala",
    ],
)
