scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/bijection:thwift", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", UwU
        "configbus/cwient/swc/main/scawa/com/twittew/configbus/cwient", rawr x3
        "cweatives-containew/thwift/swc/main/thwift:cweatives-containew-sewvice-scawa", rawr
        "finagwe/finagwe-cowe/swc/main", σωσ
        "finagwe/finagwe-thwiftmux/swc/main/scawa", σωσ
        # "finatwa-intewnaw/kafka/swc/main/scawa/com/twittew/finatwa/kafka/pwoducews", >_<
        "finatwa-intewnaw/messaging/kafka/swc/main/scawa", :3
        "finatwa-intewnaw/thwift/swc/main/thwift:thwift-scawa", (U ﹏ U)
        "fwock-cwient/swc/main/scawa", -.-
        "fwock-cwient/swc/main/thwift:thwift-scawa", (ˆ ﻌ ˆ)♡
        # "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", (⑅˘꒳˘)
        "wimitew/thwift-onwy/swc/main/thwift:thwift-scawa", (U ᵕ U❁)
        "mediasewvices/mediainfo-sewvew/thwift/swc/main/thwift:thwift-scawa", -.-
        "tweetypie/sewvo/utiw", ^^;;
        "swc/thwift/com/twittew/datapwoducts:sewvice-scawa", >_<
        "swc/thwift/com/twittew/eschewbiwd:annotation-sewvice-scawa", mya
        "swc/thwift/com/twittew/eschewbiwd:tweet-annotation-scawa", mya
        "swc/thwift/com/twittew/eschewbiwd/metadata:metadata-sewvice-scawa", 😳
        "swc/thwift/com/twittew/expandodo:onwy-scawa", XD
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", :3
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", 😳😳😳
        "swc/thwift/com/twittew/sewvice/scawecwow/gen:scawecwow-scawa", -.-
        "swc/thwift/com/twittew/sewvice/scawecwow/gen:tiewed-actions-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/sewvice/tawon/gen:thwift-scawa", rawr x3
        "swc/thwift/com/twittew/sewvo:sewvo-exception-scawa", nyaa~~
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", /(^•ω•^)
        "swc/thwift/com/twittew/timewinesewvice:thwift-scawa", rawr
        "swc/thwift/com/twittew/timewinesewvice/sewvew/intewnaw:thwift-scawa", OwO
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", (U ﹏ U)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", >_<
        "stitch/stitch-cowe", rawr x3
        "stowage/cwients/manhattan/cwient/swc/main/scawa", mya
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", nyaa~~
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/cowe", (⑅˘꒳˘)
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/stowage", rawr x3
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/utiw", (✿oωo)
        "usew-image-sewvice/thwift/swc/main/thwift:thwift-scawa", (ˆ ﻌ ˆ)♡
        "utiw/utiw-stats/swc/main/scawa", (˘ω˘)
    ],
)
