COURSE_ACTS(COURSE_BOB, _(" 1 BOB-OMBS BOMBENBERG"),
       _("BESIEGE KÖNIG BOB-OMB!")        , _("BESIEGE DEN SCHNELLEN KOOPA!")  , _("FLIEGE ZUR SCHWEBENDEN INSEL!"),
       _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("DURCHFLIEGE ALLE MÜNZENRINGE!") , _("BEFREIE DEN KETTENHUND!"))

COURSE_ACTS(COURSE_WF, _(" 2 WUMMPS WUCHTWALL"),
       _("BESIEGE KÖNIG WUMMP!")          , _("STEIGE AUF DIE BERGFESTUNG!")   , _("FLIEG INS BLAUE!"),
       _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("WECKE DIE EULE!")               , _("ZERSTÖRE DIE FELSWAND!"))

COURSE_ACTS(COURSE_JRB, _(" 3 PIRATENBUCHT PANIK"),
       _("TAUCHE IN DAS SCHIFFSWRACK!")   , _("LOCKE DEN AAL KANO HERAUS!")    , _("TAUCHE ZUR SCHATZHÖHLE!"),
       _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("FLIEGE ZU DEN STEINSÄULEN!")    , _("LAUFE DURCH DEN STRUDEL!"))

COURSE_ACTS(COURSE_CCM, _(" 4 BIBBERBERG BOB"),
       _("RUTSCHE AUF DER EISBAHN!")      , _("FINDE DAS PINGUINBABY!")        , _("BESIEGE DEN SCHNELLEN PINGUIN!"),
       _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("BAUE EINEN SCHNEEMANN!")        , _("DENKE AN DEN WANDSPRUNG!"))

COURSE_ACTS(COURSE_BBH, _(" 5 BIG BOOS BURG"),
       _("GEHE AUF GEISTERJAGD!")         , _("BESUCHE BIG BOOS KARUSSEL!")    , _("LÖSE DAS BÜCHEREI-RÄTSEL!"),
       _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("KLETTERE AUF BIG BOOS BALKON!") , _("FINDE DAS AUGE IM GEHEIMRAUM!"))

COURSE_ACTS(COURSE_HMC, _(" 6 GRÜNE GIFTGROTTE"),
       _("KLETTERE AUF NESSIS RÜCKEN!")   , _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("LAUFE AUF DEM GRUND DES SEES!"),
       _("DURCHSUCHE DAS NEBELLABYRINTH!"), _("SUCHE IM NEBEL DEN NOTAUSGANG!"), _("ACHTE AUF ROLLENDE FELSEN!"))

COURSE_ACTS(COURSE_LLL, _(" 7 LAVA LAGUNE"),
       _("WERFE BIG BULLY IN DIE LAVA!")  , _("WERFE DIE BULLIES IN DIE LAVA!"), _("FINDE DIE 8 ROTEN MÜNZEN!"),
       _("TANZE AUF DEM BAUMSTAMM!")      , _("ERKUNDE DEN VULKAN!")           , _("GEWINNE IM VULKAN AN HÖHE!"))

COURSE_ACTS(COURSE_SSL, _(" 8 WOBIWABA WÜSTE"),
       _("FOLGE DEM RIESENGEIER!")        , _("BRINGE LICHT IN DIE PYRAMIDE!") , _("BEGEBE DICH IN DIE PYRAMIDE!"),
       _("LANDE AUF ALLEN VIER SÄULEN!")  , _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("LÖSE DAS PYRAMIDENPUZZLE!"))

COURSE_ACTS(COURSE_DDD, _(" 9 WILDE WASSERWERFT"),
       _("ENTERE BOWSERS U-BOOT!")        , _("ÖFFNE DIE TRUHEN!")             , _("SPRINGE ZU DEN ROTEN MÜNZEN!"),
       _("SCHWIMME DURCH DIE RINGE!")     , _("FOLGE DEM FISCH!")              , _("VEREINE DIE MÜTZEN!"))

COURSE_ACTS(COURSE_SL, _("10 FROSTBEULEN FRUST"),
       _("ERKLIMME DEN KOPF!")            , _("SPIELE MIT BAD BULLY!")         , _("WAGE DICH INS EIS!"),
       _("GEHE ZUM EISSEE!")              , _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("SCHAU IM IGLU NACH!"))

COURSE_ACTS(COURSE_WDW, _("11 ATLANTIS AQUARIA"),
       _("FOLGE DEN BLAUEN PFEILEN!")     , _("SUCHE NACH DER SPITZE DER STADT!"), _("ERFORSCHE DIE HÖHEN UND TIEFEN!"),
       _("BEEILE DICH - EXPRESSAUFZUG!")  , _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("BEACHTE DAS ZEITLIMIT!"))

COURSE_ACTS(COURSE_TTM, _("12 FLIEGENPILZ FIASKO"),
       _("ERKLIMME DEN BERG!")            , _("ERKUNDE DEN AFFENKÄFIG!")       , _("FINDE DIE 8 ROTEN MÜNZEN!"),
       _("ERFORSCHE DIE STEILWAND!")      , _("HALTE AUSSCHAU AUF DER BRÜCKE!"), _("SUCHE DEN EINSAMEN PILZ!"))

COURSE_ACTS(COURSE_THI, _("13 GULLIVER GUMBA"),
       _("PFLÜCKE DIE SCHNAPP-PIRANHA!")  , _("BEGIB DICH ZUR SPITZE DER INSEL!"), _("TRETE NOCH EINMAL GEGEN KOOPA AN!"),
       _("LÖSE DIE 5 ITTY BITTY-RÄTSEL!") , _("FINDE DIE 8 ROTEN MÜNZEN!")     , _("DREHE WIGGLER IM KREIS!"))

COURSE_ACTS(COURSE_TTC, _("14 TICK TACK TRAUMA"),
       _("ROLLE DEN KÄFIG!")              , _("ACHTE AUF DAS PENDEL!")         , _("LASS DIR DEN WEG ZEIGEN!"),
       _("STAMPFE MÄCHTIG AUF!")          , _("SPRINGE AUF DEN SCHWEBEBALKEN!"), _("FINDE DIE 8 ROTEN MÜNZEN!"))

COURSE_ACTS(COURSE_RR, _("15 REGENBOGEN RASEREI"),
       _("REISE AUF DEN REGENBÖGEN!")     , _("SUCHE DAS HAUS AM HIMMEL!")     , _("FINDE DIE 8 ROTEN MÜNZEN!"),
       _("LASS DICH VON DER BRISE TRAGEN!"), _("ÜBERWINDE DIE MACHT DER DREIECKE!"), _("SCHAU DIR DEN REGENBOGEN AN!"))

SECRET_STAR(COURSE_BITDW, _("   BOWSERS SCHATTENWELT"))
SECRET_STAR(COURSE_BITFS, _("   BOWSERS LAVASEE"))
SECRET_STAR(COURSE_BITS, _("   BOWSERS LUFTSCHLOSS"))
SECRET_STAR(COURSE_PSS, _("   TOADSTOOLS RUTSCHBAHN"))
SECRET_STAR(COURSE_COTMC, _("   GRÜNER SCHALTERPALAST"))
SECRET_STAR(COURSE_TOTWC, _("   ROTER SCHALTERPALAST"))
SECRET_STAR(COURSE_VCUTM, _("   BLAUER SCHALTERPALAST"))
SECRET_STAR(COURSE_WMOTR, _("   REGENBOGEN FEUERWERK"))
SECRET_STAR(COURSE_SA, _("   VERSTECKTES AQUARIUM"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   GEHEIME STERNE"))

EXTRA_TEXT(0, _("EIN GEHEIMER STERN DES SCHLOSSES!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
