scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "configapi/configapi-corelon/src/main/scala/com/twittelonr/timelonlinelons/configapi",
        "configapi/configapi-deloncidelonr/src/main/scala/com/twittelonr/timelonlinelons/configapi/deloncidelonr",
        "selonrvo/deloncidelonr",
        "selonrvo/util/src/main/scala",
        "timelonlinelonrankelonr/common/src/main/scala/com/twittelonr/timelonlinelonrankelonr/modelonl",
        "timelonlinelonrankelonr/selonrvelonr/src/main/scala/com/twittelonr/timelonlinelonrankelonr/deloncidelonr",
        "timelonlinelonrankelonr/selonrvelonr/src/main/scala/com/twittelonr/timelonlinelonrankelonr/paramelontelonrs/util",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/elonxpelonrimelonnt",
        "util/util-logging",
        "util/util-stats",
    ],
)
