scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "abdecidew/swc/main/scawa", UwU
        "configapi/configapi-cowe", rawr x3
        "decidew/swc/main/scawa",
        "featuweswitches/featuweswitches-cowe/swc/main/scawa", rawr
        "sewvo/decidew/swc/main/scawa", σωσ
        "sewvo/utiw/swc/main/scawa", σωσ
        "stitch/stitch-cowe", >_<
        "utiw/utiw-wogging/swc/main/scawa", :3
        "utiw/utiw-stats/swc/main/scawa",
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions", (U ﹏ U)
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/stitch", -.-
        "visibiwity/wib/swc/main/wesouwces/config", (ˆ ﻌ ˆ)♡
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew", (⑅˘꒳˘)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi", (U ᵕ U❁)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/pawams", ^^;;
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/engine", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", mya
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/genewatows", mya
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/modews", 😳
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes", XD
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes/genewatows", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes/pwovidews", 😳😳😳
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/utiw", -.-
    ], ( ͡o ω ͡o )
    e-expowts = [
        "configapi/configapi-cowe", rawr x3
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions", nyaa~~
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew", /(^•ω•^)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi", rawr
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs", OwO
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/modews", (U ﹏ U)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes", >_<
    ], rawr x3
)
