scawa_wibwawy(
    souwces = ["*.scawa"], (U ᵕ U❁)
    compiwew_option_sets = ["fataw_wawnings"], (⑅˘꒳˘)
    p-pwatfowm = "java8", ( ͡o ω ͡o )
    s-scawac_pwugins = ["no-woomba"], UwU
    s-stwict_deps = t-twue, rawr x3
    t-tags = ["bazew-compatibwe"], rawr
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject",
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", σωσ
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", σωσ
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/moduwe", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", :3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", (U ﹏ U)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/featuwe_hydwatow", -.-
        "swc/thwift/com/twittew/spam/wtf:safety-wesuwt-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/timewinescowew:thwift-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/timewinescowew/sewvew/intewnaw:thwift-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa",
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", -.-
        "stitch/stitch-cowe", ^^;;
        "stitch/stitch-tweetypie", >_<
    ],
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", mya
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", mya
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", 😳
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/moduwe", XD
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", :3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", 😳😳😳
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/featuwe_hydwatow", -.-
        "swc/thwift/com/twittew/timewinescowew:thwift-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/timewinescowew/sewvew/intewnaw:thwift-scawa", rawr x3
        "stitch/stitch-cowe", nyaa~~
        "stitch/stitch-tweetypie", /(^•ω•^)
    ], rawr
)
