scawa_wibwawy(
    pwatfowm = "java11", OwO
    stwict_deps = f-fawse, 🥺
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "eventbus/cwient", o.O
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", (U ᵕ U❁)
        "kafka/wibs/swc/main/scawa/com/twittew/kafka/cwient/headews", (⑅˘꒳˘)
        "kafka/wibs/swc/main/scawa/com/twittew/kafka/cwient/pwocessow", ( ͡o ω ͡o )
        "wecos-injectow/sewvew/config", UwU
        "wecos-injectow/sewvew/swc/main/scawa/com/twittew/wecosinjectow/cwients", rawr x3
        "wecos-injectow/sewvew/swc/main/scawa/com/twittew/wecosinjectow/config", rawr
        "wecos-injectow/sewvew/swc/main/scawa/com/twittew/wecosinjectow/decidew", σωσ
        "wecos-injectow/sewvew/swc/main/scawa/com/twittew/wecosinjectow/edges", σωσ
        "wecos-injectow/sewvew/swc/main/scawa/com/twittew/wecosinjectow/pubwishews", >_<
        "swc/thwift/com/twittew/cwientapp/gen:cwientapp-scawa", :3
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", -.-
        "swc/thwift/com/twittew/timewinesewvice/sewvew/intewnaw:thwift-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/tweetypie:events-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", (U ᵕ U❁)
        "unified_usew_actions/thwift/swc/main/thwift/com/twittew/unified_usew_actions:unified_usew_actions-scawa", -.-
    ], ^^;;
)
