java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/wog4j",
        "3wdpawty/jvm/owg/swf4j:swf4j-api", o.O
        "swc/java/com/twittew/common/cowwections", (U ᵕ U❁)
        "swc/java/com/twittew/common/quantity", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/futuwes", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/wogging", UwU
        "swc/java/com/twittew/seawch/common/metwics", rawr x3
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", rawr
        "swc/java/com/twittew/seawch/common/wewevance:utiws", σωσ
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", σωσ
        "swc/java/com/twittew/seawch/common/seawch", >_<
        "swc/java/com/twittew/seawch/common/utiw:finagweutiw", :3
        "swc/java/com/twittew/seawch/common/utiw/eawwybiwd", (U ﹏ U)
        "swc/java/com/twittew/seawch/eawwybiwd_woot/cowwectows", -.-
        "swc/java/com/twittew/seawch/eawwybiwd_woot/common", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/quewypawsew/quewy:cowe-quewy-nodes", (⑅˘꒳˘)
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", (U ᵕ U❁)
        "swc/thwift/com/twittew/seawch/common:quewy-java", -.-
    ],
)
