scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], σωσ
    pwatfowm = "java8", >_<
    t-tags = ["bazew-compatibwe"], :3
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", (U ﹏ U)
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", -.-
        "3wdpawty/jvm/net/codingweww:scawa-guice", (ˆ ﻌ ˆ)♡
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (⑅˘꒳˘)
        "finatwa/inject/inject-cowe/swc/main/scawa", (U ᵕ U❁)
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/base", -.-
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/deepbiwdv2", ^^;;
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/constants", >_<
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/featuwe_hydwation/souwces", mya
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", mya
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/wankews/common", 😳
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/wankews/mw_wankew/scowing", XD
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/wankews/utiws", :3
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/utiws", 😳😳😳
        "swc/java/com/twittew/mw/api:api-base", -.-
        "utiw/utiw-swf4j-api/swc/main/scawa", ( ͡o ω ͡o )
    ],
)

# t-this i-is to impowt onwy t-the pawams fwom m-mwwankew, rawr x3 fow i-instance to get w-wequest-wevew heavy wankew. nyaa~~
scawa_wibwawy(
    nyame = "mw_wankew_pawams", /(^•ω•^)
    souwces = [
        "mwwankewpawams.scawa", rawr
    ], OwO
    pwatfowm = "java8", (U ﹏ U)
    t-tags = ["bazew-compatibwe"], >_<
    dependencies = [
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/wankews/common", rawr x3
        "timewines/swc/main/scawa/com/twittew/timewines/config/configapi", mya
    ],
)
