scala_library(
    sourcelons = [
        "*.scala",
        "common/*.scala",
    ],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "elonschelonrbird/src/scala/com/twittelonr/elonschelonrbird/scalding/sourcelon",
        "intelonrelonsts-ds/src/main/scala/com/twittelonr/intelonrelonsts_ds/jobs/intelonrelonsts_selonrvicelon",
        "intelonrelonsts-ds/src/main/scala/com/twittelonr/intelonrelonsts_ds/jobs/intelonrelonsts_selonrvicelon:uselonr_topic_relonlation_snapshot-scala",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/catalog/dataselonts/timelonlinelons:timelonlinelons-uselonr-topic-aggrelongatelons",
        "src/scala/com/twittelonr/onboarding/relonlelonvancelon/sourcelon:utt_account_reloncommelonndations-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:simclustelonrs_v2_elonmbelonddings_litelon-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:uselonr_topic_welonightelond_elonmbelondding-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons/prelonsto_hdfs_sourcelons",
        "src/scala/com/twittelonr/simclustelonrs_v2/scalding/common",
        "src/scala/com/twittelonr/simclustelonrs_v2/scalding/common/matrix",
        "src/scala/com/twittelonr/simclustelonrs_v2/scalding/elonmbelondding",
        "src/scala/com/twittelonr/timelonlinelons/prelondiction/common/aggrelongatelons:uselonr_topic_aggrelongatelons-scala",
        "src/scala/com/twittelonr/wtf/elonntity_relonal_graph/common",
        "src/scala/com/twittelonr/wtf/elonntity_relonal_graph/scalding/common",
        "src/scala/com/twittelonr/wtf/scalding/jobs/common:elonxeloncution_app",
        "src/scala/com/twittelonr/wtf/scalding/jobs/common:sourcelons",
        "src/scala/com/twittelonr/wtf/scalding/jobs/common:stats_util",
        "timelonlinelons/data_procelonssing/ml_util/aggrelongation_framelonwork:common_typelons",
        "timelonlinelons/data_procelonssing/ml_util/aggrelongation_framelonwork/convelonrsion",
        "timelonlinelons/data_procelonssing/ml_util/aggrelongation_framelonwork/melontrics",
        "timelonlinelons/data_procelonssing/ml_util/aggrelongation_framelonwork/scalding",
    ],
)

hadoop_binary(
    namelon = "fav_tfg_topic_elonmbelonddings-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.FavTfgTopicelonmbelonddingsAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":tfg"],
)

hadoop_binary(
    namelon = "fav_tfg_topic_elonmbelonddings_2020-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.FavTfgTopicelonmbelonddings2020AdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":tfg"],
)

hadoop_binary(
    namelon = "fav_tfg_topic_elonmbelonddings",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.FavTfgTopicelonmbelonddingsSchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":tfg"],
)

hadoop_binary(
    namelon = "fav_tfg_topic_elonmbelonddings_2020",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.FavTfgTopicelonmbelonddings2020SchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":tfg"],
)

hadoop_binary(
    namelon = "logfav_tfg_topic_elonmbelonddings-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.LogFavTfgTopicelonmbelonddingsAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":tfg"],
)

hadoop_binary(
    namelon = "logfav_tfg_topic_elonmbelonddings",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.LogFavTfgTopicelonmbelonddingsSchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":tfg"],
)

hadoop_binary(
    namelon = "fav_infelonrrelond_lang_tfg_topic_elonmbelonddings-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.FavInfelonrrelondLanguagelonTfgBaselondTopicelonmbelonddingsAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":tfg"],
)

hadoop_binary(
    namelon = "fav_infelonrrelond_lang_tfg_topic_elonmbelonddings",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.FavInfelonrrelondLanguagelonTfgBaselondTopicelonmbelonddingsSchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":tfg"],
)

hadoop_binary(
    namelon = "fav_tfg_topic_elonmbelonddings_2020_copy",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.FavTfgTopicelonmbelonddings2020CopySchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":tfg"],
)

scalding_job(
    namelon = "fav_welonightelond_uselonr_topic_tfg_elonmbelonddings_adhoc_job",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.elonngagelonmelonntWelonightelondTfgBaselondTopicelonmbelonddingsAdhocJob",
    config = [
        ("hadoop.relonducelon.jvm.total-melonmory", "8192m"),
        ("hadoop.combinelon-input", "truelon"),
        (
            "job.args",
            ["--datelon 2021-10-28"],
        ),
    ],
    hadoop_clustelonr = "atla-proc3",  #"qus1-bluelonbird",
    platform = "java8",
    rolelon = "cassowary",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":tfg",
    ],
)

scalding_job(
    namelon = "fav_welonightelond_uselonr_topic_tfg_elonmbelonddings_batch_job",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.tfg.elonngagelonmelonntWelonightelondTfgBaselondTopicelonmbelonddingsSchelondulelonJob",
    args = [],
    config = [
        ("hadoop.relonducelon.jvm.total-melonmory", "8192m"),
        ("hadoop.combinelon-input", "truelon"),
        ("submittelonr.clustelonr", "atla"),
    ],
    cron = "0 1 * * *",
    hadoop_clustelonr = "atla-proc3",
    platform = "java8",
    rolelon = "cassowary",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":tfg",
    ],
)
