scawa_wibwawy(
    souwces = ["com/twittew/timewinewankew/cwient/*.scawa"], (ꈍᴗꈍ)
    pwatfowm = "java8", ^•ﻌ•^
    tags = ["bazew-compatibwe"], OwO
    d-dependencies = [
        "finagwe/finagwe-cowe/swc/main", 🥺
        "finagwe/finagwe-stats", òωó
        "finagwe/finagwe-thwift/swc/main/java", o.O
        "sewvo/cwient/swc/main/scawa/com/twittew/sewvo/cwient", (U ᵕ U❁)
        "swc/thwift/com/twittew/timewinewankew:thwift-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/timewinewankew/sewvew/modew:thwift-scawa", ( ͡o ω ͡o )
        "timewinewankew/common:modew", UwU
        "timewines/swc/main/scawa/com/twittew/timewines/utiw/stats", rawr x3
        "utiw/utiw-stats/swc/main/scawa", rawr
    ],
)
      "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/stowe/gizmoduck", >_<
        "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/stowe/tweetypie", :3
        "wecos-injectow/sewvew/swc/main/scawa/com/twittew/wecosinjectow/decidew", (U ﹏ U)
        "scwibewib/vawidatows/swc/main/scawa/com/twittew/scwibewib/vawidatows", -.-
        "swc/scawa/com/twittew/stowehaus_intewnaw/memcache", (ˆ ﻌ ˆ)♡
        "swc/scawa/com/twittew/stowehaus_intewnaw/memcache/config", (⑅˘꒳˘)
        "swc/scawa/com/twittew/stowehaus_intewnaw/utiw", (U ᵕ U❁)
        "swc/thwift/com/twittew/gizmoduck:thwift-java", -.-
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", ^^;;
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa",
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", >_<
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", mya
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", mya
        "stitch/stitch-cowe", 😳
        "stitch/stitch-sociawgwaph", XD
        "stitch/stitch-stowehaus/swc/main/scawa", :3
        "stitch/stitch-tweetypie/swc/main/scawa", 😳😳😳
        "utiw/utiw-hashing/swc/main/scawa", -.-
        "utiw/utiw-wogging/swc/main/scawa", ( ͡o ω ͡o )
    ],
)
