scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "ads-common/woggingcwient/swc/main/scawa", (⑅˘꒳˘)
        "swc/scawa/com/twittew/ads/intewnaw/pcw/sewvice", ( ͡o ω ͡o )
        "swc/scawa/com/twittew/ads/intewnaw/pcw/stwato_adaptow", UwU
        "swc/thwift/com/twittew/ads/adsewvew:ads_shawed_types-scawa", rawr x3
        "swc/thwift/com/twittew/ads/cawwback:engagement_wequest-scawa", rawr
        "swc/thwift/com/twittew/ads/intewnaw/pcw:pwomoted_content_input-scawa", σωσ
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet_sewvice_gwaphqw-scawa", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/sewvew/context", >_<
        "twittew-context/swc/main/scawa",
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats", :3
    ],
)
