scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/spam/rtf:twelonelont-rtf-elonvelonnt-scala",
        "src/thrift/com/twittelonr/twelonelontypielon:elonvelonnts-scala",
        "src/thrift/com/twittelonr/twelonelontypielon:twelonelont-scala",
        "stitch/stitch-corelon",
        "visibility/common/src/main/scala/com/twittelonr/visibility/common",
        "visibility/common/src/main/thrift/com/twittelonr/visibility:action-scala",
        "visibility/lib/src/main/relonsourcelons/config",
        "visibility/lib/src/main/scala/com/twittelonr/visibility",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/buildelonr/twelonelonts",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/buildelonr/uselonrs",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/felonaturelons",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/intelonrfacelons/common/twelonelonts",
    ],
    elonxports = [
        "visibility/lib/src/main/scala/com/twittelonr/visibility",
    ],
)
