scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/spotify:annoy-java", (⑅˘꒳˘)
        "3wdpawty/jvm/com/spotify:annoy-snapshot", ( ͡o ω ͡o )
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", UwU
        "ann/swc/main/scawa/com/twittew/ann/common", rawr x3
        "ann/swc/main/scawa/com/twittew/ann/fiwe_stowe", rawr
        "ann/swc/main/thwift/com/twittew/ann/common:ann-common-scawa", σωσ
        "mediasewvices/commons", σωσ
        "swc/java/com/twittew/seawch/common/fiwe", >_<
        "swc/scawa/com/twittew/mw/api/embedding", :3
    ], (U ﹏ U)
    e-expowts = [
        "ann/swc/main/scawa/com/twittew/ann/common", -.-
        "swc/java/com/twittew/common_intewnaw/hadoop", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/common/fiwe", (⑅˘꒳˘)
        "swc/scawa/com/twittew/mw/api/embedding", (U ᵕ U❁)
    ],
)
