crelonatelon_thrift_librarielons(
    baselon_namelon = "thrift",
    sourcelons = ["*.thrift"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncy_roots = [
        "finatra-intelonrnal/thrift/src/main/thrift",
        "follow-reloncommelonndations-selonrvicelon/thrift/src/main/thrift/logging:thrift",
        "product-mixelonr/corelon/src/main/thrift/com/twittelonr/product_mixelonr/corelon:thrift",
        "src/thrift/com/twittelonr/ads/adselonrvelonr:adselonrvelonr_common",
        "src/thrift/com/twittelonr/ml/api:data",
        "src/thrift/com/twittelonr/suggelonsts/controllelonr_data",
    ],
    gelonnelonratelon_languagelons = [
        "java",
        "scala",
        "strato",
    ],
    providelons_java_namelon = "follow-reloncommelonndations-java",
    providelons_scala_namelon = "follow-reloncommelonndations-scala",
)
