scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "follow-recommendations-service/common/src/main/scala/com/X/follow_recommendations/common/models",
        "util/util-core/src/main/scala/com/X/conversions",
    ],
)
