scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "content-recommender/thrift/src/main/thrift:thrift-scala",
        "finatra/inject/inject-core/src/main/scala",
        "representation-scorer/server/src/main/scala/com/X/representationscorer/common",
        "representation-scorer/server/src/main/scala/com/X/representationscorer/modules",
        "representation-scorer/server/src/main/scala/com/X/representationscorer/scorestore",
        "representation-scorer/server/src/main/scala/com/X/representationscorer/twistlyfeatures",
        "representation-scorer/server/src/main/thrift:thrift-scala",
        "strato/src/main/scala/com/X/strato/fed",
        "strato/src/main/scala/com/X/strato/fed/server",
    ],
)
