scawa_wibwawy(
    souwces = ["*.scawa"], :3
    pwatfowm = "java8", 😳😳😳
    t-tags = ["bazew-compatibwe"], -.-
    d-dependencies = [
        ":data_souwces", ( ͡o ω ͡o )
        "3wdpawty/swc/jvm/com/twittew/scawding:cowe", rawr x3
        "swc/scawa/com/twittew/scawding_intewnaw/dawv2", nyaa~~
        "swc/scawa/com/twittew/scawding_intewnaw/muwtifowmat/fowmat", /(^•ω•^)
        "swc/scawa/com/twittew/scawding_intewnaw/souwce/wzo_scwooge", rawr
        "swc/scawa/com/twittew/simcwustews_v2/common", OwO
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/wtf/entity_weaw_gwaph:entity_weaw_gwaph-thwift-scawa", >_<
    ], rawr x3
)

s-scawa_wibwawy(
    n-nyame = "data_souwces", mya
    souwces = [], nyaa~~
    d-descwiption = "daw d-datasets we w-wish to expose extewnawwy", (⑅˘꒳˘)
    p-pwatfowm = "java8", rawr x3
    tags = ["bazew-compatibwe"], (✿oωo)
    dependencies = [
        ":wevewse_index_semantic_cowe_pew_wanguage_simcwustews_embeddings_pwesto-scawa", (ˆ ﻌ ˆ)♡
        ":semantic_cowe_pew_wanguage_simcwustews_embeddings_pwesto-scawa", (˘ω˘)
        "swc/scawa/com/twittew/simcwustews_v2/common", (⑅˘꒳˘)
    ],
)

cweate_datasets(
    base_name = "wevewse_index_semantic_cowe_pew_wanguage_simcwustews_embeddings_pwesto", (///ˬ///✿)
    java_schema = "com.twittew.simcwustews_v2.thwiftjava.intewnawidembeddingwithid", 😳😳😳
    p-pwatfowm = "java8", 🥺
    wowe = "cassowawy", mya
    scawa_schema = "com.twittew.simcwustews_v2.thwiftscawa.intewnawidembeddingwithid", 🥺
    s-segment_type = "snapshot", >_<
    tags = ["bazew-compatibwe"], >_<
    j-java_dependencies = [
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-java", (⑅˘꒳˘)
    ],
    scawa_dependencies = [
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", /(^•ω•^)
    ],
)

cweate_datasets(
    base_name = "semantic_cowe_pew_wanguage_simcwustews_embeddings_pwesto", rawr x3
    j-java_schema = "com.twittew.simcwustews_v2.thwiftjava.simcwustewsembeddingwithid",
    pwatfowm = "java8", (U ﹏ U)
    w-wowe = "cassowawy", (U ﹏ U)
    s-scawa_schema = "com.twittew.simcwustews_v2.thwiftscawa.simcwustewsembeddingwithid", (⑅˘꒳˘)
    segment_type = "snapshot", òωó
    tags = ["bazew-compatibwe"], ʘwʘ
    java_dependencies = [
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-java", /(^•ω•^)
    ],
    scawa_dependencies = [
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", ʘwʘ
    ],
)
