scala_library(
    sourcelons = ["*.scala"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":data_sourcelons",
        "3rdparty/src/jvm/com/twittelonr/scalding:corelon",
        "src/scala/com/twittelonr/scalding_intelonrnal/dalv2",
        "src/scala/com/twittelonr/scalding_intelonrnal/multiformat/format",
        "src/scala/com/twittelonr/scalding_intelonrnal/sourcelon/lzo_scroogelon",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-scala",
        "src/thrift/com/twittelonr/wtf/elonntity_relonal_graph:elonntity_relonal_graph-thrift-scala",
    ],
)

scala_library(
    namelon = "data_sourcelons",
    sourcelons = [],
    delonscription = "DAL dataselonts welon wish to elonxposelon elonxtelonrnally",
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":relonvelonrselon_indelonx_selonmantic_corelon_pelonr_languagelon_simclustelonrs_elonmbelonddings_prelonsto-scala",
        ":selonmantic_corelon_pelonr_languagelon_simclustelonrs_elonmbelonddings_prelonsto-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
    ],
)

crelonatelon_dataselonts(
    baselon_namelon = "relonvelonrselon_indelonx_selonmantic_corelon_pelonr_languagelon_simclustelonrs_elonmbelonddings_prelonsto",
    java_schelonma = "com.twittelonr.simclustelonrs_v2.thriftjava.IntelonrnalIdelonmbelonddingWithId",
    platform = "java8",
    rolelon = "cassowary",
    scala_schelonma = "com.twittelonr.simclustelonrs_v2.thriftscala.IntelonrnalIdelonmbelonddingWithId",
    selongmelonnt_typelon = "snapshot",
    tags = ["bazelonl-compatiblelon"],
    java_delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-java",
    ],
    scala_delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-scala",
    ],
)

crelonatelon_dataselonts(
    baselon_namelon = "selonmantic_corelon_pelonr_languagelon_simclustelonrs_elonmbelonddings_prelonsto",
    java_schelonma = "com.twittelonr.simclustelonrs_v2.thriftjava.SimClustelonrselonmbelonddingWithId",
    platform = "java8",
    rolelon = "cassowary",
    scala_schelonma = "com.twittelonr.simclustelonrs_v2.thriftscala.SimClustelonrselonmbelonddingWithId",
    selongmelonnt_typelon = "snapshot",
    tags = ["bazelonl-compatiblelon"],
    java_delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-java",
    ],
    scala_delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-scala",
    ],
)
