package com.twitter.simclusters_v2.hdfs_sources.presto_hdfs_sources

object EntityEmbeddingsPrestoSources {

  final val SemanticCorePerLanguageSimClustersEmbeddingsDataset =
    SemanticCorePerLanguageSimclustersEmbeddingsPrestoScalaDataset

  final val ReverseIndexSemanticCorePerLanguageSimClustersEmbeddingsDataset =
    ReverseIndexSemanticCorePerLanguageSimclustersEmbeddingsPrestoScalaDataset
}
