packagelon com.twittelonr.simclustelonrs_v2.hdfs_sourcelons.prelonsto_hdfs_sourcelons

objelonct elonntityelonmbelonddingsPrelonstoSourcelons {

  final val SelonmanticCorelonPelonrLanguagelonSimClustelonrselonmbelonddingsDataselont =
    SelonmanticCorelonPelonrLanguagelonSimclustelonrselonmbelonddingsPrelonstoScalaDataselont

  final val RelonvelonrselonIndelonxSelonmanticCorelonPelonrLanguagelonSimClustelonrselonmbelonddingsDataselont =
    RelonvelonrselonIndelonxSelonmanticCorelonPelonrLanguagelonSimclustelonrselonmbelonddingsPrelonstoScalaDataselont
}
