crelonatelon_thrift_librarielons(
    baselon_namelon = "intelonraction_graph",
    sourcelons = ["*.thrift"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncy_roots = [
    ],
    gelonnelonratelon_languagelons = [
        "java",
        "scala",
        "strato",
    ],
    providelons_java_namelon = "intelonraction_graph-thrift-java",
    providelons_scala_namelon = "intelonraction_graph-thrift-scala",
)
