// 0x0500C778
const GeoLayout wiggler_body_geo[] = {
    GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0x96, 0x64),
    GEO_OPEN_NODE(),
      GEO_SCALE(0, 16384),
      GEO_OPEN_NODE(),
        GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
        GEO_OPEN_NODE(),
          GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
          GEO_OPEN_NODE(),
            GEO_BILLBOARD(),
            GEO_OPEN_NODE(),
              GEO_DISPLAY_LIST(LAYER_ALPHA, wiggler_seg5_dl_0500C278),
            GEO_CLOSE_NODE(),
          GEO_CLOSE_NODE(),
          GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(1, -31, 0, 51, NULL),
            GEO_OPEN_NODE(),
              GEO_ANIMATED_PART(1, 0, 0, 0, wiggler_seg5_dl_0500BE98),
              GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 39, 0, 0, wiggler_seg5_dl_0500BE10),
                GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(1, 41, 0, 0, wiggler_seg5_dl_0500BCB8),
                GEO_CLOSE_NODE(),
              GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(1, -31, 0, -49, NULL),
            GEO_OPEN_NODE(),
              GEO_ANIMATED_PART(1, 0, 0, 0, wiggler_seg5_dl_0500C100),
              GEO_OPEN_NODE(),
                GEO_ANIMATED_PART(1, 39, 0, 0, wiggler_seg5_dl_0500C078),
                GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(1, 41, 0, 0, wiggler_seg5_dl_0500BF20),
                GEO_CLOSE_NODE(),
              GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
          GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
