scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", ( ͡o ω ͡o )
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", UwU
        "mediasewvices/media-utiw/swc/main/scawa",
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", rawr x3
        "swc/thwift/com/twittew/context:twittew-context-scawa", rawr
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", σωσ
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", σωσ
        "swc/thwift/com/twittew/spam/wtf:tweet-wtf-event-scawa", >_<
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", :3
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", (U ﹏ U)
        "stitch/stitch-cowe", -.-
        "tweetypie/swc/scawa/com/twittew/tweetypie/additionawfiewds",
        "twittew-context/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", (⑅˘꒳˘)
        "visibiwity/wib/swc/main/wesouwces/config", (U ᵕ U❁)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/tweets", ^^;;
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/usews", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", mya
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/common/tweets", mya
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/utiw", 😳
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/safety_wabew_stowe:safety-wabew-stowe-scawa", XD
    ],
)
