scala_library(
    sourcelons = [
        "*.scala",
    ],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "src/scala/com/twittelonr/selonarch/blelonndelonr/selonrvicelons/strato",
        "src/thrift/com/twittelonr/selonarch/common:constants-scala",
        "stitch/stitch-corelon",
    ],
)
