scawa_wibwawy(
    souwces = [
        "*.scawa", 🥺
    ],
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "swc/scawa/com/twittew/seawch/bwendew/sewvices/stwato", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/seawch/common:constants-scawa", UwU
        "stitch/stitch-cowe", rawr x3
    ],
)
