scawa_wibwawy(
    souwces = [
        "unifiedusewactionssouwcescwooge.scawa", >_<
    ], :3
    compiwew_option_sets = ["fataw_wawnings"], (U ﹏ U)
    # o-ouw wuntime i-is using j-java 11, -.- but fow c-compatibiwity with o-othew intewnaw w-wibwawies that
    # a-awe stiww o-on java 8, (ˆ ﻌ ˆ)♡ we'ww make ouw tawget pwatfowm to be java 8 as weww untiw evewyone c-can
    # migwate. (⑅˘꒳˘)
    pwatfowm = "java8", (U ᵕ U❁)
    tags = ["bazew-compatibwe"], -.-
    dependencies = [
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:cowe", ^^;;
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:stowm", >_<
        "3wdpawty/swc/jvm/com/twittew/towmenta:cowe", mya
        "swc/scawa/com/twittew/summingbiwd_intewnaw/souwces/common", mya
        "swc/scawa/com/twittew/towmenta_intewnaw/scheme", 😳
        "swc/scawa/com/twittew/towmenta_intewnaw/spout:kafka2", XD
        "unified_usew_actions/cwient/swc/main/scawa/com/twittew/unified_usew_actions/cwient/config",
        "unified_usew_actions/thwift/swc/main/thwift/com/twittew/unified_usew_actions:unified_usew_actions-scawa", :3
    ],
)
