scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "abdecidew/swc/main/scawa", ( ͡o ω ͡o )
        "configapi/configapi-cowe", UwU
        "sewvo/utiw/swc/main/scawa", rawr x3
        "swc/thwift/com/twittew/seawch/common:constants-scawa", rawr
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", σωσ
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", σωσ
        "stitch/stitch-cowe", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/pawams",
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", (U ﹏ U)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/modews",
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes/pwovidews", (ˆ ﻌ ˆ)♡
    ],
)
