cweate_thwift_wibwawies(
    owg = "com.twittew.unified_usew_actions.enwichew", òωó
    base_name = "intewnaw", o.O
    souwces = ["*.thwift"], (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependency_woots = [
        "swc/thwift/com/twittew/cwientapp/gen:cwientapp", ( ͡o ω ͡o )
        "unified_usew_actions/thwift/swc/main/thwift/com/twittew/unified_usew_actions", UwU
    ],
    g-genewate_wanguages = [
        "java", rawr x3
        "scawa", rawr
    ], σωσ
    p-pwovides_java_name = "enwichew_intewnaw-thwift-java", σωσ
    p-pwovides_scawa_name = "enwichew_intewnaw-thwift-scawa", >_<
)
