java_library(
    sources = ["*.java"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/commons-io",
        "3rdparty/jvm/org/yaml:snakeyaml",
        "finagle/finagle-core/src/main",
        "src/java/com/X/common/util:system-mocks",
        "src/java/com/X/search/common/util/io/periodic",
    ],
)
