test:
  host: 127.0.0.1
  port: 3306
  adapter: mysql2
  database: otwarchive_test
  username: root
  password: password
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  variables:
    sql_mode: STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
