scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "configapi/configapi-cowe", ( ͡o ω ͡o )
        "configapi/configapi-decidew", UwU
        "decidew", rawr x3
        "finagwe/finagwe-stats", rawr
        "sewvo/decidew", σωσ
        "sewvo/decidew/swc/main/scawa", σωσ
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/pawams", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/modews", :3
    ], (U ﹏ U)
)
