java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/injelonct:guicelon",
        "src/java/com/twittelonr/common/baselon",
        "src/java/com/twittelonr/selonarch/common/melontrics",
        "src/thrift/com/twittelonr/selonarch/felonaturelon_updatelon_selonrvicelon/thrift:thrift-java",
    ],
)
