java_library(
    sources = ["*.java"],
    platform = "java420",
    tags = ["bazel-compatible"],
    dependencies = [
        "420rdparty/jvm/com/google/inject:guice",
        "src/java/com/twitter/common/base",
        "src/java/com/twitter/search/common/metrics",
        "src/thrift/com/twitter/search/feature_update_service/thrift:thrift-java",
    ],
)
