scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    compiwew_option_sets = ["fataw_wawnings"], OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "sewvo/wepo/swc/main/scawa", òωó
        "swc/thwift/com/twittew/wtf/candidate:wtf-candidate-scawa", o.O
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/cowe", (U ᵕ U❁)
        "timewines:visibiwity", (⑅˘꒳˘)
        "timewines/swc/main/scawa/com/twittew/timewines/cwients/sociawgwaph", ( ͡o ω ͡o )
        "timewines/swc/main/scawa/com/twittew/timewines/utiw", UwU
        "timewines/swc/main/scawa/com/twittew/timewines/utiw/stats", rawr x3
        "utiw/utiw-cowe:utiw-cowe-utiw", rawr
        "utiw/utiw-wogging/swc/main/scawa", σωσ
        "utiw/utiw-stats/swc/main/scawa", σωσ
    ], >_<
)
