scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "selonrvo/relonpo/src/main/scala",
        "src/thrift/com/twittelonr/wtf/candidatelon:wtf-candidatelon-scala",
        "timelonlinelonrankelonr/selonrvelonr/src/main/scala/com/twittelonr/timelonlinelonrankelonr/corelon",
        "timelonlinelons:visibility",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/clielonnts/socialgraph",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/util",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/util/stats",
        "util/util-corelon:util-corelon-util",
        "util/util-logging/src/main/scala",
        "util/util-stats/src/main/scala",
    ],
)
