# java wibwawy fow featuwe encoding a-and decoding u-utiwities. rawr x3
java_wibwawy(
    s-souwces = ["*.java"], rawr
    p-pwatfowm = "java8", σωσ
    pwovides = a-awtifact(
        o-owg = "com.twittew.seawch.common", σωσ
        n-nyame = "encoding-featuwes", >_<
        w-wepo = awtifactowy,
    ), :3
    tags = ["bazew-compatibwe"], (U ﹏ U)
    dependencies = [
        "3wdpawty/jvm/com/googwe/guava", -.-
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/common/schema/base", (⑅˘꒳˘)
        "swc/thwift/com/twittew/seawch/common:indexing-java", (U ᵕ U❁)
    ],
)
