scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "abdeloncidelonr/src/main/scala",
        "configapi/configapi-abdeloncidelonr",
        "configapi/configapi-corelon",
        "configapi/configapi-felonaturelonswitchelons:v2",
        "deloncidelonr",
        "felonaturelonswitchelons/felonaturelonswitchelons-corelon/src/main/scala",
        "finaglelon/finaglelon-stats",
        "selonrvo/deloncidelonr/src/main/scala",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/configapi/configs",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/modelonls",
    ],
)
