scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "abdecidew/swc/main/scawa", ( ͡o ω ͡o )
        "configapi/configapi-abdecidew", UwU
        "configapi/configapi-cowe", rawr x3
        "configapi/configapi-featuweswitches:v2", rawr
        "decidew", σωσ
        "featuweswitches/featuweswitches-cowe/swc/main/scawa", σωσ
        "finagwe/finagwe-stats", >_<
        "sewvo/decidew/swc/main/scawa", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs", (U ﹏ U)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/modews", -.-
    ], (ˆ ﻌ ˆ)♡
)
