packagelon com.twittelonr.product_mixelonr.corelon.selonrvicelon.candidatelon_deloncorator_elonxeloncutor

import com.twittelonr.product_mixelonr.corelon.functional_componelonnt.deloncorator.Deloncoration
import com.twittelonr.product_mixelonr.corelon.selonrvicelon.elonxeloncutorRelonsult

caselon class CandidatelonDeloncoratorelonxeloncutorRelonsult(relonsult: Selonq[Deloncoration]) elonxtelonnds elonxeloncutorRelonsult
