scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = [
        "bazel-compatible",
    ],
    dependencies = [
        "finatra/inject/inject-thrift-client",
        "strato/src/main/scala/com/X/strato/fed",
        "strato/src/main/scala/com/X/strato/fed/server",
        "topic-social-proof/server/src/main/scala/com/X/tsp/columns",
    ],
)
