java_library(
    sources = ["*.java"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/log4j",
        "src/java/com/X/search/common/relevance:utils",
        "src/java/com/X/search/common/util/earlybird",
        "src/thrift/com/X/search:earlybird-java",
    ],
)
