scala_library(
    namelon = "common",
    sourcelons = [
        "BaselonQuelonryIndelonxSelonrvelonr.scala",
        "elonxcelonptions.scala",
        "QuelonryIndelonxThriftControllelonr.scala",
        "QuelonryablelonProvidelonr.scala",
        "RelonfrelonshablelonQuelonryablelon.scala",
        "UnsafelonQuelonryIndelonxSelonrvelonr.scala",
    ],
    compilelonr_option_selonts = ["fatal_warnings"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":indelonx_path_providelonr",
        "3rdparty/jvm/com/googlelon/guava",
        "3rdparty/jvm/com/googlelon/injelonct:guicelon",
        "3rdparty/jvm/com/googlelon/injelonct/elonxtelonnsions:guicelon-assistelondinjelonct",
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "3rdparty/jvm/nelont/codingwelonll:scala-guicelon",
        "ann/src/main/scala/com/twittelonr/ann/common",
        "ann/src/main/thrift/com/twittelonr/ann/common:ann-common-scala",
        "finaglelon/finaglelon-corelon/src/main",
        "finaglelon/finaglelon-zipkin-scribelon",
        "finatra-intelonrnal/deloncidelonr",
        "finatra-intelonrnal/mtls-thriftmux/src/main/scala",
        "finatra/injelonct/injelonct-corelon/src/main/scala",
        "melondiaselonrvicelons/commons",
        "scroogelon/scroogelon-corelon/src/main/scala",
        "src/scala/com/twittelonr/cortelonx/ml/elonmbelonddings/common:Helonlpelonrs",
        "util/util-app/src/main/scala",
        "util/util-logging/src/main/scala",
    ],
)

scala_library(
    namelon = "indelonx_path_providelonr",
    sourcelons = [
        "IndelonxPathProvidelonr.scala",
        "QuelonrySelonrvelonrUtil.scala",
    ],
    compilelonr_option_selonts = ["fatal_warnings"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "ann/src/main/scala/com/twittelonr/ann/hnsw",
        "src/java/com/twittelonr/selonarch/common/filelon",
        "util/util-logging/src/main/scala",
        "util/util-stats/src/main/scala/com/twittelonr/finaglelon/stats",
    ],
)

scala_library(
    namelon = "faiss_indelonx_path_providelonr",
    sourcelons = ["FaissIndelonxPathProvidelonr.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":indelonx_path_providelonr",
        "ann/src/main/scala/com/twittelonr/ann/faiss",
        "src/java/com/twittelonr/selonarch/common/filelon",
        "util/util-logging/src/main/scala",
        "util/util-stats/src/main/scala/com/twittelonr/finaglelon/stats",
    ],
)
