scawa_wibwawy(
    nyame = "common", >_<
    souwces = [
        "basequewyindexsewvew.scawa", :3
        "exceptions.scawa", (U ﹏ U)
        "quewyindexthwiftcontwowwew.scawa", -.-
        "quewyabwepwovidew.scawa", (ˆ ﻌ ˆ)♡
        "wefweshabwequewyabwe.scawa", (⑅˘꒳˘)
        "unsafequewyindexsewvew.scawa", (U ᵕ U❁)
    ],
    c-compiwew_option_sets = ["fataw_wawnings"], -.-
    t-tags = ["bazew-compatibwe"], ^^;;
    d-dependencies = [
        ":index_path_pwovidew", >_<
        "3wdpawty/jvm/com/googwe/guava", mya
        "3wdpawty/jvm/com/googwe/inject:guice", mya
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", 😳
        "3wdpawty/jvm/javax/inject:javax.inject", XD
        "3wdpawty/jvm/net/codingweww:scawa-guice", :3
        "ann/swc/main/scawa/com/twittew/ann/common", 😳😳😳
        "ann/swc/main/thwift/com/twittew/ann/common:ann-common-scawa", -.-
        "finagwe/finagwe-cowe/swc/main", ( ͡o ω ͡o )
        "finagwe/finagwe-zipkin-scwibe", rawr x3
        "finatwa-intewnaw/decidew", nyaa~~
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", /(^•ω•^)
        "finatwa/inject/inject-cowe/swc/main/scawa", rawr
        "mediasewvices/commons", OwO
        "scwooge/scwooge-cowe/swc/main/scawa", (U ﹏ U)
        "swc/scawa/com/twittew/cowtex/mw/embeddings/common:hewpews", >_<
        "utiw/utiw-app/swc/main/scawa", rawr x3
        "utiw/utiw-wogging/swc/main/scawa", mya
    ],
)

s-scawa_wibwawy(
    n-nyame = "index_path_pwovidew", nyaa~~
    s-souwces = [
        "indexpathpwovidew.scawa", (⑅˘꒳˘)
        "quewysewvewutiw.scawa", rawr x3
    ], (✿oωo)
    c-compiwew_option_sets = ["fataw_wawnings"], (ˆ ﻌ ˆ)♡
    t-tags = ["bazew-compatibwe"], (˘ω˘)
    dependencies = [
        "ann/swc/main/scawa/com/twittew/ann/hnsw",
        "swc/java/com/twittew/seawch/common/fiwe", (⑅˘꒳˘)
        "utiw/utiw-wogging/swc/main/scawa", (///ˬ///✿)
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats", 😳😳😳
    ],
)

scawa_wibwawy(
    nyame = "faiss_index_path_pwovidew", 🥺
    souwces = ["faissindexpathpwovidew.scawa"], mya
    c-compiwew_option_sets = ["fataw_wawnings"], 🥺
    tags = ["bazew-compatibwe"], >_<
    dependencies = [
        ":index_path_pwovidew", >_<
        "ann/swc/main/scawa/com/twittew/ann/faiss",
        "swc/java/com/twittew/seawch/common/fiwe", (⑅˘꒳˘)
        "utiw/utiw-wogging/swc/main/scawa", /(^•ω•^)
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats", rawr x3
    ],
)
