scawa_wibwawy(
    souwces = ["*.scawa"], UwU
    compiwew_option_sets = ["fataw_wawnings"], rawr x3
    p-pwatfowm = "java8", rawr
    p-pwovides = scawa_awtifact(
        o-owg = "com.twittew.tweetypie", σωσ
        n-nyame = "context", σωσ
        w-wepo = a-awtifactowy, >_<
    ),
    s-stwict_deps = t-twue, :3
    tags = ["bazew-compatibwe"], (U ﹏ U)
    dependencies = [
        "finagwe/finagwe-cowe/swc/main", -.-
        "gwaphqw/common/swc/main/scawa/com/twittew/gwaphqw/common/cowe", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/context:twittew-context-scawa", (⑅˘꒳˘)
        "twittew-context/swc/main/scawa", (U ᵕ U❁)
        "utiw/utiw-cowe:scawa", -.-
    ], ^^;;
)
