target(
    name = "earlybird_ranking",
    dependencies = [
        "timelines/data_processing/ad_hoc/earlybird_ranking/common",
        "timelines/data_processing/ad_hoc/earlybird_ranking/model_evaluation",
        "timelines/data_processing/ad_hoc/earlybird_ranking/training_data_generation",
    ],
)
