targelont(
    namelon = "elonarlybird_ranking",
    delonpelonndelonncielons = [
        "timelonlinelons/data_procelonssing/ad_hoc/elonarlybird_ranking/common",
        "timelonlinelons/data_procelonssing/ad_hoc/elonarlybird_ranking/modelonl_elonvaluation",
        "timelonlinelons/data_procelonssing/ad_hoc/elonarlybird_ranking/training_data_gelonnelonration",
    ],
)
