scala_library(
    sourcelons = ["*.scala"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/graphjelont",
        "snowflakelon:id",
        "snowflakelon/src/main/scala/com/twittelonr/snowflakelon/id",
        "src/scala/com/twittelonr/reloncos/util:reloncos-util",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
        "src/thrift/com/twittelonr/reloncos/uselonr_videlono_graph:uselonr_videlono_graph-scala",
    ],
)
