scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "user-signal-service/server/src/main/scala/com/twitter/usersignalservice/base",
        "user-signal-service/server/src/main/scala/com/twitter/usersignalservice/columns",
        "user-signal-service/server/src/main/scala/com/twitter/usersignalservice/config",
    ],
)
