scala_library(
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/X/algebird:core",
        "3rdparty/jvm/com/X/algebird:util",
        "servo/decider",
        "src/scala/com/X/storehaus_internal/manhattan",
        "src/thrift/com/X/ml/api:interpretable-model-java",
        "src/thrift/com/X/simclusters_v2:simclusters_v2-thrift-scala",
    ],
)
