java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/commons-wogging", òωó
        "3wdpawty/jvm/owg/apache/kafka:kafka-cwients", o.O
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (U ᵕ U❁)
        "decidew/swc/main/scawa", (⑅˘꒳˘)
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", ( ͡o ω ͡o )
        "swc/java/com/twittew/common/base", UwU
        "swc/java/com/twittew/common/utiw:system-mocks", rawr x3
        "swc/java/com/twittew/common_intewnaw/text/vewsion", rawr
        "swc/java/com/twittew/seawch/common/debug", σωσ
        "swc/java/com/twittew/seawch/common/decidew", σωσ
        "swc/java/com/twittew/seawch/common/metwics", >_<
        "swc/java/com/twittew/seawch/common/pawtitioning/base", :3
        "swc/java/com/twittew/seawch/common/wewevance:entities_and_fiwtews", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/utiw/io/kafka", -.-
        "swc/java/com/twittew/seawch/common/utiw/thwift:text-pwotocow", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/ingestew/modew", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/ingestew/pipewine/twittew", (U ᵕ U❁)
        "swc/java/com/twittew/seawch/ingestew/pipewine/utiw", -.-
        "swc/java/com/twittew/seawch/ingestew/pipewine/wiwe", ^^;;
        "swc/java/owg/apache/commons/pipewine", >_<
        "swc/thwift/com/twittew/seawch/common:indexing-java", mya
        "swc/thwift/com/twittew/seawch/common:schema-java", mya
        "swc/thwift/com/twittew/seawch/common/debug:debug-java", 😳
        "utiw/utiw-cowe:utiw-cowe-utiw", XD
        "utiw/utiw-cowe/swc/main/java/com/twittew/utiw/javaintewop", :3
    ],
)
