scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "product-mixer/core/src/main/scala/com/twitter/product_mixer/core/model/common",
        "util/util-slf4j-api/src/main/scala",
    ],
)
