scawa_wibwawy(
    nyame = "defauwt", (U ᵕ U❁)
    souwces = ["defauwtpawtitionew.scawa"], (⑅˘꒳˘)
    t-tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        ":base", UwU
        "unified_usew_actions/enwichew/swc/main/thwift/com/twittew/unified_usew_actions/enwichew/intewnaw:intewnaw-scawa", rawr x3
    ],
)

s-scawa_wibwawy(
    n-name = "base", rawr
    s-souwces = ["pawtitionew.scawa"], σωσ
    t-tags = ["bazew-compatibwe"], σωσ
    d-dependencies = [
        "unified_usew_actions/enwichew/swc/main/thwift/com/twittew/unified_usew_actions/enwichew/intewnaw:intewnaw-scawa", >_<
    ],
)
