scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "finagwe-intewnaw/swo/swc/main/scawa/com/twittew/finagwe/swo", òωó
        "finatwa/inject/inject-thwift-cwient", o.O
        "wepwesentation-scowew/sewvew/swc/main/scawa/com/twittew/wepwesentationscowew/cowumns", (U ᵕ U❁)
        "stwato/swc/main/scawa/com/twittew/stwato/fed", (⑅˘꒳˘)
        "stwato/swc/main/scawa/com/twittew/stwato/fed/sewvew", ( ͡o ω ͡o )
        "twittew-sewvew-intewnaw/swc/main/scawa", UwU
    ], rawr x3
)
