scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", UwU
        "configapi/configapi-cowe", rawr x3
        "configapi/configapi-decidew", rawr
        "sewvo/decidew", σωσ
        "utiw/utiw-cowe:utiw-cowe-utiw", σωσ
        "utiw/utiw-wogging", >_<
    ],
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", :3
        "configapi/configapi-cowe", (U ﹏ U)
        "configapi/configapi-decidew", -.-
        "sewvo/decidew", (ˆ ﻌ ˆ)♡
        "utiw/utiw-cowe:utiw-cowe-utiw", (⑅˘꒳˘)
        "utiw/utiw-wogging", (U ᵕ U❁)
    ],
)
