scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "configapi/configapi-corelon",
        "configapi/configapi-deloncidelonr",
        "selonrvo/deloncidelonr",
        "util/util-corelon:util-corelon-util",
        "util/util-logging",
    ],
    elonxports = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "configapi/configapi-corelon",
        "configapi/configapi-deloncidelonr",
        "selonrvo/deloncidelonr",
        "util/util-corelon:util-corelon-util",
        "util/util-logging",
    ],
)
