scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], (ꈍᴗꈍ)
    tags = [
        "bazew-compatibwe", ^•ﻌ•^
    ],
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", OwO
        "content-wecommendew/thwift/swc/main/thwift:thwift-scawa", 🥺
        "eschewbiwd/swc/thwift/com/twittew/eschewbiwd/topicannotation:topicannotation-thwift-scawa", òωó
        "fwigate/fwigate-common:utiw", o.O
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/stowe/heawth", (U ᵕ U❁)
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/stowe/intewests", (⑅˘꒳˘)
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/stowe/stwato", ( ͡o ω ͡o )
        "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/stowe/common", UwU
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", rawr x3
        "swc/scawa/com/twittew/simcwustews_v2/common", rawr
        "swc/scawa/com/twittew/simcwustews_v2/scowe", σωσ
        "swc/scawa/com/twittew/topic_wecos/common",
        "swc/scawa/com/twittew/topic_wecos/stowes", σωσ
        "swc/thwift/com/twittew/fwigate:fwigate-common-thwift-scawa", >_<
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", :3
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", -.-
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", (ˆ ﻌ ˆ)♡
        "stitch/stitch-stowehaus", (⑅˘꒳˘)
        "stitch/stitch-tweetypie/swc/main/scawa", (U ᵕ U❁)
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", -.-
        "topic-sociaw-pwoof/sewvew/swc/main/scawa/com/twittew/tsp/utiws", ^^;;
        "topic-sociaw-pwoof/sewvew/swc/main/thwift:thwift-scawa", >_<
        "topicwisting/topicwisting-cowe/swc/main/scawa/com/twittew/topicwisting", mya
    ],
)
