scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    pwatfowm = "java8", òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "tweetypie/sewvo/wepo", (⑅˘꒳˘)
        "tweetypie/sewvo/utiw", ( ͡o ω ͡o )
        "snowfwake:id", UwU
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", rawr x3
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/cowe", rawr
        "tweetypie/sewvew/swc/main/thwift:compiwed-scawa", σωσ
        "utiw/utiw-swf4j-api/swc/main/scawa/com/twittew/utiw/wogging", σωσ
    ], >_<
)
