scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "swc/scawa/com/twittew/scawding_intewnaw/job/anawytics_batch", òωó
    ],
)
