scala_library(
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "finagle/finagle-stats",
        "hermit/hermit-core/src/main/scala/com/twitter/hermit/store/common",
        "src/scala/com/twitter/simclusters_v2/stores",
    ],
)
