#include <ultra64.h>
#include "sm64.h"
#include "surface_terrains.h"
#include "moving_texture_macros.h"
#include "level_misc_macros.h"
#include "macro_preset_names.h"
#include "special_preset_names.h"
#include "textures.h"

#include "make_const_nonconst.h"
#include "levels/sa/texture.inc.c"
#include "levels/sa/areas/1/1/model.inc.c"
#include "levels/sa/areas/1/2/model.inc.c"
#include "levels/sa/areas/1/collision.inc.c"
#include "levels/sa/areas/1/macro.inc.c"
