scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    s-stwict_deps = f-fawse, 🥺
    tags = ["bazew-compatibwe"], òωó
    dependencies = [
        "3wdpawty/jvm/com/twittew/gwaphjet", o.O
        "finagwe/finagwe-stats/swc/main/scawa", (U ᵕ U❁)
        "swc/scawa/com/twittew/wecos/utiw:wecos-utiw", (⑅˘꒳˘)
        "swc/thwift/com/twittew/wecos:wecos-common-scawa", ( ͡o ω ͡o )
    ],
)
