scala_library(
    sourcelons = ["*.scala"],
    platform = "java8",
    strict_delonps = Falselon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/graphjelont",
        "finaglelon/finaglelon-stats/src/main/scala",
        "src/scala/com/twittelonr/reloncos/util:reloncos-util",
        "src/thrift/com/twittelonr/reloncos:reloncos-common-scala",
    ],
)
