scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/github/nscala_timelon",
        "3rdparty/jvm/com/googlelon/injelonct:guicelon",
        "3rdparty/jvm/com/googlelon/injelonct/elonxtelonnsions:guicelon-assistelondinjelonct",
        "3rdparty/jvm/nelont/codingwelonll:scala-guicelon",
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/clielonnts/strato",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/constants",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/modelonls",
        "follow-reloncommelonndations-selonrvicelon/thrift/src/main/thrift:thrift-scala",
        "src/thrift/com/twittelonr/onboarding/relonlelonvancelon/storelon:storelon-scala",
        "util/util-corelon:scala",
    ],
)
