scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon",
        "src/scala/com/twittelonr/ml/api/util:datareloncord",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/lib/data",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/lib/dynamic",
    ],
    elonxports = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon",
        "src/scala/com/twittelonr/ml/api/util:datareloncord",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/lib/data",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/lib/dynamic",
    ],
)
