scala_library(
    compiler_option_sets = ["fatal_warnings"],
    strict_deps = True,
    tags = ["bazel-compatible"],
    dependencies = [
        "finagle/finagle-core/src/main",
        "incentives/jiminy/src/main/thrift/com/twitter/incentives/jiminy:thrift-scala",
        "tweetypie/servo/util/src/main/scala",
        "stitch/stitch-core",
        "strato/src/main/scala/com/twitter/strato/client",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/core",
        "util/util-core",
        "util/util-stats",
    ],
)
