cweate_thwift_wibwawies(
    base_name = "thwift", o.O
    souwces = ["*.thwift"], (U ᵕ U❁)
    p-pwatfowm = "java8", (⑅˘꒳˘)
    t-tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependency_woots = [
        "swc/thwift/com/twittew/ads/adsewvew:adsewvew_common", UwU
        "swc/thwift/com/twittew/mw/api:data", rawr x3
        "swc/thwift/com/twittew/suggests/contwowwew_data", rawr
    ], σωσ
    g-genewate_wanguages = [
        "java", σωσ
        "scawa", >_<
        "stwato", :3
    ],
    p-pwovides_java_name = "fowwow-wecommendations-wogging-java", (U ﹏ U)
    p-pwovides_scawa_name = "fowwow-wecommendations-wogging-scawa", -.-
)
