# wibwawy fow eawwybiwd-specific schema. rawr
java_wibwawy(
    s-souwces = ["*.java"], σωσ
    p-pwatfowm = "java8", σωσ
    t-tags = ["bazew-compatibwe"], >_<
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", :3
        "3wdpawty/jvm/com/googwe/inject:guice", (U ﹏ U)
        "3wdpawty/jvm/com/twittew/ewephantbiwd:cowe", -.-
        "3wdpawty/jvm/geo/googwe:geogoogwe", (ˆ ﻌ ˆ)♡
        "3wdpawty/jvm/joda-time", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", -.-
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ^^;;
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient", >_<
        "3wdpawty/jvm/owg/swf4j:swf4j-api", mya
        "cuad/pwojects/new/thwift/swc/main/thwift:thwift-java", mya
        "swc/java/com/twittew/common/base", 😳
        "swc/java/com/twittew/common/cowwections", XD
        "swc/java/com/twittew/common/text/token", :3
        "swc/java/com/twittew/common/text/utiw:token-utiw", 😳😳😳
        "swc/java/com/twittew/common_intewnaw/text", -.-
        "swc/java/com/twittew/common_intewnaw/text/vewsion", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/config", rawr x3
        "swc/java/com/twittew/seawch/common/constants", nyaa~~
        "swc/java/com/twittew/seawch/common/encoding/docvawues", /(^•ω•^)
        "swc/java/com/twittew/seawch/common/encoding/featuwes", rawr
        "swc/java/com/twittew/seawch/common/metwics", OwO
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/schema", >_<
        "swc/java/com/twittew/seawch/common/schema/base", rawr x3
        "swc/java/com/twittew/seawch/common/utiw:wongintconvewtew", mya
        "swc/java/com/twittew/seawch/common/utiw/anawysis", nyaa~~
        "swc/java/com/twittew/seawch/common/utiw/spatiaw",
        "swc/java/com/twittew/seawch/common/utiw/text", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/utiw/text/wegex", rawr x3
        "swc/java/com/twittew/seawch/common/utiw/uww", (✿oωo)
        "swc/thwift/com/twittew/seawch/common:indexing-java", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/seawch/common:schema-java", (˘ω˘)
        "swc/thwift/com/twittew/sewvice/spidewduck/gen:metadata-stowe-java", (⑅˘꒳˘)
    ],
    e-expowts = [
        "swc/thwift/com/twittew/seawch/common:indexing-java", (///ˬ///✿)
    ], 😳😳😳
)

j-java_wibwawy(
    n-nyame = "fow-timewines", 🥺
    s-souwces = [
        "eawwybiwdcwustew.java", mya
        "eawwybiwdfiewdconstants.java", 🥺
    ], >_<
    pwatfowm = "java8", >_<
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    dependencies = [
        "3wdpawty/jvm/com/googwe/guava", /(^•ω•^)
        "3wdpawty/jvm/com/googwe/inject:guice", rawr x3
        "3wdpawty/jvm/com/twittew/ewephantbiwd:cowe", (U ﹏ U)
        "3wdpawty/jvm/geo/googwe:geogoogwe",
        "3wdpawty/jvm/joda-time", (U ﹏ U)
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", òωó
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ʘwʘ
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient", /(^•ω•^)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", ʘwʘ
        "cuad/pwojects/new/thwift/swc/main/thwift:thwift-java", σωσ
        "swc/java/com/twittew/common/base", OwO
        "swc/java/com/twittew/common/cowwections", 😳😳😳
        "swc/java/com/twittew/common/text/token", 😳😳😳
        "swc/java/com/twittew/common/text/utiw:token-utiw", o.O
        "swc/java/com/twittew/common_intewnaw/text/vewsion",
        "swc/java/com/twittew/seawch/common/config", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/constants", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/encoding/docvawues", (///ˬ///✿)
        "swc/java/com/twittew/seawch/common/encoding/featuwes", >w<
        "swc/java/com/twittew/seawch/common/metwics", rawr
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", mya
        "swc/java/com/twittew/seawch/common/schema", ^^
        "swc/java/com/twittew/seawch/common/schema/base", 😳😳😳
        "swc/java/com/twittew/seawch/common/utiw:wongintconvewtew", mya
        "swc/java/com/twittew/seawch/common/utiw/anawysis", 😳
        "swc/java/com/twittew/seawch/common/utiw/spatiaw", -.-
        "swc/java/com/twittew/seawch/common/utiw/text", 🥺
        "swc/java/com/twittew/seawch/common/utiw/text/wegex", o.O
        "swc/java/com/twittew/seawch/common/utiw/uww", /(^•ω•^)
        "swc/thwift/com/twittew/seawch/common:indexing-java", nyaa~~
        "swc/thwift/com/twittew/seawch/common:schema-java",
        "swc/thwift/com/twittew/sewvice/spidewduck/gen:metadata-stowe-java", nyaa~~
    ], :3
    expowts = [
        "swc/thwift/com/twittew/seawch/common:indexing-java", 😳😳😳
    ],
)
