scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "configapi/configapi-core",
        "configapi/configapi-decider",
        "follow-recommendations-service/server/src/main/scala/com/ExTwitter/follow_recommendations/products/common",
    ],
)
