scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject",
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/candidate_souwce/stwato", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/timewines/impwession:thwift-scawa", UwU
        "stwato/config/cowumns/timewines/impwession-stowe:impwession-stowe-stwato-cwient", rawr x3
    ],
    e-expowts = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/candidate_souwce/stwato", rawr
        "stwato/config/cowumns/timewines/impwession-stowe:impwession-stowe-stwato-cwient", σωσ
    ],
)
