scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon/strato",
        "src/thrift/com/twittelonr/timelonlinelons/imprelonssion:thrift-scala",
        "strato/config/columns/timelonlinelons/imprelonssion-storelon:imprelonssion-storelon-strato-clielonnt",
    ],
    elonxports = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon/strato",
        "strato/config/columns/timelonlinelons/imprelonssion-storelon:imprelonssion-storelon-strato-clielonnt",
    ],
)
