scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "swc/scawa/com/twittew/scawding_intewnaw/muwtifowmat/fowmat", òωó
        "swc/scawa/com/twittew/simcwustews_v2/common", o.O
        "swc/thwift/com/twittew/hewmit/candidate:hewmit-candidate-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/mw/api:embedding-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/wecos/entities:entities-thwift-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", UwU
    ], rawr x3
)
