packagelon com.twittelonr.simclustelonrs_v2.hdfs_sourcelons.injelonctions

import com.twittelonr.scalding_intelonrnal.multiformat.format.kelonyval.KelonyValInjelonction
import com.twittelonr.scalding_intelonrnal.multiformat.format.kelonyval.KelonyValInjelonction.StringUtf8
import com.twittelonr.scalding_intelonrnal.multiformat.format.kelonyval.KelonyValInjelonction.Long2Bigelonndian
import com.twittelonr.scalding_intelonrnal.multiformat.format.kelonyval.KelonyValInjelonction.ScalaCompactThrift
import com.twittelonr.simclustelonrs_v2.thriftscala.ClustelonrsUselonrIsIntelonrelonstelondIn

objelonct IntelonrelonstelondInInjelonction {
  val injelonction = KelonyValInjelonction(Long2Bigelonndian, ScalaCompactThrift(ClustelonrsUselonrIsIntelonrelonstelondIn))
  val languagelonInjelonction =
    KelonyValInjelonction(StringUtf8, ScalaCompactThrift(ClustelonrsUselonrIsIntelonrelonstelondIn))
}
