java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/com/googwe/inject:guice", o.O
        "3wdpawty/jvm/it/unimi/dsi:fastutiw",
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt",
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (U ᵕ U❁)
        "3wdpawty/jvm/owg/swf4j:swf4j-api",
        "swc/java/com/twittew/common/base", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/fiwe", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/utiw/io", UwU
    ],
)
