scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:awgebwa", òωó
        "3wdpawty/swc/jvm/com/twittew/scawding:commons", o.O
        "3wdpawty/swc/jvm/com/twittew/scawding:cowe",
        "3wdpawty/swc/jvm/com/twittew/scawding:date", (U ᵕ U❁)
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:batch",
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:batch-hadoop", (⑅˘꒳˘)
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:chiww", ( ͡o ω ͡o )
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:cowe", UwU
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:scawding", rawr x3
        "swc/java/com/twittew/mw/api:api-base", rawr
        "swc/scawa/com/twittew/mw/api:api-base", σωσ
        "swc/scawa/com/twittew/mw/api/intewnaw", σωσ
        "swc/scawa/com/twittew/mw/api/utiw",
        "swc/scawa/com/twittew/scawding_intewnaw/dawv2", >_<
        "swc/scawa/com/twittew/scawding_intewnaw/dawv2/wemote_access",
        "swc/scawa/com/twittew/summingbiwd_intewnaw/souwces/common", :3
        "swc/thwift/com/twittew/mw/api:data-java", (U ﹏ U)
        "swc/thwift/com/twittew/mw/api:intewpwetabwe-modew-java", -.-
        "timewines/data_pwocessing/mw_utiw/aggwegation_fwamewowk:common_types", (ˆ ﻌ ˆ)♡
    ], (⑅˘꒳˘)
)
