scawa_wibwawy(
    souwces = ["*.scawa"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "unified_usew_actions/enwichew/swc/main/scawa/com/twittew/unified_usew_actions/enwichew", OwO
        "unified_usew_actions/enwichew/swc/main/scawa/com/twittew/unified_usew_actions/enwichew/hydwatow:base", 🥺
        "unified_usew_actions/enwichew/swc/main/scawa/com/twittew/unified_usew_actions/enwichew/pawtitionew:base", òωó
        "unified_usew_actions/enwichew/swc/main/thwift/com/twittew/unified_usew_actions/enwichew/intewnaw:intewnaw-scawa", o.O
        "unified_usew_actions/thwift/swc/main/thwift/com/twittew/unified_usew_actions:unified_usew_actions-scawa", (U ᵕ U❁)
    ],
)
