scala_library(
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
    dependencies = [
        "unified_user_actions/enricher/src/main/scala/com/twitter/unified_user_actions/enricher",
        "unified_user_actions/enricher/src/main/scala/com/twitter/unified_user_actions/enricher/hydrator:base",
        "unified_user_actions/enricher/src/main/scala/com/twitter/unified_user_actions/enricher/partitioner:base",
        "unified_user_actions/enricher/src/main/thrift/com/twitter/unified_user_actions/enricher/internal:internal-scala",
        "unified_user_actions/thrift/src/main/thrift/com/twitter/unified_user_actions:unified_user_actions-scala",
    ],
)
