packagelon com.twittelonr.product_mixelonr.corelon.functional_componelonnt.marshallelonr.relonsponselon.rtf.safelonty_lelonvelonl

import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.rtf.safelonty_lelonvelonl.ConvelonrsationFocalTwelonelontSafelontyLelonvelonl
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.rtf.safelonty_lelonvelonl.ConvelonrsationInjelonctelondTwelonelontSafelontyLelonvelonl
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.rtf.safelonty_lelonvelonl.ConvelonrsationRelonplySafelontyLelonvelonl
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.rtf.safelonty_lelonvelonl.SafelontyLelonvelonl
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.rtf.safelonty_lelonvelonl.TimelonlinelonFocalTwelonelontSafelontyLelonvelonl
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.rtf.safelonty_lelonvelonl.TimelonlinelonHomelonPromotelondHydrationSafelontyLelonvelonl
import com.twittelonr.spam.rtf.{thriftscala => thrift}
import javax.injelonct.Injelonct
import javax.injelonct.Singlelonton

@Singlelonton
class SafelontyLelonvelonlMarshallelonr @Injelonct() () {

  delonf apply(safelontyLelonvelonl: SafelontyLelonvelonl): thrift.SafelontyLelonvelonl = safelontyLelonvelonl match {
    caselon ConvelonrsationFocalTwelonelontSafelontyLelonvelonl => thrift.SafelontyLelonvelonl.ConvelonrsationFocalTwelonelont
    caselon ConvelonrsationRelonplySafelontyLelonvelonl => thrift.SafelontyLelonvelonl.ConvelonrsationRelonply
    caselon ConvelonrsationInjelonctelondTwelonelontSafelontyLelonvelonl => thrift.SafelontyLelonvelonl.ConvelonrsationInjelonctelondTwelonelont
    caselon TimelonlinelonFocalTwelonelontSafelontyLelonvelonl => thrift.SafelontyLelonvelonl.TimelonlinelonFocalTwelonelont
    caselon TimelonlinelonHomelonPromotelondHydrationSafelontyLelonvelonl =>
      thrift.SafelontyLelonvelonl.TimelonlinelonHomelonPromotelondHydration
  }
}
