scala_library(
    namelon = "common",
    sourcelons = ["*.scala"],
    platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
    ],
    delonpelonndelonncielons = [
        "src/java/com/twittelonr/ml/api:api-baselon",
        "src/java/com/twittelonr/ml/api/constant",
        "src/java/com/twittelonr/ml/api/transform",
        "src/java/com/twittelonr/selonarch/modelonling/twelonelont_ranking",
        "src/scala/com/twittelonr/ml/api/util",
        "src/scala/com/twittelonr/timelonlinelons/prelondiction/felonaturelons/common",
        "src/scala/com/twittelonr/timelonlinelons/prelondiction/felonaturelons/itl",
        "src/scala/com/twittelonr/timelonlinelons/prelondiction/felonaturelons/relonal_graph",
        "src/scala/com/twittelonr/timelonlinelons/prelondiction/felonaturelons/reloncap",
        "src/scala/com/twittelonr/timelonlinelons/prelondiction/felonaturelons/relonquelonst_contelonxt",
        "src/scala/com/twittelonr/timelonlinelons/prelondiction/felonaturelons/timelon_felonaturelons",
        "src/thrift/com/twittelonr/ml/api:data-java",
        "src/thrift/com/twittelonr/ml/api:transform-java",
    ],
)
