scawa_wibwawy(
    nyame = "common", OwO
    souwces = ["*.scawa"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = [
        "bazew-compatibwe", o.O
        "bazew-compatibwe:migwated", (U ᵕ U❁)
    ],
    d-dependencies = [
        "swc/java/com/twittew/mw/api:api-base", (⑅˘꒳˘)
        "swc/java/com/twittew/mw/api/constant", ( ͡o ω ͡o )
        "swc/java/com/twittew/mw/api/twansfowm", UwU
        "swc/java/com/twittew/seawch/modewing/tweet_wanking", rawr x3
        "swc/scawa/com/twittew/mw/api/utiw", rawr
        "swc/scawa/com/twittew/timewines/pwediction/featuwes/common", σωσ
        "swc/scawa/com/twittew/timewines/pwediction/featuwes/itw", σωσ
        "swc/scawa/com/twittew/timewines/pwediction/featuwes/weaw_gwaph", >_<
        "swc/scawa/com/twittew/timewines/pwediction/featuwes/wecap", :3
        "swc/scawa/com/twittew/timewines/pwediction/featuwes/wequest_context", (U ﹏ U)
        "swc/scawa/com/twittew/timewines/pwediction/featuwes/time_featuwes", -.-
        "swc/thwift/com/twittew/mw/api:data-java", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/mw/api:twansfowm-java", (⑅˘꒳˘)
    ],
)
