scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", ( ͡o ω ͡o )
        "communities/thwift/swc/main/thwift/com/twittew/communities:thwift-scawa", UwU
        "communities/thwift/swc/main/thwift/com/twittew/communities/modewation:thwift-scawa",
        "communities/thwift/swc/main/thwift/com/twittew/communities/visibiwity:thwift-scawa", rawr x3
        "eschewbiwd/swc/thwift/com/twittew/eschewbiwd/softintewvention:softintewvention_thwift-scawa", rawr
        "mediasewvices/media-utiw/swc/main/scawa", σωσ
        "notificationsewvice/common/swc/main/scawa/com/twittew/notificationsewvice/modew:awias", σωσ
        "notificationsewvice/common/swc/main/scawa/com/twittew/notificationsewvice/modew/notification", >_<
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", :3
        "swc/thwift/com/twittew/context:twittew-context-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/eschewbiwd/common:common-scawa", -.-
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/seawch/common:constants-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/spam/wtf:tweet-wtf-event-scawa", -.-
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", ^^;;
        "stitch/stitch-cowe", >_<
        # "tweetypie/swc/scawa/com/twittew/tweetypie/additionawfiewds", mya
        "twittew-context/swc/main/scawa", mya
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", 😳
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/stitch", XD
        "visibiwity/wib/swc/main/wesouwces/config", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", 😳😳😳
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/usews", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", ( ͡o ω ͡o )
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/common/bwendew", rawr x3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/common/seawch", nyaa~~
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/common/tweets", /(^•ω•^)
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/stwato:vf-stwato-scawa", rawr
    ], OwO
)
