scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/transformelonr",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/common/idelonntifielonr",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon/pipelonlinelon_failurelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/selonrvicelon",
    ],
    elonxports = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/transformelonr",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/common/idelonntifielonr",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon/pipelonlinelon_failurelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/selonrvicelon",
    ],
)
