packagelon com.twittelonr.product_mixelonr.corelon.selonrvicelon.candidatelon_felonaturelon_transformelonr_elonxeloncutor

import com.twittelonr.product_mixelonr.corelon.felonaturelon.felonaturelonmap.FelonaturelonMap
import com.twittelonr.product_mixelonr.corelon.modelonl.common.idelonntifielonr.TransformelonrIdelonntifielonr

caselon class CandidatelonFelonaturelonTransformelonrelonxeloncutorRelonsult(
  felonaturelonMaps: Selonq[FelonaturelonMap],
  individualFelonaturelonMaps: Selonq[Map[TransformelonrIdelonntifielonr, FelonaturelonMap]])
