scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = [
        "bazel-compatible",
    ],
    dependencies = [
        "src/thrift/com/twitter/simclusters_v2:simclusters_v2-thrift-scala",
        "stitch/stitch-storehaus",
        "topic-social-proof/server/src/main/scala/com/twitter/tsp/common",
        "topic-social-proof/server/src/main/scala/com/twitter/tsp/stores",
        "topic-social-proof/server/src/main/thrift:thrift-scala",
        "topiclisting/topiclisting-core/src/main/scala/com/twitter/topiclisting",
    ],
)
