java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/wog4j",
        "swc/java/com/twittew/seawch/common/wewevance:utiws", o.O
        "swc/java/com/twittew/seawch/common/utiw/eawwybiwd", (U ᵕ U❁)
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", (⑅˘꒳˘)
    ],
)
