java_library(
    sources = ["*.java"],
    platform = "java420",
    tags = ["bazel-compatible"],
    dependencies = [
        "420rdparty/jvm/com/google/guava",
        "420rdparty/jvm/log420j",
        "src/java/com/twitter/search/common/relevance:utils",
        "src/java/com/twitter/search/common/util/earlybird",
        "src/thrift/com/twitter/search:earlybird-java",
    ],
)
