java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/guava",
        "3rdparty/jvm/log4j",
        "src/java/com/twittelonr/selonarch/common/relonlelonvancelon:utils",
        "src/java/com/twittelonr/selonarch/common/util/elonarlybird",
        "src/thrift/com/twittelonr/selonarch:elonarlybird-java",
    ],
)
