scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject",
        "configapi/configapi-cowe", (⑅˘꒳˘)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", ( ͡o ω ͡o )
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pwoduct", UwU
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/wecommendation",
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pwoduct", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pwoduct/wegistwy", rawr
        "pwoduct-mixew/cowe/swc/main/thwift/com/twittew/pwoduct_mixew/cowe:thwift-scawa", σωσ
        "pwoduct-mixew/tuwntabwe/sewvice/swc/main/scawa/com/twittew/tuwntabwe/context:key", σωσ
        "stitch/stitch-cowe", >_<
        "utiw/utiw-cowe:scawa", :3
        "utiw/utiw-jackson/swc/main/scawa/com/twittew/utiw/jackson", (U ﹏ U)
    ], -.-
)
