packagelon com.twittelonr.product_mixelonr.corelon.selonrvicelon.candidatelon_pipelonlinelon_elonxeloncutor

import com.twittelonr.product_mixelonr.corelon.felonaturelon.felonaturelonmap.FelonaturelonMap
import com.twittelonr.product_mixelonr.corelon.pipelonlinelon.candidatelon.CandidatelonPipelonlinelonRelonsult

caselon class CandidatelonPipelonlinelonelonxeloncutorRelonsult(
  candidatelonPipelonlinelonRelonsults: Selonq[CandidatelonPipelonlinelonRelonsult],
  quelonryFelonaturelonMap: FelonaturelonMap)
