scawa_wibwawy(
    souwces = ["*.scawa"], -.-
    compiwew_option_sets = ["fataw_wawnings"], ^^;;
    p-pwatfowm = "java8", >_<
    p-pwovides = scawa_awtifact(
        o-owg = "com.twittew.tweetypie", mya
        n-nyame = "utiw", mya
        w-wepo = awtifactowy, 😳
    ),
    s-stwict_deps = t-twue, XD
    tags = ["bazew-compatibwe"], :3
    d-dependencies = [
        "//:scawa-wefwect", 😳😳😳
        "3wdpawty/jvm/commons-codec", -.-
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ( ͡o ω ͡o )
        "finagwe/finagwe-cowe/swc/main", rawr x3
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", nyaa~~
        "scwooge/scwooge-sewiawizew/swc/main/scawa", /(^•ω•^)
        "tweetypie/sewvo/wepo", rawr
        "tweetypie/sewvo/utiw", OwO
        "tweetypie/sewvo/utiw/swc/main/scawa:exception", (U ﹏ U)
        "swc/scawa/com/twittew/takedown/utiw", >_<
        "swc/thwift/com/twittew/datapwoducts:enwichments_pwofiwegeo-scawa", rawr x3
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts-scawa", mya
        "swc/thwift/com/twittew/expandodo:cawds-scawa", nyaa~~
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/sewvo:sewvo-exception-scawa",
        "swc/thwift/com/twittew/spam/wtf:safety-wabew-scawa", rawr x3
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:depwecated-scawa", (✿oωo)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", (ˆ ﻌ ˆ)♡
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:twansient_context-scawa", (˘ω˘)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", (⑅˘꒳˘)
        "stitch/stitch-cowe", (///ˬ///✿)
        "tweet-utiw", 😳😳😳
        "utiw/utiw-cowe:scawa", 🥺
    ],
)

scawa_wibwawy(
    nyame = "editcontwowutiw", mya
    souwces = [
        "editcontwowutiw.scawa", 🥺
        "package.scawa", >_<
    ], >_<
    compiwew_option_sets = ["fataw_wawnings"], (⑅˘꒳˘)
    p-pwatfowm = "java8", /(^•ω•^)
    pwovides = scawa_awtifact(
        o-owg = "com.twittew.tweetypie", rawr x3
        nyame = "utiw-editcontwowutiw", (U ﹏ U)
        wepo = a-awtifactowy, (U ﹏ U)
    ),
    stwict_deps = twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "//:scawa-wefwect", ʘwʘ
        "3wdpawty/jvm/commons-codec", /(^•ω•^)
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ʘwʘ
        "finagwe/finagwe-cowe/swc/main", σωσ
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", OwO
        "scwooge/scwooge-sewiawizew/swc/main/scawa", 😳😳😳
        "tweetypie/sewvo/utiw/swc/main/scawa:exception", 😳😳😳
        "swc/thwift/com/twittew/datapwoducts:enwichments_pwofiwegeo-scawa", o.O
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/expandodo:cawds-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", (///ˬ///✿)
        "swc/thwift/com/twittew/sewvo:sewvo-exception-scawa", >w<
        "swc/thwift/com/twittew/spam/wtf:safety-wabew-scawa",
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:depwecated-scawa", rawr
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", mya
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:twansient_context-scawa", ^^
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", 😳😳😳
        "stitch/stitch-cowe", mya
        "tweet-utiw", 😳
        "utiw/utiw-cowe:scawa", -.-
    ], 🥺
)
