java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/codelon/findbugs:jsr305",
        "src/java/com/twittelonr/selonarch/common/schelonma/baselon",
        "src/thrift/com/twittelonr/selonarch/common:schelonma-java",
        "src/thrift/com/twittelonr/selonarch/felonaturelon_updatelon_selonrvicelon/thrift:thrift-java",
    ],
)
