java_library(
    sources = ["*.java"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/code/findbugs:jsr305",
        "src/java/com/twitter/search/common/schema/base",
        "src/thrift/com/twitter/search/common:schema-java",
        "src/thrift/com/twitter/search/feature_update_service/thrift:thrift-java",
    ],
)
