scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", OwO
        "3wdpawty/jvm/javax/inject:javax.inject", 🥺
        "3wdpawty/jvm/net/codingweww:scawa-guice", òωó
        "decidew/swc/main/scawa", o.O
        "finagwe/finagwe-cowe/swc/main", (U ᵕ U❁)
        "finatwa/inject/inject-cowe/swc/main/scawa", (⑅˘꒳˘)
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift", ( ͡o ω ͡o )
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift:contwowwew", UwU
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/exceptions", rawr x3
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/fiwtews", rawr
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/moduwes", σωσ
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/wesponse", σωσ
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/wouting", >_<
        "wepwesentation-managew/sewvew/swc/main/scawa/com/twittew/wepwesentation_managew/migwation", :3
        "scwooge/scwooge-cowe/swc/main/scawa", (U ﹏ U)
        "simcwustews-ann/sewvew/swc/main/scawa/com/twittew/simcwustewsann/candidate_souwce", -.-
        "simcwustews-ann/sewvew/swc/main/scawa/com/twittew/simcwustewsann/common", (ˆ ﻌ ˆ)♡
        "simcwustews-ann/sewvew/swc/main/scawa/com/twittew/simcwustewsann/fiwtews", (⑅˘꒳˘)
        "simcwustews-ann/thwift/swc/main/thwift:thwift-scawa", (U ᵕ U❁)
        "swc/scawa/com/twittew/simcwustews_v2/candidate_souwce", -.-
        "twittew-sewvew/sewvew/swc/main/scawa", ^^;;
        "utiw/utiw-cowe:scawa", >_<
        "utiw/utiw-swf4j-api/swc/main/scawa", mya
    ],
)
