scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/marshallelonr",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/marshallelonr/relonsponselon/urt",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/marshalling/relonsponselon/urp",
        "src/thrift/com/twittelonr/pagelons/relonndelonr:thrift-scala",
        "strato/config/src/thrift/com/twittelonr/strato/graphql/timelonlinelons:graphql-timelonlinelons-scala",
    ],
    elonxports = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/marshallelonr",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/marshallelonr/relonsponselon/urt",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/marshalling/relonsponselon/urp",
        "src/thrift/com/twittelonr/pagelons/relonndelonr:thrift-scala",
        "strato/config/src/thrift/com/twittelonr/strato/graphql/timelonlinelons:graphql-timelonlinelons-scala",
    ],
)
