scala_library(
    sourcelons = ["*.scala"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/org/apachelon/thrift:libthrift",
        "scroogelon/scroogelon-corelon/src/main/scala",
        "selonrvo/util",
        "src/thrift/com/twittelonr/selonarch:elonarlybird-scala",
        "timelonlinelonrankelonr/common/src/main/scala/com/twittelonr/timelonlinelonrankelonr/modelonl",
        "timelonlinelonrankelonr/selonrvelonr/src/main/scala/com/twittelonr/timelonlinelonrankelonr/corelon",
        "util/util-stats/src/main/scala/com/twittelonr/finaglelon/stats",
    ],
)
