scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    pwatfowm = "java8", 🥺
    s-stwict_deps = t-twue, òωó
    tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (U ᵕ U❁)
        "scwooge/scwooge-cowe/swc/main/scawa", (⑅˘꒳˘)
        "sewvo/utiw", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/seawch:eawwybiwd-scawa", UwU
        "timewinewankew/common/swc/main/scawa/com/twittew/timewinewankew/modew", rawr x3
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/cowe", rawr
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats", σωσ
    ], σωσ
)
