scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], OwO
    pwatfowm = "java8", 🥺
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews",
        "fowwow-wecommendations-sewvice/thwift/swc/main/thwift:thwift-scawa", o.O
        "stwingcentew/cwient", (U ᵕ U❁)
    ], (⑅˘꒳˘)
    e-expowts = [
    ], ( ͡o ω ͡o )
)
