scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", UwU
        "account-wecommendations-mixew/thwift/swc/main/thwift:thwift-scawa", rawr x3
        "content-wecommendew/thwift/swc/main/thwift:thwift-scawa", rawr
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa", σωσ
        "decidew/swc/main/scawa", σωσ
        "expwowe/expwowe-wankew/thwift/swc/main/thwift:thwift-scawa", >_<
        "finagwe/finagwe-memcached/swc/main/scawa", :3
        "finagwe/finagwe-thwiftmux/swc/main/scawa", (U ﹏ U)
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", -.-
        "finatwa/inject/inject-cowe/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "finatwa/inject/inject-thwift-cwient/swc/main/scawa", (⑅˘꒳˘)
        "finatwa/utiws/swc/main/java/com/twittew/finatwa/annotations", (U ᵕ U❁)
        "fowwow-wecommendations-sewvice/thwift/swc/main/thwift:thwift-scawa", -.-
        "home-scowew/thwift/swc/main/thwift:thwift-scawa", ^^;;
        "intewests_discovewy/thwift/swc/main/thwift:sewvice-thwift-scawa", >_<
        "onboawding/sewvice/thwift/swc/main/thwift:thwift-scawa", mya
        "peopwe-discovewy/api/thwift/swc/main/thwift:thwift-scawa", mya
        "swc/scawa/com/twittew/summingbiwd_intewnaw/wunnew/stowe_config", 😳
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", XD
        "swc/thwift/com/twittew/seawch:eawwybiwd-scawa", :3
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", 😳😳😳
        "swc/thwift/com/twittew/timewinemixew:thwift-scawa", -.-
        "swc/thwift/com/twittew/timewinewankew:thwift-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/timewines/impwession_stowe:thwift-scawa", rawr x3
        "swc/thwift/com/twittew/timewinescowew:thwift-scawa", nyaa~~
        "swc/thwift/com/twittew/timewinesewvice:thwift-scawa", /(^•ω•^)
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", rawr
        "stitch/stitch-gizmoduck", OwO
        "stitch/stitch-sociawgwaph", (U ﹏ U)
        "stitch/stitch-timewinesewvice/swc/main/scawa", >_<
        "stitch/stitch-tweetypie", rawr x3
        "timewines/swc/main/scawa/com/twittew/timewines/impwessionstowe/stowe", mya
        "tweetconvosvc/cwient/swc/main/scawa/com/twittew/tweetconvosvc/cwient/buiwdew", nyaa~~
        "usew_session_stowe/swc/main/scawa/com/twittew/usew_session_stowe/config", (⑅˘꒳˘)
        "usew_session_stowe/swc/main/scawa/com/twittew/usew_session_stowe/impw/manhattan/weadonwy", rawr x3
        "usew_session_stowe/swc/main/scawa/com/twittew/usew_session_stowe/impw/manhattan/weadwwite", (✿oωo)
    ], (ˆ ﻌ ˆ)♡
    e-expowts = [
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", (˘ω˘)
        "account-wecommendations-mixew/thwift/swc/main/thwift:thwift-scawa", (⑅˘꒳˘)
        "content-wecommendew/thwift/swc/main/thwift:thwift-scawa", (///ˬ///✿)
        "finagwe/finagwe-memcached/swc/main/scawa", 😳😳😳
        "finagwe/finagwe-thwiftmux/swc/main/scawa", 🥺
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", mya
        "finatwa/inject/inject-cowe/swc/main/scawa", 🥺
        "finatwa/inject/inject-thwift-cwient/swc/main/scawa", >_<
        "finatwa/utiws/swc/main/java/com/twittew/finatwa/annotations", >_<
        "fowwow-wecommendations-sewvice/thwift/swc/main/thwift:thwift-scawa", (⑅˘꒳˘)
        "intewests_discovewy/thwift/swc/main/thwift:sewvice-thwift-scawa", /(^•ω•^)
        "onboawding/sewvice/thwift/swc/main/thwift:thwift-scawa", rawr x3
        "swc/scawa/com/twittew/summingbiwd_intewnaw/wunnew/stowe_config", (U ﹏ U)
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/timewinewankew:thwift-scawa",
        "swc/thwift/com/twittew/timewines/impwession_stowe:thwift-scawa", òωó
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", ʘwʘ
        "stitch/stitch-gizmoduck", /(^•ω•^)
        "stitch/stitch-sociawgwaph", ʘwʘ
        "stitch/stitch-tweetypie", σωσ
        "timewines/swc/main/scawa/com/twittew/timewines/impwessionstowe/stowe", OwO
        "usew_session_stowe/swc/main/scawa/com/twittew/usew_session_stowe/config", 😳😳😳
        "usew_session_stowe/swc/main/scawa/com/twittew/usew_session_stowe/impw/manhattan/weadonwy", 😳😳😳
        "usew_session_stowe/swc/main/scawa/com/twittew/usew_session_stowe/impw/manhattan/weadwwite", o.O
    ], ( ͡o ω ͡o )
)
