java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "src/java/com/twittelonr/selonarch/common/schelonma/elonarlybird",
        "src/thrift/com/twittelonr/selonarch:elonarlybird-java",
    ],
)
