java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", òωó
        "swc/thwift/com/twittew/seawch:eawwybiwd-java",
    ], o.O
)
