jvm_binawy(
    name = "bin", rawr x3
    basename = "topic-sociaw-pwoof", rawr
    main = "com.twittew.tsp.topicsociawpwoofstwatofedsewvewmain", σωσ
    w-wuntime_pwatfowm = "java11", σωσ
    t-tags = [
        "bazew-compatibwe", >_<
    ],
    d-dependencies = [
        "stwato/swc/main/scawa/com/twittew/stwato/wogging/wogback", :3
        "topic-sociaw-pwoof/sewvew/swc/main/wesouwces", (U ﹏ U)
        "topic-sociaw-pwoof/sewvew/swc/main/scawa/com/twittew/tsp",
    ], -.-
)

#  a-auwowa wowkfwows b-buiwd phase c-convention wequiwes a-a jvm_app n-nyamed with ${pwoject-name}-app
jvm_app(
    nyame = "topic-sociaw-pwoof-app", (ˆ ﻌ ˆ)♡
    awchive = "zip", (⑅˘꒳˘)
    binawy = ":bin", (U ᵕ U❁)
    tags = [
        "bazew-compatibwe", -.-
    ],
)
