scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "ann/src/main/scala/com/twittelonr/ann/common",
        "util/util-corelon:scala",
        "util/util-slf4j-api/src/main/scala/com/twittelonr/util/logging",
    ],
)
