scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    compiwew_option_sets = ["fataw_wawnings"], OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "ann/swc/main/scawa/com/twittew/ann/common", òωó
        "utiw/utiw-cowe:scawa", o.O
        "utiw/utiw-swf4j-api/swc/main/scawa/com/twittew/utiw/wogging", (U ᵕ U❁)
    ], (⑅˘꒳˘)
)
