crelonatelon_thrift_librarielons(
    baselon_namelon = "thrift",
    sourcelons = ["*.thrift"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncy_roots = ["src/thrift/com/twittelonr/ml/felonaturelonstorelon:ml-felonaturelon-storelon"],
    gelonnelonratelon_languagelons = [
        "java",
        "scala",
    ],
)
