cweate_thwift_wibwawies(
    base_name = "thwift", OwO
    souwces = ["*.thwift"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependency_woots = ["swc/thwift/com/twittew/mw/featuwestowe:mw-featuwe-stowe"], (U ᵕ U❁)
    genewate_wanguages = [
        "java", (⑅˘꒳˘)
        "scawa", ( ͡o ω ͡o )
    ], UwU
)
