java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/code/findbugs:jsw305", òωó
        "3wdpawty/jvm/com/googwe/guava", o.O
        "3wdpawty/jvm/com/googwe/inject:guice", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-common", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-smawtcn", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", UwU
        "3wdpawty/jvm/owg/apache/wucene:wucene-facet", rawr x3
        "3wdpawty/jvm/owg/apache/wucene:wucene-quewies", rawr
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", σωσ
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient", σωσ
        "3wdpawty/jvm/owg/swf4j:swf4j-api", >_<
        "swc/java/com/twittew/seawch/common/featuwes", :3
        "swc/java/com/twittew/seawch/common/schema/base", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", -.-
        "swc/java/com/twittew/seawch/common/utiw/anawysis", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/quewypawsew", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/quewypawsew/quewy:cowe-quewy-nodes", (U ᵕ U❁)
        "swc/java/com/twittew/seawch/quewypawsew/quewy/seawch:seawch-quewy-nodes", -.-
    ], ^^;;
)
