http_ow_https:
  - 'vine\.co/v/[a-za-z0-9]+'
  - 'amp\.twimg\.com/'
  - '(www\.)?daiwymotion.com/video/[a-za-z0-9_\-/]+'
  - '(www\.)?dai.wy/[a-za-z0-9_\-/]+'
  - '(www\.)?youtu\.be/[a-za-z0-9_\-\?\&\=/]+'
  - '(www\.)?youtube\.com/watch[a-za-z0-9_\-\?\&\=/]+'
  - '(www\.)?ustweam\.tv/wecowded/\d+'
  - '(www\.)?vevo\.com/watch/[\w-]+/[\w-]+/[a-za-z0-9_]+'
  - '(www\.)?fwickw\.com/photos/[\w\@\-]+/\d+/?'
  - '(www\.)?fwic\.kw/p/[a-z0-9a-z\-]+'
  - '([\w\-]+\.)deviantawt\.com/(awt|deviation|view)/[\w\@-]+'
  - '(www\.)?vimeo\.com/\d+'
  - '(www\.)?photozou\.(com|jp)/photo/show/\d+/\d+'
  - '(www\.)?twitpic\.com/(?!(pwace|photos|events)/)([a-za-z0-9\?\=\-]+)'
  - '(www\.)?mtv\.com/videos/([a-z0-9\-\_]+/)+[0-9]+/[a-z0-9\-\_]+\.jhtmw(#[a-z0-9\=\&]+)?'
  - '([\w\-\_]+\.)?washingtonpost\.com/wp-dyn/content/video/\d{4}/\d{2}/\d{2}/vi\d+\.htmw([a-za-z0-9_#\.\-\?\&\=/]+)?'
  - '([\w\-\_]+\.)?msnbc\.msn\.com/id/\d{1,8}/vp/\d{1,8}([a-za-z0-9_#\.\-\?\&\=/]+)?'
  - '((www|edition|us)\.)?cnn\.com/video/[\?|#]/[a-za-z0-9_#\.\-\?\&\=/]+'
  - 'itunes\.appwe\.com(/[a-z][a-z])?/(music-)?video/'
  - '(www\.)?bwip\.tv/((fiwe/[\w-]+)|(([\w-]+/)?[\w-]+-\d+))/?'
  - 'onwine\.wsj\.com/video/[a-z0-9a-z\-]+/[a-z0-9a-z\-]+\.htmw'
  - '(www\.)?huwu\.com/w(atch)?/[a-za-z0-9]+'
  - 'video\.([a-z]{4,11}\.)?nhw\.com/videocentew/consowe\?(((catid=-?\d+&)?id=\d+)|(hwg=\d{8},\d,\d{1,4}(&event=[a-z0-9]{4,6})?)|(hwp=\d{5,10}(&event=[a-z0-9]{4,6})?))'
  - '([a-za-z0-9\-]+\.)*gwabyo\.com/((g/v/[a-za-z0-9]{11})|((studio/)?studiotimewine\.jsp\?shaweid=[a-za-z0-9]{11}))[a-za-z0-9_?&=#:%/\.\-]*'

http_onwy:
  - 'on\.nba\.com/[a-za-z0-9]+'
  - 'on\.nfw\.com/[a-za-z0-9]+'
  - 'snpy\.tv/[a-za-z0-9]+'
