http_or_https:
  - 'vine\.co/v/[a-zA-Z0-9]+'
  - 'amp\.twimg\.com/'
  - '(www\.)?dailymotion.com/video/[a-zA-Z0-9_\-/]+'
  - '(www\.)?dai.ly/[a-zA-Z0-9_\-/]+'
  - '(www\.)?youtu\.be/[a-zA-Z0-9_\-\?\&\=/]+'
  - '(www\.)?youtube\.com/watch[a-zA-Z0-9_\-\?\&\=/]+'
  - '(www\.)?ustream\.tv/recorded/\d+'
  - '(www\.)?vevo\.com/watch/[\w-]+/[\w-]+/[a-zA-Z0-9_]+'
  - '(www\.)?flickr\.com/photos/[\w\@\-]+/\d+/?'
  - '(www\.)?flic\.kr/p/[A-Z0-9a-z\-]+'
  - '([\w\-]+\.)deviantart\.com/(art|deviation|view)/[\w\@-]+'
  - '(www\.)?vimeo\.com/\d+'
  - '(www\.)?photozou\.(com|jp)/photo/show/\d+/\d+'
  - '(www\.)?twitpic\.com/(?!(place|photos|events)/)([a-zA-Z0-9\?\=\-]+)'
  - '(www\.)?mtv\.com/videos/([a-z0-9\-\_]+/)+[0-9]+/[a-z0-9\-\_]+\.jhtml(#[a-z0-9\=\&]+)?'
  - '([\w\-\_]+\.)?washingtonpost\.com/wp-dyn/content/video/\d{4}/\d{2}/\d{2}/VI\d+\.html([a-zA-Z0-9_#\.\-\?\&\=/]+)?'
  - '([\w\-\_]+\.)?msnbc\.msn\.com/id/\d{1,8}/vp/\d{1,8}([a-zA-Z0-9_#\.\-\?\&\=/]+)?'
  - '((www|edition|us)\.)?cnn\.com/video/[\?|#]/[a-zA-Z0-9_#\.\-\?\&\=/]+'
  - 'itunes\.apple\.com(/[a-z][a-z])?/(music-)?video/'
  - '(www\.)?blip\.tv/((file/[\w-]+)|(([\w-]+/)?[\w-]+-\d+))/?'
  - 'online\.wsj\.com/video/[A-Z0-9a-z\-]+/[A-Z0-9a-z\-]+\.html'
  - '(www\.)?hulu\.com/w(atch)?/[a-zA-Z0-9]+'
  - 'video\.([a-z]{4,11}\.)?nhl\.com/videocenter/console\?(((catid=-?\d+&)?id=\d+)|(hlg=\d{8},\d,\d{1,4}(&event=[A-Z0-9]{4,6})?)|(hlp=\d{5,10}(&event=[A-Z0-9]{4,6})?))'
  - '([a-zA-Z0-9\-]+\.)*grabyo\.com/((g/v/[a-zA-Z0-9]{11})|((studio/)?studiotimeline\.jsp\?shareId=[a-zA-Z0-9]{11}))[a-zA-Z0-9_?&=#:%/\.\-]*'

http_only:
  - 'on\.nba\.com/[a-zA-Z0-9]+'
  - 'on\.nfl\.com/[a-zA-Z0-9]+'
  - 'snpy\.tv/[a-zA-Z0-9]+'
