scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/joda-time",
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/geotoows:gt-wefewencing", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/wocationtech/spatiaw4j", UwU
        "compwiance/usew-consent/swc/main/scawa/com/twittew/usewconsent/compwiance/biwthdate", rawr x3
        "cweatives-containew/thwift/swc/main/thwift:cweatives-containew-sewvice-scawa", rawr
        "diffshow", σωσ
        "eventbus/cwient", σωσ
        "featuweswitches/featuweswitches-cowe/swc/main/scawa",
        "finatwa/inject/inject-swf4j/swc/main/scawa/com/twittew/inject", >_<
        "fwock-cwient", :3
        "fwock-cwient/swc/main/thwift:thwift-scawa", (U ﹏ U)
        "geoduck/sewvice/swc/main/scawa/com/twittew/geoduck/sewvice/common/cwientmoduwes", -.-
        "geoduck/utiw/swc/main/scawa/com/twittew/geoduck/utiw/pwimitives", (ˆ ﻌ ˆ)♡
        "geoduck/utiw/swc/main/scawa/com/twittew/geoduck/utiw/sewvice", (⑅˘꒳˘)
        "gizmoduck/common/swc/main/scawa/com/twittew/gizmoduck/utiw:scawa",
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", (U ᵕ U❁)
        "scwooge-intewnaw/scwooge-schema/swc/main/scawa/com/twittew/scwooge/schema", -.-
        "scwooge-intewnaw/scwooge-schema/swc/main/scawa/com/twittew/scwooge/schema/scwooge/scawa", ^^;;
        "scwooge-intewnaw/scwooge-schema/swc/main/scawa/com/twittew/scwooge/schema/twee",
        "scwooge-intewnaw/swc/main/scawa/com/twittew/scwooge_intewnaw/wintew/known_annotations", >_<
        "scwooge/scwooge-cowe", mya
        "tweetypie/sewvo/wepo", mya
        "tweetypie/sewvo/utiw", 😳
        "snowfwake:id", XD
        "swc/scawa/com/twittew/takedown/utiw", :3
        "swc/thwift/com/twittew/botmakew:botmakew-scawa", 😳😳😳
        "swc/thwift/com/twittew/bouncew:bounce-action-thwift-scawa", -.-
        "swc/thwift/com/twittew/context:testing-signaws-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/context:twittew-context-scawa", rawr x3
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts-scawa", nyaa~~
        "swc/thwift/com/twittew/expandodo:onwy-scawa", /(^•ω•^)
        "swc/thwift/com/twittew/geoduck:geoduck-scawa", rawr
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", OwO
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/gizmoduck:usew-type-thwift-scawa", >_<
        "swc/thwift/com/twittew/wewevance/featuwe_stowe:featuwe_stowe-scawa", rawr x3
        "swc/thwift/com/twittew/sewvice/scawecwow/gen:scawecwow-scawa", mya
        "swc/thwift/com/twittew/sewvice/scawecwow/gen:tiewed-actions-scawa", nyaa~~
        "swc/thwift/com/twittew/sewvice/tawon/gen:thwift-scawa",
        "swc/thwift/com/twittew/sewvo:sewvo-exception-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/spam/featuwes:safety-meta-data-scawa", rawr x3
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", (✿oωo)
        "swc/thwift/com/twittew/spam/wtf:tweet-wtf-event-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/timewinesewvice/sewvew/intewnaw:thwift-scawa", (˘ω˘)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:audit-scawa", (⑅˘꒳˘)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:dewete_wocation_data-scawa", (///ˬ///✿)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:media-entity-scawa", 😳😳😳
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", 🥺
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:stowed-tweet-info-scawa", mya
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", 🥺
        "stitch/stitch-cowe", >_<
        "tco-utiw", >_<
        "tweet-utiw/swc/main/scawa", (⑅˘꒳˘)
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", /(^•ω•^)
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/backends", rawr x3
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/cowe", (U ﹏ U)
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/media", (U ﹏ U)
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/wepositowy", (⑅˘꒳˘)
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/sewvewutiw", òωó
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/stowe", ʘwʘ
        "tweetypie/sewvew/swc/main/thwift:compiwed-scawa", /(^•ω•^)
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/additionawfiewds", ʘwʘ
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/jiminy/tweetypie",
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/media", σωσ
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/stowage", OwO
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/thwiftscawa/entities", 😳😳😳
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/tweettext", 😳😳😳
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/utiw", o.O
        "twittew-context", ( ͡o ω ͡o )
        "twittew-text/wib/java/swc/main/java/com/twittew/twittewtext",
        "utiw/utiw-swf4j-api/swc/main/scawa/com/twittew/utiw/wogging", (U ﹏ U)
        "utiw/utiw-stats", (///ˬ///✿)
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", >w<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew", rawr
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/genewatows", mya
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/modews", ^^
        "visibiwity/wwitew/swc/main/scawa/com/twittew/visibiwity/wwitew",
        "visibiwity/wwitew/swc/main/scawa/com/twittew/visibiwity/wwitew/intewfaces/tweets", 😳😳😳
        "visibiwity/wwitew/swc/main/scawa/com/twittew/visibiwity/wwitew/modews", mya
    ], 😳
)
