packagelon com.twittelonr.product_mixelonr.corelon.pipelonlinelon

import com.twittelonr.product_mixelonr.corelon.felonaturelon.Felonaturelon
import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.CandidatelonWithDelontails

privatelon[corelon] objelonct CandidatelonPipelonlinelonRelonsults
    elonxtelonnds Felonaturelon[PipelonlinelonQuelonry, Selonq[CandidatelonWithDelontails]]
