scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "src/scala/com/X/twistly/common",
        "src/scala/com/X/twistly/store",
        "src/thrift/com/X/simclusters_v2:simclusters_v2-thrift-scala",
        "strato/src/main/scala/com/X/strato/fed",
        "strato/src/main/scala/com/X/strato/fed/server",
        "user-signal-service/server/src/main/scala/com/X/usersignalservice/config",
        "user-signal-service/server/src/main/scala/com/X/usersignalservice/module",
        "user-signal-service/thrift/src/main/thrift:thrift-scala",
    ],
)
