scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/fastelonrxml/jackson/corelon:jackson-annotations",
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "3rdparty/jvm/javax/mail",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/common/alelonrt/prelondicatelon",
        "strato/src/main/scala/com/twittelonr/strato/catalog",
        "util/util-corelon:scala",
    ],
    elonxports = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/common/alelonrt/prelondicatelon",
        "strato/src/main/scala/com/twittelonr/strato/catalog",
        "util/util-corelon:scala",
    ],
)
