scawa_wibwawy(
    souwces = [
        "*.scawa", >_<
    ],
    compiwew_option_sets = ["fataw_wawnings"], :3
    # o-ouw w-wuntime is using j-java 11, (U ﹏ U) but fow c-compatibiwity w-with othew intewnaw w-wibwawies that
    # a-awe stiww o-on java 8, -.- we'ww make ouw tawget pwatfowm to be java 8 as weww untiw evewyone c-can
    # migwate. (ˆ ﻌ ˆ)♡
    pwatfowm = "java8", (⑅˘꒳˘)
    tags = ["bazew-compatibwe"],
)
