# Java library for tweet features and utilities.
java_library(
    sources = ["*.java"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/com/X/elephantbird:core",
        "3rdparty/jvm/org/apache/hadoop:hadoop-client-default",
        "3rdparty/jvm/org/apache/thrift:libthrift",
        "src/java/com/X/common/base",
        "src/java/com/X/common/text/token",
        "src/java/com/X/search/common/encoding/features",
        "src/java/com/X/search/common/features",
        "src/java/com/X/search/common/metrics",
        "src/java/com/X/search/common/schema/base",
        "src/java/com/X/search/common/schema/earlybird",
        "src/java/com/X/search/common/util/lang",
        "src/thrift/com/X/search/common:constants-java",
        "src/thrift/com/X/search/common:features-java",
        "src/thrift/com/X/search/common:schema-java",
    ],
)
