scawa_wibwawy(
    souwces = ["*.scawa"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/gwaphjet", OwO
        "sewvo/wequest/swc/main/scawa", 🥺
        "swc/scawa/com/twittew/wecos/usew_tweet_gwaph/stowe", òωó
        "swc/scawa/com/twittew/wecos/usew_tweet_gwaph/utiw", o.O
        "swc/scawa/com/twittew/wecos/utiw:wecos-utiw", (U ᵕ U❁)
        "swc/thwift/com/twittew/wecos/usew_tweet_gwaph:usew_tweet_gwaph-scawa", (⑅˘꒳˘)
    ],
)
