java_wibwawy(
    nyame = "eawwybiwd_woot-wib", -.-
    souwces = ["*.java"], (ˆ ﻌ ˆ)♡
    p-pwatfowm = "java8", (⑅˘꒳˘)
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", -.-
        "3wdpawty/jvm/commons-wang", ^^;;
        "3wdpawty/jvm/owg/swf4j:swf4j-api", >_<
        "decidew/swc/main/scawa",
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", mya
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authowization/sewvew", mya
        "finagwe/finagwe-memcached/swc/main/java", 😳
        "finagwe/finagwe-mux/swc/main/scawa", XD
        "finagwe/finagwe-thwift/swc/main/java", :3
        "finagwe/finagwe-thwift/swc/main/scawa", 😳😳😳
        "finatwa/inject/inject-cowe/swc/main/scawa", -.-
        "finatwa/inject/inject-sewvew/swc/main/scawa/com/twittew/inject/sewvew", ( ͡o ω ͡o )
        "swc/java/com/googwe/common/utiw/concuwwent", rawr x3
        "swc/java/com/twittew/common/cowwections", nyaa~~
        "swc/java/com/twittew/common_intewnaw/text/vewsion", /(^•ω•^)
        "swc/java/com/twittew/seawch/common/caching", rawr
        "swc/java/com/twittew/seawch/common/cwientstats", OwO
        "swc/java/com/twittew/seawch/common/config", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/dawk", >_<
        "swc/java/com/twittew/seawch/common/decidew", rawr x3
        "swc/java/com/twittew/seawch/common/metwics", mya
        "swc/java/com/twittew/seawch/common/pawtitioning/base", nyaa~~
        "swc/java/com/twittew/seawch/common/pawtitioning/zookeepew", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/wewevance:wanking", rawr x3
        "swc/java/com/twittew/seawch/common/woot",
        "swc/java/com/twittew/seawch/common/wuntime", (✿oωo)
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/common/seawch", (˘ω˘)
        "swc/java/com/twittew/seawch/common/utiw/eawwybiwd", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/utiw/io/pewiodic", (///ˬ///✿)
        "swc/java/com/twittew/seawch/common/utiw/zookeepew", 😳😳😳
        "swc/java/com/twittew/seawch/eawwybiwd/common", 🥺
        "swc/java/com/twittew/seawch/eawwybiwd/config", mya
        "swc/java/com/twittew/seawch/eawwybiwd_woot/caching", 🥺
        "swc/java/com/twittew/seawch/eawwybiwd_woot/common", >_<
        "swc/java/com/twittew/seawch/eawwybiwd_woot/fiwtews", >_<
        "swc/java/com/twittew/seawch/eawwybiwd_woot/mewgews", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/eawwybiwd_woot/quota", /(^•ω•^)
        "swc/java/com/twittew/seawch/eawwybiwd_woot/woutews", rawr x3
        "swc/java/com/twittew/seawch/eawwybiwd_woot/visitows", (U ﹏ U)
        "swc/java/com/twittew/seawch/quewypawsew", (U ﹏ U)
        "swc/java/com/twittew/seawch/quewypawsew/quewy:cowe-quewy-nodes",
        "swc/java/com/twittew/seawch/quewypawsew/quewy/seawch:seawch-quewy-nodes", (⑅˘꒳˘)
        "swc/thwift/com/twittew/seawch:benchmawk_quewy-java", òωó
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", ʘwʘ
        "stitch/stitch-cowe", /(^•ω•^)
        "stwato/swc/main/scawa/com/twittew/stwato/catawog", ʘwʘ
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", σωσ
        "thwift-web-fowms", OwO
        "thwift-web-fowms/swc/main/scawa/com/twittew/thwiftwebfowms/modew", 😳😳😳
    ],
)

j-jvm_binawy(
    n-nyame = "eawwybiwd_woot-binawy", 😳😳😳
    basename = "eawwybiwd_woot", o.O
    # t-the main cwass i-is weset in the a-auwowa fiwes (it's a wequiwed pawam). ( ͡o ω ͡o )
    # we nyeed to set it to something hewe, (U ﹏ U) b-because hadoop_binawy wequiwes it. (///ˬ///✿)
    main = "com.twittew.seawch.eawwybiwd_woot.weawtimewootappmain", >w<
    w-wuntime_pwatfowm = "java11", rawr
    tags = ["bazew-compatibwe"],
    dependencies = [
        "3wdpawty/jvm/owg/swf4j:swf4j-wog4j12", mya
        ":eawwybiwd_woot-wib", ^^
        "swc/java/com/twittew/seawch/common/wogging:seawch-wog4j", 😳😳😳
        # f-fow /admin/wogging. mya
        "twittew-sewvew/swf4j-wog4j12/swc/main/scawa", 😳
    ], -.-
)
