scawa_wibwawy(
    nyame = "uwt", -.-
    souwces = ["**/*.scawa"] + e-excwude_gwobs(["buiwdew/wichtext/*.scawa"]), (ˆ ﻌ ˆ)♡
    c-compiwew_option_sets = ["fataw_wawnings"],
    p-pwatfowm = "java8", (⑅˘꒳˘)
    s-scawac_pwugins = ["no-woomba"],
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], -.-
    d-dependencies = [
        ":wichtext", ^^;;
        "3wdpawty/jvm/com/twittew/bijection:json", >_<
        "3wdpawty/jvm/com/twittew/bijection:scwooge", mya
        "expwowe/expwowe-mixew/sewvew/swc/main/scawa/com/twittew/expwowe_mixew/modew/wequest", mya
        "intewests-mixew/sewvew/swc/main/scawa/com/twittew/intewests_mixew/modew/wequest", 😳
        "onboawding/sewvice/thwift/swc/main/thwift:thwift-scawa",
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/candidate_souwce/peopwe_discovewy", XD
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", :3
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate/ads", 😳😳😳
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate/suggestion", -.-
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate/twends_events", ( ͡o ω ͡o )
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/pwesentation/uwt", rawr x3
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/pipewine/candidate/fwexibwe_injection_pipewine/twansfowmew", nyaa~~
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", /(^•ω•^)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/decowatow/uwt/buiwdew", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common/pwesentation/uwt", OwO
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/awewt", (U ﹏ U)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/covew", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/icon", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/item", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/metadata", nyaa~~
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/opewation", (⑅˘꒳˘)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/timewine_moduwe", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", (✿oωo)
        "swc/thwift/com/twittew/ads/adsewvew:ad_metadata_containew-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/ads/adsewvew:adsewvew_common-scawa", (˘ω˘)
        "swc/thwift/com/twittew/hewmit:hewmit-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/suggests/contwowwew_data:contwowwew_data-scawa", (///ˬ///✿)
        "swc/thwift/com/twittew/timewines/sewvice:thwift-scawa", 😳😳😳
        "swc/thwift/com/twittew/timewinescowew/common/scowedtweetcandidate:thwift-scawa", 🥺
        "swc/thwift/com/twittew/timewinesewvice/sewvew/intewnaw:thwift-scawa", mya
        "stwingcentew/cwient", 🥺
        "stwingcentew/cwient/swc/main/java", >_<
        "stwingcentew/cwient/swc/main/scawa/com/twittew/stwingcentew/cwient", >_<
        "timewines/swc/main/scawa/com/twittew/timewines/utiw", (⑅˘꒳˘)
        "twends/twending_content/swc/main/scawa/com/twittew/twends/twending_content/utiw:compacting-numbew-wocawizew", /(^•ω•^)
        "tweetconvosvc/common/swc/main/thwift/com/twittew/tweetconvosvc/tweet_ancestow:thwift-scawa", rawr x3
        "twittew-text/wib/java/swc/main/java/com/twittew/twittewtext",
    ], (U ﹏ U)
    expowts = [
        ":wichtext", (U ﹏ U)
        "3wdpawty/jvm/com/twittew/bijection:json", (⑅˘꒳˘)
        "3wdpawty/jvm/com/twittew/bijection:scwooge", òωó
        "expwowe/expwowe-mixew/sewvew/swc/main/scawa/com/twittew/expwowe_mixew/modew/wequest", ʘwʘ
        "intewests-mixew/sewvew/swc/main/scawa/com/twittew/intewests_mixew/modew/wequest", /(^•ω•^)
        "onboawding/sewvice/thwift/swc/main/thwift:thwift-scawa", ʘwʘ
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", σωσ
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate/ads", OwO
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate/suggestion", 😳😳😳
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/pwesentation/uwt", 😳😳😳
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/pipewine/candidate/fwexibwe_injection_pipewine/twansfowmew",
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", o.O
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/decowatow/uwt/buiwdew", ( ͡o ω ͡o )
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common/pwesentation/uwt", (U ﹏ U)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/awewt", (///ˬ///✿)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/covew", >w<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/icon", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/item", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/metadata", ^^
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/opewation", 😳😳😳
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/timewine_moduwe", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", 😳
        "swc/thwift/com/twittew/ads/adsewvew:ad_metadata_containew-scawa", -.-
        "swc/thwift/com/twittew/ads/adsewvew:adsewvew_common-scawa", 🥺
        "swc/thwift/com/twittew/suggests/contwowwew_data:contwowwew_data-scawa", o.O
        "swc/thwift/com/twittew/timewines/sewvice:thwift-scawa", /(^•ω•^)
        "swc/thwift/com/twittew/timewinescowew/common/scowedtweetcandidate:thwift-scawa", nyaa~~
        "swc/thwift/com/twittew/timewinesewvice/sewvew/intewnaw:thwift-scawa", nyaa~~
        "stwingcentew/cwient", :3
        "stwingcentew/cwient/swc/main/java", 😳😳😳
        "stwingcentew/cwient/swc/main/scawa/com/twittew/stwingcentew/cwient", (˘ω˘)
        "timewines/swc/main/scawa/com/twittew/timewines/utiw", ^^
        "tweetconvosvc/common/swc/main/thwift/com/twittew/tweetconvosvc/tweet_ancestow:thwift-scawa", :3
        "twittew-text/wib/java/swc/main/java/com/twittew/twittewtext", -.-
    ],
)

scawa_wibwawy(
    nyame = "wichtext", 😳
    souwces = ["buiwdew/wichtext/*.scawa"], mya
    c-compiwew_option_sets = ["fataw_wawnings"], (˘ω˘)
    pwatfowm = "java8", >_<
    stwict_deps = twue, -.-
    t-tags = ["bazew-compatibwe"], 🥺
    dependencies = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap", (U ﹏ U)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/decowatow/uwt/buiwdew", >w<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/metadata", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/wichtext", >w<
        "twittew-text/wib/java/swc/main/java/com/twittew/twittewtext", nyaa~~
    ],
    e-expowts = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap", (✿oωo)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/decowatow/uwt/buiwdew", ʘwʘ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/metadata", (ˆ ﻌ ˆ)♡
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/wichtext", 😳😳😳
        "twittew-text/wib/java/swc/main/java/com/twittew/twittewtext", :3
    ],
)
