scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", (⑅˘꒳˘)
        "3wdpawty/jvm/javax/inject:javax.inject", ( ͡o ω ͡o )
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", UwU
        "ann/swc/main/scawa/com/twittew/ann/hnsw", rawr x3
        "ann/swc/main/thwift/com/twittew/ann/common:ann-common-scawa", rawr
        "configapi/configapi-cowe", σωσ
        "content-wecommendew/thwift/swc/main/thwift:thwift-scawa", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/bwendew", >_<
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/config", :3
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/fiwtew", (U ﹏ U)
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/wogging", -.-
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/modew", (ˆ ﻌ ˆ)♡
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam", (⑅˘꒳˘)
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam/decidew", (U ᵕ U❁)
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/wankew", -.-
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/simiwawity_engine", ^^;;
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/souwce_signaw",
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/utiw", >_<
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa", mya
        "cuad/pwojects/hashspace/thwift:thwift-scawa", mya
        "decidew/swc/main/scawa", 😳
        "finatwa/inject/inject-cowe/swc/main/scawa", XD
        "fowwow-wecommendations-sewvice/thwift/swc/main/thwift:thwift-scawa", :3
        "fwigate/fwigate-common:base", 😳😳😳
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/base",
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/candidate", -.-
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/utiw:stats_utiw", ( ͡o ω ͡o )
        "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/constants", rawr x3
        "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/modew", nyaa~~
        "simcwustews-ann/thwift/swc/main/thwift:thwift-scawa", /(^•ω•^)
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", rawr
        "swc/scawa/com/twittew/cowtex/mw/embeddings/common:hewpews", OwO
        "swc/scawa/com/twittew/mw/featuwestowe/wib", (U ﹏ U)
        "swc/scawa/com/twittew/simcwustews_v2/common", >_<
        "swc/thwift/com/twittew/fwigate/data_pipewine/scawding:bwue_vewified_annotations-scawa",
        "swc/thwift/com/twittew/mw/api:embedding-scawa", rawr x3
        "swc/thwift/com/twittew/wecos/usew_tweet_gwaph:usew_tweet_gwaph-scawa", mya
        "swc/thwift/com/twittew/wecos/usew_tweet_gwaph_pwus:usew_tweet_gwaph_pwus-scawa", nyaa~~
        "swc/thwift/com/twittew/seawch:eawwybiwd-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/seawch/quewy_intewaction_gwaph/sewvice:qig-sewvice-scawa", rawr x3
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", (✿oωo)
        "swc/thwift/com/twittew/wtf/candidate:wtf-candidate-scawa", (ˆ ﻌ ˆ)♡
        "stwato/config/cowumns/cuad/hashspace:hashspace-stwato-cwient",
    ], (˘ω˘)
)
