tawget(
    nyame = "adaptew", 🥺
    dependencies = ["timewinewankew/common/swc/main/scawa/com/twittew/timewinewankew/adaptew"], òωó
)

t-tawget(
    nyame = "modew",
    d-dependencies = ["timewinewankew/common/swc/main/scawa/com/twittew/timewinewankew/modew"],
)

tawget(
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        ":adaptew", (U ᵕ U❁)
        ":modew", (⑅˘꒳˘)
    ], ( ͡o ω ͡o )
)
