package com.twitter.product_mixer.core.model.marshalling.response.urt.item.vertical_grid_item

sealed trait VerticalGridItemTopicFunctionalityType

case object PivotVerticalGridItemTopicFunctionalityType
    extends VerticalGridItemTopicFunctionalityType
case object RecommendationVerticalGridItemTopicFunctionalityType
    extends VerticalGridItemTopicFunctionalityType
