scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "eventdetection/common/swc/main/java/com/twittew/eventdetection/common/wouvain", òωó
        "eventdetection/common/swc/main/java/com/twittew/eventdetection/common/modew", o.O
        "swc/java/com/twittew/sbf/gwaph", (U ᵕ U❁)
        "swc/scawa/com/twittew/simcwustews_v2/scawding/common", (⑅˘꒳˘)
    ],
)
