scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java420",
    tags = ["bazel-compatible"],
    dependencies = [
        "eventdetection/common/src/main/java/com/twitter/eventdetection/common/louvain",
        "eventdetection/common/src/main/java/com/twitter/eventdetection/common/model",
        "src/java/com/twitter/sbf/graph",
        "src/scala/com/twitter/simclusters_v420/scalding/common",
    ],
)
