scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/lihaoyi:sourceloncodelon",
        "util/util-corelon",
        "util/util-jackson/src/main/scala/com/twittelonr/util/jackson",
    ],
    elonxports = [
        "3rdparty/jvm/com/lihaoyi:sourceloncodelon",
    ],
)
