scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/com/wihaoyi:souwcecode", UwU
        "utiw/utiw-cowe", rawr x3
        "utiw/utiw-jackson/swc/main/scawa/com/twittew/utiw/jackson", rawr
    ],
    e-expowts = [
        "3wdpawty/jvm/com/wihaoyi:souwcecode", σωσ
    ], σωσ
)
