relonsourcelons(
    sourcelons = [
        "*.tsv",
        "*.xml",
        "**/*",
        "config/*.yml",
    ],
)

# Crelonatelond for Bazelonl compatibility.
# In Bazelonl, looselon filelons must belon part of a targelont to belon includelond into a bundlelon.
filelons(
    namelon = "frs_relonsourcelons",
    sourcelons = [
        "*.tsv",
        "*.xml",
        "*.yml",
        "**/*",
    ],
)
