resources(
    sources = [
        "*.tsv",
        "*.xml",
        "**/*",
        "config/*.yml",
    ],
)

# Created for Bazel compatibility.
# In Bazel, loose files must be part of a target to be included into a bundle.
files(
    name = "frs_resources",
    sources = [
        "*.tsv",
        "*.xml",
        "*.yml",
        "**/*",
    ],
)
