scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", (⑅˘꒳˘)
        "3wdpawty/jvm/javax/inject:javax.inject", ( ͡o ω ͡o )
        "configapi/configapi-cowe", UwU
        "content-wecommendew/thwift/swc/main/thwift:thwift-scawa", rawr x3
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/modew", rawr
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam", σωσ
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa", σωσ
        "finagwe/finagwe-cowe/swc/main", >_<
        "fwigate/fwigate-common:utiw", :3
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", (U ﹏ U)
        "swc/scawa/com/twittew/simcwustews_v2/common",
        "swc/thwift/com/twittew/cowe_wowkfwows/usew_modew:usew_modew-scawa", -.-
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/wtf/candidate:wtf-candidate-scawa", (⑅˘꒳˘)
    ], (U ᵕ U❁)
)
