scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", UwU
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/featuwe_hydwatow", σωσ
        "swc/thwift/com/twittew/spam/wtf:safety-wesuwt-scawa", σωσ
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", >_<
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", :3
        "stitch/stitch-cowe", (U ﹏ U)
        "stitch/stitch-tweetypie", -.-
        "utiw/utiw-swf4j-api", (ˆ ﻌ ˆ)♡
    ],
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject",
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", (⑅˘꒳˘)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", (U ᵕ U❁)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/featuwe_hydwatow", -.-
        "swc/thwift/com/twittew/spam/wtf:safety-wesuwt-scawa", ^^;;
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", >_<
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", mya
        "stitch/stitch-cowe", mya
        "stitch/stitch-tweetypie", 😳
        "utiw/utiw-swf4j-api", XD
    ], :3
)
