scala_library(
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":candidatelon-algorithm-adaptelonr",
        ":clielonnt-contelonxt-adaptelonr",
        ":post-nux-algorithm-adaptelonr",
        ":prelon-felontchelond-felonaturelon-adaptelonr",
    ],
)

targelont(
    namelon = "common",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/baselon",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/clielonnts/strato",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/constants",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/felonaturelon_hydration/common",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/modelonls",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/utils",
        "src/java/com/twittelonr/ml/api:api-baselon",
        "src/scala/com/twittelonr/ml/api/util",
        "src/scala/com/twittelonr/onboarding/relonlelonvancelon/util/melontadata",
        "util/util-slf4j-api/src/main/scala",
    ],
)

scala_library(
    namelon = "candidatelon-algorithm-adaptelonr",
    sourcelons = [
        "CandidatelonAlgorithmAdaptelonr.scala",
    ],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":common",
        "helonrmit/helonrmit-corelon/src/main/scala/com/twittelonr/helonrmit/constants",
    ],
)

scala_library(
    namelon = "clielonnt-contelonxt-adaptelonr",
    sourcelons = [
        "ClielonntContelonxtAdaptelonr.scala",
    ],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":common",
        "snowflakelon/src/main/scala/com/twittelonr/snowflakelon/id",
    ],
)

scala_library(
    namelon = "post-nux-algorithm-adaptelonr",
    sourcelons = [
        "PostNuxAlgorithmAdaptelonr.scala",
    ],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":common",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/catalog/felonaturelons/customelonr_journelony:post-nux-algorithm-aggrelongatelon",
    ],
)

scala_library(
    namelon = "prelon-felontchelond-felonaturelon-adaptelonr",
    sourcelons = [
        "PrelonFelontchelondFelonaturelonAdaptelonr.scala",
    ],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":common",
    ],
)
