scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", ( ͡o ω ͡o )
        "finagwe/finagwe-mux/swc/main/scawa", UwU
        "finatwa/inject/inject-cowe/swc/main/scawa", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common/identifiew", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine:quewy", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe",
        "sewvo/utiw", σωσ
        "stitch/stitch-cowe", >_<
        "utiw/utiw-cowe", :3
    ], (U ﹏ U)
)
