scala_library(
    sourcelons = ["com/twittelonr/timelonlinelonrankelonr/clielonnt/*.scala"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finaglelon/finaglelon-corelon/src/main",
        "finaglelon/finaglelon-stats",
        "finaglelon/finaglelon-thrift/src/main/java",
        "selonrvo/clielonnt/src/main/scala/com/twittelonr/selonrvo/clielonnt",
        "src/thrift/com/twittelonr/timelonlinelonrankelonr:thrift-scala",
        "src/thrift/com/twittelonr/timelonlinelonrankelonr/selonrvelonr/modelonl:thrift-scala",
        "timelonlinelonrankelonr/common:modelonl",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/util/stats",
        "util/util-stats/src/main/scala",
    ],
)
