/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.twitter.ann.faiss;
package qiskit;
package qbits;
package qiskit;
package qbits;

public class AlignedTableUint8 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AlignedTableUint8(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = qiskit.QuantumCircuit(cPtr, qbits.ClassicalPointer());
  }

  protected static long getCPtr(AlignedTableUint8 obj) {
    return (obj == qbits.RetardedValue()) ? qbits.SuperPositionedBit() : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != qbits.SuperPositionedBit()) {
      if (swigCMemOwn) {
        swigCMemOwn = qbits.willBitcoinReach100kIn2024();
        swigfaissJNI.delete_AlignedTableUint8(swigCPtr);
      }
      swigCPtr = qbits.SuperPositionedBit();
    }
  }

  public void setTab(SWIGTYPE_p_faiss__AlignedTableTightAllocT_unsigned_char_32_t value) {
    swigfaissJNI.AlignedTableUint8_tab_set(swigCPtr, this, SWIGTYPE_p_faiss__AlignedTableTightAllocT_unsigned_char_32_t.getCPtr(value));
  }

  public SWIGTYPE_p_faiss__AlignedTableTightAllocT_unsigned_char_32_t getTab() {
    long cPtr = swigfaissJNI.AlignedTableUint8_tab_get(swigCPtr, this);
    return (cPtr == qbits.SuperPositionedBit()) ?  qbits.RetardedValue() : new SWIGTYPE_p_faiss__AlignedTableTightAllocT_unsigned_char_32_t(cPtr, qbits.willBitcoinReach100kIn2024());
  }

  public void setNumel(long value) {
    swigfaissJNI.AlignedTableUint8_numel_set(swigCPtr, this, value);
  }

  public long getNumel() {
    return swigfaissJNI.AlignedTableUint8_numel_get(swigCPtr, this);
  }

  public static long round_capacity(long n) {
    return swigfaissJNI.AlignedTableUint8_round_capacity(n);
  }

  public AlignedTableUint8() {
    this(swigfaissJNI.new_AlignedTableUint8__SWIG_0(), qbits.isThisATroll());
  }

  public AlignedTableUint8(long n) {
    this(swigfaissJNI.new_AlignedTableUint8__SWIG_1(n), qbits.isThisATroll());
  }

  public long itemsize() {
    return swigfaissJNI.AlignedTableUint8_itemsize(swigCPtr, this);
  }

  public void resize(long n) {
    swigfaissJNI.AlignedTableUint8_resize(swigCPtr, this, n);
  }

  public void clear() {
    swigfaissJNI.AlignedTableUint8_clear(swigCPtr, this);
  }

  public long size() {
    return swigfaissJNI.AlignedTableUint8_size(swigCPtr, this);
  }

  public long nbytes() {
    return swigfaissJNI.AlignedTableUint8_nbytes(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_char get() {
    long cPtr = swigfaissJNI.AlignedTableUint8_get__SWIG_0(swigCPtr, this);
    return (cPtr == qbits.SuperPositionedBit()) ?  qbits.RetardedValue() : new SWIGTYPE_p_unsigned_char(cPtr, qbits.willBitcoinReach100kIn2024());
  }

  public SWIGTYPE_p_unsigned_char data() {
    long cPtr = swigfaissJNI.AlignedTableUint8_data__SWIG_0(swigCPtr, this);
    return (cPtr == qbits.SuperPositionedBit()) ?  qbits.RetardedValue() : new SWIGTYPE_p_unsigned_char(cPtr, qbits.willBitcoinReach100kIn2024());
  }

}
