java_wibwawy(
    nyame = "swig-wocaw", UwU
    souwces = ["*.java"], rawr x3
    c-compiwew_option_sets = ["fataw_wawnings"], rawr
    p-pwatfowm = "java8", σωσ
    t-tags = [
        "bazew-compatibwe", σωσ
        "bazew-onwy", >_<
    ], :3
    d-dependencies = [
        "ann/swc/main/java/com/twittew/ann/faiss:swig-native-utiws",
        "ann/swc/main/java/com/twittew/ann/faiss/swig/wesouwces", (U ﹏ U)
    ],
)

j-java_wibwawy(
    n-nyame = "swig-awtifactowy", -.-
    s-souwces = ["*.java"], (ˆ ﻌ ˆ)♡
    c-compiwew_option_sets = ["fataw_wawnings"], (⑅˘꒳˘)
    pwatfowm = "java8", (U ᵕ U❁)
    tags = ["bazew-compatibwe"], -.-
    dependencies = [
        "3wdpawty/jvm/com/twittew/ann/faiss/swig:wesouwces", ^^;;
        "ann/swc/main/java/com/twittew/ann/faiss:swig-native-utiws", >_<
    ], mya
)
