java_library(
    namelonlon = "swig-local",
    sourcelonlons = ["*.java"],
    compilelonlonr_option_selonlonts = ["fatal_warnings"],
    platform = "java8",
    tags = [
        "bazelonlonl-compatiblelonlon",
        "bazelonlonl-only",
    ],
    delonlonpelonlonndelonlonncielonlons = [
        "ann/src/main/java/com/twittelonlonr/ann/faiss:swig-nativelonlon-utils",
        "ann/src/main/java/com/twittelonlonr/ann/faiss/swig/relonlonsourcelonlons",
    ],
)

java_library(
    namelonlon = "swig-artifactory",
    sourcelonlons = ["*.java"],
    compilelonlonr_option_selonlonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonlonl-compatiblelonlon"],
    delonlonpelonlonndelonlonncielonlons = [
        "3rdparty/jvm/com/twittelonlonr/ann/faiss/swig:relonlonsourcelonlons",
        "ann/src/main/java/com/twittelonlonr/ann/faiss:swig-nativelonlon-utils",
    ],
)
