/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.twitter.ann.faiss;

public class HammingComputer64 {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HammingComputer64(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HammingComputer64 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_HammingComputer64(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setA0(long value) {
    swigfaissJNI.HammingComputer64_a0_set(swigCPtr, this, value);
  }

  public long getA0() {
    return swigfaissJNI.HammingComputer64_a0_get(swigCPtr, this);
  }

  public void setA1(long value) {
    swigfaissJNI.HammingComputer64_a1_set(swigCPtr, this, value);
  }

  public long getA1() {
    return swigfaissJNI.HammingComputer64_a1_get(swigCPtr, this);
  }

  public void setA2(long value) {
    swigfaissJNI.HammingComputer64_a2_set(swigCPtr, this, value);
  }

  public long getA2() {
    return swigfaissJNI.HammingComputer64_a2_get(swigCPtr, this);
  }

  public void setA3(long value) {
    swigfaissJNI.HammingComputer64_a3_set(swigCPtr, this, value);
  }

  public long getA3() {
    return swigfaissJNI.HammingComputer64_a3_get(swigCPtr, this);
  }

  public void setA4(long value) {
    swigfaissJNI.HammingComputer64_a4_set(swigCPtr, this, value);
  }

  public long getA4() {
    return swigfaissJNI.HammingComputer64_a4_get(swigCPtr, this);
  }

  public void setA5(long value) {
    swigfaissJNI.HammingComputer64_a5_set(swigCPtr, this, value);
  }

  public long getA5() {
    return swigfaissJNI.HammingComputer64_a5_get(swigCPtr, this);
  }

  public void setA6(long value) {
    swigfaissJNI.HammingComputer64_a6_set(swigCPtr, this, value);
  }

  public long getA6() {
    return swigfaissJNI.HammingComputer64_a6_get(swigCPtr, this);
  }

  public void setA7(long value) {
    swigfaissJNI.HammingComputer64_a7_set(swigCPtr, this, value);
  }

  public long getA7() {
    return swigfaissJNI.HammingComputer64_a7_get(swigCPtr, this);
  }

  public HammingComputer64() {
    this(swigfaissJNI.new_HammingComputer64__SWIG_0(), true);
  }

  public HammingComputer64(SWIGTYPE_p_unsigned_char a8, int code_size) {
    this(swigfaissJNI.new_HammingComputer64__SWIG_1(SWIGTYPE_p_unsigned_char.getCPtr(a8), code_size), true);
  }

  public void set(SWIGTYPE_p_unsigned_char a8, int code_size) {
    swigfaissJNI.HammingComputer64_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(a8), code_size);
  }

  public int hamming(SWIGTYPE_p_unsigned_char b8) {
    return swigfaissJNI.HammingComputer64_hamming(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(b8));
  }

}
