/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.twitter.ann.faiss;

public class OneRecallAtRCriterion extends AutoTuneCriterion {
  private transient long swigCPtr;

  protected OneRecallAtRCriterion(long cPtr, boolean cMemoryOwn) {
    super(swigfaissJNI.OneRecallAtRCriterion_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OneRecallAtRCriterion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        swigfaissJNI.delete_OneRecallAtRCriterion(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setR(long value) {
    swigfaissJNI.OneRecallAtRCriterion_R_set(swigCPtr, this, value);
  }

  public long getR() {
    return swigfaissJNI.OneRecallAtRCriterion_R_get(swigCPtr, this);
}

  public OneRecallAtRCriterion(long nq, long R) {
    this(swigfaissJNI.new_OneRecallAtRCriterion(nq, R), true);
  }

  public double evaluate(SWIGTYPE_p_float D, LongVector I) {
    return swigfaissJNI.OneRecallAtRCriterion_evaluate(swigCPtr, this, SWIGTYPE_p_float.getCPtr(D), SWIGTYPE_p_long_long.getCPtr(I.data()), I);
  }

}
