java_wibwawy(
    souwces = ["*.java"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", o.O
        "3wdpawty/jvm/commons-io", (U ᵕ U❁)
        "3wdpawty/jvm/commons-wogging", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", UwU
        "cuad/pwojects/new/cwient/swc/main/scawa/com/twittew/cuad/new/cwient", rawr x3
        "cuad/pwojects/new/thwift/swc/main/thwift:thwift-java", rawr
        "decidew/swc/main/scawa", σωσ
        "eventbus/cwient/swc/main/scawa/com/twittew/eventbus/cwient", σωσ
        "finagwe/finagwe-cowe/swc/main", >_<
        "finagwe/finagwe-thwiftmux/swc/main/scawa", :3
        "pink-fwoyd/pink-common/swc/main/java/com/twittew/spidewduck/common", (U ﹏ U)
        "scwooge/scwooge-cowe", -.-
        "scwooge/scwooge-sewiawizew/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "sewvo/utiw/swc/main/scawa", (⑅˘꒳˘)
        "swc/java/com/twittew/common/text/wanguage:wocawe-utiw", (U ᵕ U❁)
        "swc/java/com/twittew/common/utiw:system-mocks", -.-
        "swc/java/com/twittew/common_intewnaw/text/vewsion", ^^;;
        "swc/java/com/twittew/metastowe/cwient_v2", >_<
        "swc/java/com/twittew/seawch/common/config", mya
        "swc/java/com/twittew/seawch/common/convewtew/eawwybiwd",
        "swc/java/com/twittew/seawch/common/debug", mya
        "swc/java/com/twittew/seawch/common/decidew", 😳
        "swc/java/com/twittew/seawch/common/encoding/featuwes", XD
        "swc/java/com/twittew/seawch/common/wogging",
        "swc/java/com/twittew/seawch/common/metwics", :3
        "swc/java/com/twittew/seawch/common/pawtitioning:timeswice-managew", 😳😳😳
        "swc/java/com/twittew/seawch/common/pawtitioning/base", -.-
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/wewevance:cwassifiews", rawr x3
        "swc/java/com/twittew/seawch/common/wewevance:entities_and_fiwtews", nyaa~~
        "swc/java/com/twittew/seawch/common/wewevance:scowews", /(^•ω•^)
        "swc/java/com/twittew/seawch/common/wewevance:text", rawr
        "swc/java/com/twittew/seawch/common/schema", OwO
        "swc/java/com/twittew/seawch/common/schema/base", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", >_<
        "swc/java/com/twittew/seawch/common/utiw/text", rawr x3
        "swc/java/com/twittew/seawch/common/utiw/thwift:text-pwotocow", mya
        "swc/java/com/twittew/seawch/ingestew/modew",
        "swc/java/com/twittew/seawch/ingestew/modew/engagements", nyaa~~
        "swc/java/com/twittew/seawch/ingestew/pipewine/stwato_fetchews", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/ingestew/pipewine/twittew/fiwtews", rawr x3
        "swc/java/com/twittew/seawch/ingestew/pipewine/twittew/thwiftpawse", (✿oωo)
        "swc/java/com/twittew/seawch/ingestew/pipewine/utiw", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/ingestew/pipewine/wiwe", (˘ω˘)
        "swc/java/owg/apache/commons/pipewine", (⑅˘꒳˘)
        "swc/thwift/com/twittew/expandodo:cawds-java", (///ˬ///✿)
        "swc/thwift/com/twittew/gizmoduck:thwift-java", 😳😳😳
        "swc/thwift/com/twittew/pink-fwoyd/thwift:dewivatives-java", 🥺
        "swc/thwift/com/twittew/pink-fwoyd/thwift:thwift-java", mya
        "swc/thwift/com/twittew/seawch/common:indexing-java", 🥺
        "swc/thwift/com/twittew/seawch/common:schema-java", >_<
        "swc/thwift/com/twittew/seawch/common/debug:debug-java", >_<
        "swc/thwift/com/twittew/sewvice/spidewduck/gen:metadata-stowe-java", (⑅˘꒳˘)
        "swc/thwift/com/twittew/timewinesewvice/sewvew/intewnaw:thwift-java", /(^•ω•^)
        "swc/thwift/com/twittew/tweetypie:events-java", rawr x3
        "swc/thwift/com/twittew/tweetypie:events-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/tweetypie:sewvice-java", (U ﹏ U)
        "swc/thwift/com/twittew/tweetypie:tweet-java", (⑅˘꒳˘)
        "stitch/stitch-cowe", òωó
        "stowage/cwients/manhattan/cwient/swc/main/scawa", ʘwʘ
        "stwato/swc/main/scawa/com/twittew/stwato/catawog", /(^•ω•^)
        "ubs/common/swc/main/thwift/com/twittew/ubs:bwoadcast-thwift-java", ʘwʘ
        "utiw/utiw-cowe:scawa", σωσ
        "utiw/utiw-cowe/swc/main/java", OwO
        "utiw/utiw-function/swc/main/java", 😳😳😳
    ], 😳😳😳
)
