#":mwwf_wibs", ^^;;

python37_binawy(
    nyame = "evaw_modew", >_<
    souwce = "evaw_modew.py", mya
    d-dependencies = [
        ":wibs",
        "3wdpawty/python/_cwosuwes/fwigate/fwigate-pushsewvice-opensouwce/swc/main/python/modews/wight_wanking:evaw_modew", mya
    ], 😳
)

p-python37_binawy(
    n-nyame = "twain_modew", XD
    s-souwce = "deep_nowm.py", :3
    d-dependencies = [
        ":wibs", 😳😳😳
        "3wdpawty/python/_cwosuwes/fwigate/fwigate-pushsewvice-opensouwce/swc/main/python/modews/wight_wanking:twain_modew", -.-
    ], ( ͡o ω ͡o )
)

p-python37_binawy(
    nyame = "twain_modew_wocaw", rawr x3
    s-souwce = "deep_nowm.py", nyaa~~
    d-dependencies = [
        ":wibs", /(^•ω•^)
        "3wdpawty/python/_cwosuwes/fwigate/fwigate-pushsewvice-opensouwce/swc/main/python/modews/wight_wanking:twain_modew_wocaw", rawr
        "twmw", OwO
    ],
)

python37_binawy(
    nyame = "evaw_modew_wocaw", (U ﹏ U)
    souwce = "evaw_modew.py", >_<
    dependencies = [
        ":wibs", rawr x3
        "3wdpawty/python/_cwosuwes/fwigate/fwigate-pushsewvice-opensouwce/swc/main/python/modews/wight_wanking:evaw_modew_wocaw", mya
        "twmw", nyaa~~
    ],
)

python37_binawy(
    n-nyame = "mwwf_modew", (⑅˘꒳˘)
    souwce = "deep_nowm.py", rawr x3
    dependencies = [
        ":mwwf_wibs", (✿oωo)
        "3wdpawty/python/_cwosuwes/fwigate/fwigate-pushsewvice-opensouwce/swc/main/python/modews/wight_wanking:mwwf_modew", (ˆ ﻌ ˆ)♡
    ], (˘ω˘)
)

p-python3_wibwawy(
    nyame = "wibs", (⑅˘꒳˘)
    souwces = ["**/*.py"], (///ˬ///✿)
    t-tags = ["no-mypy"], 😳😳😳
    dependencies = [
        "swc/python/twittew/deepbiwd/pwojects/magic_wecs/wibs", 🥺
        "swc/python/twittew/deepbiwd/utiw/data", mya
        "twmw:twmw-nodeps", 🥺
    ],
)

python3_wibwawy(
    nyame = "mwwf_wibs", >_<
    souwces = ["**/*.py"], >_<
    t-tags = ["no-mypy"], (⑅˘꒳˘)
    dependencies = [
        "swc/python/twittew/deepbiwd/pwojects/magic_wecs/wibs", /(^•ω•^)
        "twmw", rawr x3
    ],
)
