java_library(
    sourcelons = ["*.java"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/codelon/findbugs:jsr305",
        "deloncidelonr/src/main/scala",
        "src/java/com/twittelonr/selonarch/common/deloncidelonr",
        "src/java/com/twittelonr/selonarch/common/relonlelonvancelon:elonntitielons_and_filtelonrs",
        "util/util-corelon:scala",
    ],
)
