java_wibwawy(
    souwces = ["*.java"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/code/findbugs:jsw305", o.O
        "decidew/swc/main/scawa", (U ᵕ U❁)
        "swc/java/com/twittew/seawch/common/decidew", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/wewevance:entities_and_fiwtews", ( ͡o ω ͡o )
        "utiw/utiw-cowe:scawa", UwU
    ],
)
