scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "cache/cwient", (U ᵕ U❁)
        "finagwe/finagwe-memcached/swc/main/scawa", (⑅˘꒳˘)
        "finatwa/inject/inject-cowe/swc/main/scawa", ( ͡o ω ͡o )
        "finatwa/inject/inject-thwift-cwient/swc/main/scawa", UwU
        "stitch/stitch-cowe", rawr x3
        "utiw/utiw-cowe:scawa", rawr
        "utiw/utiw-thwift", σωσ
    ],
)
