java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/com/googwe/inject:guice", o.O
        "3wdpawty/jvm/commons-io", (U ᵕ U❁)
        "3wdpawty/jvm/geo/googwe:geogoogwe", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/bookkeepew:bookkeepew-sewvew", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/apache/bookkeepew:bookkeepew-twittew-science-pwovidew", UwU
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", rawr x3
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-common", rawr
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-smawtcn", σωσ
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", σωσ
        "3wdpawty/jvm/owg/apache/wucene:wucene-facet", >_<
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", :3
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient", (U ﹏ U)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", -.-
        "3wdpawty/swc/jvm/com/twittew/scawding:cowe", (ˆ ﻌ ˆ)♡
        "3wdpawty/swc/jvm/com/twittew/scawding:date",
        "3wdpawty/swc/jvm/com/twittew/scawding:pawquet", (⑅˘꒳˘)
        "decidew/swc/main/scawa", (U ᵕ U❁)
        "swc/java/com/twittew/common/base", -.-
        "swc/java/com/twittew/common/utiw:system-mocks",
        "swc/java/com/twittew/common_intewnaw/hadoop", ^^;;
        "swc/java/com/twittew/seawch/common/wogging", >_<
        "swc/java/com/twittew/seawch/common/metwics", mya
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", mya
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", 😳
        "swc/java/com/twittew/seawch/common/utiw/hash", XD
        "swc/java/com/twittew/seawch/common/utiw/io", :3
        "swc/java/com/twittew/seawch/common/utiw/io:dw-weadew-wwitew", 😳😳😳
        "swc/java/com/twittew/seawch/common/utiw/io:fwushabwe", -.-
        "swc/java/com/twittew/seawch/common/utiw/io:wecowd-weadew-api", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/eawwybiwd/common/config", rawr x3
        "swc/scawa/com/twittew/scawding_intewnaw/ewwow_handwing", nyaa~~
        "swc/scawa/com/twittew/scawding_intewnaw/muwtifowmat", /(^•ω•^)
        "swc/scawa/com/twittew/scawding_intewnaw/souwce", rawr
        "swc/scawa/com/twittew/seawch/usew_tabwe/souwces", OwO
        "swc/thwift/com/twittew/seawch/common:indexing-java", (U ﹏ U)
        "swc/thwift/com/twittew/tweetypie:events-java", >_<
        "utiw/utiw-cowe:scawa", rawr x3
    ],
)
