scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "ann/src/main/scala/com/twittelonr/ann/common",
        "ann/src/main/scala/com/twittelonr/ann/faiss",
        "ann/src/main/scala/com/twittelonr/ann/hnsw",
        "twittelonr-selonrvelonr-intelonrnal/src/main/scala",
        "util/util-stats/src/main/scala/com/twittelonr/finaglelon/stats",
    ],
)
