scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    compiwew_option_sets = ["fataw_wawnings"], OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "ann/swc/main/scawa/com/twittew/ann/common", òωó
        "swc/scawa/com/twittew/mw/featuwestowe/wib", o.O
        "swc/scawa/com/twittew/mw/featuwestowe/wib/onwine", (U ᵕ U❁)
    ],
)
