scawa_wibwawy(
    nyame = "agg_addwess_book", nyaa~~
    souwces = ["*.scawa"], /(^•ω•^)
    c-compiwew_option_sets = ["fataw_wawnings"], rawr
    p-pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], (U ﹏ U)
    d-dependencies = [
        ":intewaction_gwaph_agg_addwess_book_edge_snapshot-scawa", >_<
        ":intewaction_gwaph_agg_addwess_book_vewtex_snapshot-scawa", rawr x3
        "3wdpawty/jvm/com/twittew/stowehaus:awgebwa", mya
        "addwessbook/jobs/swc/main/scawa/com/twittew/addwessbook/jobs/simpwematches:simpwe_usew_matches-scawa", nyaa~~
        "beam-intewnaw/swc/main/scawa/com/twittew/beam/io/daw", (⑅˘꒳˘)
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/job", rawr x3
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/wunnew/datafwow", (✿oωo)
        "consumew-data-toows/swc/main/scawa/com/twittew/cde/scio/daw_wead",
        "swc/scawa/com/twittew/intewaction_gwaph/scio/common", (ˆ ﻌ ˆ)♡
    ], (˘ω˘)
)

j-jvm_binawy(
    n-nyame = "intewaction_gwaph_addwess_book_scio", (⑅˘꒳˘)
    m-main = "com.twittew.intewaction_gwaph.scio.agg_addwess_book.intewactiongwaphaddwessbookjob", (///ˬ///✿)
    p-pwatfowm = "java8", 😳😳😳
    tags = ["bazew-compatibwe"], 🥺
    dependencies = [
        ":agg_addwess_book", mya
    ], 🥺
)

cweate_datasets(
    base_name = "intewaction_gwaph_agg_addwess_book_edge_snapshot", >_<
    descwiption = "usew-usew d-diwected edges with addwessbook featuwes", >_<
    j-java_schema = "com.twittew.intewaction_gwaph.thwiftjava.edge", (⑅˘꒳˘)
    pwatfowm = "java8", /(^•ω•^)
    w-wowe = "cassowawy", rawr x3
    scawa_schema = "com.twittew.intewaction_gwaph.thwiftscawa.edge", (U ﹏ U)
    segment_type = "snapshot",
    tags = ["bazew-compatibwe"], (U ﹏ U)
    java_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-java", (⑅˘꒳˘)
    ],
    scawa_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-scawa", òωó
    ],
)

c-cweate_datasets(
    base_name = "intewaction_gwaph_agg_addwess_book_vewtex_snapshot", ʘwʘ
    d-descwiption = "usew v-vewtex with addwessbook featuwes", /(^•ω•^)
    java_schema = "com.twittew.intewaction_gwaph.thwiftjava.vewtex", ʘwʘ
    pwatfowm = "java8", σωσ
    wowe = "cassowawy", OwO
    s-scawa_schema = "com.twittew.intewaction_gwaph.thwiftscawa.vewtex", 😳😳😳
    segment_type = "snapshot", 😳😳😳
    tags = ["bazew-compatibwe"], o.O
    java_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-java", ( ͡o ω ͡o )
    ],
    scawa_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-scawa", (U ﹏ U)
    ],
)
