scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", UwU
        "swc/java/com/twittew/mw/api:api-base", rawr x3
        "swc/scawa/com/twittew/mw/api/utiw:datawecowd", rawr
        "swc/thwift/com/twittew/daw/pewsonaw_data:pewsonaw_data-java", σωσ
        "swc/thwift/com/twittew/mw/api:data-java", σωσ
        "swc/thwift/com/twittew/mw/api:data-scawa",
    ], >_<
    e-expowts = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", :3
        "swc/thwift/com/twittew/daw/pewsonaw_data:pewsonaw_data-java", (U ﹏ U)
        "swc/thwift/com/twittew/mw/api:data-java", -.-
        "swc/thwift/com/twittew/mw/api:data-scawa", (ˆ ﻌ ˆ)♡
    ], (⑅˘꒳˘)
)
