scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon",
        "src/java/com/twittelonr/ml/api:api-baselon",
        "src/scala/com/twittelonr/ml/api/util:datareloncord",
        "src/thrift/com/twittelonr/dal/pelonrsonal_data:pelonrsonal_data-java",
        "src/thrift/com/twittelonr/ml/api:data-java",
        "src/thrift/com/twittelonr/ml/api:data-scala",
    ],
    elonxports = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon",
        "src/thrift/com/twittelonr/dal/pelonrsonal_data:pelonrsonal_data-java",
        "src/thrift/com/twittelonr/ml/api:data-java",
        "src/thrift/com/twittelonr/ml/api:data-scala",
    ],
)
