scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/algelonbird:corelon",
        "belonam-intelonrnal/src/main/scala/com/twittelonr/belonam/io/dal",
        "belonam-intelonrnal/src/main/scala/com/twittelonr/scio_intelonrnal/job",
        "belonam-intelonrnal/src/main/scala/com/twittelonr/scio_intelonrnal/runnelonr/dataflow",
        "flockdb-tools/dataselonts/flock/src/main/thrift:thrift-scala",
        "src/scala/com/twittelonr/pluck/sourcelon/combinelond_uselonr_scroogelon_sourcelon",
        "src/thrift/com/twittelonr/gizmoduck:uselonr-thrift-scala",
        "src/thrift/com/twittelonr/intelonraction_graph:intelonraction_graph-scala",
        "src/thrift/com/twittelonr/socialgraph:thrift-scala",
        "src/thrift/com/twittelonr/twadoop/uselonr/gelonn:gelonn-scala",
        "src/thrift/com/twittelonr/uselonr_selonssion_storelon:thrift-scala",
        "uselonrsourcelon/snapshot/src/main/scala/com/twittelonr/uselonrsourcelon/snapshot/flat:uselonrsourcelon_flat-scala",
    ],
)

scala_library(
    namelon = "felonaturelon_groups",
    sourcelons = ["FelonaturelonGroups.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/intelonraction_graph:intelonraction_graph-scala",
    ],
)
