scawa_wibwawy(
    souwces = ["*.scawa"], ( ͡o ω ͡o )
    compiwew_option_sets = ["fataw_wawnings"], UwU
    p-pwatfowm = "java8", rawr x3
    t-tags = ["bazew-compatibwe"], rawr
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/awgebiwd:cowe", σωσ
        "beam-intewnaw/swc/main/scawa/com/twittew/beam/io/daw", σωσ
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/job", >_<
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/wunnew/datafwow", :3
        "fwockdb-toows/datasets/fwock/swc/main/thwift:thwift-scawa", (U ﹏ U)
        "swc/scawa/com/twittew/pwuck/souwce/combined_usew_scwooge_souwce", -.-
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-scawa",
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/twadoop/usew/gen:gen-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/usew_session_stowe:thwift-scawa", -.-
        "usewsouwce/snapshot/swc/main/scawa/com/twittew/usewsouwce/snapshot/fwat:usewsouwce_fwat-scawa", ^^;;
    ],
)

s-scawa_wibwawy(
    n-nyame = "featuwe_gwoups", >_<
    s-souwces = ["featuwegwoups.scawa"], mya
    compiwew_option_sets = ["fataw_wawnings"], mya
    p-pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], 😳
    dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-scawa", XD
    ],
)
