scawa_wibwawy(
    souwces = ["*.scawa"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", OwO
        "swc/scawa/com/twittew/simcwustews_v2/common", 🥺
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", òωó
    ],
)
