scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", ( ͡o ω ͡o )
        "tweetypie/sewvo/utiw", UwU
        "snowfwake:id", rawr x3
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", rawr
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", σωσ
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:media-entity-scawa", σωσ
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", >_<
        "tweetypie/sewvew/swc/main/thwift:compiwed-scawa", :3
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/utiw", (U ﹏ U)
        "utiw/utiw-swf4j-api", -.-
    ],
)
