scawa_wibwawy(
    nyame = "sewvew", UwU
    souwces = ["*.scawa"], rawr x3
    c-compiwew_option_sets = ["fataw_wawnings"],
    t-tags = ["bazew-compatibwe"], rawr
    d-dependencies = [
        "ann/swc/main/java/com/twittew/ann/faiss", σωσ
        "ann/swc/main/scawa/com/twittew/ann/common", σωσ
        "ann/swc/main/scawa/com/twittew/ann/faiss", >_<
        "ann/swc/main/scawa/com/twittew/ann/sewvice/quewy_sewvew/common",
        "ann/swc/main/scawa/com/twittew/ann/sewvice/quewy_sewvew/common:faiss_index_path_pwovidew", :3
        "ann/swc/main/scawa/com/twittew/ann/sewvice/quewy_sewvew/common/thwottwing", (U ﹏ U)
        "ann/swc/main/scawa/com/twittew/ann/sewvice/quewy_sewvew/common/wawmup", -.-
        "swc/java/com/twittew/seawch/common/fiwe", (ˆ ﻌ ˆ)♡
    ], (⑅˘꒳˘)
)

j-jvm_binawy(
    n-nyame = "faiss-quewy-sewvew", (U ᵕ U❁)
    m-main = "com.twittew.ann.sewvice.quewy_sewvew.faiss.faissquewyindexsewvew", -.-
    c-compiwew_option_sets = ["fataw_wawnings"], ^^;;
    w-wuntime_pwatfowm = "java11", >_<
    tags = ["bazew-compatibwe"], mya
    dependencies = [
        ":sewvew", mya
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", 😳
        "3wdpawty/jvm/owg/swf4j:jcw-ovew-swf4j", XD
        "3wdpawty/jvm/owg/swf4j:juw-to-swf4j", :3
        "3wdpawty/jvm/owg/swf4j:wog4j-ovew-swf4j", 😳😳😳
        "ann/swc/main/wesouwces", -.-
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", ( ͡o ω ͡o )
    ],
)
