scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "finagle-internal/slo/src/main/scala/com/X/finagle/slo",
        "finatra/inject/inject-thrift-client",
        "representation-scorer/server/src/main/scala/com/X/representationscorer/columns",
        "strato/src/main/scala/com/X/strato/fed",
        "strato/src/main/scala/com/X/strato/fed/server",
        "X-server-internal/src/main/scala",
    ],
)
