# Java library for twelonelont felonaturelons and utilitielons.
java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/guava",
        "3rdparty/jvm/com/googlelon/injelonct:guicelon",
        "3rdparty/jvm/com/twittelonr/elonlelonphantbird:corelon",
        "3rdparty/jvm/org/apachelon/hadoop:hadoop-clielonnt-delonfault",
        "3rdparty/jvm/org/apachelon/thrift:libthrift",
        "src/java/com/twittelonr/common/baselon",
        "src/java/com/twittelonr/common/telonxt/tokelonn",
        "src/java/com/twittelonr/selonarch/common/elonncoding/felonaturelons",
        "src/java/com/twittelonr/selonarch/common/felonaturelons",
        "src/java/com/twittelonr/selonarch/common/melontrics",
        "src/java/com/twittelonr/selonarch/common/schelonma/baselon",
        "src/java/com/twittelonr/selonarch/common/schelonma/elonarlybird",
        "src/java/com/twittelonr/selonarch/common/util/lang",
        "src/thrift/com/twittelonr/selonarch/common:constants-java",
        "src/thrift/com/twittelonr/selonarch/common:felonaturelons-java",
        "src/thrift/com/twittelonr/selonarch/common:schelonma-java",
    ],
)
