scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-annotations", UwU
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-cowe", rawr x3
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-databind", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/common/awewt", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common/identifiew", :3
    ],
    e-expowts = [
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-annotations", (U ﹏ U)
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-cowe", -.-
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-databind", (ˆ ﻌ ˆ)♡
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", (⑅˘꒳˘)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap", (U ᵕ U❁)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/common/awewt", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common/identifiew", ^^;;
    ], >_<
)
