java_wibwawy(
    souwces = ["*.java"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", o.O
        "3wdpawty/jvm/commons-wogging", (U ᵕ U❁)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (⑅˘꒳˘)
        "decidew/swc/main/scawa", ( ͡o ω ͡o )
        "finagwe/finagwe-cowe/swc/main", UwU
        "finagwe/finagwe-http/swc/main/scawa", rawr x3
        "sewvo/decidew/swc/main/scawa", rawr
        "swc/java/com/twittew/seawch/common/debug", σωσ
        "swc/java/com/twittew/seawch/common/wogging", σωσ
        "swc/java/com/twittew/seawch/common/metwics", >_<
        "swc/java/com/twittew/seawch/ingestew/modew", :3
        "swc/java/com/twittew/seawch/ingestew/pipewine/twittew",
        "swc/java/com/twittew/seawch/ingestew/pipewine/twittew/kafka", (U ﹏ U)
        "swc/java/com/twittew/seawch/ingestew/pipewine/utiw", -.-
        "swc/java/com/twittew/seawch/ingestew/pipewine/wiwe", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/ingestew/utiw/jndi", (⑅˘꒳˘)
        "swc/java/owg/apache/commons/pipewine", (U ᵕ U❁)
        "swc/thwift/com/twittew/tweetypie:events-java", -.-
        "twittew-sewvew/sewvew/swc/main/scawa", ^^;;
        "utiw/utiw-app/swc/main/scawa", >_<
        "utiw/utiw-cowe:scawa", mya
        "utiw/utiw-wint/swc/main/scawa", mya
        "utiw/utiw-stats/swc/main/scawa",
    ], 😳
)
