cweate_thwift_wibwawies(
    base_name = "thwift", 🥺
    souwces = [
        "com/twittew/wepwesentation_managew/sewvice.thwift", òωó
    ], o.O
    p-pwatfowm = "java8",
    t-tags = [
        "bazew-compatibwe", (U ᵕ U❁)
    ], (⑅˘꒳˘)
    d-dependency_woots = [
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift", ( ͡o ω ͡o )
    ],
    g-genewate_wanguages = [
        "java", UwU
        "scawa", rawr x3
        "stwato", rawr
    ], σωσ
)
