scala_library(
    namelon = "simclustelonrs_indelonx_gelonnelonration",
    sourcelons = [
        "**/*.scala",
    ],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:ads_fav_baselond_simclustelonrs_clustelonr_to_twelonelont_indelonx-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:ads_fav_click_baselond_simclustelonrs_clustelonr_to_twelonelont_indelonx-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:fav_baselond_elonvelonrgrelonelonn_contelonnt_simclustelonrs_clustelonr_to_twelonelont_indelonx-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:fav_baselond_simclustelonrs_clustelonr_to_twelonelont_indelonx-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:fav_baselond_videlono_simclustelonrs_clustelonr_to_twelonelont_indelonx-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:push_opelonn_baselond_simclustelonrs_clustelonr_to_twelonelont_indelonx-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:relonply_baselond_simclustelonrs_clustelonr_to_twelonelont_indelonx-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:relontwelonelont_baselond_simclustelonrs_clustelonr_to_twelonelont_indelonx-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:videlono_vielonw_baselond_simclustelonrs_clustelonr_to_twelonelont_indelonx-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/scio/bq_gelonnelonration/common",
        "src/scala/com/twittelonr/simclustelonrs_v2/scio/bq_gelonnelonration/sql",
        "src/scala/com/twittelonr/simclustelonrs_v2/scio/bq_gelonnelonration/twelonelonts_ann:bq_gelonnelonration",
        "unifielond_uselonr_actions/thrift/src/main/thrift/com/twittelonr/unifielond_uselonr_actions:unifielond_uselonr_actions-scala",
    ],
)

jvm_binary(
    namelon = "fav-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.FavBaselondClustelonrToTwelonelontIndelonxGelonnelonrationAdhocJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "fav-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.FavBaselondClustelonrToTwelonelontIndelonxGelonnelonrationBatchJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "videlono-vielonw-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.VidelonoVielonwBaselondClustelonrToTwelonelontIndelonxGelonnelonrationAdhocJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "videlono-vielonw-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.VidelonoVielonwBaselondClustelonrToTwelonelontIndelonxGelonnelonrationBatchJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "relontwelonelont-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.RelontwelonelontBaselondClustelonrToTwelonelontIndelonxGelonnelonrationAdhocJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "relontwelonelont-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.RelontwelonelontBaselondClustelonrToTwelonelontIndelonxGelonnelonrationBatchJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "relonply-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.RelonplyBaselondClustelonrToTwelonelontIndelonxGelonnelonrationAdhocJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "relonply-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.RelonplyBaselondClustelonrToTwelonelontIndelonxGelonnelonrationBatchJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "push-opelonn-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.PushOpelonnBaselondClustelonrToTwelonelontIndelonxGelonnelonrationAdhocJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "push-opelonn-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.PushOpelonnBaselondClustelonrToTwelonelontIndelonxGelonnelonrationBatchJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "ads-fav-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.AdsFavBaselondClustelonrToTwelonelontIndelonxGelonnelonrationAdhocJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "ads-fav-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.AdsFavBaselondClustelonrToTwelonelontIndelonxGelonnelonrationBatchJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "ads-fav-click-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.AdsFavClickBaselondClustelonrToTwelonelontIndelonxGelonnelonrationAdhocJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "ads-fav-click-baselond-clustelonr-to-twelonelont-indelonx-gelonnelonration-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.AdsFavClickBaselondClustelonrToTwelonelontIndelonxGelonnelonrationBatchJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "fav-baselond-elonvelonrgrelonelonn-contelonnt-clustelonr-to-twelonelont-indelonx-gelonnelonration-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.FavBaselondelonvelonrgrelonelonnContelonntClustelonrToTwelonelontIndelonxGelonnelonrationAdhocJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "fav-baselond-elonvelonrgrelonelonn-contelonnt-clustelonr-to-twelonelont-indelonx-gelonnelonration-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.FavBaselondelonvelonrgrelonelonnContelonntClustelonrToTwelonelontIndelonxGelonnelonrationBatchJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "fav-baselond-videlono-clustelonr-to-twelonelont-indelonx-gelonnelonration-adhoc-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.FavBaselondVidelonoClustelonrToTwelonelontIndelonxGelonnelonrationAdhocJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)

jvm_binary(
    namelon = "fav-baselond-videlono-clustelonr-to-twelonelont-indelonx-gelonnelonration-batch-job",
    main = "com.twittelonr.simclustelonrs_v2.scio.bq_gelonnelonration.simclustelonrs_indelonx_gelonnelonration.FavBaselondVidelonoClustelonrToTwelonelontIndelonxGelonnelonrationBatchJob",
    delonpelonndelonncielons = [
        ":simclustelonrs_indelonx_gelonnelonration",
    ],
)
