scala_library(
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/storelonhaus:corelon",
        "frigatelon/frigatelon-common:baselon",
        "frigatelon/frigatelon-common/src/main/scala/com/twittelonr/frigatelon/common/baselon",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
        "src/scala/com/twittelonr/simclustelonrs_v2/scorelon",
        "src/scala/com/twittelonr/simclustelonrs_v2/summingbird/storelons",
        "src/scala/com/twittelonr/simclustelonrs_v2/twelonelont_similarity",
        "src/thrift/com/twittelonr/reloncos/uselonr_twelonelont_elonntity_graph:uselonr_twelonelont_elonntity_graph-scala",
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-scala",
        "src/thrift/com/twittelonr/wtf/intelonrelonst:intelonrelonst-thrift-scala",
        "util/util-stats/src/main/scala/com/twittelonr/finaglelon/stats",
    ],
)
