scala_library(
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/twitter/storehaus:core",
        "frigate/frigate-common:base",
        "frigate/frigate-common/src/main/scala/com/twitter/frigate/common/base",
        "src/scala/com/twitter/simclusters_v2/common",
        "src/scala/com/twitter/simclusters_v2/score",
        "src/scala/com/twitter/simclusters_v2/summingbird/stores",
        "src/scala/com/twitter/simclusters_v2/tweet_similarity",
        "src/thrift/com/twitter/recos/user_tweet_entity_graph:user_tweet_entity_graph-scala",
        "src/thrift/com/twitter/simclusters_v2:simclusters_v2-thrift-scala",
        "src/thrift/com/twitter/wtf/interest:interest-thrift-scala",
        "util/util-stats/src/main/scala/com/twitter/finagle/stats",
    ],
)
