scawa_wibwawy(
    souwces = ["*.scawa"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/gwaphjet", OwO
        "snowfwake:id", 🥺
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", òωó
        "swc/scawa/com/twittew/wecos/utiw:wecos-utiw", o.O
        "swc/scawa/com/twittew/simcwustews_v2/common", (U ᵕ U❁)
        "swc/thwift/com/twittew/wecos/usew_tweet_gwaph:usew_tweet_gwaph-scawa", (⑅˘꒳˘)
    ],
)
