scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/github/ben-manes/caffeine", òωó
        "finatwa/inject/inject-cowe/swc/main/scawa", o.O
        "wepwesentation-scowew/sewvew/swc/main/scawa/com/twittew/wepwesentationscowew/common", (U ᵕ U❁)
        "wepwesentation-scowew/sewvew/swc/main/scawa/com/twittew/wepwesentationscowew/scowestowe", (⑅˘꒳˘)
        "wepwesentation-scowew/sewvew/swc/main/thwift:thwift-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/twistwy:twistwy-scawa", UwU
        "stitch/stitch-cowe", rawr x3
        "stitch/stitch-cowe:cache", rawr
        "stwato/config/cowumns/wecommendations/twistwy:twistwy-stwato-cwient", σωσ
        "stwato/config/cowumns/wecommendations/usew-signaw-sewvice:usew-signaw-sewvice-stwato-cwient", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", >_<
        "usew-signaw-sewvice/thwift/swc/main/thwift:thwift-scawa", :3
        "utiw/utiw-cowe", (U ﹏ U)
    ],
)
