java_library(
    sources = ["*.java"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/com/google/inject:guice",
        "3rdparty/jvm/it/unimi/dsi:fastutil",
        "3rdparty/jvm/org/apache/hadoop:hadoop-client-default",
        "3rdparty/jvm/org/apache/thrift:libthrift",
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "src/java/com/X/common/base",
        "src/java/com/X/search/common/file",
        "src/java/com/X/search/common/util/io",
    ],
)
