scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "finatra/inject/inject-thrift-client",
        "frigate/frigate-common/src/main/scala/com/X/frigate/common/store/strato",
        "hermit/hermit-core/src/main/scala/com/X/hermit/store/common",
        "relevance-platform/src/main/scala/com/X/relevance_platform/common/readablestore",
        "representation-manager/client/src/main/scala/com/X/representation_manager/config",
        "representation-manager/server/src/main/thrift:thrift-scala",
        "src/scala/com/X/simclusters_v2/common",
        "src/thrift/com/X/simclusters_v2:simclusters_v2-thrift-scala",
        "stitch/stitch-storehaus",
        "strato/src/main/scala/com/X/strato/client",
    ],
)
