#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/ttm/header.h"

#include "levels/ttm/star_cage/geo.inc.c"
#include "levels/ttm/rolling_log/geo.inc.c"
#include "levels/ttm/areas/1/3/geo.inc.c"
#include "levels/ttm/areas/1/4/geo.inc.c"
#include "levels/ttm/areas/1/5/geo.inc.c"
#include "levels/ttm/areas/1/6/geo.inc.c"
#include "levels/ttm/areas/1/7/geo.inc.c"
#include "levels/ttm/areas/1/8/geo.inc.c"
#include "levels/ttm/areas/1/9/geo.inc.c"
#include "levels/ttm/areas/1/10/geo.inc.c"
#include "levels/ttm/areas/1/11/geo.inc.c"
#include "levels/ttm/areas/1/12/geo.inc.c"
#include "levels/ttm/areas/1/13/geo.inc.c"
#include "levels/ttm/areas/1/14/geo.inc.c"
#include "levels/ttm/areas/1/15/geo.inc.c"
#include "levels/ttm/areas/1/16/geo.inc.c"
#include "levels/ttm/areas/1/17/geo.inc.c"
#include "levels/ttm/areas/1/18/geo.inc.c"
#include "levels/ttm/areas/1/19/geo.inc.c"
#include "levels/ttm/areas/1/20/geo.inc.c"
#include "levels/ttm/areas/1/21/geo.inc.c"
#include "levels/ttm/areas/1/geo.inc.c"
#include "levels/ttm/areas/2/geo.inc.c"
#include "levels/ttm/areas/3/geo.inc.c"
#include "levels/ttm/areas/4/geo.inc.c"
#include "levels/ttm/blue_smiley/geo.inc.c"
#include "levels/ttm/yellow_smiley/geo.inc.c"
#include "levels/ttm/star_smiley/geo.inc.c"
#include "levels/ttm/moon_smiley/geo.inc.c"
#include "levels/ttm/slide_exit_podium/geo.inc.c"
