scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", UwU
        "notificationsewvice/common/swc/main/scawa/com/twittew/notificationsewvice/modew:awias",
        "notificationsewvice/common/swc/main/scawa/com/twittew/notificationsewvice/modew/notification", rawr x3
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", rawr
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", σωσ
        "swc/thwift/com/twittew/spam/wtf:safety-wabew-scawa", σωσ
        "stitch/stitch-cowe", >_<
        "stitch/stitch-gizmoduck/swc/main/scawa", :3
        "stitch/stitch-sociawgwaph", (U ﹏ U)
        "stitch/stitch-sociawgwaph/swc/main/scawa", -.-
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", (ˆ ﻌ ˆ)♡
        "visibiwity/common/swc/main/thwift/com/twittew/visibiwity:action-scawa", (⑅˘꒳˘)
        "visibiwity/wib/swc/main/wesouwces/config", (U ᵕ U❁)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/tweets", ^^;;
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/usews", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/pawams",
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", mya
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/common/tweets", mya
    ],
    e-expowts = [
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", 😳
    ], XD
)
