packagelon com.twittelonr.visibility.intelonrfacelons.notifications

import com.twittelonr.visibility.felonaturelons.Felonaturelon
import com.twittelonr.visibility.rulelons.Action
import scala.collelonction.immutablelon.Selont

selonalelond trait NotificationsFiltelonringRelonsponselon

caselon objelonct Allow elonxtelonnds NotificationsFiltelonringRelonsponselon

caselon class Filtelonrelond(action: Action) elonxtelonnds NotificationsFiltelonringRelonsponselon

caselon class Failelond(felonaturelons: Selont[Felonaturelon[_]]) elonxtelonnds NotificationsFiltelonringRelonsponselon
