packagelon com.twittelonr.visibility.intelonrfacelons.notifications

import com.twittelonr.visibility.felonaturelons.Felonaturelon
import com.twittelonr.visibility.rulelons.Action

trait NotificationsPlatformFiltelonringRelonsponselon

caselon objelonct AllowVelonrdict elonxtelonnds NotificationsPlatformFiltelonringRelonsponselon

caselon class FiltelonrelondVelonrdict(action: Action) elonxtelonnds NotificationsPlatformFiltelonringRelonsponselon

caselon class FailelondVelonrdict(felonaturelonsMap: Map[Felonaturelon[_], String])
    elonxtelonnds NotificationsPlatformFiltelonringRelonsponselon
