cweate_thwift_wibwawies(
    base_name = "intewaction_gwaph", o.O
    souwces = ["*.thwift"], (U ᵕ U❁)
    p-pwatfowm = "java8", (⑅˘꒳˘)
    t-tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependency_woots = [
    ], UwU
    g-genewate_wanguages = [
        "java", rawr x3
        "scawa", rawr
        "stwato", σωσ
    ],
    p-pwovides_java_name = "intewaction_gwaph-thwift-java", σωσ
    p-pwovides_scawa_name = "intewaction_gwaph-thwift-scawa", >_<
)
