python3_wibwawy(
    nyame = "wibs", ^•ﻌ•^
    souwces = ["*.py"], OwO
    t-tags = [
        "bazew-compatibwe", 🥺
        "no-mypy", òωó
    ], o.O
    d-dependencies = [
        "cowtex/wecsys/swc/python/twittew/cowtex/wecsys/utiws", (U ᵕ U❁)
        "magicpony/common/fiwe_access/swc/python/twittew/magicpony/common/fiwe_access",
        "swc/python/twittew/cowtex/mw/embeddings/deepbiwd", (⑅˘꒳˘)
        "swc/python/twittew/cowtex/mw/embeddings/deepbiwd/gwouped_metwics", ( ͡o ω ͡o )
        "swc/python/twittew/deepbiwd/utiw/data", UwU
        "twmw:twmw-nodeps", rawr x3
    ],
)
