scawa_wibwawy(
    tags = ["bazew-compatibwe"], >_<
    dependencies = [
        "3wdpawty/jvm/com/googwe/guava", (ꈍᴗꈍ)
        "3wdpawty/jvm/com/twittew/stowehaus:cowe",
        "fwigate/fwigate-common:base", ^•ﻌ•^
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/base", OwO
        "simcwustews-ann/thwift/swc/main/thwift:thwift-scawa", 🥺
        "swc/scawa/com/twittew/simcwustews_v2/common", òωó
        "swc/scawa/com/twittew/simcwustews_v2/summingbiwd/stowes", o.O
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", (U ᵕ U❁)
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats", (⑅˘꒳˘)
    ],
)
