scala_library(
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/guava",
        "3rdparty/jvm/com/twittelonr/storelonhaus:corelon",
        "frigatelon/frigatelon-common:baselon",
        "frigatelon/frigatelon-common/src/main/scala/com/twittelonr/frigatelon/common/baselon",
        "simclustelonrs-ann/thrift/src/main/thrift:thrift-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
        "src/scala/com/twittelonr/simclustelonrs_v2/summingbird/storelons",
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-scala",
        "util/util-stats/src/main/scala/com/twittelonr/finaglelon/stats",
    ],
)
