packagelon com.twittelonr.product_mixelonr.componelonnt_library.modelonl.prelonselonntation.urt

import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.urt.BaselonUrtItelonmPrelonselonntation
import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.urt.IsDispelonnsablelon
import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.urt.WithItelonmTrelonelonDisplay

trait ConvelonrsationModulelonItelonm
    elonxtelonnds BaselonUrtItelonmPrelonselonntation
    with IsDispelonnsablelon
    with WithItelonmTrelonelonDisplay
