packagelon com.twittelonr.product_mixelonr.componelonnt_library.modelonl.prelonselonntation.urt

import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.urt.BaselonUrtItelonmPrelonselonntation
import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.urt.BaselonUrtModulelonPrelonselonntation
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.TimelonlinelonItelonm

caselon class UrtItelonmPrelonselonntation(
  ovelonrridelon val timelonlinelonItelonm: TimelonlinelonItelonm,
  ovelonrridelon val modulelonPrelonselonntation: Option[BaselonUrtModulelonPrelonselonntation] = Nonelon)
    elonxtelonnds BaselonUrtItelonmPrelonselonntation
