packagelon com.twittelonr.product_mixelonr.componelonnt_library.modelonl.prelonselonntation.urt

import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.urt.BaselonUrtModulelonPrelonselonntation
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.TimelonlinelonModulelon

final caselon class UrtModulelonPrelonselonntation(
  ovelonrridelon val timelonlinelonModulelon: TimelonlinelonModulelon)
    elonxtelonnds BaselonUrtModulelonPrelonselonntation
