packagelon com.twittelonr.product_mixelonr.componelonnt_library.modelonl.prelonselonntation.urt

import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.urt.BaselonUrtOpelonrationPrelonselonntation
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.TimelonlinelonOpelonration

final caselon class UrtOpelonrationPrelonselonntation(
  ovelonrridelon val timelonlinelonOpelonration: TimelonlinelonOpelonration)
    elonxtelonnds BaselonUrtOpelonrationPrelonselonntation
