scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", UwU
        "3wdpawty/jvm/com/ibm/icu:icu4j", rawr x3
        "decidew/swc/main/scawa", rawr
        "sewvo/decidew/swc/main/scawa", σωσ
        "sewvo/wepo", σωσ
        "swc/thwift/com/twittew/context:twittew-context-scawa", >_<
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", :3
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa",
        "swc/thwift/com/twittew/spam/wtf:tweet-wtf-event-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/timewines/wendew:thwift-scawa", -.-
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", (⑅˘꒳˘)
        "stitch/stitch-cowe", (U ᵕ U❁)
        "twanswation/swc/main/scawa", -.-
        "twittew-config/yamw", ^^;;
        "twittew-context/swc/main/scawa",
        "uwt/wichtext/swc/main/scawa/com/twittew/uwt/wichtext",
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", >_<
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions", mya
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/fiwtewed_weason", mya
        "visibiwity/common/swc/main/thwift/com/twittew/visibiwity:action-scawa", 😳
        "visibiwity/wib/swc/main/wesouwces/config", XD
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/tweets", 😳😳😳
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/usews", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs", ( ͡o ω ͡o )
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/pawams", rawr x3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", nyaa~~
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/common/tweets", /(^•ω•^)
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/wogging:vf-wogging-scawa", rawr
        "visibiwity/wesuwts/swc/main/scawa/com/twittew/visibiwity/wesuwts/wichtext", OwO
        "visibiwity/wesuwts/swc/main/scawa/com/twittew/visibiwity/wesuwts/twanswation", (U ﹏ U)
        "visibiwity/wesuwts/swc/main/scawa/com/twittew/visibiwity/wesuwts/uwt", >_<
    ],
    e-expowts = [
        "visibiwity/common/swc/main/thwift/com/twittew/visibiwity:action-scawa", rawr x3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", mya
    ], nyaa~~
)
