scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/owg/mapdb", (⑅˘꒳˘)
        "ann/swc/main/java/com/twittew/ann/hnsw",
        "ann/swc/main/scawa/com/twittew/ann/common", ( ͡o ω ͡o )
        "ann/swc/main/scawa/com/twittew/ann/sewiawization", UwU
        "ann/swc/main/thwift/com/twittew/ann/common:ann-common-scawa", rawr x3
        "mediasewvices/commons/swc/main/scawa:futuwetwackew", rawr
        "swc/java/com/twittew/common_intewnaw/hadoop", σωσ
        "swc/java/com/twittew/seawch/common/fiwe",
        "swc/scawa/com/twittew/mw/api/embedding", σωσ
    ],
    e-expowts = [
        "ann/swc/main/scawa/com/twittew/ann/common",
        "swc/java/com/twittew/common_intewnaw/hadoop", >_<
        "swc/java/com/twittew/seawch/common/fiwe", :3
        "swc/scawa/com/twittew/mw/api/embedding", (U ﹏ U)
    ], -.-
)
tion", :3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wequest", (U ﹏ U)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine:quewy", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/sewvice", (ˆ ﻌ ˆ)♡
    ],
    e-expowts = [
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", (⑅˘꒳˘)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", (U ᵕ U❁)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap/asyncfeatuwemap", ^^;;
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/decowatow:decowation", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common/pwesentation", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wequest", 😳
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine:quewy", XD
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/sewvice", :3
    ],
)
