scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", (⑅˘꒳˘)
        "finagwe/finagwe-cowe/swc/main", ( ͡o ω ͡o )
        "finagwe/finagwe-memcached/swc/main/scawa", UwU
        "scwooge/scwooge-cowe", rawr x3
        "tweetypie/sewvo/utiw", rawr
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", σωσ
        "stitch/stitch-cowe/swc/main/scawa/com/twittew/stitch", σωσ
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", >_<
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/cwient_id", :3
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/thwiftscawa/entities", (U ﹏ U)
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/tweettext", -.-
        "twittew-config/yamw", (ˆ ﻌ ˆ)♡
        "utiw/utiw-hashing/swc/main/scawa", (⑅˘꒳˘)
        "utiw/utiw-swf4j-api/swc/main/scawa/com/twittew/utiw/wogging", (U ᵕ U❁)
        "utiw/utiw-stats/swc/main/scawa", -.-
    ], ^^;;
)
