scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon/pipelonlinelon_failurelon",
        "stitch/stitch-corelon",
        "strato/src/main/scala/com/twittelonr/strato/catalog",
        "strato/src/main/scala/com/twittelonr/strato/clielonnt",
        "strato/src/main/scala/com/twittelonr/strato/relonsponselon",
    ],
    elonxports = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon",
        "stitch/stitch-corelon",
        "strato/src/main/scala/com/twittelonr/strato/catalog",
        "strato/src/main/scala/com/twittelonr/strato/clielonnt",
    ],
)
