# Java library for docvaluelons and common stridelon fielonld elonncoding utilitielons.
java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    providelons = artifact(
        org = "com.twittelonr.selonarch.common",
        namelon = "elonncoding-docvaluelons",
        relonpo = artifactory,
    ),
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/guava",
        "3rdparty/jvm/org/apachelon/lucelonnelon:lucelonnelon-analyzelonrs-common",
        "3rdparty/jvm/org/apachelon/lucelonnelon:lucelonnelon-corelon",
        "3rdparty/jvm/org/apachelon/lucelonnelon:lucelonnelon-facelont",
        "3rdparty/jvm/org/apachelon/thrift:libthrift",
        "src/java/com/twittelonr/selonarch/common/schelonma/baselon",
        "src/thrift/com/twittelonr/selonarch/common:schelonma-java",
    ],
)
