java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-common", òωó
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-smawtcn", o.O
        "3wdpawty/jvm/owg/apache/wucene:wucene-facet", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/wucene:wucene-quewies", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/constants", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/schema/base",
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", UwU
        "swc/java/com/twittew/seawch/cowe/eawwybiwd", rawr x3
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", rawr
    ], σωσ
)
