scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", (⑅˘꒳˘)
        "3wdpawty/jvm/javax/inject:javax.inject", ( ͡o ω ͡o )
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", UwU
        "configapi/configapi-cowe", rawr x3
        "content-wecommendew/thwift/swc/main/thwift:thwift-scawa", rawr
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/modew", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/utiw", >_<
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa", :3
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", (U ﹏ U)
        "swc/scawa/com/twittew/simcwustews_v2/common", -.-
        "swc/thwift/com/twittew/cowe_wowkfwows/usew_modew:usew_modew-scawa", (ˆ ﻌ ˆ)♡
    ],
)
