scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finatra/injelonct/injelonct-corelon/src/main/scala/com/twittelonr/injelonct",
        "pelonoplelon-discovelonry/api/thrift:thrift-scala",
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/candidatelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon/pipelonlinelon_failurelon",
        "src/thrift/com/twittelonr/ads/adselonrvelonr:adselonrvelonr_common-scala",
        "src/thrift/com/twittelonr/helonrmit:helonrmit-scala",
        "stitch/stitch-corelon",
    ],
    elonxports = [
        "finatra/injelonct/injelonct-corelon/src/main/scala/com/twittelonr/injelonct",
        "pelonoplelon-discovelonry/api/thrift:thrift-scala",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon",
        "stitch/stitch-corelon",
    ],
)
