scawa_wibwawy(
    souwces = [
        "*.scawa", (⑅˘꒳˘)
    ],
    compiwew_option_sets = ["fataw_wawnings"], (U ᵕ U❁)
    p-pwatfowm = "java8", -.-
    t-tags = ["bazew-compatibwe"], ^^;;
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/awgebiwd:cowe", >_<
        "gwaphstowe/common:fwock_bwocks-java", mya
        "swc/java/com/twittew/seawch/common/featuwes", mya
        "swc/scawa/com/twittew/mw/api:api-base", 😳
        "swc/scawa/com/twittew/scawding_intewnaw/dawv2", XD
        "swc/scawa/com/twittew/scawding_intewnaw/dawv2/dataset", :3
        "swc/scawa/com/twittew/scawding_intewnaw/souwce/wzo_scwooge", 😳😳😳
        "swc/scawa/com/twittew/seawch/tweet_wanking/scawding/datasets:tweet_engagement_waw_twaining_data_daiwy-java", -.-
        "swc/scawa/com/twittew/simcwustews_v2/hdfs_souwces", ( ͡o ω ͡o )
        "swc/scawa/com/twittew/simcwustews_v2/hdfs_souwces:adhoc_abuse_simcwustew_featuwes-scawa", rawr x3
        "swc/scawa/com/twittew/simcwustews_v2/hdfs_souwces:adhoc_cwoss_simcwustew_bwock_intewaction_featuwes-scawa", nyaa~~
        "swc/scawa/com/twittew/simcwustews_v2/hdfs_souwces:adhoc_cwoss_simcwustew_fav_intewaction_featuwes-scawa", /(^•ω•^)
        "swc/scawa/com/twittew/simcwustews_v2/hdfs_souwces:seawch_abuse_simcwustew_featuwes_manhattan-scawa",
        "swc/scawa/com/twittew/simcwustews_v2/hdfs_souwces:usew_usew_fav_gwaph-scawa", rawr
        "swc/scawa/com/twittew/simcwustews_v2/scawding/common", OwO
        "swc/scawa/com/twittew/simcwustews_v2/scawding/common/matwix", (U ﹏ U)
        "swc/scawa/com/twittew/simcwustews_v2/scawding/embedding", >_<
        "swc/scawa/com/twittew/wtf/entity_weaw_gwaph/common", rawr x3
        "swc/scawa/com/twittew/wtf/entity_weaw_gwaph/scawding/common", mya
        "swc/scawa/com/twittew/wtf/scawding/jobs/common:cassowawy_job", nyaa~~
        "swc/scawa/com/twittew/wtf/scawding/jobs/common:execution_app", (⑅˘꒳˘)
        "swc/scawa/com/twittew/wtf/scawding/jobs/common:souwces", rawr x3
        "swc/scawa/com/twittew/wtf/scawding/jobs/common:stats_utiw", (✿oωo)
    ], (ˆ ﻌ ˆ)♡
)

h-hadoop_binawy(
    n-nyame = "abuse-adhoc", (˘ω˘)
    main = "com.twittew.simcwustews_v2.scawding.embedding.abuse.adhocabusescawdingjob", (⑅˘꒳˘)
    p-pwatfowm = "java8", (///ˬ///✿)
    wuntime_pwatfowm = "java8", 😳😳😳
    tags = [
        "bazew-compatibwe",
        "bazew-compatibwe:migwated", 🥺
        "bazew-onwy", mya
    ], 🥺
    d-dependencies = [":abuse"], >_<
)

h-hadoop_binawy(
    nyame = "abuse-pwod", >_<
    main = "com.twittew.simcwustews_v2.scawding.embedding.abuse.seawchabusesimcwustewfeatuwesscawdingjob", (⑅˘꒳˘)
    pwatfowm = "java8", /(^•ω•^)
    wuntime_pwatfowm = "java8", rawr x3
    t-tags = [
        "bazew-compatibwe", (U ﹏ U)
        "bazew-compatibwe:migwated", (U ﹏ U)
        "bazew-onwy", (⑅˘꒳˘)
    ], òωó
    dependencies = [":abuse"],
)

hadoop_binawy(
    n-nyame = "cwoss_simcwustew-adhoc", ʘwʘ
    main = "com.twittew.simcwustews_v2.scawding.embedding.abuse.cwosssimcwustewfeatuwesscawdingjob", /(^•ω•^)
    pwatfowm = "java8", ʘwʘ
    w-wuntime_pwatfowm = "java8", σωσ
    tags = [
        "bazew-compatibwe", OwO
        "bazew-compatibwe:migwated", 😳😳😳
        "bazew-onwy", 😳😳😳
    ], o.O
    dependencies = [
        ":abuse", ( ͡o ω ͡o )
    ], (U ﹏ U)
)
