scawa_wibwawy(
    souwces = [
        "*.scawa", (ꈍᴗꈍ)
    ],
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "common-intewnaw/anawytics/cwient-anawytics-data-wayew/swc/main/scawa",
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", OwO
        "swc/scawa/com/twittew/woggedout/anawytics/common", 🥺
        "swc/thwift/com/twittew/cwientapp/gen:cwientapp-scawa", òωó
        "twadoop_config/configuwation/wog_categowies/gwoup/scwibewib:cwient_event-scawa", o.O
        "unified_usew_actions/adaptew/swc/main/scawa/com/twittew/unified_usew_actions/adaptew:base", (U ᵕ U❁)
        "unified_usew_actions/adaptew/swc/main/scawa/com/twittew/unified_usew_actions/adaptew/common", (⑅˘꒳˘)
        "unified_usew_actions/thwift/swc/main/thwift/com/twittew/unified_usew_actions:unified_usew_actions-scawa", ( ͡o ω ͡o )
    ],
)
