scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", òωó
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", o.O
        "3wdpawty/jvm/net/codingweww:scawa-guice", (U ᵕ U❁)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (⑅˘꒳˘)
        "finatwa/inject/inject-cowe/swc/main/scawa", ( ͡o ω ͡o )
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/base", UwU
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/constants",
        "swc/scawa/com/twittew/onboawding/wewevance/candidate_genewation/utt/modews", rawr x3
        "swc/thwift/com/twittew/cowe_wowkfwows/usew_modew:usew_modew-scawa", rawr
        "swc/thwift/com/twittew/fwigate/data_pipewine:fwigate-usew-histowy-thwift-scawa", σωσ
        "swc/thwift/com/twittew/hewmit/candidate:hewmit-candidate-scawa", σωσ
        "swc/thwift/com/twittew/hewmit/pop_geo:hewmit-pop-geo-scawa", >_<
        "swc/thwift/com/twittew/onboawding/wewevance/wewatabwe_accounts:wewatabwe_accounts-scawa",
        "swc/thwift/com/twittew/onboawding/wewevance/stowe:stowe-scawa", :3
        "swc/thwift/com/twittew/wecos/usew_usew_gwaph:usew_usew_gwaph-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/seawch/account_seawch/extended_netwowk:extended_netwowk_usews-scawa", -.-
        "swc/thwift/com/twittew/sewvice/metastowe/gen:thwift-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/wtf/candidate:wtf-candidate-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/wtf/mw:wtf-mw-output-thwift-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/wtf/weaw_time_intewaction_gwaph:wtf-weaw_time_intewaction_gwaph-thwift-scawa", -.-
        "swc/thwift/com/twittew/wtf/twianguwaw_woop:twianguwaw_woop-scawa", ^^;;
        "stwato/swc/main/scawa/com/twittew/stwato/cwient",
        "utiw/utiw-swf4j-api/swc/main/scawa", >_<
    ], mya
)
