java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", òωó
        "3wdpawty/jvm/commons-io", o.O
        "3wdpawty/jvm/owg/apache/kafka:kafka-cwients", (U ᵕ U❁)
        "3wdpawty/jvm/owg/yamw:snakeyamw", (⑅˘꒳˘)
        "decidew/swc/main/scawa",
        "finagwe/finagwe-cowe/swc/main", ( ͡o ω ͡o )
        "finagwe/finagwe-exp/swc/main/scawa", UwU
        "finagwe/finagwe-thwiftmux/swc/main/scawa", rawr x3
        "finagwe/finagwe-zipkin-cowe/swc/main/scawa", rawr
        "finagwe/finagwe-zipkin-scwibe/swc/main/scawa", σωσ
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", σωσ
        "finatwa/inject/inject-app/swc/main/java/com/twittew/inject/annotations", >_<
        "finatwa/inject/inject-cowe/swc/main/scawa", :3
        "finatwa/inject/inject-moduwes/swc/main/scawa", (U ﹏ U)
        "finatwa/inject/inject-moduwes/swc/main/scawa/com/twittew/inject/moduwes", -.-
        "finatwa/inject/inject-thwift-cwient/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift", (⑅˘꒳˘)
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift:contwowwew", (U ᵕ U❁)
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/exceptions", -.-
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/fiwtews", ^^;;
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/moduwes", >_<
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/wesponse", mya
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/wouting", mya
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", 😳
        "swc/java/com/twittew/common/base", XD
        "swc/java/com/twittew/common/utiw:system-mocks", :3
        "swc/java/com/twittew/seawch/common/decidew", 😳😳😳
        "swc/java/com/twittew/seawch/common/metwics", -.-
        "swc/java/com/twittew/seawch/common/pawtitioning/base", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/utiw/io/kafka", rawr x3
        "swc/java/com/twittew/seawch/common/utiw/io/pewiodic", nyaa~~
        "swc/java/com/twittew/seawch/featuwe_update_sewvice/fiwtews", /(^•ω•^)
        "swc/java/com/twittew/seawch/featuwe_update_sewvice/stats", rawr
        "swc/java/com/twittew/seawch/featuwe_update_sewvice/whitewist",
        "swc/java/com/twittew/spam/finagwe", OwO
        "swc/thwift/com/twittew/seawch/common:indexing-java", (U ﹏ U)
        "swc/thwift/com/twittew/seawch/common:schema-java", >_<
        "swc/thwift/com/twittew/seawch/featuwe_update_sewvice/thwift:thwift-java", rawr x3
        "swc/thwift/com/twittew/tweetypie:sewvice-java", mya
        "swc/thwift/com/twittew/tweetypie:tweet-java", nyaa~~
        "utiw/utiw-cowe/swc/main/java", (⑅˘꒳˘)
    ],
)
