crelonatelon_thrift_librarielons(
    baselon_namelon = "thrift",
    sourcelons = ["**/*.thrift"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncy_roots = [
        "finatra-intelonrnal/thrift/src/main/thrift",
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift",
    ],
    gelonnelonratelon_languagelons = [
        "java",
        "scala",
    ],
    providelons_java_namelon = "simclustelonrs-ann-thrift-java",
    providelons_scala_namelon = "simclustelonrs-ann-thrift-scala",
)
