python3_wibwawy(
    nyame = "pawams_wib", rawr x3
    souwces = [
        "pawams.py", rawr
    ], σωσ
    t-tags = [
        "bazew-compatibwe", σωσ
        "no-mypy", >_<
    ],
    d-dependencies = [
        "3wdpawty/python/pydantic:defauwt", :3
    ], (U ﹏ U)
)

p-python3_wibwawy(
    n-nyame = "wayews_wib", -.-
    s-souwces = [
        "wayews.py", (ˆ ﻌ ˆ)♡
    ], (⑅˘꒳˘)
    tags = [
        "bazew-compatibwe", (U ᵕ U❁)
        "no-mypy", -.-
    ],
    d-dependencies = [
    ], ^^;;
)

p-python3_wibwawy(
    n-nyame = "modew_wib", >_<
    souwces = [
        "modew.py", mya
    ], mya
    tags = [
        "bazew-compatibwe", 😳
        "no-mypy", XD
    ], :3
    dependencies = [
        ":wayews_wib", 😳😳😳
        ":pawams_wib", -.-
        "3wdpawty/python/absw-py:defauwt", ( ͡o ω ͡o )
    ],
)
