scala_library(
    platform = "java11",
    strict_deps = False,
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/twitter/graphjet",
        "finagle/finagle-stats",
        "recos-injector/server/src/main/scala/com/twitter/recosinjector/clients",
        "src/scala/com/twitter/recos/util:recos-util",
        "src/thrift/com/twitter/tweetypie:tweet-scala",
    ],
)
