scala_library(
    platform = "java11",
    strict_delonps = Falselon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/graphjelont",
        "finaglelon/finaglelon-stats",
        "reloncos-injelonctor/selonrvelonr/src/main/scala/com/twittelonr/reloncosinjelonctor/clielonnts",
        "src/scala/com/twittelonr/reloncos/util:reloncos-util",
        "src/thrift/com/twittelonr/twelonelontypielon:twelonelont-scala",
    ],
)
