scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", (⑅˘꒳˘)
        "3wdpawty/jvm/javax/inject:javax.inject", ( ͡o ω ͡o )
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", UwU
        "configapi/configapi-cowe", rawr x3
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/config", rawr
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/modew", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam/decidew", >_<
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa", :3
        "decidew/swc/main/scawa", (U ﹏ U)
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", -.-
        "finatwa/inject/inject-cowe/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "fowwow-wecommendations-sewvice/thwift/swc/main/thwift:thwift-scawa", (⑅˘꒳˘)
        "fwigate/fwigate-common:base", (U ᵕ U❁)
        "fwigate/fwigate-common:utiw",
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/base", -.-
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/candidate", ^^;;
        "swc/scawa/com/twittew/simcwustews_v2/common", >_<
        "swc/thwift/com/twittew/cowe_wowkfwows/usew_modew:usew_modew-scawa", mya
        "swc/thwift/com/twittew/hewmit/stp:hewmit-stp-scawa", mya
        "swc/thwift/com/twittew/onboawding/wewevance/cowdstawt_wookawike:cowdstawtwookawike-thwift-scawa", 😳
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", XD
        "swc/thwift/com/twittew/wtf/candidate:wtf-candidate-scawa", :3
        "usew-signaw-sewvice/thwift/swc/main/thwift:thwift-scawa", 😳😳😳
    ],
)
