scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], (ꈍᴗꈍ)
    tags = [
        "bazew-compatibwe", ^•ﻌ•^
    ],
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", OwO
        "abdecidew/swc/main/scawa", 🥺
        "content-wecommendew/thwift/swc/main/thwift:thwift-scawa", òωó
        "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/stowe/common", o.O
        "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/stowe/gizmoduck", (U ᵕ U❁)
        "swc/scawa/com/twittew/topic_wecos/stowes", (⑅˘꒳˘)
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", UwU
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", rawr x3
        "stitch/stitch-stowehaus", rawr
        "topic-sociaw-pwoof/sewvew/swc/main/scawa/com/twittew/tsp/common",
        "topic-sociaw-pwoof/sewvew/swc/main/scawa/com/twittew/tsp/handwews", σωσ
        "topic-sociaw-pwoof/sewvew/swc/main/scawa/com/twittew/tsp/moduwes", σωσ
        "topic-sociaw-pwoof/sewvew/swc/main/scawa/com/twittew/tsp/stowes", >_<
        "topic-sociaw-pwoof/sewvew/swc/main/thwift:thwift-scawa", :3
    ],
)
