scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "configapi/configapi-cowe/swc/main/scawa/com/twittew/timewines/configapi", (⑅˘꒳˘)
        "sewvo/decidew", ( ͡o ω ͡o )
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/decidew", UwU
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/pawametews/utiw", rawr x3
    ],
)
