scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "sewvo/utiw", UwU
        "stitch/stitch-cowe", rawr x3
        "utiw/utiw-cowe:utiw-cowe-utiw", rawr
        "utiw/utiw-stats", σωσ
    ], σωσ
    e-expowts = [
        "sewvo/utiw", >_<
        "stitch/stitch-cowe", :3
        "utiw/utiw-cowe:utiw-cowe-utiw", (U ﹏ U)
        "utiw/utiw-stats", -.-
    ], (ˆ ﻌ ˆ)♡
)
