scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "selonrvo/util",
        "stitch/stitch-corelon",
        "util/util-corelon:util-corelon-util",
        "util/util-stats",
    ],
    elonxports = [
        "selonrvo/util",
        "stitch/stitch-corelon",
        "util/util-corelon:util-corelon-util",
        "util/util-stats",
    ],
)
