scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "finagwe/finagwe-cowe/swc/main", UwU
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe", rawr x3
        "sewvo/utiw", rawr
        "snowfwake:id", σωσ
        "stitch/stitch-cowe", σωσ
        "utiw/utiw-cowe:utiw-cowe-utiw", >_<
        "utiw/utiw-stats", :3
    ],
    e-expowts = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe", (U ﹏ U)
        "sewvo/utiw", -.-
        "snowfwake:id", (ˆ ﻌ ˆ)♡
        "stitch/stitch-cowe",
        "utiw/utiw-cowe:utiw-cowe-utiw", (⑅˘꒳˘)
        "utiw/utiw-stats", (U ᵕ U❁)
    ],
)
