scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finaglelon/finaglelon-corelon/src/main",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon/pipelonlinelon_failurelon",
        "selonrvo/util",
        "snowflakelon:id",
        "stitch/stitch-corelon",
        "util/util-corelon:util-corelon-util",
        "util/util-stats",
    ],
    elonxports = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon/pipelonlinelon_failurelon",
        "selonrvo/util",
        "snowflakelon:id",
        "stitch/stitch-corelon",
        "util/util-corelon:util-corelon-util",
        "util/util-stats",
    ],
)
