scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "configapi/configapi-corelon",
        "finaglelon/finaglelon-stats",
        "visibility/common/src/main/scala/com/twittelonr/visibility/common:modelonl_threlonsholds",
    ],
    elonxports = [
        "visibility/common/src/main/scala/com/twittelonr/visibility/common:modelonl_threlonsholds",
    ],
)
