packagelon com.twittelonr.visibility.configapi.params

privatelon[visibility] objelonct TimelonlinelonConvelonrsationsDownrankingSpeloncificParams {

  objelonct elonnablelonPSpammyTwelonelontDownrankConvosLowQualityParam elonxtelonnds RulelonParam(falselon)

  objelonct elonnablelonRitoActionelondTwelonelontDownrankConvosLowQualityParam elonxtelonnds RulelonParam(falselon)

  objelonct elonnablelonHighSpammyTwelonelontContelonntScorelonConvoDownrankAbusivelonQualityRulelonParam
      elonxtelonnds RulelonParam(falselon)

  objelonct elonnablelonHighCryptospamScorelonConvoDownrankAbusivelonQualityRulelonParam elonxtelonnds RulelonParam(falselon)
}
