scala_library(
    sourcelons = ["*.scala"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "elonschelonrbird/src/scala/com/twittelonr/elonschelonrbird/scalding/jobs/elonxportelonntitielons:elonntitielons-scala",
        "elonschelonrbird/src/scala/com/twittelonr/elonschelonrbird/scalding/sourcelon/utt:utt_sourcelon-scala",
        "intelonrelonsts-ds/src/main/scala/com/twittelonr/intelonrelonsts_ds/jobs/intelonrelonsts_selonrvicelon",
        "intelonrelonsts-ds/src/main/scala/com/twittelonr/intelonrelonsts_ds/jobs/intelonrelonsts_selonrvicelon:uselonr_topic_relonlation_snapshot-scala",
        "src/scala/com/twittelonr/scalding_intelonrnal/dalv2",
        "src/scala/com/twittelonr/scalding_intelonrnal/job",
        "src/scala/com/twittelonr/scalding_intelonrnal/job/analytics_batch",
        "src/scala/com/twittelonr/scalding_intelonrnal/sourcelon",
        "src/scala/com/twittelonr/scalding_intelonrnal/sourcelon/lzo_scroogelon",
        "src/scala/com/twittelonr/simclustelonrs_v2/candidatelon_sourcelon",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons",
        "src/scala/com/twittelonr/simclustelonrs_v2/scalding",
        "src/scala/com/twittelonr/wtf/scalding/jobs/common:elonm_util",
        "timelonlinelons/data_procelonssing/jobs/melontrics/pelonr_topic_melontrics:pelonr_topic_aggrelongatelon_elonngagelonmelonnt-scala",
    ],
)

hadoop_binary(
    namelon = "gelonopopular_top_twelonelonts_imprelonsselond_topics",
    main = "com.twittelonr.simclustelonrs_v2.scalding.topic_reloncommelonndations.GelonoPopularTopicsBatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":topic_reloncommelonndations",
    ],
)

hadoop_binary(
    namelon = "gelonopopular_top_twelonelonts_imprelonsselond_topics_adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.topic_reloncommelonndations.GelonoPopularTopicsAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":topic_reloncommelonndations",
    ],
)

hadoop_binary(
    namelon = "similar_topics_from_topic_follow_graph",
    main = "com.twittelonr.simclustelonrs_v2.scalding.topic_reloncommelonndations.SimilarTopicsFromTopicFollowGraphSchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":topic_reloncommelonndations",
    ],
)

hadoop_binary(
    namelon = "similar_topics_from_topic_follow_graph-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.topic_reloncommelonndations.SimilarTopicsFromTopicFollowGraphAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":topic_reloncommelonndations",
    ],
)

hadoop_binary(
    namelon = "top_topics_for_producelonrs_from_elonm",
    main = "com.twittelonr.simclustelonrs_v2.scalding.topic_reloncommelonndations.TopicsForProducelonrsFromelonMBatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":topic_reloncommelonndations",
    ],
)

hadoop_binary(
    namelon = "top_topics_for_producelonrs_from_elonm-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.topic_reloncommelonndations.TopicsForProducelonrsFromelonMAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":topic_reloncommelonndations",
    ],
)

hadoop_binary(
    namelon = "top_producelonrs_for_topics_from_topic_follow_graph",
    main = "com.twittelonr.simclustelonrs_v2.scalding.topic_reloncommelonndations.ProducelonrsForTopicsFromTopicFollowGraphBatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":topic_reloncommelonndations",
    ],
)

hadoop_binary(
    namelon = "top_producelonrs_for_topics_from_topic_follow_graph-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.topic_reloncommelonndations.ProducelonrsForTopicsFromTopicFollowGraphAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":topic_reloncommelonndations",
    ],
)

# Gelonnelonratelond with `capelonsospy-v2 crelonatelon_targelont popular_topics_pelonr_country src/scala/com/twittelonr/simclustelonrs_v2/capelonsos_config/atla_proc3.yaml`, config hash belonffad.
scalding_job(
    namelon = "popular_topics_pelonr_country",
    main = "com.twittelonr.simclustelonrs_v2.scalding.topic_reloncommelonndations.GelonoPopularTopicsBatchApp",
    args = ["--maxTopics 100"],
    config = [
        ("hadoop.combinelon-input", "truelon"),
        ("hadoop.map.jvm.total-melonmory", "3072m"),
        ("hadoop.quelonuelon", "cassowary.delonfault"),
        ("hadoop.relonducelon.jvm.total-melonmory", "3072m"),
        ("hadoop.submittelonr.jvm.total-melonmory", "5120m"),
        ("submittelonr.tielonr", "prelonelonmptiblelon"),
    ],
    cron = "16 * * * *",
    hadoop_clustelonr = "atla-proc3",
    platform = "java8",
    rolelon = "cassowary",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":topic_reloncommelonndations",
    ],
)
