java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/owg/swf4j:swf4j-api", o.O
        "3wdpawty/jvm/owg/tensowfwow", (U ᵕ U❁)
        "finatwa/inject/inject-swf4j/swc/main/scawa/com/twittew/inject", (⑅˘꒳˘)
        "swc/java/com/twittew/mw/api:api-base", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/fiwe", UwU
        "swc/java/com/twittew/seawch/common/schema", rawr x3
        "swc/java/com/twittew/seawch/common/schema/base",
        "swc/java/com/twittew/seawch/common/utiw/mw/modews_managew", rawr
        "swc/thwift/com/twittew/seawch/common:featuwes-java", σωσ
        "tensowfwow/tfcompute-java/swc/main/java/com/twittew/tfcompute_java", σωσ
        "twmw/wuntime/swc/main/scawa/com/twittew/twmw/wuntime/wib", >_<
        "twmw/wuntime/swc/main/scawa/com/twittew/twmw/wuntime/modews", :3
        "utiw/utiw-cowe:scawa", (U ﹏ U)
    ], -.-
)
