scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "stitch/stitch-storehaus",
        "strato/src/main/scala/com/X/strato/fed",
        "strato/src/main/scala/com/X/strato/fed/server",
        "user-signal-service/server/src/main/scala/com/X/usersignalservice/config",
        "user-signal-service/server/src/main/scala/com/X/usersignalservice/handler",
        "user-signal-service/server/src/main/scala/com/X/usersignalservice/module",
        "user-signal-service/thrift/src/main/thrift:thrift-scala",
    ],
)
