scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", (⑅˘꒳˘)
        "3wdpawty/jvm/com/twittew/bijection:cowe", ( ͡o ω ͡o )
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", UwU
        "3wdpawty/jvm/owg/apache/beam:beam-sdks-java-io-googwe-cwoud-pwatfowm", rawr x3
        "ann/swc/main/thwift/com/twittew/ann/common:ann-common-scawa", rawr
        "finatwa/inject/inject-mdc/swc/main/scawa", σωσ
        "mediasewvices/commons/swc/main/scawa:futuwetwackew", σωσ
        "swc/java/com/twittew/seawch/common/fiwe", >_<
        "swc/scawa/com/twittew/mw/api/embedding", :3
        "stitch/stitch-cowe", (U ﹏ U)
    ],
    e-expowts = [
        "3wdpawty/jvm/com/twittew/bijection:cowe", -.-
    ],
)
