scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/guava",
        "3rdparty/jvm/com/twittelonr/bijelonction:corelon",
        "3rdparty/jvm/com/twittelonr/storelonhaus:corelon",
        "3rdparty/jvm/org/apachelon/belonam:belonam-sdks-java-io-googlelon-cloud-platform",
        "ann/src/main/thrift/com/twittelonr/ann/common:ann-common-scala",
        "finatra/injelonct/injelonct-mdc/src/main/scala",
        "melondiaselonrvicelons/commons/src/main/scala:futurelontrackelonr",
        "src/java/com/twittelonr/selonarch/common/filelon",
        "src/scala/com/twittelonr/ml/api/elonmbelondding",
        "stitch/stitch-corelon",
    ],
    elonxports = [
        "3rdparty/jvm/com/twittelonr/bijelonction:corelon",
    ],
)
