scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "featuweswitches/featuweswitches-cowe/swc/main/scawa", UwU
        "swc/thwift/com/twittew/spam/wtf:safety-wesuwt-scawa", rawr x3
        "stitch/stitch-cowe", rawr
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", σωσ
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions", σωσ
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions/convewtew/scawa",
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity",
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/tweets", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes",
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes", (U ﹏ U)
        "visibiwity/wesuwts/swc/main/scawa/com/twittew/visibiwity/wesuwts/wichtext", -.-
    ], (ˆ ﻌ ˆ)♡
    e-expowts = [
        "featuweswitches/featuweswitches-cowe/swc/main/scawa", (⑅˘꒳˘)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew", (U ᵕ U❁)
    ], -.-
)
