scala_library(
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/X/storehaus:core",
        "hermit/hermit-core/src/main/scala/com/X/hermit/store/common",
        "src/scala/com/X/simclusters_v2/common",
        "src/scala/com/X/storehaus_internal/manhattan",
        "src/scala/com/X/storehaus_internal/util",
        "src/scala/com/X/wtf/scalding/jobs/injection",
        "src/thrift/com/X/recos/entities:entities-thrift-scala",
        "storage/clients/manhattan/client/src/main/scala",
    ],
)
