java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/guava",
        "3rdparty/jvm/commons-io",
        "3rdparty/jvm/org/json",
        "src/java/com/twittelonr/common/util:systelonm-mocks",
        "src/java/com/twittelonr/selonarch/common/dark",
        "src/java/com/twittelonr/selonarch/common/melontrics",
        "src/java/com/twittelonr/selonarch/common/util/io/pelonriodic",
        "src/java/com/twittelonr/selonarch/common/util/json",
    ],
)
