java_library(
    sources = ["*.java"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/guava",
        "3rdparty/jvm/commons-io",
        "3rdparty/jvm/org/json",
        "src/java/com/twitter/common/util:system-mocks",
        "src/java/com/twitter/search/common/dark",
        "src/java/com/twitter/search/common/metrics",
        "src/java/com/twitter/search/common/util/io/periodic",
        "src/java/com/twitter/search/common/util/json",
    ],
)
