scawa_wibwawy(
    nyame = "wabews", (U ᵕ U❁)
    souwces = ["*.scawa"], -.-
    c-compiwew_option_sets = ["fataw_wawnings"],
    p-pwatfowm = "java8", ^^;;
    t-tags = ["bazew-compatibwe"], >_<
    d-dependencies = [
        ":intewaction_gwaph_wabews_daiwy-scawa", mya
        "beam-intewnaw/swc/main/scawa/com/twittew/beam/io/daw", mya
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/job", 😳
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/wunnew/datafwow", XD
        "consumew-data-toows/swc/main/scawa/com/twittew/cde/scio/daw_wead", :3
        "sociawgwaph/hadoop/swc/main/scawa/com/twittew/sociawgwaph/hadoop:sociawgwaph-fowwow-events-scawa", 😳😳😳
        "swc/scawa/com/twittew/intewaction_gwaph/scio/agg_cwient_event_wogs:intewaction_gwaph_agg_cwient_event_wogs_edge_daiwy-scawa", -.-
        "swc/scawa/com/twittew/intewaction_gwaph/scio/agg_diwect_intewactions:intewaction_gwaph_agg_diwect_intewactions_edge_daiwy-scawa", ( ͡o ω ͡o )
        "swc/scawa/com/twittew/intewaction_gwaph/scio/agg_emaiw:intewaction_gwaph_extended_emaiw_edge_daiwy-scawa", rawr x3
        "swc/scawa/com/twittew/intewaction_gwaph/scio/agg_notifications:intewaction_gwaph_agg_notifications_edge_daiwy-scawa", nyaa~~
        "swc/scawa/com/twittew/intewaction_gwaph/scio/agg_wetweets:intewaction_gwaph_extended_wetweet_edge_daiwy-scawa", /(^•ω•^)
        "swc/scawa/com/twittew/intewaction_gwaph/scio/agg_shawes:intewaction_gwaph_extended_shawe_edge_daiwy-scawa", rawr
        "tcdc/bq_bwastew/swc/main/scawa/com/twittew/tcdc/bqbwastew/beam", OwO
    ],
)

j-jvm_binawy(
    n-nyame = "intewaction_gwaph_wabews", (U ﹏ U)
    m-main = "com.twittew.intewaction_gwaph.scio.mw.wabews.intewactiongwaphwabewsjob", >_<
    p-pwatfowm = "java8", rawr x3
    tags = ["bazew-compatibwe"], mya
    dependencies = [
        ":wabews", nyaa~~
    ], (⑅˘꒳˘)
)

cweate_datasets(
    base_name = "intewaction_gwaph_wabews_daiwy", rawr x3
    descwiption = "daiwy w-wabews", (✿oωo)
    java_schema = "com.twittew.intewaction_gwaph.thwiftjava.edgewabew", (ˆ ﻌ ˆ)♡
    pwatfowm = "java8", (˘ω˘)
    w-wowe = "cassowawy", (⑅˘꒳˘)
    scawa_schema = "com.twittew.intewaction_gwaph.thwiftscawa.edgewabew", (///ˬ///✿)
    s-segment_type = "pawtitioned", 😳😳😳
    tags = ["bazew-compatibwe"], 🥺
    java_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-java", mya
    ], 🥺
    scawa_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-scawa", >_<
    ], >_<
)
