scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Falselon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "appselonc/sanitization-lib/src/main/scala",
        "src/thrift/com/twittelonr/elonxpandodo:cards-scala",
        "stitch/stitch-corelon",
        "visibility/lib/src/main/relonsourcelons/config",
        "visibility/lib/src/main/scala/com/twittelonr/visibility",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/buildelonr/twelonelonts",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/buildelonr/uselonrs",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/felonaturelons",
    ],
)
