scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = f-fawse, (U ᵕ U❁)
    tags = ["bazew-compatibwe"],
    d-dependencies = [
        "appsec/sanitization-wib/swc/main/scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/expandodo:cawds-scawa", ( ͡o ω ͡o )
        "stitch/stitch-cowe", UwU
        "visibiwity/wib/swc/main/wesouwces/config", rawr x3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", rawr
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/tweets", σωσ
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/usews",
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", σωσ
    ],
)
