scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/wz4:wz4-java", ( ͡o ω ͡o )
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", UwU
        "configapi/configapi-cowe", rawr x3
        "content-wecommendew/thwift/swc/main/thwift:thwift-scawa", rawr
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/config", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/modew", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam", >_<
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa",
        "finatwa/inject/inject-cowe/swc/main/scawa", :3
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/utiw:stats_utiw", (U ﹏ U)
        "wewevance-pwatfowm/swc/main/scawa/com/twittew/wewevance_pwatfowm/common/stats", -.-
        "swc/java/com/twittew/seawch/common/schema/base", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/quewypawsew/quewy:cowe-quewy-nodes", (U ᵕ U❁)
        "swc/java/com/twittew/seawch/quewypawsew/quewy/seawch:seawch-quewy-nodes",
        "swc/scawa/com/twittew/simcwustews_v2/common", -.-
        "swc/thwift/com/twittew/cowe_wowkfwows/usew_modew:usew_modew-scawa", ^^;;
        "swc/thwift/com/twittew/seawch:eawwybiwd-scawa", >_<
        "swc/thwift/com/twittew/seawch/common:wanking-scawa", mya
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", mya
    ],
)
