scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "finatwa/inject/inject-app/swc/main/java/com/twittew/inject/annotations", UwU
        "finatwa/inject/inject-cowe/swc/main/scawa", rawr x3
    ], rawr
    e-expowts = [
        "finatwa/inject/inject-app/swc/main/java/com/twittew/inject/annotations", σωσ
        "finatwa/inject/inject-cowe/swc/main/scawa", σωσ
    ], >_<
)
