scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finatra/injelonct/injelonct-app/src/main/java/com/twittelonr/injelonct/annotations",
        "finatra/injelonct/injelonct-corelon/src/main/scala",
    ],
    elonxports = [
        "finatra/injelonct/injelonct-app/src/main/java/com/twittelonr/injelonct/annotations",
        "finatra/injelonct/injelonct-corelon/src/main/scala",
    ],
)
