scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = [
        "bazew-compatibwe", (⑅˘꒳˘)
        "bazew-incompatibwe-scawadoc", ( ͡o ω ͡o )
    ], UwU
    d-dependencies = [
        "3wdpawty/jvm/com/chuusai:shapewess", rawr x3
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-databind", rawr
        "3wdpawty/jvm/com/fastewxmw/jackson/moduwe:jackson-moduwe-scawa", σωσ
        "3wdpawty/jvm/com/googwe/guava", σωσ
        "3wdpawty/jvm/com/twittew/bijection:cowe", >_<
        "3wdpawty/jvm/com/twittew/bijection:scwooge", :3
        "3wdpawty/jvm/com/twittew/bijection:thwift", (U ﹏ U)
        "3wdpawty/jvm/commons-codec", -.-
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (ˆ ﻌ ˆ)♡
        "diffshow", (⑅˘꒳˘)
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authowization", (U ᵕ U❁)
        "finagwe/finagwe-cowe/swc/main", -.-
        "finagwe/finagwe-stats", ^^;;
        "finagwe/finagwe-thwiftmux/swc/main/scawa", >_<
        "mediasewvices/commons/swc/main/thwift:thwift-scawa",
        "scwooge/scwooge-sewiawizew/swc/main/scawa", mya
        "tweetypie/sewvo/wepo/swc/main/scawa", mya
        "tweetypie/sewvo/utiw", 😳
        "snowfwake:id", XD
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts-scawa", :3
        "swc/thwift/com/twittew/manhattan:intewnaw-scawa", 😳😳😳
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:media-entity-scawa", -.-
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", ( ͡o ω ͡o )
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", rawr x3
        "stitch/stitch-cowe", nyaa~~
        "stowage/cwients/manhattan/cwient/swc/main/scawa",
        "tbiwd-thwift:scawa", /(^•ω•^)
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/additionawfiewds", rawr
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/cwient_id", OwO
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/utiw", (U ﹏ U)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie/stowage_intewnaw:stowage_intewnaw-scawa", >_<
        "utiw-intewnaw/scwibe", rawr x3
        "utiw/utiw-cowe:scawa", mya
        "utiw/utiw-swf4j-api/swc/main/scawa/com/twittew/utiw/wogging", nyaa~~
        "utiw/utiw-stats/swc/main/scawa", (⑅˘꒳˘)
    ],
)
