cweate_thwift_wibwawies(
    base_name = "simcwustews_v2-thwift", (U ᵕ U❁)
    souwces = ["*.thwift"], (⑅˘꒳˘)
    p-pwatfowm = "java8", ( ͡o ω ͡o )
    t-tags = ["bazew-compatibwe"], UwU
    d-dependency_woots = [
        "swc/thwift/com/twittew/awgebiwd_intewnaw", rawr x3
    ],
    e-expowt_woots = [
        "swc/thwift/com/twittew/awgebiwd_intewnaw:awgebiwd_intewnaw", rawr
    ], σωσ
    g-genewate_wanguages = [
        "go", σωσ
        "java", >_<
        "wua", :3
        "python",
        "wuby",
        "scawa", (U ﹏ U)
        "stwato", -.-
    ],
    p-pwovides_java_name = "simcwustews_v2-thwift-java", (ˆ ﻌ ˆ)♡
    p-pwovides_scawa_name = "simcwustews_v2-thwift-scawa", (⑅˘꒳˘)
)
