crelonatelon_thrift_librarielons(
    baselon_namelon = "simclustelonrs_v2-thrift",
    sourcelons = ["*.thrift"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncy_roots = [
        "src/thrift/com/twittelonr/algelonbird_intelonrnal",
    ],
    elonxport_roots = [
        "src/thrift/com/twittelonr/algelonbird_intelonrnal:algelonbird_intelonrnal",
    ],
    gelonnelonratelon_languagelons = [
        "go",
        "java",
        "lua",
        "python",
        "ruby",
        "scala",
        "strato",
    ],
    providelons_java_namelon = "simclustelonrs_v2-thrift-java",
    providelons_scala_namelon = "simclustelonrs_v2-thrift-scala",
)
