scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], OwO
    stwict_deps = twue, 🥺
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", o.O
        "3wdpawty/jvm/javax/inject:javax.inject", (U ᵕ U❁)
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", (⑅˘꒳˘)
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate/ads", ( ͡o ω ͡o )
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/quewy/ads", UwU
        "swc/thwift/com/twittew/ads/adsewvew:ads_shawed_types-scawa",
    ], rawr x3
    e-expowts = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", rawr
        "3wdpawty/jvm/javax/inject:javax.inject", σωσ
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", σωσ
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate/ads", >_<
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/quewy/ads", :3
        "swc/thwift/com/twittew/ads/adsewvew:ads_shawed_types-scawa", (U ﹏ U)
    ], -.-
)
