scala_library(
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/storelonhaus:corelon",
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/candidatelon",
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/candidatelon/ads",
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/quelonry/ads",
        "src/thrift/com/twittelonr/ads/adselonrvelonr:ads_sharelond_typelons-scala",
    ],
    elonxports = [
        "3rdparty/jvm/com/twittelonr/storelonhaus:corelon",
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/candidatelon",
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/candidatelon/ads",
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/quelonry/ads",
        "src/thrift/com/twittelonr/ads/adselonrvelonr:ads_sharelond_typelons-scala",
    ],
)
