scala_library(
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "follow-recommendations-service/common/src/main/scala/com/X/follow_recommendations/common/base",
        "follow-recommendations-service/common/src/main/scala/com/X/follow_recommendations/common/clients/adserver",
        "follow-recommendations-service/common/src/main/scala/com/X/follow_recommendations/common/clients/socialgraph",
        "follow-recommendations-service/common/src/main/scala/com/X/follow_recommendations/common/models",
        "src/thrift/com/X/socialgraph:thrift-scala",
    ],
)
