scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "configapi/configapi-corelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon/product",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/product",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/product/relongistry",
        "stitch/stitch-corelon",
        "strato/config/src/thrift/com/twittelonr/strato/graphql:api-melondia-graphql-scala",
        "strato/config/src/thrift/com/twittelonr/strato/graphql:graphql-scala",
        "strato/config/src/thrift/com/twittelonr/strato/graphql:topics-graphql-scala",
        "util/util-corelon:scala",
    ],
    elonxports = [
        "strato/config/src/thrift/com/twittelonr/strato/graphql:graphql-scala",
    ],
)
