scawa_wibwawy(
    pwatfowm = "java8", (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "gwaph-featuwe-sewvice/swc/main/thwift/com/twittew/gwaph_featuwe_sewvice:gwaph_featuwe_sewvice_thwift-scawa", OwO
    ],
)
