scala_library(
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "graph-felonaturelon-selonrvicelon/src/main/thrift/com/twittelonr/graph_felonaturelon_selonrvicelon:graph_felonaturelon_selonrvicelon_thrift-scala",
    ],
)
