scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "finatra/inject/inject-thrift-client",
        "representation-manager/server/src/main/scala/com/twitter/representation_manager/columns/topic",
        "representation-manager/server/src/main/scala/com/twitter/representation_manager/columns/tweet",
        "representation-manager/server/src/main/scala/com/twitter/representation_manager/columns/user",
        "strato/src/main/scala/com/twitter/strato/fed",
        "strato/src/main/scala/com/twitter/strato/fed/server",
    ],
)
