scala_library(
    sourcelons = ["*.scala"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/fastelonrxml/jackson:jackson-modulelon-scala",
        "3rdparty/jvm/com/fastelonrxml/jackson/corelon:jackson-corelon",
        "3rdparty/jvm/com/fastelonrxml/jackson/corelon:jackson-databind",
        "3rdparty/jvm/com/fastelonrxml/jackson/modulelon:jackson-modulelon-scala",
        "src/scala/com/twittelonr/scalding_intelonrnal/job/analytics_batch",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
        "strato/src/main/scala/com/twittelonr/strato/scalding",
    ],
)
