scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/fastewxmw/jackson:jackson-moduwe-scawa", òωó
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-cowe", o.O
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-databind", (U ᵕ U❁)
        "3wdpawty/jvm/com/fastewxmw/jackson/moduwe:jackson-moduwe-scawa", (⑅˘꒳˘)
        "swc/scawa/com/twittew/scawding_intewnaw/job/anawytics_batch", ( ͡o ω ͡o )
        "swc/scawa/com/twittew/simcwustews_v2/common", UwU
        "stwato/swc/main/scawa/com/twittew/stwato/scawding", rawr x3
    ],
)
