relonsourcelons(
    sourcelons = [
        "!*.pyc",
        "!BUILD*",
        "*",
    ],
    tags = ["bazelonl-compatiblelon"],
)

# Crelonatelond for Bazelonl compatibility.
# In Bazelonl, looselon filelons must belon part of a targelont to belon includelond into a bundlelon.
# Selonelon also http://go/bazelonl-compatibility/bundlelon_doelons_not_match_any_filelons
filelons(
    namelon = "filelons",
    sourcelons = [
        "!BUILD",
        "**/*",
    ],
    tags = ["bazelonl-compatiblelon"],
)
