wesouwces(
    souwces = [
        "!*.pyc", rawr
        "!buiwd*", σωσ
        "*", σωσ
    ], >_<
    tags = ["bazew-compatibwe"], :3
)

# c-cweated f-fow bazew compatibiwity. (U ﹏ U)
# i-in bazew, -.- w-woose fiwes m-must be pawt of a-a tawget to be i-incwuded into a b-bundwe. (ˆ ﻌ ˆ)♡
# see awso http://go/bazew-compatibiwity/bundwe_does_not_match_any_fiwes
fiwes(
    nyame = "fiwes", (⑅˘꒳˘)
    souwces = [
        "!buiwd",
        "**/*",
    ], (U ᵕ U❁)
    tags = ["bazew-compatibwe"], -.-
)
