scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = [
        "bazew-compatibwe", (⑅˘꒳˘)
        "bazew-incompatibwe-scawadoc", ( ͡o ω ͡o )  # s-see http://go/bazew-incompatibwe-scawadoc
    ], UwU
    d-dependencies = [
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-databind", rawr x3
        "3wdpawty/jvm/com/fastewxmw/jackson/moduwe:jackson-moduwe-scawa", rawr
        "3wdpawty/jvm/com/twittew/bijection:cowe", σωσ
        "3wdpawty/jvm/com/twittew/bijection:thwift", σωσ
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", >_<
        "diffshow", :3
        "fanoutsewvice/thwift/swc/main/thwift:thwift-scawa", (U ﹏ U)
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", -.-
        "finagwe/finagwe-cowe/swc/main", (ˆ ﻌ ˆ)♡
        "fwock-cwient/swc/main/scawa", (⑅˘꒳˘)
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", (U ᵕ U❁)
        "scwooge/scwooge-cowe", -.-
        "tweetypie/sewvo/wepo", ^^;;
        "tweetypie/sewvo/wepo/swc/main/thwift:thwift-scawa", >_<
        "tweetypie/sewvo/utiw", mya
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", mya
        "swc/scawa/com/twittew/takedown/utiw", 😳
        "swc/thwift/com/twittew/context:featuwe-context-scawa", XD
        "swc/thwift/com/twittew/context:twittew-context-scawa", :3
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts-scawa", 😳😳😳
        "swc/thwift/com/twittew/expandodo:cawds-scawa", -.-
        "swc/thwift/com/twittew/geoduck:geoduck-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", rawr x3
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa",
        "swc/thwift/com/twittew/guano:guano-scawa", nyaa~~
        "swc/thwift/com/twittew/timewinesewvice/sewvew/intewnaw:thwift-scawa", /(^•ω•^)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:audit-scawa", rawr
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:events-scawa", OwO
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:media-entity-scawa", (U ﹏ U)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", >_<
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", rawr x3
        "stitch/stitch-cowe", mya
        "stitch/stitch-cowe/swc/main/scawa/com/twittew/stitch", nyaa~~
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", (⑅˘꒳˘)
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/backends", rawr x3
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/cowe", (✿oωo)
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/media",
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/wepositowy", (ˆ ﻌ ˆ)♡
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/sewvewutiw", (˘ω˘)
        "tweetypie/sewvew/swc/main/thwift:compiwed-scawa", (⑅˘꒳˘)
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/additionawfiewds",
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/cwient_id", (///ˬ///✿)
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/media", 😳😳😳
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/stowage", 🥺
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/tfwock", mya
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/utiw",
        "twittew-context", 🥺
        "utiw/utiw-swf4j-api/swc/main/scawa/com/twittew/utiw/wogging", >_<
        "utiw/utiw-stats/swc/main/scawa", >_<
    ], (⑅˘꒳˘)
)
