jvm_binawy(
    name = "uua-tws-favs-bin", (˘ω˘)
    basename = "uua-tws-favs-bin", ʘwʘ
    main = "com.twittew.unified_usew_actions.sewvice.twsfavssewvicemain", ( ͡o ω ͡o )
    w-wuntime_pwatfowm = "java11", o.O
    t-tags = ["bazew-compatibwe"], >w<
    d-dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", 😳
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", 🥺
        "twittew-sewvew-intewnaw/swc/main/scawa", rawr x3
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", o.O
        "unified_usew_actions/sewvice/swc/main/wesouwces", rawr
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:tws-favs", ʘwʘ
    ],
)

j-jvm_app(
    n-nyame = "uua-tws-favs", 😳😳😳
    a-awchive = "zip", ^^;;
    b-binawy = ":uua-tws-favs-bin", o.O
    b-bundwes = [
        bundwe(
            fiweset = ["**/*"], (///ˬ///✿)
            owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", σωσ
            wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", nyaa~~
        ), ^^;;
    ],
    t-tags = ["bazew-compatibwe"], ^•ﻌ•^
)

jvm_binawy(
    nyame = "uua-cwient-event-bin", σωσ
    b-basename = "uua-cwient-event-bin", -.-
    main = "com.twittew.unified_usew_actions.sewvice.cwienteventsewvicemain", ^^;;
    w-wuntime_pwatfowm = "java11", XD
    tags = ["bazew-compatibwe"], 🥺
    dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", òωó
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", (ˆ ﻌ ˆ)♡
        "twittew-sewvew-intewnaw/swc/main/scawa", -.-
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", :3
        "unified_usew_actions/sewvice/swc/main/wesouwces", ʘwʘ
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:cwient-event", 🥺
    ],
)

jvm_app(
    n-nyame = "uua-cwient-event", >_<
    awchive = "zip", ʘwʘ
    b-binawy = ":uua-cwient-event-bin", (˘ω˘)
    b-bundwes = [
        bundwe(
            fiweset = ["**/*"], (✿oωo)
            owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes",
            wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", (///ˬ///✿)
        ), rawr x3
    ],
    t-tags = ["bazew-compatibwe"], -.-
)


jvm_binawy(
    nyame = "uua-tweetypie-event-bin", ^^
    basename = "uua-tweetypie-event-bin",
    main = "com.twittew.unified_usew_actions.sewvice.tweetypieeventsewvicemain", (⑅˘꒳˘)
    w-wuntime_pwatfowm = "java11", nyaa~~
    tags = ["bazew-compatibwe"], /(^•ω•^)
    d-dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", (U ﹏ U)
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", 😳😳😳
        "twittew-sewvew-intewnaw/swc/main/scawa", >w<
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", XD
        "unified_usew_actions/sewvice/swc/main/wesouwces", o.O
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:tweetypie-event", mya
    ],
)

jvm_app(
    n-nyame = "uua-tweetypie-event", 🥺
    awchive = "zip", ^^;;
    b-binawy = ":uua-tweetypie-event-bin", :3
    b-bundwes = [
        bundwe(
            fiweset = ["**/*"], (U ﹏ U)
            o-owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", OwO
            wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", 😳😳😳
        ),
    ], (ˆ ﻌ ˆ)♡
    tags = ["bazew-compatibwe"], XD
)

j-jvm_binawy(
    nyame = "uua-sociaw-gwaph-bin", (ˆ ﻌ ˆ)♡
    basename = "uua-sociaw-gwaph-bin", ( ͡o ω ͡o )
    main = "com.twittew.unified_usew_actions.sewvice.sociawgwaphsewvicemain", rawr x3
    wuntime_pwatfowm = "java11",
    tags = ["bazew-compatibwe"], nyaa~~
    d-dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", >_<
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", ^^;;
        "twittew-sewvew-intewnaw/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", ^^;;
        "unified_usew_actions/sewvice/swc/main/wesouwces", (⑅˘꒳˘)
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:sociaw-gwaph-event", rawr x3
    ],
)

jvm_app(
    nyame = "uua-sociaw-gwaph", (///ˬ///✿)
    awchive = "zip", 🥺
    b-binawy = ":uua-sociaw-gwaph-bin", >_<
    b-bundwes = [
        b-bundwe(
            fiweset = ["**/*"], UwU
            owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", >_<
            wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", -.-
        ), mya
    ],
    t-tags = ["bazew-compatibwe"], >w<
)

j-jvm_binawy(
    nyame = "uua-emaiw-notification-event-bin", (U ﹏ U)
    b-basename = "uua-emaiw-notification-event-bin", 😳😳😳
    m-main = "com.twittew.unified_usew_actions.sewvice.emaiwnotificationeventsewvicemain", o.O
    wuntime_pwatfowm = "java11",
    t-tags = ["bazew-compatibwe"], òωó
    dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", 😳😳😳
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", σωσ
        "twittew-sewvew-intewnaw/swc/main/scawa", (⑅˘꒳˘)
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", (///ˬ///✿)
        "unified_usew_actions/sewvice/swc/main/wesouwces", 🥺
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:emaiw-notification-event", OwO
    ], >w<
)

j-jvm_app(
    nyame = "uua-emaiw-notification-event", 🥺
    awchive = "zip", nyaa~~
    b-binawy = ":uua-emaiw-notification-event-bin", ^^
    bundwes = [
        b-bundwe(
            fiweset = ["**/*"], >w<
            o-owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", OwO
            w-wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", XD
        ), ^^;;
    ],
    tags = ["bazew-compatibwe"], 🥺
)

jvm_binawy(
    nyame = "uua-usew-modification-bin", XD
    basename = "uua-usew-modification-bin", (U ᵕ U❁)
    main = "com.twittew.unified_usew_actions.sewvice.usewmodificationsewvicemain", :3
    wuntime_pwatfowm = "java11", ( ͡o ω ͡o )
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", σωσ
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", (U ᵕ U❁)
        "twittew-sewvew-intewnaw/swc/main/scawa", (✿oωo)
        "twittew-sewvew/wogback-cwassic/swc/main/scawa",
        "unified_usew_actions/sewvice/swc/main/wesouwces", ^^
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:usew-modification-event", ^•ﻌ•^
    ],
)

jvm_app(
    nyame = "uua-usew-modification", XD
    a-awchive = "zip", :3
    b-binawy = ":uua-usew-modification-bin", (ꈍᴗꈍ)
    b-bundwes = [
        bundwe(
            fiweset = ["**/*"], :3
            owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", (U ﹏ U)
            w-wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", UwU
        ),
    ], 😳😳😳
    tags = ["bazew-compatibwe"], XD
)

jvm_binawy(
    nyame = "uua-ads-cawwback-engagements-bin", o.O
    basename = "uua-ads-cawwback-engagements-bin", (⑅˘꒳˘)
    m-main = "com.twittew.unified_usew_actions.sewvice.adscawwbackengagementssewvicemain", 😳😳😳
    wuntime_pwatfowm = "java11", nyaa~~
    t-tags = ["bazew-compatibwe"], rawr
    d-dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", -.-
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", (✿oωo)
        "twittew-sewvew-intewnaw/swc/main/scawa", /(^•ω•^)
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", 🥺
        "unified_usew_actions/sewvice/swc/main/wesouwces", ʘwʘ
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:ads-cawwback-engagements", UwU
    ],
)

j-jvm_app(
    nyame = "uua-ads-cawwback-engagements", XD
    awchive = "zip", (✿oωo)
    binawy = ":uua-ads-cawwback-engagements-bin", :3
    b-bundwes = [
        b-bundwe(
            f-fiweset = ["**/*"], (///ˬ///✿)
            o-owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", nyaa~~
            wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces",
        ), >w<
    ], -.-
    tags = ["bazew-compatibwe"], (✿oωo)
)

j-jvm_binawy(
    n-nyame = "uua-favowite-awchivaw-events-bin", (˘ω˘)
    b-basename = "uua-favowite-awchivaw-events-bin", rawr
    m-main = "com.twittew.unified_usew_actions.sewvice.favowiteawchivaweventssewvicemain", OwO
    w-wuntime_pwatfowm = "java11", ^•ﻌ•^
    tags = ["bazew-compatibwe"], UwU
    dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", (˘ω˘)
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", (///ˬ///✿)
        "twittew-sewvew-intewnaw/swc/main/scawa", σωσ
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", /(^•ω•^)
        "unified_usew_actions/sewvice/swc/main/wesouwces", 😳
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:favowite-awchivaw-events", 😳
    ],
)

jvm_app(
    nyame = "uua-favowite-awchivaw-events", (⑅˘꒳˘)
    awchive = "zip", 😳😳😳
    b-binawy = ":uua-favowite-awchivaw-events-bin", 😳
    bundwes = [
        bundwe(
            fiweset = ["**/*"], XD
            owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes",
            wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", mya
        ), ^•ﻌ•^
    ],
    tags = ["bazew-compatibwe"], ʘwʘ
)

j-jvm_binawy(
    nyame = "uua-wetweet-awchivaw-events-bin", ( ͡o ω ͡o )
    basename = "uua-wetweet-awchivaw-events-bin", mya
    main = "com.twittew.unified_usew_actions.sewvice.wetweetawchivaweventssewvicemain", o.O
    wuntime_pwatfowm = "java11", (✿oωo)
    t-tags = ["bazew-compatibwe"], :3
    d-dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", 😳
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", (U ﹏ U)
        "twittew-sewvew-intewnaw/swc/main/scawa", mya
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", (U ᵕ U❁)
        "unified_usew_actions/sewvice/swc/main/wesouwces", :3
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:wetweet-awchivaw-events", mya
    ],
)

j-jvm_app(
    nyame = "uua-wetweet-awchivaw-events", OwO
    a-awchive = "zip", (ˆ ﻌ ˆ)♡
    binawy = ":uua-wetweet-awchivaw-events-bin", ʘwʘ
    b-bundwes = [
        b-bundwe(
            fiweset = ["**/*"], o.O
            owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", UwU
            wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces",
        ), rawr x3
    ], 🥺
    tags = ["bazew-compatibwe"], :3
)

jvm_binawy(
    nyame = "wekey-uua-bin", (ꈍᴗꈍ)
    basename = "wekey-uua-bin", 🥺
    m-main = "com.twittew.unified_usew_actions.sewvice.wekeyuuasewvicemain", (✿oωo)
    wuntime_pwatfowm = "java11", (U ﹏ U)
    t-tags = ["bazew-compatibwe"],
    dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", :3
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", ^^;;
        "twittew-sewvew-intewnaw/swc/main/scawa", rawr
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", 😳😳😳
        "unified_usew_actions/sewvice/swc/main/wesouwces",
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:wekey-uua", (✿oωo)
    ], OwO
)

j-jvm_app(
    nyame = "wekey-uua", ʘwʘ
    a-awchive = "zip", (ˆ ﻌ ˆ)♡
    binawy = ":wekey-uua-bin", (U ﹏ U)
    bundwes = [
        b-bundwe(
            f-fiweset = ["**/*"], UwU
            owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", XD
            w-wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", ʘwʘ
        ),
    ], rawr x3
    t-tags = ["bazew-compatibwe"], ^^;;
)

jvm_binawy(
    nyame = "wekey-uua-iesouwce-bin", ʘwʘ
    basename = "wekey-uua-iesouwce-bin", (U ﹏ U)
    main = "com.twittew.unified_usew_actions.sewvice.wekeyuuaiesouwcesewvicemain", (˘ω˘)
    wuntime_pwatfowm = "java11", (ꈍᴗꈍ)
    t-tags = ["bazew-compatibwe"], /(^•ω•^)
    d-dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", >_<
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", σωσ
        "twittew-sewvew-intewnaw/swc/main/scawa", ^^;;
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", 😳
        "unified_usew_actions/sewvice/swc/main/wesouwces", >_<
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:wekey-uua-iesouwce", -.-
    ],
)

j-jvm_app(
    nyame = "wekey-uua-iesouwce", UwU
    a-awchive = "zip",
    b-binawy = ":wekey-uua-iesouwce-bin", :3
    bundwes = [
        b-bundwe(
            fiweset = ["**/*"], σωσ
            owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", >w<
            wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", (ˆ ﻌ ˆ)♡
        ), ʘwʘ
    ],
    tags = ["bazew-compatibwe"], :3
)

j-jvm_binawy(
    n-nyame = "uua-enwichment-pwannew-bin", (˘ω˘)
    basename = "uua-enwichment-pwannew-bin", 😳😳😳
    main = "com.twittew.unified_usew_actions.sewvice.enwichmentpwannewsewvicemain", rawr x3
    w-wuntime_pwatfowm = "java11", (✿oωo)
    t-tags = ["bazew-compatibwe"], (ˆ ﻌ ˆ)♡
    dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", :3
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", (U ᵕ U❁)
        "twittew-sewvew-intewnaw/swc/main/scawa", ^^;;
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", mya
        "unified_usew_actions/sewvice/swc/main/wesouwces", 😳😳😳
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:enwichment-pwannew", OwO
    ],
)

jvm_app(
    nyame = "uua-enwichment-pwannew", rawr
    a-awchive = "zip", XD
    binawy = ":uua-enwichment-pwannew-bin", (U ﹏ U)
    bundwes = [
        bundwe(
            fiweset = ["**/*"], (˘ω˘)
            o-owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", UwU
            wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", >_<
        ),
    ], σωσ
    tags = ["bazew-compatibwe"], 🥺
)

j-jvm_binawy(
    n-nyame = "uua-enwichew-bin", 🥺
    basename = "uua-enwichew-bin", ʘwʘ
    main = "com.twittew.unified_usew_actions.sewvice.enwichewsewvicemain", :3
    wuntime_pwatfowm = "java11", (U ﹏ U)
    t-tags = ["bazew-compatibwe"], (U ﹏ U)
    d-dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", ʘwʘ
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", >w<
        "twittew-sewvew-intewnaw/swc/main/scawa", rawr x3
        "twittew-sewvew/wogback-cwassic/swc/main/scawa", OwO
        "unified_usew_actions/sewvice/swc/main/wesouwces", ^•ﻌ•^
        "unified_usew_actions/sewvice/swc/main/scawa/com/twittew/unified_usew_actions/sewvice:enwichew", >_<
    ],
)

jvm_app(
    nyame = "uua-enwichew", OwO
    awchive = "zip", >_<
    binawy = ":uua-enwichew-bin", (ꈍᴗꈍ)
    bundwes = [
        b-bundwe(
            fiweset = ["**/*"], >w<
            o-owning_tawget = "unified_usew_actions/sewvice/swc/main/wesouwces:fiwes", (U ﹏ U)
            wew_path = "unified_usew_actions/sewvice/swc/main/wesouwces", ^^
        ), (U ﹏ U)
    ],
    tags = ["bazew-compatibwe"], :3
)
