scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "finagwe/finagwe-cowe/swc/main", ( ͡o ω ͡o )
        "finagwe/finagwe-thwiftmux/swc/main/scawa", UwU
        "finatwa-intewnaw/mtws-http/swc/main/scawa",
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", rawr x3
        "utiw/utiw-cowe", rawr
    ],
    e-expowts = [
        "finagwe/finagwe-cowe/swc/main", σωσ
        "finagwe/finagwe-thwiftmux/swc/main/scawa", σωσ
        "finatwa-intewnaw/mtws-http/swc/main/scawa", >_<
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", :3
        "utiw/utiw-cowe", (U ﹏ U)
    ],
)
