scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finaglelon/finaglelon-corelon/src/main",
        "finaglelon/finaglelon-thriftmux/src/main/scala",
        "finatra-intelonrnal/mtls-http/src/main/scala",
        "finatra-intelonrnal/mtls-thriftmux/src/main/scala",
        "util/util-corelon",
    ],
    elonxports = [
        "finaglelon/finaglelon-corelon/src/main",
        "finaglelon/finaglelon-thriftmux/src/main/scala",
        "finatra-intelonrnal/mtls-http/src/main/scala",
        "finatra-intelonrnal/mtls-thriftmux/src/main/scala",
        "util/util-corelon",
    ],
)
