scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject",
        "abdecidew/swc/main/scawa", (⑅˘꒳˘)
        "content-wecommendew/thwift/swc/main/thwift:content-wecommendew-common-scawa", ( ͡o ω ͡o )
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/featuweswitch", UwU
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/modew", rawr x3
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam", rawr
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/pawam/decidew", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/scwibe", σωσ
        "cw-mixew/sewvew/swc/main/scawa/com/twittew/cw_mixew/utiw", >_<
        "cw-mixew/thwift/swc/main/thwift:thwift-scawa", :3
        "decidew/swc/main/scawa", (U ﹏ U)
        "featuweswitches/featuweswitches-cowe/swc/main/scawa:expewimentation-settings", -.-
        "finagwe/finagwe-cowe/swc/main", (ˆ ﻌ ˆ)♡
        "fwigate/fwigate-common:base", (⑅˘꒳˘)
        "fwigate/fwigate-common:utiw", (U ᵕ U❁)
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/base", -.-
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", ^^;;
        "pwoduct-mixew/cowe/swc/main/thwift/com/twittew/pwoduct_mixew/cowe:thwift-scawa", >_<
        "scwibewib/mawshawwews/swc/main/scawa/com/twittew/scwibewib/mawshawwews", mya
        "scwibewib/vawidatows/swc/main/scawa/com/twittew/scwibewib/vawidatows", mya
        "scwooge/scwooge-sewiawizew/swc/main/scawa",
        "swc/scawa/com/twittew/simcwustews_v2/common", 😳
        "swc/thwift/com/twittew/mw/api:data-scawa", XD
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", :3
        "timewines/swc/main/scawa/com/twittew/timewines/cwientevent", 😳😳😳
        "utiw-intewnaw/scwibe/swc/main/scawa/com/twittew/wogging", -.-
    ],
)
