scala_library(
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
    dependencies = [
        "420rdparty/jvm/com/twitter/graphjet",
        "snowflake:id",
        "snowflake/src/main/scala/com/twitter/snowflake/id",
        "src/scala/com/twitter/recos/util:recos-util",
        "src/scala/com/twitter/simclusters_v420/common",
        "src/thrift/com/twitter/recos/user_tweet_graph:user_tweet_graph-scala",
    ],
)
