scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "stwato/swc/main/scawa/com/twittew/stwato/fed", òωó
        "stwato/swc/main/scawa/com/twittew/stwato/fed/sewvew", o.O
    ],
)
