scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    scalac_plugins = ["no-roomba"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "ads-injelonction/lib/src/main/scala/com/twittelonr/goldfinch/modelonl",
        "ads-injelonction/lib/src/main/scala/com/twittelonr/goldfinch/modelonl/promotelond",
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/candidatelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/common",
        "src/thrift/com/twittelonr/ads/adselonrvelonr:adselonrvelonr_common-scala",
    ],
    elonxports = [
        "ads-injelonction/lib/src/main/scala/com/twittelonr/goldfinch/modelonl",
        "ads-injelonction/lib/src/main/scala/com/twittelonr/goldfinch/modelonl/promotelond",
        "product-mixelonr/componelonnt-library/src/main/scala/com/twittelonr/product_mixelonr/componelonnt_library/modelonl/candidatelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/common",
        "src/thrift/com/twittelonr/ads/adselonrvelonr:adselonrvelonr_common-scala",
    ],
)
