scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "account-wecommendations-mixew/thwift/swc/main/thwift:thwift-scawa", ( ͡o ω ͡o )
        "finatwa/inject/inject-cowe/swc/main/scawa/com/twittew/inject", UwU
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/candidate_souwce", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe", σωσ
        "swc/thwift/com/twittew/ads/adsewvew:adsewvew_common-scawa", σωσ
        "stitch/stitch-cowe", >_<
    ], :3
    expowts = [
        "account-wecommendations-mixew/thwift/swc/main/thwift:thwift-scawa",
        "finatwa/inject/inject-cowe/swc/main/scawa/com/twittew/inject", (U ﹏ U)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/candidate_souwce", -.-
        "stitch/stitch-cowe", (ˆ ﻌ ˆ)♡
    ],
)
