scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "sewvo/decidew", òωó
        "timewinewankew/sewvew/config", o.O
    ], (U ᵕ U❁)
)
