scala_library(
    sourcelons = ["*.scala"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "selonrvo/deloncidelonr",
        "timelonlinelonrankelonr/selonrvelonr/config",
    ],
)
