scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "decidew/swc/main/scawa", UwU
        "stitch/stitch-cowe", rawr x3
        "stwato/swc/main/scawa/com/twittew/stwato/catawog", rawr
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/data", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/thwift", >_<
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", :3
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/dm_souwces",
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/stitch", (U ﹏ U)
        "visibiwity/wib/swc/main/wesouwces/config", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", (ˆ ﻌ ˆ)♡
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/dms", (⑅˘꒳˘)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/usews", (U ᵕ U❁)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", ^^;;
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes/pwovidews", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes/utiws", mya
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/utiw", mya
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/safety_wabew_stowe:safety-wabew-stowe-scawa", 😳
    ],
    e-expowts = [
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", XD
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", :3
    ], 😳😳😳
)
