scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", òωó
        "configapi/configapi-cowe", o.O
        "configapi/configapi-decidew", (U ᵕ U❁)
        "configapi/configapi-featuweswitches:v2", (⑅˘꒳˘)
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/configapi/decidews", ( ͡o ω ͡o )
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/modews", UwU
    ], rawr x3
)
