scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/bijection:cowe", ( ͡o ω ͡o )
        "featuweswitches/featuweswitches-cowe/swc/main/scawa", UwU
        "scwooge/scwooge-sewiawizew/swc/main/scawa", rawr x3
        "tweetypie/sewvo/wepo", rawr
        "tweetypie/sewvo/utiw", σωσ
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", σωσ
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", >_<
        "stitch/stitch-cowe", :3
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie",
        "tweetypie/sewvew/swc/main/thwift:compiwed-scawa", (U ﹏ U)
    ], -.-
)
