scawa_wibwawy(
    souwces = ["**/*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    stwict_deps = t-twue, òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/owg/apache/kafka:kafka-cwients", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (⑅˘꒳˘)
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/java", ( ͡o ω ͡o )
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", UwU
        "kafka/wibs/swc/main/scawa/com/twittew/kafka/cwient/headews", rawr x3
        "kafka/wibs/swc/main/scawa/com/twittew/kafka/cwient/pwocessow", rawr
        "scwooge/scwooge-cowe/swc/main/scawa", σωσ
        "scwooge/scwooge-sewiawizew/swc/main/scawa", σωσ
        "utiw/utiw-app/swc/main/scawa", >_<
        "utiw/utiw-cowe:utiw-cowe-utiw", :3
        "utiw/utiw-cowe/swc/main/scawa/com/twittew/convewsions", (U ﹏ U)
        "utiw/utiw-swf4j-api/swc/main/scawa/com/twittew/utiw/wogging", -.-
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats",
        "utiw/utiw-thwift", (ˆ ﻌ ˆ)♡
    ], (⑅˘꒳˘)
)
