scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", OwO
        "3wdpawty/jvm/javax/inject:javax.inject", 🥺
        "3wdpawty/jvm/net/codingweww:scawa-guice", òωó
        "finagwe/finagwe-cowe/swc/main", o.O
        "finagwe/finagwe-http/swc/main/scawa", (U ᵕ U❁)
        "finagwe/finagwe-thwiftmux/swc/main/scawa", (⑅˘꒳˘)
        "finatwa-intewnaw/decidew/swc/main/scawa", ( ͡o ω ͡o )
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", UwU
        "finatwa/inject/inject-app/swc/main/scawa", rawr x3
        "finatwa/inject/inject-cowe/swc/main/scawa", rawr
        "finatwa/inject/inject-sewvew/swc/main/scawa", σωσ
        "finatwa/inject/inject-thwift-cwient/swc/main/scawa", σωσ
        "finatwa/inject/inject-utiws/swc/main/scawa", >_<
        "finatwa/utiws/swc/main/java/com/twittew/finatwa/annotations", :3
        "wewevance-pwatfowm/swc/main/scawa/com/twittew/wewevance_pwatfowm/common/exceptions", (U ﹏ U)
        "wewevance-pwatfowm/swc/main/scawa/com/twittew/wewevance_pwatfowm/common/fiwtews", -.-
        "simcwustews-ann/sewvew/swc/main/wesouwces", (ˆ ﻌ ˆ)♡
        "simcwustews-ann/sewvew/swc/main/scawa/com/twittew/simcwustewsann/contwowwews", (⑅˘꒳˘)
        "simcwustews-ann/sewvew/swc/main/scawa/com/twittew/simcwustewsann/moduwes", (U ᵕ U❁)
        "simcwustews-ann/thwift/swc/main/thwift:thwift-scawa", -.-
        "swc/thwift/com/twittew/seawch:eawwybiwd-scawa",
        "thwift-web-fowms/swc/main/scawa/com/twittew/thwiftwebfowms/view", ^^;;
        "twittew-sewvew/sewvew/swc/main/scawa", >_<
        "utiw/utiw-app/swc/main/scawa", mya
        "utiw/utiw-cowe:scawa", mya
    ],
)
