scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "finagwe/finagwe-http/swc/main/scawa", ( ͡o ω ͡o )
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", UwU
        "finatwa/http-cwient/swc/main/scawa", rawr x3
        "finatwa/inject/inject-app/swc/main/java/com/twittew/inject/annotations", rawr
        "finatwa/inject/inject-cowe/swc/main/scawa", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/moduwe/pwoduct_mixew_fwags", σωσ
        "pwoduct-mixew/shawed-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/shawed_wibwawy/http_cwient", >_<
        "utiw/utiw-cowe:scawa", :3
        "utiw/utiw-jackson/swc/main/scawa/com/twittew/utiw/jackson", (U ﹏ U)
        "utiw/utiw-secuwity/swc/main/scawa/com/twittew/utiw/secuwity", -.-
    ], (ˆ ﻌ ˆ)♡
    e-expowts = [
        "finagwe/finagwe-http/swc/main/scawa", (⑅˘꒳˘)
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", (U ᵕ U❁)
        "finatwa/http-cwient/swc/main/scawa", -.-
        "finatwa/inject/inject-app/swc/main/java/com/twittew/inject/annotations", ^^;;
        "finatwa/inject/inject-cowe/swc/main/scawa", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/moduwe/pwoduct_mixew_fwags", mya
        "pwoduct-mixew/shawed-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/shawed_wibwawy/http_cwient", mya
        "utiw/utiw-cowe:scawa", 😳
        "utiw/utiw-jackson/swc/main/scawa/com/twittew/utiw/jackson", XD
        "utiw/utiw-secuwity/swc/main/scawa/com/twittew/utiw/secuwity", :3
    ],
)
