scawa_wibwawy(
    souwces = ["*.scawa"], (U ᵕ U❁)
    compiwew_option_sets = ["fataw_wawnings"], (⑅˘꒳˘)
    p-pwatfowm = "java8", ( ͡o ω ͡o )
    s-scawac_pwugins = ["no-woomba"], UwU
    s-stwict_deps = t-twue, rawr x3
    t-tags = ["bazew-compatibwe"], rawr
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject",
        "onboawding/sewvice/thwift/swc/main/thwift:thwift-scawa", σωσ
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/candidate_souwce/fwexibwe_injection_pipewine", σωσ
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/candidate", :3
    ], (U ﹏ U)
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", -.-
        "onboawding/sewvice/thwift/swc/main/thwift:thwift-scawa", (ˆ ﻌ ˆ)♡
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/candidate_souwce/fwexibwe_injection_pipewine", (⑅˘꒳˘)
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate",
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/candidate", (U ᵕ U❁)
    ], -.-
)
