#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/bitdw/header.h"

#include "levels/bitdw/areas/1/starting_platform/geo.inc.c"
#include "levels/bitdw/areas/1/large_platform/geo.inc.c"
#include "levels/bitdw/areas/1/wooden_bridge_and_fences/geo.inc.c"
#include "levels/bitdw/areas/1/quartzy_path_1/geo.inc.c"
#include "levels/bitdw/areas/1/quartzy_path_2/geo.inc.c"
#include "levels/bitdw/areas/1/quartzy_path_fences/geo.inc.c"
#include "levels/bitdw/areas/1/octogonal_platform/geo.inc.c"
#include "levels/bitdw/areas/1/platform_with_hill/geo.inc.c"
#include "levels/bitdw/areas/1/wooden_platform/geo.inc.c"
#include "levels/bitdw/areas/1/platforms_and_tilting/geo.inc.c"
#include "levels/bitdw/areas/1/platforms_and_tilting_2/geo.inc.c"
#include "levels/bitdw/areas/1/quartz_crystal/geo.inc.c"
#include "levels/bitdw/areas/1/staircase_slope_and_platform/geo.inc.c"
#include "levels/bitdw/areas/1/track_for_pyramid_platforms/geo.inc.c"
#include "levels/bitdw/areas/1/narrow_path_platform/geo.inc.c"
#include "levels/bitdw/sliding_platform/geo.inc.c"
#include "levels/bitdw/seesaw_platform/geo.inc.c"
#include "levels/bitdw/square_platform/geo.inc.c"
#include "levels/bitdw/ferris_wheel_axle/geo.inc.c"
#include "levels/bitdw/ferris_platform/geo.inc.c"
#include "levels/bitdw/collapsing_stairs_1/geo.inc.c"
#include "levels/bitdw/collapsing_stairs_2/geo.inc.c"
#include "levels/bitdw/collapsing_stairs_3/geo.inc.c"
#include "levels/bitdw/collapsing_stairs_4/geo.inc.c"
#include "levels/bitdw/collapsing_stairs_5/geo.inc.c"
#include "levels/bitdw/areas/1/geo.inc.c"
