scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/swc/java/com/twittew/wogpipewine/cwient:wogpipewine-event-pubwishew-thin", UwU
        "decidew/swc/main/scawa", rawr x3
        "featuweswitches/featuweswitches-cowe/swc/main/scawa", rawr
        "mediasewvices/media-utiw/swc/main/scawa", σωσ
        "sewvo/decidew/swc/main/scawa", σωσ
        "swc/thwift/com/twittew/context:twittew-context-scawa", >_<
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts-scawa", :3
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", -.-
        "swc/thwift/com/twittew/spam/wtf:tweet-wtf-event-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/tweetypie:tweet-scawa",
        "stitch/stitch-cowe", (⑅˘꒳˘)
        "stwato/swc/main/scawa/com/twittew/stwato/catawog", (U ᵕ U❁)
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", -.-
        "twittew-context/swc/main/scawa", ^^;;
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", >_<
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions/convewtew/scawa", mya
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/tweets", mya
        "visibiwity/common/swc/main/thwift/com/twittew/visibiwity/tweets:tweets-scawa", 😳
        "visibiwity/wib/swc/main/wesouwces/config", XD
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/common", 😳😳😳
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/media", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/tweets", ( ͡o ω ͡o )
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/usews", rawr x3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs", nyaa~~
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", /(^•ω•^)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/genewatows", rawr
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/common/tweets", OwO
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/tweets/enwichments", (U ﹏ U)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes/pwovidews", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes/utiws", rawr x3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/utiw",
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/wogging:vf-wogging-scawa", mya
    ], nyaa~~
    e-expowts = [
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", (⑅˘꒳˘)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", rawr x3
    ], (✿oωo)
)
