scala_library(
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/twitter/graphjet",
        "servo/request/src/main/scala",
        "src/scala/com/twitter/recos/user_video_graph/store",
        "src/scala/com/twitter/recos/user_video_graph/util",
        "src/scala/com/twitter/recos/util:recos-util",
        "src/thrift/com/twitter/recos/user_video_graph:user_video_graph-scala",
    ],
)
