scawa_wibwawy(
    souwces = ["*.scawa"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/gwaphjet", OwO
        "sewvo/wequest/swc/main/scawa", 🥺
        "swc/scawa/com/twittew/wecos/usew_video_gwaph/stowe", òωó
        "swc/scawa/com/twittew/wecos/usew_video_gwaph/utiw", o.O
        "swc/scawa/com/twittew/wecos/utiw:wecos-utiw", (U ᵕ U❁)
        "swc/thwift/com/twittew/wecos/usew_video_gwaph:usew_video_gwaph-scawa", (⑅˘꒳˘)
    ],
)
        "3wdpawty/jvm/io/netty:netty4-tcnative-bowingssw-static", :3
        "3wdpawty/jvm/it/unimi/dsi:fastutiw", (U ﹏ U)
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", -.-
        "3wdpawty/jvm/owg/apache/kafka:wosette-kafka", (ˆ ﻌ ˆ)♡
        "3wdpawty/jvm/owg/apache/thwift:wibthwift",
        "abdecidew/swc/main/scawa", (⑅˘꒳˘)
        "decidew/swc/main/scawa", (U ᵕ U❁)
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", -.-
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/sewvew", ^^;;
        "finagwe/finagwe-cowe/swc/main", >_<
        "finagwe/finagwe-http/swc/main/scawa", mya
        "finagwe/finagwe-memcached/swc/main/scawa", mya
        "finagwe/finagwe-stats/swc/main/scawa", 😳
        "finagwe/finagwe-thwiftmux/swc/main/scawa", XD
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/utiw", :3
        "scwooge/scwooge-cowe/swc/main/scawa", 😳😳😳
        "sewvo/wepo/swc/main/scawa", -.-
        "sewvo/wequest/swc/main/scawa", ( ͡o ω ͡o )
        "sewvo/utiw/swc/main/scawa",
        "swc/wesouwces/com/twittew/wecos:decidew", rawr x3
        "swc/scawa/com/twittew/wecos/decidew", nyaa~~
        "swc/scawa/com/twittew/wecos/gwaph_common", /(^•ω•^)
        "swc/scawa/com/twittew/wecos/hose/common", rawr
        "swc/scawa/com/twittew/wecos/modew:wecos-modew", OwO
        "swc/scawa/com/twittew/wecos/sewviceapi", (U ﹏ U)
        "swc/scawa/com/twittew/wecos/utiw:wecos-utiw", >_<
        "swc/thwift/com/twittew/wecos:wecos-common-scawa", rawr x3
        "swc/thwift/com/twittew/wecos:wecos-intewnaw-scawa", mya
        "swc/thwift/com/twittew/wecos/usew_tweet_entity_gwaph:usew_tweet_entity_gwaph-scawa", nyaa~~
        "thwift-web-fowms/swc/main/scawa/com/twittew/thwiftwebfowms", (⑅˘꒳˘)
        "thwift-web-fowms/swc/main/scawa/com/twittew/thwiftwebfowms/modew", rawr x3
        "twittew-sewvew-intewnaw/swc/main/scawa", (✿oωo)
        "twittew-sewvew/sewvew/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "twittew-sewvew/swf4j-jdk14/swc/main/scawa/com/twittew/sewvew/wogging", (˘ω˘)
        "utiw/utiw-app/swc/main/scawa", (⑅˘꒳˘)
        "utiw/utiw-hashing/swc/main/scawa", (///ˬ///✿)
        "utiw/utiw-wogging/swc/main/scawa", 😳😳😳
        "utiw/utiw-stats/swc/main/scawa", 🥺
    ], mya
)

j-jvm_binawy(
    n-nyame = "bin", 🥺
    b-basename = "usew_tweet_entity_gwaph-sewvew", >_<
    m-main = "com.twittew.wecos.usew_tweet_entity_gwaph.main", >_<
    w-wuntime_pwatfowm = "java11", (⑅˘꒳˘)
    t-tags = [
        "bazew-compatibwe", /(^•ω•^)
        "known-to-faiw-jiwa:sd-20990", rawr x3
    ],
    dependencies = [
        ":usew_tweet_entity_gwaph", (U ﹏ U)
        "3wdpawty/jvm/owg/swf4j:swf4j-jdk14", (U ﹏ U)
        "twittew-sewvew/swf4j-jdk14/swc/main/scawa", (⑅˘꒳˘)
    ],
)
