scala_library(
    sourcelons = ["*.scala"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/graphjelont",
        "selonrvo/relonquelonst/src/main/scala",
        "src/scala/com/twittelonr/reloncos/uselonr_videlono_graph/storelon",
        "src/scala/com/twittelonr/reloncos/uselonr_videlono_graph/util",
        "src/scala/com/twittelonr/reloncos/util:reloncos-util",
        "src/thrift/com/twittelonr/reloncos/uselonr_videlono_graph:uselonr_videlono_graph-scala",
    ],
)
