scala_library(
    sources = [
        "*.scala",
    ],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "beam-internal/src/main/scala/com/X/beam/io/dal",
        "beam-internal/src/main/scala/com/X/scio_internal/runner/dataflow",
        "src/scala/com/X/simclusters_v2/hdfs_sources",
        "src/scala/com/X/simclusters_v2/scalding",
    ],
)
