scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "finagwe/finagwe-cowe/swc/main", ( ͡o ω ͡o )
        "finagwe/finagwe-http/swc/main/scawa", UwU
        "finagwe/finagwe-thwiftmux/swc/main/scawa", rawr x3
        "finatwa-intewnaw/mtws-http/swc/main/scawa", rawr
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", σωσ
        "utiw/utiw-cowe", σωσ
    ],
    e-expowts = [
        "finagwe/finagwe-cowe/swc/main", >_<
        "finagwe/finagwe-http/swc/main/scawa", :3
        "finagwe/finagwe-thwiftmux/swc/main/scawa", (U ﹏ U)
        "finatwa-intewnaw/mtws-http/swc/main/scawa", -.-
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "utiw/utiw-cowe", (⑅˘꒳˘)
    ],
)
