scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "addwessbook/thwift/swc/thwift/com/twittew/addwessbook:thwift-scawa", (U ᵕ U❁)
        "addwessbook/thwift/swc/thwift/com/twittew/addwessbook/datatypes:thwift-scawa", (⑅˘꒳˘)
    ],
)
