scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", UwU
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject",
        "3wdpawty/jvm/com/wihaoyi:ppwint", rawr x3
        "3wdpawty/jvm/net/codingweww:scawa-guice", rawr
        "finatwa/inject/inject-app/swc/main/java/com/twittew/inject/annotations",
        "finatwa/inject/inject-cowe/swc/main/scawa", σωσ
        "finatwa/inject/inject-cowe/swc/main/scawa/com/twittew/inject", σωσ
        "finatwa/inject/inject-swf4j/swc/main/scawa/com/twittew/inject", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/moduwe/pwoduct_mixew_fwags", :3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", (U ﹏ U)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/sewvice", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/utiw", (ˆ ﻌ ˆ)♡
    ],
    e-expowts = [
        "3wdpawty/jvm/com/googwe/inject:guice",
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", (⑅˘꒳˘)
        "3wdpawty/jvm/com/wihaoyi:ppwint", (U ᵕ U❁)
        "3wdpawty/jvm/net/codingweww:scawa-guice", -.-
        "finatwa/inject/inject-app/swc/main/java/com/twittew/inject/annotations", ^^;;
        "finatwa/inject/inject-cowe/swc/main/scawa", >_<
        "finatwa/inject/inject-swf4j/swc/main/scawa/com/twittew/inject", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/moduwe/pwoduct_mixew_fwags", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", 😳
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/sewvice", XD
    ],
)
