packagelon com.twittelonr.product_mixelonr.corelon.selonrvicelon.gatelon_elonxeloncutor

import com.twittelonr.product_mixelonr.corelon.functional_componelonnt.gatelon.GatelonRelonsult
import com.twittelonr.product_mixelonr.corelon.modelonl.common.idelonntifielonr.GatelonIdelonntifielonr

caselon class elonxeloncutelondGatelonRelonsult(idelonntifielonr: GatelonIdelonntifielonr, relonsult: GatelonRelonsult)
