scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", ( ͡o ω ͡o )
        "pwoduct-mixew/component-wibwawy/swc/main/thwift/com/twittew/pwoduct_mixew/component_wibwawy:thwift-scawa", UwU
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/mawshawwew", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/swice", rawr
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw:api-media-gwaphqw-scawa", σωσ
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw:gwaphqw-scawa", σωσ
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw:topics-gwaphqw-scawa", >_<
    ], :3
)
