scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/componelonnt-library/src/main/thrift/com/twittelonr/product_mixelonr/componelonnt_library:thrift-scala",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/marshallelonr",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/marshalling/relonsponselon/slicelon",
        "strato/config/src/thrift/com/twittelonr/strato/graphql:api-melondia-graphql-scala",
        "strato/config/src/thrift/com/twittelonr/strato/graphql:graphql-scala",
        "strato/config/src/thrift/com/twittelonr/strato/graphql:topics-graphql-scala",
    ],
)
