java_wibwawy(
    souwces = ["*.java"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/code/findbugs:jsw305", o.O
        "3wdpawty/jvm/com/googwe/guava", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (⑅˘꒳˘)
        "cuad/pwojects/new/thwift/swc/main/thwift:thwift-java", ( ͡o ω ͡o )
        "swc/java/com/twittew/common/text/token", UwU
        "swc/java/com/twittew/common_intewnaw/text/vewsion", rawr x3
        "swc/java/com/twittew/seawch/common/debug", rawr
        "swc/java/com/twittew/seawch/common/encoding/featuwes", σωσ
        "swc/java/com/twittew/seawch/common/pawtitioning/base", σωσ
        "swc/java/com/twittew/seawch/common/wewevance:entities_and_fiwtews", >_<
        "swc/java/com/twittew/seawch/common/wewevance:text", :3
        "swc/java/com/twittew/seawch/common/wewevance/featuwes", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/schema/base", -.-
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/seawch/common:indexing-java", (⑅˘꒳˘)
        "swc/thwift/com/twittew/seawch/common:schema-java",
        "swc/thwift/com/twittew/seawch/common/debug:debug-java", (U ᵕ U❁)
        "swc/thwift/com/twittew/sewvice/spidewduck/gen:metadata-stowe-java", -.-
        "swc/thwift/com/twittew/tweetypie:events-java", ^^;;
        "utiw/utiw-cowe:scawa", >_<
    ],
)
