scawa_wibwawy(
    souwces = [
        "*.scawa", ^•ﻌ•^
    ],
    compiwew_option_sets = ["fataw_wawnings"], OwO
    t-tags = [
        "bazew-compatibwe", 🥺
        "bazew-onwy", òωó
    ],
    d-dependencies = [
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", o.O
        "swc/thwift/com/twittew/ads/biwwing/spendsewvew:spendsewvew_thwift-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/ads/eventstweam:eventstweam-scawa", (⑅˘꒳˘)
        "unified_usew_actions/adaptew/swc/main/scawa/com/twittew/unified_usew_actions/adaptew:base", ( ͡o ω ͡o )
        "unified_usew_actions/adaptew/swc/main/scawa/com/twittew/unified_usew_actions/adaptew/common", UwU
        "unified_usew_actions/thwift/swc/main/thwift/com/twittew/unified_usew_actions:unified_usew_actions-scawa", rawr x3
    ],
)
