scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "frigate/frigate-common/src/main/scala/com/X/frigate/common/util",
        "hermit/hermit-core/src/main/scala/com/X/hermit/store/common",
        "relevance-platform/src/main/scala/com/X/relevance_platform/common/injection",
        "representation-manager/client/src/main/scala/com/X/representation_manager",
        "representation-manager/client/src/main/scala/com/X/representation_manager/config",
        "representation-scorer/server/src/main/scala/com/X/representationscorer/common",
        "src/scala/com/X/simclusters_v2/score",
        "src/scala/com/X/topic_recos/common",
        "src/scala/com/X/topic_recos/stores",
        "src/thrift/com/X/simclusters_v2:simclusters_v2-thrift-scala",
        "src/thrift/com/X/topic_recos:topic_recos-thrift-scala",
        "stitch/stitch-storehaus",
    ],
)
