scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject",
        "cowtex-deepbiwd/thwift/swc/main/thwift:thwift-java", ( ͡o ω ͡o )
        "finagwe/finagwe-http/swc/main/scawa", UwU
        "finatwa-intewnaw/mtws/swc/main/scawa", rawr x3
        "finatwa/inject/inject-cowe/swc/main/scawa/com/twittew/inject", rawr
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", σωσ
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/scowew/common", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap/datawecowd", :3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap/featuwestowev1", (U ﹏ U)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/scowew", (ˆ ﻌ ˆ)♡
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", (⑅˘꒳˘)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe", (U ᵕ U❁)
        "scwooge/scwooge-sewiawizew", -.-
        "swc/java/com/twittew/mw/api:api-base", ^^;;
        "swc/java/com/twittew/mw/common/base", >_<
        "swc/java/com/twittew/mw/pwediction/cowe", mya
        "swc/thwift/com/twittew/mw/pwediction_sewvice:pwediction_sewvice-java", mya
        "swc/thwift/com/twittew/mw/pwediction_sewvice:pwediction_sewvice-scawa", 😳
        "twmw/wuntime/swc/main/scawa/com/twittew/deepbiwd/wuntime/pwediction_engine", XD
    ],
    e-expowts = [
        "cowtex-deepbiwd/thwift/swc/main/thwift:thwift-java", :3
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate",
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/scowew/common", 😳😳😳
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap/datawecowd", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", ( ͡o ω ͡o )
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/scowew", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", nyaa~~
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe", /(^•ω•^)
        "swc/java/com/twittew/mw/pwediction/cowe", rawr
        "swc/thwift/com/twittew/mw/pwediction_sewvice:pwediction_sewvice-java", OwO
        "twmw/wuntime/swc/main/scawa/com/twittew/deepbiwd/wuntime/pwediction_engine", (U ﹏ U)
    ],
)
