scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ( ͡o ω ͡o )
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", UwU
        "scwooge/scwooge-cowe", rawr x3
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts-scawa", rawr
        "swc/thwift/com/twittew/spam/wtf:safety-wabew-scawa", σωσ
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", σωσ
    ], >_<
)
