scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", UwU
        "3wdpawty/jvm/javax/inject:javax.inject", rawr x3
        "finatwa/inject/inject-cowe/swc/main/scawa", rawr
        "pwoduct-mixew/cowe/swc/main/java/com/twittew/pwoduct_mixew/cowe/pwoduct/guice/scope", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wequest", >_<
    ], :3
    e-expowts = [
        "pwoduct-mixew/cowe/swc/main/java/com/twittew/pwoduct_mixew/cowe/pwoduct/guice/scope", (U ﹏ U)
    ],
)
