scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/injelonct:guicelon",
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "finatra/injelonct/injelonct-corelon/src/main/scala",
        "product-mixelonr/corelon/src/main/java/com/twittelonr/product_mixelonr/corelon/product/guicelon/scopelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/common",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/marshalling/relonquelonst",
    ],
    elonxports = [
        "product-mixelonr/corelon/src/main/java/com/twittelonr/product_mixelonr/corelon/product/guicelon/scopelon",
    ],
)
