scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    compiwew_option_sets = ["fataw_wawnings"], OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/com/googwe/inject:guice", o.O
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", (U ᵕ U❁)
        "timewinewankew/common:modew", (⑅˘꒳˘)
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/cowe", ( ͡o ω ͡o )
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/pawametews/wevchwon", UwU
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/utiw", rawr x3
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/visibiwity", rawr
        "timewines/swc/main/scawa/com/twittew/timewines/cwients/wewevance_seawch", σωσ
        "timewines/swc/main/scawa/com/twittew/timewines/utiw/stats", σωσ
        "timewines/swc/main/scawa/com/twittew/timewines/visibiwity", >_<
        "timewinesewvice/common/swc/main/scawa/com/twittew/timewinesewvice/modew", :3
        "utiw/utiw-cowe:utiw-cowe-utiw",
        "utiw/utiw-wogging/swc/main/scawa", (U ﹏ U)
        "utiw/utiw-stats/swc/main/scawa", -.-
    ],
)
