scala_library(
    name = "hcache",
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/guava",
        "util/util-cache-guava/src/main/scala",
        "util/util-cache/src/main/scala",
        "util/util-stats/src/main/scala/com/twitter/finagle/stats",
    ],
)
