scawa_wibwawy(
    nyame = "hcache", ^•ﻌ•^
    souwces = ["*.scawa"], OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "utiw/utiw-cache-guava/swc/main/scawa", o.O
        "utiw/utiw-cache/swc/main/scawa", (U ᵕ U❁)
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats",
    ], (⑅˘꒳˘)
)
