scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = [
        "bazel-compatible",
    ],
    dependencies = [
        "3rdparty/jvm/javax/inject:javax.inject",
        "abdecider/src/main/scala",
        "content-recommender/thrift/src/main/thrift:thrift-scala",
        "hermit/hermit-core/src/main/scala/com/twitter/hermit/store/common",
        "hermit/hermit-core/src/main/scala/com/twitter/hermit/store/gizmoduck",
        "src/scala/com/twitter/topic_recos/stores",
        "src/thrift/com/twitter/gizmoduck:thrift-scala",
        "src/thrift/com/twitter/gizmoduck:user-thrift-scala",
        "src/thrift/com/twitter/simclusters_v2:simclusters_v2-thrift-scala",
        "stitch/stitch-storehaus",
        "topic-social-proof/server/src/main/scala/com/twitter/tsp/common",
        "topic-social-proof/server/src/main/scala/com/twitter/tsp/handlers",
        "topic-social-proof/server/src/main/scala/com/twitter/tsp/modules",
        "topic-social-proof/server/src/main/scala/com/twitter/tsp/stores",
        "topic-social-proof/server/src/main/thrift:thrift-scala",
    ],
)
