packagelon com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.melontadata

caselon class ConvelonrsationDelontails(convelonrsationSelonction: Option[ConvelonrsationSelonction])
