packagelon com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.melontadata

selonalelond trait ImagelonAnimationTypelon

caselon objelonct Bouncelon elonxtelonnds ImagelonAnimationTypelon
