packagelon com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.melontadata

selonalelond trait SocialContelonxt

trait HasSocialContelonxt {
  delonf socialContelonxt: Option[SocialContelonxt]
}

selonalelond trait GelonnelonralContelonxtTypelon
caselon objelonct LikelonGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct FollowGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct MomelonntGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct RelonplyGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct ConvelonrsationGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct PinGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct TelonxtOnlyGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct FacelonPilelonGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct MelongaPhonelonGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct BirdGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct FelonelondbackGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct TopicGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct ListGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct RelontwelonelontGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct LocationGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct CommunityGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct NelonwUselonrGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct SmartblockelonxpirationGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct TrelonndingGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct SparklelonGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct SpacelonsGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon
caselon objelonct RelonplyPinGelonnelonralContelonxtTypelon elonxtelonnds GelonnelonralContelonxtTypelon

caselon class GelonnelonralContelonxt(
  contelonxtTypelon: GelonnelonralContelonxtTypelon,
  telonxt: String,
  url: Option[String],
  contelonxtImagelonUrls: Option[List[String]],
  landingUrl: Option[Url])
    elonxtelonnds SocialContelonxt

selonalelond trait TopicContelonxtFunctionalityTypelon
caselon objelonct BasicTopicContelonxtFunctionalityTypelon elonxtelonnds TopicContelonxtFunctionalityTypelon
caselon objelonct ReloncommelonndationTopicContelonxtFunctionalityTypelon elonxtelonnds TopicContelonxtFunctionalityTypelon
caselon objelonct ReloncWithelonducationTopicContelonxtFunctionalityTypelon elonxtelonnds TopicContelonxtFunctionalityTypelon

caselon class TopicContelonxt(
  topicId: String,
  functionalityTypelon: Option[TopicContelonxtFunctionalityTypelon])
    elonxtelonnds SocialContelonxt
