// 0x0C000098
const GeoLayout peach_geo_000098[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_seg5_dl_05007230),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, peach_seg5_dl_05006A18),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
                  GEO_OPEN_NODE(),
                     GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_seg5_dl_05005CE0),
                     GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_seg5_dl_05005D38),
                     GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_seg5_dl_05005D90),
                     GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_seg5_dl_05005DE8),
                     GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_seg5_dl_05005E40),
                     GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_seg5_dl_05005E98),
                     GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_seg5_dl_05005EF0),
                     GEO_DISPLAY_LIST(LAYER_OPAQUE, peach_seg5_dl_05005F48),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 38, -78, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_seg5_dl_05007AB8),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, peach_seg5_dl_05009148),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 132, 0, 0, peach_seg5_dl_05008F20),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, 84, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_seg5_dl_05007E58),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, peach_seg5_dl_050087A8),
                     GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, peach_seg5_dl_05009500),
                     GEO_CLOSE_NODE(),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_seg5_dl_05008560),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 63, 0, -84, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_seg5_dl_05008228),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 104, 0, 0, peach_seg5_dl_05008CF8),
                     GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 87, 0, 0, peach_seg5_dl_05009940),
                     GEO_CLOSE_NODE(),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_seg5_dl_05008AB0),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, peach_seg5_dl_050060E0),
            GEO_ANIMATED_PART(LAYER_OPAQUE, -23, -1, 0, NULL),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, peach_seg5_dl_0500A0A8),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_RETURN(),
};

// 0x0C000254
const GeoLayout peach_geo_000254[] = {
   GEO_NODE_START(),
   GEO_OPEN_NODE(),
      GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, NULL),
      GEO_OPEN_NODE(),
#ifdef VERSION_JP
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_seg5_dl_05007230),
#else
         GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_seg5_us_dl_05007288),
#endif
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, peach_seg5_dl_05006A18),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, NULL),
               GEO_OPEN_NODE(),
                  GEO_SWITCH_CASE(8, geo_switch_peach_eyes),
                  GEO_OPEN_NODE(),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_seg5_dl_05005CE0),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_seg5_dl_05005D38),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_seg5_dl_05005D90),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_seg5_dl_05005DE8),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_seg5_dl_05005E40),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_seg5_dl_05005E98),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_seg5_dl_05005EF0),
                     GEO_DISPLAY_LIST(LAYER_TRANSPARENT, peach_seg5_dl_05005F48),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 38, -78, 0, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_seg5_dl_05007AB8),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, peach_seg5_dl_05009148),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 132, 0, 0, peach_seg5_dl_05008F20),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, 84, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_seg5_dl_05007E58),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, peach_seg5_dl_050087A8),
                     GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, peach_seg5_dl_05009500),
                     GEO_CLOSE_NODE(),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_seg5_dl_05008560),
               GEO_CLOSE_NODE(),
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 63, 0, -84, NULL),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_seg5_dl_05008228),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_TRANSPARENT, 104, 0, 0, peach_seg5_dl_05008CF8),
                     GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_TRANSPARENT, 87, 0, 0, peach_seg5_dl_05009940),
                     GEO_CLOSE_NODE(),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_seg5_dl_05008AB0),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, peach_seg5_dl_050060E0),
            GEO_ANIMATED_PART(LAYER_TRANSPARENT, -23, -1, 0, NULL),
            GEO_OPEN_NODE(),
#ifdef VERSION_JP
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_seg5_dl_0500A0A8),
#else
               GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, peach_seg5_us_dl_0500A188),
#endif
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_RETURN(),
};

// 0x0C000410
const GeoLayout peach_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_9_VERTS, 0x96, 100),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ASM(10, geo_update_layer_transparency),
         GEO_SWITCH_CASE(2, geo_switch_anim_state),
         GEO_OPEN_NODE(),
            GEO_BRANCH(1, peach_geo_000098),
            GEO_BRANCH(1, peach_geo_000254),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};

UNUSED static const u64 peach_unused_1 = 0;
