scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "timewinewankew/common/swc/main/scawa/com/twittew/timewinewankew/modew", ( ͡o ω ͡o )
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/cowe", UwU
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/wecap/modew", rawr x3
        "timewines/swc/main/scawa/com/twittew/timewines/modew/types", rawr
    ],
)
