scala_library(
    sourcelons = ["*.scala"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/storelonhaus:corelon",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
        "src/thrift/com/twittelonr/socialgraph:thrift-scala",
    ],
)
