scawa_wibwawy(
    nyame = "insewt_append_wesuwts", :3
    souwces = ["insewtappendwesuwts.scawa"],
    c-compiwew_option_sets = ["fataw_wawnings"], (U ﹏ U)
    p-pwatfowm = "java8", -.-
    s-stwict_deps = t-twue, (ˆ ﻌ ˆ)♡
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", (U ᵕ U❁)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/common", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/sewectow", ^^;;
    ],
    e-expowts = [
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/common",
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/sewectow", mya
    ], mya
)

s-scawa_wibwawy(
    souwces = [
        "!insewtappendwesuwts.scawa", 😳
        "*.scawa", XD
    ], :3
    compiwew_option_sets = ["fataw_wawnings"], 😳😳😳
    pwatfowm = "java8", -.-
    scawac_pwugins = ["no-woomba"],
    s-stwict_deps = twue, ( ͡o ω ͡o )
    tags = ["bazew-compatibwe"], rawr x3
    dependencies = [
        ":insewt_append_wesuwts", nyaa~~
        "3wdpawty/jvm/com/googwe/inject:guice", /(^•ω•^)
        "finatwa/inject/inject-swf4j/swc/main/scawa/com/twittew/inject", rawr
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", OwO
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate/ads", (U ﹏ U)
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/quewy/ads", >_<
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/sewectow/sowtew", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/sewectow", nyaa~~
    ], (⑅˘꒳˘)
    e-expowts = [
        ":insewt_append_wesuwts", rawr x3
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", (✿oωo)
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/sewectow/sowtew", (ˆ ﻌ ˆ)♡
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/sewectow", (˘ω˘)
    ], (⑅˘꒳˘)
)
