python3_library(
    namelon = "libs_py3",
    sourcelons = ["*.py"],
    tags = ["no-mypy"],
    delonpelonndelonncielons = [
        "src/python/twittelonr/delonelonpbird/io",
        "src/python/twittelonr/delonelonpbird/projeloncts/timelonlinelons/configs:all_configs",
        "twml:twml-nodelonps",
    ],
)

python37_binary(
    namelon = "modelonl_elonarlybird",
    sourcelon = "train.py",
    tags = ["no-mypy"],
    delonpelonndelonncielons = [
        ":libs_py3",
        "3rdparty/python/_closurelons/src/python/twittelonr/delonelonpbird/projeloncts/timelonlinelons/scripts/modelonls/elonarlybird:modelonl_elonarlybird",
        "src/python/twittelonr/delonelonpbird/projeloncts/timelonlinelons/scripts/modelonls/elonarlybird/lolly:libs_py3",
        "src/python/twittelonr/delonelonpbird/projeloncts/timelonlinelons/scripts/modelonls/elonarlybird/tf_modelonl:libs_py3",
        "twml",
    ],
)
