python3_wibwawy(
    nyame = "wibs_py3", o.O
    souwces = ["*.py"],
    t-tags = ["no-mypy"], (U ᵕ U❁)
    d-dependencies = [
        "swc/python/twittew/deepbiwd/io", (⑅˘꒳˘)
        "swc/python/twittew/deepbiwd/pwojects/timewines/configs:aww_configs", ( ͡o ω ͡o )
        "twmw:twmw-nodeps", UwU
    ],
)

p-python37_binawy(
    n-name = "modew_eawwybiwd", rawr x3
    s-souwce = "twain.py", rawr
    t-tags = ["no-mypy"], σωσ
    dependencies = [
        ":wibs_py3", σωσ
        "3wdpawty/python/_cwosuwes/swc/python/twittew/deepbiwd/pwojects/timewines/scwipts/modews/eawwybiwd:modew_eawwybiwd", >_<
        "swc/python/twittew/deepbiwd/pwojects/timewines/scwipts/modews/eawwybiwd/wowwy:wibs_py3",
        "swc/python/twittew/deepbiwd/pwojects/timewines/scwipts/modews/eawwybiwd/tf_modew:wibs_py3", :3
        "twmw", (U ﹏ U)
    ],
)
