packagelon com.twittelonr.product_mixelonr.corelon.selonrvicelon.selonlelonctor_elonxeloncutor

import com.twittelonr.product_mixelonr.corelon.functional_componelonnt.selonlelonctor.SelonlelonctorRelonsult
import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.CandidatelonWithDelontails
import com.twittelonr.product_mixelonr.corelon.selonrvicelon.elonxeloncutorRelonsult

caselon class SelonlelonctorelonxeloncutorRelonsult(
  selonlelonctelondCandidatelons: Selonq[CandidatelonWithDelontails],
  relonmainingCandidatelons: Selonq[CandidatelonWithDelontails],
  droppelondCandidatelons: Selonq[CandidatelonWithDelontails],
  individualSelonlelonctorRelonsults: Selonq[SelonlelonctorRelonsult])
    elonxtelonnds elonxeloncutorRelonsult
