scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finatra/injelonct/injelonct-corelon/src/main/scala/com/twittelonr/injelonct",
        "onboarding/selonrvicelon/thrift/src/main/thrift:thrift-scala",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon",
        "stitch/stitch-corelon",
    ],
    elonxports = [
        "onboarding/selonrvicelon/thrift/src/main/thrift:thrift-scala",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon",
    ],
)
