scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject",
        "finatwa/inject/inject-cowe/swc/main/scawa/com/twittew/inject", ( ͡o ω ͡o )
        "intewests-sewvice/thwift/swc/main/thwift:thwift-scawa", UwU
        "intewests_discovewy/thwift/swc/main/thwift:sewvice-thwift-scawa", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/candidate_souwce", rawr
        "stitch/stitch-cowe", σωσ
    ],
    e-expowts = [
        "intewests-sewvice/thwift/swc/main/thwift:thwift-scawa", σωσ
        "intewests_discovewy/thwift/swc/main/thwift:sewvice-thwift-scawa", >_<
    ],
)
