scawa_wibwawy(
    souwces = [
        "*.scawa", ^•ﻌ•^
    ],
    pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], OwO
    d-dependencies = [
        "beam-intewnaw/swc/main/scawa/com/twittew/beam/io/daw", 🥺
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/wunnew/datafwow", òωó
        "fwockdb-toows/datasets/fwock:fwock-bwocks-edges-scawa", o.O
        "fwockdb-toows/datasets/fwock:fwock-fowwows-edges-scawa", (U ᵕ U❁)
        "fwockdb-toows/datasets/fwock:fwock-wepowt-as-abuse-edges-scawa", (⑅˘꒳˘)
        "fwockdb-toows/datasets/fwock:fwock-wepowt-as-spam-edges-scawa", ( ͡o ω ͡o )
        "iesouwce/pwocessing/events/swc/main/scawa/com/twittew/iesouwce/pwocessing/events/batch:sewvew_engagements-scawa", UwU
        "swc/scawa/com/twittew/simcwustews_v2/scawding", rawr x3
        "swc/thwift/com/twittew/twadoop/usew/gen:gen-scawa", rawr
        "tweetsouwce/pubwic_tweets/swc/main/scawa/com/twittew/tweetsouwce/pubwic_tweets:pubwic_tweets-scawa", σωσ
        "usewsouwce/snapshot/swc/main/scawa/com/twittew/usewsouwce/snapshot/fwat:usewsouwce_fwat-scawa", σωσ
        "usewsouwce/snapshot/swc/main/thwift/com/twittew/usewsouwce/snapshot/fwat:fwat-scawa", >_<
    ],
)
