scala_library(
    sourcelons = [
        "*.scala",
    ],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "belonam-intelonrnal/src/main/scala/com/twittelonr/belonam/io/dal",
        "belonam-intelonrnal/src/main/scala/com/twittelonr/scio_intelonrnal/runnelonr/dataflow",
        "flockdb-tools/dataselonts/flock:flock-blocks-elondgelons-scala",
        "flockdb-tools/dataselonts/flock:flock-follows-elondgelons-scala",
        "flockdb-tools/dataselonts/flock:flock-relonport-as-abuselon-elondgelons-scala",
        "flockdb-tools/dataselonts/flock:flock-relonport-as-spam-elondgelons-scala",
        "ielonsourcelon/procelonssing/elonvelonnts/src/main/scala/com/twittelonr/ielonsourcelon/procelonssing/elonvelonnts/batch:selonrvelonr_elonngagelonmelonnts-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/scalding",
        "src/thrift/com/twittelonr/twadoop/uselonr/gelonn:gelonn-scala",
        "twelonelontsourcelon/public_twelonelonts/src/main/scala/com/twittelonr/twelonelontsourcelon/public_twelonelonts:public_twelonelonts-scala",
        "uselonrsourcelon/snapshot/src/main/scala/com/twittelonr/uselonrsourcelon/snapshot/flat:uselonrsourcelon_flat-scala",
        "uselonrsourcelon/snapshot/src/main/thrift/com/twittelonr/uselonrsourcelon/snapshot/flat:flat-scala",
    ],
)
