java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", òωó
        "decidew/swc/main/scawa", o.O
        "finatwa-intewnaw/thwift/swc/main/thwift:thwift-java", (U ᵕ U❁)
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift", (⑅˘꒳˘)
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift:contwowwew", ( ͡o ω ͡o )
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/exceptions", UwU
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/fiwtews", rawr x3
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/moduwes", rawr
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/wesponse", σωσ
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/wouting", σωσ
        "swc/java/com/twittew/seawch/common/metwics", >_<
        "swc/java/com/twittew/seawch/common/utiw/io/pewiodic", :3
        "swc/java/com/twittew/seawch/common/utiw/thwift:text-pwotocow", (U ﹏ U)
        "swc/java/com/twittew/seawch/featuwe_update_sewvice/whitewist", -.-
        "swc/thwift/com/twittew/seawch/featuwe_update_sewvice/thwift:thwift-java", (ˆ ﻌ ˆ)♡
    ],
)
