scala_library(
    sourcelons = ["*.scala"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "deloncidelonr/src/main/scala",
        "src/scala/com/twittelonr/reloncos/util:reloncos-util",
    ],
)
