scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "decidew/swc/main/scawa", òωó
        "swc/scawa/com/twittew/wecos/utiw:wecos-utiw", o.O
    ],
)
