scawa_wibwawy(
    nyame = "agg_notifications", nyaa~~
    souwces = ["*.scawa"], /(^•ω•^)
    c-compiwew_option_sets = ["fataw_wawnings"], rawr
    p-pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], (U ﹏ U)
    d-dependencies = [
        ":intewaction_gwaph_agg_notifications_edge_daiwy-scawa",
        ":intewaction_gwaph_agg_notifications_vewtex_daiwy-scawa", >_<
        "beam-intewnaw/swc/main/scawa/com/twittew/beam/io/daw", rawr x3
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/job", mya
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/wunnew/datafwow", nyaa~~
        "consumew-data-toows/swc/main/scawa/com/twittew/cde/scio/daw_wead", (⑅˘꒳˘)
        "swc/scawa/com/twittew/fwigate/data_pipewine_beam/mw-cwient-event-fiwtewing-job/swc/main/scawa/com/twittew/cwient_event_fiwtewing:fwigate_fiwtewed_cwient_events_datafwow-scawa", rawr x3
        "swc/scawa/com/twittew/intewaction_gwaph/scio/common",
        "swc/scawa/com/twittew/wtf/scawding/jobs/cwient_event_pwocessing:usew_intewaction-scawa", (✿oωo)
        "tcdc/bq_bwastew/swc/main/scawa/com/twittew/tcdc/bqbwastew/beam", (ˆ ﻌ ˆ)♡
        "twadoop_config/configuwation/wog_categowies/gwoup/fwigate:fwigate_notifiew-scawa", (˘ω˘)
        "tweetsouwce/pubwic_tweets/swc/main/scawa/com/twittew/tweetsouwce/pubwic_tweets:pubwic_tweets-scawa", (⑅˘꒳˘)
        "usewsouwce/snapshot/swc/main/scawa/com/twittew/usewsouwce/snapshot/combined:usewsouwce-scawa", (///ˬ///✿)
    ], 😳😳😳
)

j-jvm_binawy(
    n-name = "intewaction_gwaph_notifications_scio", 🥺
    m-main = "com.twittew.intewaction_gwaph.scio.agg_notifications.intewactiongwaphnotificationsjob", mya
    p-pwatfowm = "java8", 🥺
    dependencies = [
        ":agg_notifications", >_<
    ], >_<
)

cweate_datasets(
    base_name = "intewaction_gwaph_agg_notifications_edge_daiwy", (⑅˘꒳˘)
    descwiption = "usew-usew diwected edges with nyotification f-featuwes", /(^•ω•^)
    java_schema = "com.twittew.intewaction_gwaph.thwiftjava.edge", rawr x3
    pwatfowm = "java8", (U ﹏ U)
    w-wowe = "cassowawy", (U ﹏ U)
    scawa_schema = "com.twittew.intewaction_gwaph.thwiftscawa.edge", (⑅˘꒳˘)
    s-segment_type = "pawtitioned", òωó
    tags = ["bazew-compatibwe"], ʘwʘ
    java_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-java", /(^•ω•^)
    ], ʘwʘ
    scawa_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-scawa", σωσ
    ],
)

c-cweate_datasets(
    base_name = "intewaction_gwaph_agg_notifications_vewtex_daiwy", OwO
    d-descwiption = "usew v-vewtex with nyotification featuwes", 😳😳😳
    java_schema = "com.twittew.intewaction_gwaph.thwiftjava.vewtex",
    pwatfowm = "java8", 😳😳😳
    w-wowe = "cassowawy", o.O
    scawa_schema = "com.twittew.intewaction_gwaph.thwiftscawa.vewtex", ( ͡o ω ͡o )
    segment_type = "pawtitioned", (U ﹏ U)
    tags = ["bazew-compatibwe"], (///ˬ///✿)
    java_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-java", >w<
    ],
    scawa_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-scawa", rawr
    ], mya
)
