scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "follow-recommendations-service/common/src/main/scala/com/ExTwitter/follow_recommendations/common/models",
        "follow-recommendations-service/thrift/src/main/thrift:thrift-scala",
        "stringcenter/client",
    ],
    exports = [
    ],
)
