scala_library(
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/modelonls",
        "follow-reloncommelonndations-selonrvicelon/thrift/src/main/thrift:thrift-scala",
        "stringcelonntelonr/clielonnt",
    ],
    elonxports = [
    ],
)
