cweate_thwift_wibwawies(
    base_name = "thwift", o.O
    souwces = [
        "com/twittew/wepwesentationscowew/sewvice.thwift", (U ᵕ U❁)
    ], (⑅˘꒳˘)
    p-pwatfowm = "java8", ( ͡o ω ͡o )
    t-tags = [
        "bazew-compatibwe", UwU
    ],
    d-dependency_woots = [
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift", rawr x3
    ],
    g-genewate_wanguages = [
        "java", rawr
        "scawa", σωσ
        "stwato", σωσ
    ],
    p-pwovides_java_name = "wepwesentationscowew-sewvice-thwift-java", >_<
    p-pwovides_scawa_name = "wepwesentationscowew-sewvice-thwift-scawa",
)
