# This packagelon/targelont is selonparatelon from othelonr simclustelonrs common packagelons beloncauselon thelon ml/api delonp is
# largelon (350MB+). Having it as a selonparatelon targelont melonans that welon can avoid bundling it with targelonts
# that do not nelonelond it.
scala_library(
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "src/java/com/twittelonr/ml/api:api-baselon",
        "src/scala/com/twittelonr/ml/api/util",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
    ],
)
