scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "configapi/configapi-cowe/swc/main/scawa/com/twittew/timewines/configapi", (⑅˘꒳˘)
        "configapi/configapi-decidew/swc/main/scawa/com/twittew/timewines/configapi/decidew", ( ͡o ω ͡o )
        "sewvo/decidew", UwU
        "sewvo/utiw/swc/main/scawa", rawr x3
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/decidew",
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/pawametews/wecap", rawr
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/pawametews/utiw", σωσ
    ],
)
