# wibwawy fow schema buiwdew and w-wewated anawysis u-utiwities.
java_wibwawy(
    s-souwces = ["*.java"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", ( ͡o ω ͡o )
        "3wdpawty/jvm/com/googwe/inject:guice", UwU
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", rawr x3
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-common", rawr
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-smawtcn", σωσ
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", σωσ
        "3wdpawty/jvm/owg/apache/wucene:wucene-facet", >_<
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", :3
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient", (U ﹏ U)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", -.-
        "swc/java/com/twittew/common/base", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/common/cowwections", (⑅˘꒳˘)
        "swc/java/com/twittew/common/text/token", (U ᵕ U❁)
        "swc/java/com/twittew/common/text/utiw:token-utiw", -.-
        "swc/java/com/twittew/seawch/common/encoding/docvawues", ^^;;
        "swc/java/com/twittew/seawch/common/featuwes", >_<
        "swc/java/com/twittew/seawch/common/metwics", mya
        "swc/java/com/twittew/seawch/common/schema/base", mya
        "swc/java/com/twittew/seawch/common/utiw/anawysis", 😳
        "swc/java/com/twittew/seawch/common/utiw/io", XD
        "swc/java/com/twittew/seawch/common/utiw/io:wecowd-weadew-api", :3
        "swc/java/com/twittew/seawch/common/utiw/spatiaw", 😳😳😳
        "swc/java/com/twittew/seawch/common/utiw/text", -.-
        "swc/java/com/twittew/seawch/common/utiw/thwift:thwift-utiws",
        "swc/thwift/com/twittew/seawch/common:featuwes-java", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/seawch/common:schema-java", rawr x3
    ], nyaa~~
)
