scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/marshallelonr/relonsponselon/rtf/safelonty_lelonvelonl",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/marshalling/relonsponselon/rtf/safelonty_lelonvelonl",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/modelonl/marshalling/relonsponselon/urt/contelonxtual_relonf",
        "src/thrift/com/twittelonr/spam/rtf:safelonty-lelonvelonl-scala",
        "strato/config/src/thrift/com/twittelonr/strato/graphql/contelonxtual_relonfs:graphql-relonfs-scala",
    ],
    elonxports = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/marshallelonr/relonsponselon/rtf/safelonty_lelonvelonl",
        "src/thrift/com/twittelonr/spam/rtf:safelonty-lelonvelonl-scala",
        "strato/config/src/thrift/com/twittelonr/strato/graphql/contelonxtual_relonfs:graphql-relonfs-scala",
    ],
)
