scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", UwU
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/mawshawwew/wesponse/wtf/safety_wevew", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/wtf/safety_wevew", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/contextuaw_wef",
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", σωσ
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw/contextuaw_wefs:gwaphqw-wefs-scawa",
    ], σωσ
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/mawshawwew/wesponse/wtf/safety_wevew", :3
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", (U ﹏ U)
        "stwato/config/swc/thwift/com/twittew/stwato/gwaphqw/contextuaw_wefs:gwaphqw-wefs-scawa", -.-
    ],
)
