scala_library(
    sourcelons = [
        "*.scala",
        "common/*.scala",
    ],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "elonschelonrbird/src/scala/com/twittelonr/elonschelonrbird/scalding/sourcelon",
        "flockdb-tools/dataselonts/flock:flock-blocks-elondgelons-scala",
        "flockdb-tools/dataselonts/flock:flock-follows-elondgelons-scala",
        "flockdb-tools/dataselonts/flock:flock-relonport-as-abuselon-elondgelons-scala",
        "flockdb-tools/dataselonts/flock:flock-relonport-as-spam-elondgelons-scala",
        "ielonsourcelon/procelonssing/elonvelonnts/src/main/scala/com/twittelonr/ielonsourcelon/procelonssing/elonvelonnts/batch:selonrvelonr_elonngagelonmelonnts-scala",
        "intelonrelonsts-ds/src/main/scala/com/twittelonr/intelonrelonsts_ds/jobs/intelonrelonsts_selonrvicelon",
        "intelonrelonsts-ds/src/main/scala/com/twittelonr/intelonrelonsts_ds/jobs/intelonrelonsts_selonrvicelon:uselonr_topic_relonlation_snapshot-scala",
        "src/java/com/twittelonr/common/telonxt/languagelon:localelon-util",
        "src/scala/com/twittelonr/frigatelon/data_pipelonlinelon/scalding/magicreloncs/magicreloncs_notification_litelon:magicreloncs_notification_litelon_1day_lag-scala",
        "src/scala/com/twittelonr/onboarding/relonlelonvancelon/sourcelon:utt_account_reloncommelonndations-scala",
        "src/scala/com/twittelonr/pelonnguin/scalding/dataselonts:pelonnguin_uselonr_languagelons-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons:simclustelonrs_v2_elonmbelonddings_litelon-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons/prelonsto_hdfs_sourcelons",
        "src/scala/com/twittelonr/simclustelonrs_v2/scalding/common",
        "src/scala/com/twittelonr/simclustelonrs_v2/scalding/common/matrix",
        "src/scala/com/twittelonr/wtf/elonntity_relonal_graph/common",
        "src/scala/com/twittelonr/wtf/elonntity_relonal_graph/scalding/common",
        "src/scala/com/twittelonr/wtf/scalding/jobs/common:elonxeloncution_app",
        "src/scala/com/twittelonr/wtf/scalding/jobs/common:sourcelons",
        "src/scala/com/twittelonr/wtf/scalding/jobs/common:stats_util",
        "src/thrift/com/twittelonr/helonrmit/candidatelon:helonrmit-candidatelon-scala",
        "src/thrift/com/twittelonr/onboarding/relonlelonvancelon/candidatelons:candidatelons-scala",
        "src/thrift/com/twittelonr/reloncos/elonntitielons:elonntitielons-thrift-scala",
        "src/thrift/com/twittelonr/selonarch/adaptivelon/scribing:adaptivelon-scribing-scala",
        "src/thrift/com/twittelonr/wtf/elonntity_relonal_graph:elonntity_relonal_graph-thrift-scala",
        "twadoop_config/configuration/log_catelongorielons/group/selonarch:adaptivelon_selonarch-scala",
        "uselonrsourcelon/snapshot/src/main/scala/com/twittelonr/uselonrsourcelon/snapshot/flat:uselonrsourcelon_flat-scala",
        "uselonrsourcelon/snapshot/src/main/thrift/com/twittelonr/uselonrsourcelon/snapshot/flat:flat-scala",
    ],
)

hadoop_binary(
    namelon = "elonntity_elonmbelonddings_job-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.elonntityToSimClustelonrselonmbelonddingAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "elonntity_pelonr_languagelon_elonmbelonddings_job-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.LocalelonelonntitySimClustelonrselonmbelonddingAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "selonmantic_corelon_elonntity_elonmbelonddings_delonc11_modelonl_job",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.SelonmanticCorelonelonntityelonmbelonddingsDelonc11ModelonlApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "selonmantic_corelon_elonntity_elonmbelonddings_2020_job",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.SelonmanticCorelonelonntityelonmbelonddings2020App",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "selonmantic_corelon_elonntity_elonmbelonddings_pelonr_languagelon_job",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.LocalelonelonntitySimClustelonrselonmbelonddingSchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "localelon_elonntity_simclustelonrs_elonmbelondding_v2",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.LocalelonelonntitySimClustelonrselonmbelonddingV2SchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "localelon_elonntity_simclustelonrs_elonmbelondding_v2-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.LocalelonelonntitySimClustelonrselonmbelonddingV2AdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "producelonr_elonmbelonddings_from_intelonrelonstelond_in-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.ProducelonrelonmbelonddingsFromIntelonrelonstelondInAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "producelonr_elonmbelonddings_from_intelonrelonstelond_in_by_fav_scorelon",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.ProducelonrelonmbelonddingsFromIntelonrelonstelondInByFavScorelonBatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "producelonr_elonmbelonddings_from_intelonrelonstelond_in_by_fav_scorelon_2020",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.ProducelonrelonmbelonddingsFromIntelonrelonstelondInByFavScorelon2020BatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "producelonr_elonmbelonddings_from_intelonrelonstelond_in_by_fav_scorelon_delonc11",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.ProducelonrelonmbelonddingsFromIntelonrelonstelondInByFavScorelonDelonc11BatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "producelonr_elonmbelonddings_from_intelonrelonstelond_in_by_follow_scorelon",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.ProducelonrelonmbelonddingsFromIntelonrelonstelondInByFollowScorelonBatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "producelonr_elonmbelonddings_from_intelonrelonstelond_in_by_follow_scorelon_2020",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.ProducelonrelonmbelonddingsFromIntelonrelonstelondInByFollowScorelon2020BatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "producelonr_elonmbelonddings_from_intelonrelonstelond_in_by_follow_scorelon_delonc11",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.ProducelonrelonmbelonddingsFromIntelonrelonstelondInByFollowScorelonDelonc11BatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "similar_uselonrs_by_simclustelonrs_elonmbelonddings-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.SimilarUselonrsBySimClustelonrselonmbelonddingAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "similar_uselonrs_by_simclustelonrs_elonmbelonddings",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.SimilarUselonrsBySimClustelonrselonmbelonddingBatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "elonntity_elonmbelondding_from_producelonr_elonmbelondding-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.elonntityelonmbelonddingFromProducelonrelonmbelonddingAdhocJob",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "elonntity_elonmbelondding_from_producelonr_elonmbelondding_job",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.elonntityelonmbelonddingFromProducelonrelonmbelonddingSchelondulelondJob",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

# Gelonnelonratelond with `capelonsospy-v2 crelonatelon_targelont similar_uselonrs_by_simclustelonrs_elonmbelonddings_job src/scala/com/twittelonr/simclustelonrs_v2/capelonsos_config/atla_proc3.yaml`, config hash b8cf4d.
scalding_job(
    namelon = "similar_uselonrs_by_simclustelonrs_elonmbelonddings_job",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.SimiliarUselonrsBySimClustelonrselonmbelonddingBatchApp",
    config = [
        ("hadoop.combinelon-input", "truelon"),
        ("hadoop.map.jvm.total-melonmory", "3072m"),
        ("hadoop.quelonuelon", "cassowary.delonfault"),
        ("hadoop.relonducelon.jvm.total-melonmory", "3072m"),
        ("hadoop.submittelonr.jvm.total-melonmory", "5120m"),
        ("submittelonr.tielonr", "prelonelonmptiblelon"),
    ],
    cron = "15 * * * *",
    hadoop_clustelonr = "atla-proc3",
    platform = "java8",
    rolelon = "cassowary",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)

hadoop_binary(
    namelon = "global_simclustelonrs_languagelon_elonmbelondding_job",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmbelondding.GlobalSimClustelonrsLanguagelonelonmbelonddingBatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [":elonmbelondding"],
)
