[package]
name = "bpr_thrift"
description = "Thrift parser for Batch Prediction Request"
version = "0.1.0"
edition = "2021"

[dependencies]
thrift = { version = "0.17.0", default-features = false, features = ["server" ]}
