scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", ( ͡o ω ͡o )
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", UwU
        "swc/thwift/com/twittew/context:twittew-context-scawa", rawr x3
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", rawr
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", σωσ
        "swc/thwift/com/twittew/spam/wtf:tweet-wtf-event-scawa", σωσ
        "stitch/stitch-cowe", >_<
        "twittew-context/swc/main/scawa", :3
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", (U ﹏ U)
        "visibiwity/wib/swc/main/wesouwces/config", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", (ˆ ﻌ ˆ)♡
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/common", (⑅˘꒳˘)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/usews", (U ᵕ U❁)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/utiw", ^^;;
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/safety_wabew_stowe:safety-wabew-stowe-scawa", >_<
    ],
)
