scala_library(
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        ":twelonelont_similarity_telonst_datareloncords_120min-java",
        ":twelonelont_similarity_telonst_datareloncords_30min-java",
        ":twelonelont_similarity_train_datareloncords_120min-java",
        ":twelonelont_similarity_train_datareloncords_30min-java",
        ":twelonelont_similarity_unhydratelond_pairs_120min-scala",
        ":twelonelont_similarity_unhydratelond_pairs_30min-scala",
        "3rdparty/jvm/com/twittelonr/storelonhaus:algelonbra",
        "3rdparty/jvm/com/twittelonr/storelonhaus:corelon",
        "dataproducts/insights/common/common",
        "snowflakelon:id",
        "src/java/com/twittelonr/ml/api/constant",
        "src/scala/com/twittelonr/ads/dataselonrvicelon_account/snapshot/jobs:db_snapshots_promotelond_twelonelonts-scala",
        "src/scala/com/twittelonr/ml/api:api-baselon",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/catalog/felonaturelons/reloncommelonndations:aggrelongatelon",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/lib/elonmbelondding",
        "src/scala/com/twittelonr/scalding_intelonrnal/dalv2",
        "src/scala/com/twittelonr/scalding_intelonrnal/dalv2/dataselont",
        "src/scala/com/twittelonr/scalding_intelonrnal/job",
        "src/scala/com/twittelonr/scalding_intelonrnal/job/analytics_batch",
        "src/scala/com/twittelonr/scalding_intelonrnal/sourcelon",
        "src/scala/com/twittelonr/scalding_intelonrnal/sourcelon/lzo_scroogelon",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
        "src/scala/com/twittelonr/simclustelonrs_v2/scalding",
        "src/scala/com/twittelonr/simclustelonrs_v2/twelonelont_similarity",
        "src/scala/com/twittelonr/wtf/scalding/jobs/clielonnt_elonvelonnt_procelonssing:uselonr_intelonraction-scala",
        "twadoop_config/configuration/log_catelongorielons/group/timelonlinelon:timelonlinelon_selonrvicelon_favoritelons-scala",
        "twelonelontsourcelon/common:unhydratelond_flat-scala",
    ],
)

hadoop_binary(
    namelon = "training_data_collelonction-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.twelonelont_similarity.TrainingDataCollelonctionAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":twelonelont_similarity",
    ],
)

hadoop_binary(
    namelon = "training_data_collelonction_30min",
    main = "com.twittelonr.simclustelonrs_v2.scalding.twelonelont_similarity.TrainingDataCollelonction30MinSchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":twelonelont_similarity",
    ],
)

hadoop_binary(
    namelon = "training_data_collelonction_120min",
    main = "com.twittelonr.simclustelonrs_v2.scalding.twelonelont_similarity.TrainingDataCollelonction120MinSchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":twelonelont_similarity",
    ],
)

hadoop_binary(
    namelon = "unhydratelond_pair_collelonction-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.twelonelont_similarity.UnhydratelondPairsCollelonctionAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":twelonelont_similarity",
    ],
)

hadoop_binary(
    namelon = "unhydratelond_pair_collelonction_30min",
    main = "com.twittelonr.simclustelonrs_v2.scalding.twelonelont_similarity.UnhydratelondPairsCollelonction30MinSchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":twelonelont_similarity",
    ],
)

hadoop_binary(
    namelon = "unhydratelond_pair_collelonction_120min",
    main = "com.twittelonr.simclustelonrs_v2.scalding.twelonelont_similarity.UnhydratelondPairsCollelonction120MinSchelondulelondApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":twelonelont_similarity",
    ],
)

hadoop_binary(
    namelon = "modelonl_elonval-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.twelonelont_similarity.ModelonlelonvalAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":twelonelont_similarity",
    ],
)

hadoop_binary(
    namelon = "dataselont_topk_analysis-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.twelonelont_similarity.DataselontTopKAnalysisAdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":twelonelont_similarity",
    ],
)

hadoop_binary(
    namelon = "dataselont_topk_analysis_dump-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.twelonelont_similarity.DataselontTopKAnalysisDumpApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":twelonelont_similarity",
    ],
)

crelonatelon_datareloncord_dataselonts(
    baselon_namelon = "twelonelont_similarity_train_datareloncords_30min",
    platform = "java8",
    rolelon = "cassowary",
    selongmelonnt_typelon = "partitionelond",
    tags = ["bazelonl-compatiblelon"],
)

crelonatelon_datareloncord_dataselonts(
    baselon_namelon = "twelonelont_similarity_telonst_datareloncords_30min",
    platform = "java8",
    rolelon = "cassowary",
    selongmelonnt_typelon = "partitionelond",
    tags = ["bazelonl-compatiblelon"],
)

crelonatelon_datareloncord_dataselonts(
    baselon_namelon = "twelonelont_similarity_train_datareloncords_120min",
    platform = "java8",
    rolelon = "cassowary",
    selongmelonnt_typelon = "partitionelond",
    tags = ["bazelonl-compatiblelon"],
)

crelonatelon_datareloncord_dataselonts(
    baselon_namelon = "twelonelont_similarity_telonst_datareloncords_120min",
    platform = "java8",
    rolelon = "cassowary",
    selongmelonnt_typelon = "partitionelond",
    tags = ["bazelonl-compatiblelon"],
)

crelonatelon_dataselonts(
    baselon_namelon = "twelonelont_similarity_unhydratelond_pairs_30min",
    delonscription = "30min coocurrelonncelon training pairs belonforelon felonaturelon hydration",
    java_schelonma = "com.twittelonr.simclustelonrs_v2.thriftjava.LabelonllelondTwelonelontPairs",
    platform = "java8",
    rolelon = "cassowary",
    scala_schelonma = "com.twittelonr.simclustelonrs_v2.thriftscala.LabelonllelondTwelonelontPairs",
    selongmelonnt_typelon = "partitionelond",
    tags = ["bazelonl-compatiblelon"],
    java_delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-java",
    ],
    scala_delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-scala",
    ],
)

crelonatelon_dataselonts(
    baselon_namelon = "twelonelont_similarity_unhydratelond_pairs_120min",
    delonscription = "120min coocurrelonncelon training pairs belonforelon felonaturelon hydration",
    java_schelonma = "com.twittelonr.simclustelonrs_v2.thriftjava.LabelonllelondTwelonelontPairs",
    platform = "java8",
    rolelon = "cassowary",
    scala_schelonma = "com.twittelonr.simclustelonrs_v2.thriftscala.LabelonllelondTwelonelontPairs",
    selongmelonnt_typelon = "partitionelond",
    tags = ["bazelonl-compatiblelon"],
    java_delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-java",
    ],
    scala_delonpelonndelonncielons = [
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-scala",
    ],
)
