// 0x0D000358
const GeoLayout piranha_plant_geo[] = {
   GEO_SHADOW(SHADOW_CIRCLE_4_VERTS, 0x9B, 200),
   GEO_OPEN_NODE(),
      GEO_SCALE(0x00, 16384),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 14, 3, NULL),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, piranha_plant_seg6_dl_06015850),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_OPAQUE, 46, 0, 0, piranha_plant_seg6_dl_06016F20),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 154, 0, 0, piranha_plant_seg6_dl_06016D98),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_OPAQUE, 153, 0, 0, piranha_plant_seg6_dl_06016C10),
                     GEO_OPEN_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 236, 42, 0, NULL),
                        GEO_OPEN_NODE(),
                           GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, piranha_plant_seg6_dl_060160B0),
                           GEO_OPEN_NODE(),
                              GEO_DISPLAY_LIST(LAYER_ALPHA, piranha_plant_seg6_dl_06016120),
                           GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                        GEO_ANIMATED_PART(LAYER_OPAQUE, 217, -2, 0, NULL),
                        GEO_OPEN_NODE(),
                           GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, piranha_plant_seg6_dl_060169E8),
                           GEO_OPEN_NODE(),
                              GEO_DISPLAY_LIST(LAYER_ALPHA, piranha_plant_seg6_dl_06016A78),
                           GEO_CLOSE_NODE(),
                        GEO_CLOSE_NODE(),
                     GEO_CLOSE_NODE(),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, -34, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, piranha_plant_seg6_dl_06015480),
                  GEO_CLOSE_NODE(),
                  GEO_ANIMATED_PART(LAYER_OPAQUE, 49, 0, 37, NULL),
                  GEO_OPEN_NODE(),
                     GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, piranha_plant_seg6_dl_06015578),
                  GEO_CLOSE_NODE(),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
