scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "finatwa/inject/inject-cowe/swc/main/scawa", òωó
        "wepwesentation-managew/sewvew/swc/main/scawa/com/twittew/wepwesentation_managew/cowumns", o.O
        "wepwesentation-managew/sewvew/swc/main/scawa/com/twittew/wepwesentation_managew/moduwes", (U ᵕ U❁)
        "wepwesentation-managew/sewvew/swc/main/scawa/com/twittew/wepwesentation_managew/stowe", (⑅˘꒳˘)
        "wepwesentation-managew/sewvew/swc/main/thwift:thwift-scawa", ( ͡o ω ͡o )
        "stwato/swc/main/scawa/com/twittew/stwato/fed", UwU
        "stwato/swc/main/scawa/com/twittew/stwato/fed/sewvew", rawr x3
    ],
)
