scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/candidatelon_sourcelon/strato",
        "strato/config/columns/intelonrelonsts:intelonrelonsts-strato-clielonnt",
        "strato/src/main/scala/com/twittelonr/strato/clielonnt",
    ],
)
