scala_library(
    name = "base",
    sources = [
        "AbstractAdapter.scala",
    ],
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "util/util-stats/src/main/scala/com/twitter/finagle/stats",
    ],
)
