scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", UwU
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", rawr x3
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", rawr
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/moduwe", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/featuwe_hydwatow", :3
        "swc/thwift/com/twittew/spam/wtf:safety-wesuwt-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/timewinescowew:thwift-scawa",
        "swc/thwift/com/twittew/timewinescowew/sewvew/intewnaw:thwift-scawa", -.-
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/tweetypie:tweet-scawa",
        "stitch/stitch-cowe", (⑅˘꒳˘)
        "stitch/stitch-tweetypie", (U ᵕ U❁)
    ],
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", -.-
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", ^^;;
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate", >_<
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/moduwe", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", mya
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", 😳
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/featuwe_hydwatow", XD
        "swc/thwift/com/twittew/timewinescowew:thwift-scawa", :3
        "swc/thwift/com/twittew/timewinescowew/sewvew/intewnaw:thwift-scawa", 😳😳😳
        "stitch/stitch-cowe", -.-
    ],
)
