scawa_wibwawy(
    pwatfowm = "java11", OwO
    stwict_deps = f-fawse, 🥺
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/owg/apache/thwift:wibthwift",
        "finatwa-intewnaw/messaging/kafka/swc/main/scawa", o.O
        "sewvo/wepo/swc/main/scawa",
        "swc/thwift/com/twittew/wecos:wecos-injectow-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/wecos:wecos-intewnaw-scawa", (⑅˘꒳˘)
    ], ( ͡o ω ͡o )
)
dpawty/jvm/owg/apache/commons:commons-math3", UwU
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", rawr x3
        "decidew/swc/main/scawa", rawr
        "swc/java/com/twittew/common_intewnaw/text/vewsion", σωσ
        "swc/java/com/twittew/metastowe/cwient_v2", σωσ
        "swc/java/com/twittew/metastowe/data", >_<
        "swc/java/com/twittew/seawch/common/debug", :3
        "swc/java/com/twittew/seawch/common/encoding/featuwes", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/metwics", -.-
        "swc/java/com/twittew/seawch/common/pawtitioning/base", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/common/wewevance:entities_and_fiwtews", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/wewevance/featuwes", (U ᵕ U❁)
        "swc/java/com/twittew/seawch/common/schema", -.-
        "swc/java/com/twittew/seawch/common/schema/base", ^^;;
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", >_<
        "swc/java/com/twittew/seawch/common/utiw/geocoding", mya
        "swc/java/com/twittew/seawch/common/utiw/text", mya
        "swc/java/com/twittew/seawch/ingestew/modew", 😳
        "swc/java/owg/apache/commons/pipewine", XD
        "swc/scawa/com/twittew/common_intewnaw/anawytics/test_usew_fiwtew", :3
        "swc/thwift/com/twittew/expandodo:cawds-java", 😳😳😳
        "swc/thwift/com/twittew/manhattan:intewnaw-scawa", -.-
        "swc/thwift/com/twittew/seawch/common:indexing-java", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/seawch/common:schema-java",
        "swc/thwift/com/twittew/sewvice/metastowe/gen:thwift-java", rawr x3
        "stitch/stitch-cowe", nyaa~~
        "stowage/cwients/manhattan", /(^•ω•^)
        "utiw/utiw-cowe:scawa", rawr
    ],
)
