scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/io/gwpc:gwpc-netty", ( ͡o ω ͡o )
        "3wdpawty/jvm/io/netty:netty4-tcnative-bowingssw-static", UwU
        "3wdpawty/jvm/io/opiw:tensowfwow-sewving-cwient", rawr x3
        "3wdpawty/jvm/javax/inject:javax.inject", rawr
        "3wdpawty/jvm/twiton/infewence:twiton-gwpc", σωσ
        "finagwe-intewnaw/finagwe-gwpc/swc/main/scawa", σωσ
        "finagwe-intewnaw/finagwe-gwpc/swc/test/java", >_<
        "finagwe-intewnaw/finagwe-gwpc/swc/test/pwoto", :3
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", (U ﹏ U)
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/cwient", -.-
        "finagwe/finagwe-http/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "finatwa-intewnaw/mtws/swc/main/scawa", (⑅˘꒳˘)
        "finatwa/inject/inject-cowe/swc/main/scawa/com/twittew/inject", (U ᵕ U❁)
        "mw-sewving/scawa:kfsewving-tfsewving-convewtew", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", ^^;;
        "stitch/stitch-cowe", >_<
    ], mya
    e-expowts = [
        "3wdpawty/jvm/twiton/infewence:twiton-gwpc", mya
        "finagwe/finagwe-http/swc/main/scawa", 😳
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", XD
        "stitch/stitch-cowe", :3
    ], 😳😳😳
)
