scala_library(
    sources = ["*.scala"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "src/scala/com/X/scalding_internal/multiformat/format",
        "src/scala/com/X/simclusters_v2/common",
        "src/thrift/com/X/hermit/candidate:hermit-candidate-scala",
        "src/thrift/com/X/ml/api:embedding-scala",
        "src/thrift/com/X/recos/entities:entities-thrift-scala",
        "src/thrift/com/X/simclusters_v2:simclusters_v2-thrift-scala",
    ],
)
