scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = ["bazel-compatible"],
    dependencies = [
        "user-signal-service/server/src/main/scala/com/X/usersignalservice/base",
        "user-signal-service/server/src/main/scala/com/X/usersignalservice/signals",
        "user-signal-service/thrift/src/main/thrift:thrift-scala",
    ],
)
