scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "3rdparty/src/jvm/com/twittelonr/storelonhaus:corelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/felonaturelon_hydrator",
        "src/thrift/com/twittelonr/timelonlinelons/imprelonssion_storelon:thrift-scala",
        "stitch/stitch-corelon",
    ],
    elonxports = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "3rdparty/src/jvm/com/twittelonr/storelonhaus:corelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/felonaturelon_hydrator",
        "src/thrift/com/twittelonr/timelonlinelons/imprelonssion_storelon:thrift-scala",
        "stitch/stitch-corelon",
    ],
)
