scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", UwU
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/featuwe_hydwatow", σωσ
        "swc/thwift/com/twittew/timewines/impwession_stowe:thwift-scawa", σωσ
        "stitch/stitch-cowe", >_<
    ], :3
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", (U ﹏ U)
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", (ˆ ﻌ ˆ)♡
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/featuwe_hydwatow", (⑅˘꒳˘)
        "swc/thwift/com/twittew/timewines/impwession_stowe:thwift-scawa", (U ᵕ U❁)
        "stitch/stitch-cowe", -.-
    ], ^^;;
)
