scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon/datareloncord",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon/felonaturelonmap",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon/felonaturelonstorelonv1",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon/felonaturelonstorelonv1/felonaturelonvaluelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/felonaturelon_hydrator",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon/pipelonlinelon_failurelon",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/lib/onlinelon",
    ],
    elonxports = [
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon/felonaturelonmap",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon/felonaturelonstorelonv1",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/felonaturelon/felonaturelonstorelonv1/felonaturelonvaluelon",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/functional_componelonnt/felonaturelon_hydrator",
        "product-mixelonr/corelon/src/main/scala/com/twittelonr/product_mixelonr/corelon/pipelonlinelon/pipelonlinelon_failurelon",
        "src/scala/com/twittelonr/ml/felonaturelonstorelon/lib/onlinelon",
    ],
)
