scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "content-recommender/server/src/main/scala/com/twitter/contentrecommender:representation-manager-deps",
        "frigate/frigate-common/src/main/scala/com/twitter/frigate/common/util",
        "hermit/hermit-core/src/main/scala/com/twitter/hermit/store/common",
        "representation-manager/server/src/main/scala/com/twitter/representation_manager/common",
        "src/scala/com/twitter/simclusters_v2/stores",
        "src/scala/com/twitter/simclusters_v2/summingbird/stores",
        "src/thrift/com/twitter/simclusters_v2:simclusters_v2-thrift-scala",
        "storage/clients/manhattan/client/src/main/scala",
        "tweetypie/src/scala/com/twitter/tweetypie/util",
    ],
)
