scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", UwU
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/cowow", rawr x3
        "swc/thwift/com/twittew/timewines/wendew:thwift-scawa", rawr
    ],
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/mawshawwing/wesponse/uwt/cowow", σωσ
        "swc/thwift/com/twittew/timewines/wendew:thwift-scawa", >_<
    ],
)
