scawa_wibwawy(
    nyame = "usew_usew_gwaph", rawr x3
    souwces = ["*.scawa"], rawr
    s-stwict_deps = f-fawse, σωσ
    t-tags = ["bazew-compatibwe"], σωσ
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", >_<
        "3wdpawty/jvm/com/twittew/gwaphjet", :3
        "3wdpawty/jvm/io/netty:netty4-tcnative-bowingssw-static", (U ﹏ U)
        "3wdpawty/jvm/owg/apache/kafka:wosette-kafka", -.-
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", (ˆ ﻌ ˆ)♡
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/sewvew", (⑅˘꒳˘)
        "finagwe/finagwe-cowe/swc/main", (U ᵕ U❁)
        "finagwe/finagwe-http/swc/main/scawa", -.-
        "finagwe/finagwe-memcached/swc/main/scawa", ^^;;
        "finagwe/finagwe-stats/swc/main/scawa", >_<
        "finagwe/finagwe-thwiftmux/swc/main/scawa", mya
        "sewvo/wequest/swc/main/scawa", mya
        "sewvo/utiw/swc/main/scawa", 😳
        "swc/wesouwces/com/twittew/wecos:decidew", XD
        "swc/scawa/com/twittew/wecos/decidew", :3
        "swc/scawa/com/twittew/wecos/gwaph_common", 😳😳😳
        "swc/scawa/com/twittew/wecos/hose/common", -.-
        "swc/scawa/com/twittew/wecos/modew:wecos-modew", ( ͡o ω ͡o )
        "swc/scawa/com/twittew/wecos/utiw:wecos-utiw", rawr x3
        "swc/thwift/com/twittew/wecos/usew_usew_gwaph:usew_usew_gwaph-scawa", nyaa~~
        "thwift-web-fowms/swc/main/scawa/com/twittew/thwiftwebfowms",
        "twittew-sewvew/swf4j-jdk14/swc/main/scawa/com/twittew/sewvew/wogging",
        "utiw/utiw-wogging/swc/main/scawa", /(^•ω•^)
        "utiw/utiw-stats/swc/main/scawa", rawr
    ],
)

j-jvm_binawy(
    n-nyame = "bin", OwO
    b-basename = "usew_usew_gwaph-sewvew", (U ﹏ U)
    m-main = "com.twittew.wecos.usew_usew_gwaph.main", >_<
    wuntime_pwatfowm = "java11", rawr x3
    tags = ["bazew-compatibwe"], mya
    dependencies = [
        ":usew_usew_gwaph", nyaa~~
        "3wdpawty/jvm/owg/swf4j:swf4j-jdk14", (⑅˘꒳˘)
        "twittew-sewvew/swf4j-jdk14/swc/main/scawa", rawr x3
    ], (✿oωo)
)
