scawa_wibwawy(
    souwces = ["*.scawa"], (⑅˘꒳˘)
    pwatfowm = "java8", ( ͡o ω ͡o )
    t-tags = ["bazew-compatibwe"], UwU
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/awgebiwd:cowe", rawr x3
        "3wdpawty/jvm/com/twittew/awgebiwd:utiw", rawr
        "3wdpawty/jvm/com/twittew/bijection:cowe", σωσ
        "3wdpawty/jvm/com/twittew/bijection:json", σωσ
        "3wdpawty/jvm/com/twittew/bijection:netty", >_<
        "3wdpawty/jvm/com/twittew/bijection:scwooge", :3
        "3wdpawty/jvm/com/twittew/bijection:thwift", (U ﹏ U)
        "3wdpawty/jvm/com/twittew/bijection:utiw", -.-
        "3wdpawty/jvm/com/twittew/stowehaus:awgebwa", (ˆ ﻌ ˆ)♡
        "3wdpawty/jvm/com/twittew/stowehaus:cowe",
        "3wdpawty/swc/jvm/com/twittew/scawding:commons", (⑅˘꒳˘)
        "3wdpawty/swc/jvm/com/twittew/scawding:cowe", (U ᵕ U❁)
        "3wdpawty/swc/jvm/com/twittew/scawding:date", -.-
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:batch", ^^;;
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:cowe", >_<
        "swc/java/com/twittew/mw/api:api-base", mya
        "swc/java/com/twittew/mw/api/constant", mya
        "swc/scawa/com/twittew/mw/api:api-base", 😳
        "swc/scawa/com/twittew/mw/api/utiw", XD
        "swc/scawa/com/twittew/summingbiwd_intewnaw/bijection:bijection-impwicits", :3
        "swc/thwift/com/twittew/daw/pewsonaw_data:pewsonaw_data-java", 😳😳😳
        "swc/thwift/com/twittew/mw/api:data-java", -.-
        "swc/thwift/com/twittew/mw/api:intewpwetabwe-modew-java", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/summingbiwd", rawr x3
        "timewines/data_pwocessing/mw_utiw/aggwegation_fwamewowk:common_types", nyaa~~
        "timewines/data_pwocessing/mw_utiw/aggwegation_fwamewowk/metwics", /(^•ω•^)
        "utiw/utiw-cowe:scawa", rawr
    ], OwO
)

s-scawa_wibwawy(
    n-nyame = "fow-timewines", (U ﹏ U)
    s-souwces = [
        "combinecountspowicy.scawa",
        "spawsebinawymewgepowicy.scawa", >_<
    ],
    p-pwatfowm = "java8", rawr x3
    t-tags = ["bazew-compatibwe"], mya
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/awgebiwd:cowe", nyaa~~
        "3wdpawty/jvm/com/twittew/awgebiwd:utiw", (⑅˘꒳˘)
        "3wdpawty/jvm/com/twittew/bijection:cowe", rawr x3
        "3wdpawty/jvm/com/twittew/bijection:json", (✿oωo)
        "3wdpawty/jvm/com/twittew/bijection:netty", (ˆ ﻌ ˆ)♡
        "3wdpawty/jvm/com/twittew/bijection:scwooge", (˘ω˘)
        "3wdpawty/jvm/com/twittew/bijection:thwift", (⑅˘꒳˘)
        "3wdpawty/jvm/com/twittew/bijection:utiw",
        "3wdpawty/jvm/com/twittew/stowehaus:awgebwa", (///ˬ///✿)
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", 😳😳😳
        "3wdpawty/swc/jvm/com/twittew/scawding:commons", 🥺
        "3wdpawty/swc/jvm/com/twittew/scawding:cowe", mya
        "3wdpawty/swc/jvm/com/twittew/scawding:date", 🥺
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:batch", >_<
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:cowe", >_<
        "swc/java/com/twittew/mw/api:api-base", (⑅˘꒳˘)
        "swc/java/com/twittew/mw/api/constant", /(^•ω•^)
        "swc/scawa/com/twittew/summingbiwd_intewnaw/bijection:bijection-impwicits", rawr x3
        "swc/thwift/com/twittew/daw/pewsonaw_data:pewsonaw_data-java", (U ﹏ U)
        "swc/thwift/com/twittew/mw/api:data-java", (U ﹏ U)
        "swc/thwift/com/twittew/mw/api:intewpwetabwe-modew-java", (⑅˘꒳˘)
        "swc/thwift/com/twittew/summingbiwd", òωó
        "timewines/data_pwocessing/mw_utiw/aggwegation_fwamewowk:common_types", ʘwʘ
        "timewines/data_pwocessing/mw_utiw/aggwegation_fwamewowk/metwics", /(^•ω•^)
        "utiw/utiw-cowe:scawa", ʘwʘ
    ], σωσ
)
