scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/inject:guice",
        "configapi/configapi-core",
        "configapi/configapi-decider",
        "configapi/configapi-featureswitches:v2",
        "follow-recommendations-service/server/src/main/scala/com/twitter/follow_recommendations/configapi/deciders",
        "follow-recommendations-service/server/src/main/scala/com/twitter/follow_recommendations/models",
    ],
)
