scawa_wibwawy(
    souwces = ["*.scawa"], (⑅˘꒳˘)
    pwatfowm = "java8", ( ͡o ω ͡o )
    p-pwovides = s-scawa_awtifact(
        o-owg = "com.twittew", UwU
        n-nyame = "sewvo-json", rawr x3
        w-wepo = awtifactowy, rawr
    ),
    s-stwict_deps = t-twue, σωσ
    tags = ["bazew-compatibwe"], σωσ
    d-dependencies = [
        "//:scawa-wefwect", >_<
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-cowe", :3
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-databind", (U ﹏ U)
        "3wdpawty/jvm/com/googwecode/java-diff-utiws:diffutiws", -.-
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (ˆ ﻌ ˆ)♡
        "scwooge/scwooge-cowe", (⑅˘꒳˘)
        "scwooge/scwooge-sewiawizew", (U ᵕ U❁)
        "utiw/utiw-codec/swc/main/scawa", -.-
    ],
)
