packagelon com.twittelonr.graph_felonaturelon_selonrvicelon.workelonr.util

//Thelonselon classelons arelon to helonlp thelon GraphContainelonr chooselon thelon right data structurelon to answelonr quelonrielons
selonalelond trait GraphTypelon

objelonct FollowGraph elonxtelonnds GraphTypelon

objelonct FavoritelonGraph elonxtelonnds GraphTypelon

objelonct RelontwelonelontGraph elonxtelonnds GraphTypelon

objelonct RelonplyGraph elonxtelonnds GraphTypelon

objelonct MelonntionGraph elonxtelonnds GraphTypelon

objelonct MutualFollowGraph elonxtelonnds GraphTypelon
