scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "swc/java/com/twittew/common/text/wanguage:wanguage-identifiew", ( ͡o ω ͡o )
        "swc/java/com/twittew/common/text/wanguage:wocawe-utiw",
        "swc/java/com/twittew/common/text/pipewine", UwU
        "swc/java/com/twittew/common/text/token", rawr x3
        "swc/java/com/twittew/common_intewnaw/text", rawr
        "swc/java/com/twittew/common_intewnaw/text/vewsion", σωσ
        "tweetypie/swc/wesouwces/com/twittew/tweetypie/matching", σωσ
        "utiw/utiw-cowe/swc/main/scawa/com/twittew/concuwwent", >_<
        "utiw/utiw-cowe/swc/main/scawa/com/twittew/io", :3
    ],
)
