scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", (U ᵕ U❁)
        "finatwa/inject/inject-thwift-cwient", (⑅˘꒳˘)
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/common", ( ͡o ω ͡o )
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", UwU
        "gwaph-featuwe-sewvice/swc/main/thwift/com/twittew/gwaph_featuwe_sewvice:gwaph_featuwe_sewvice_thwift-scawa", rawr x3
        "stitch/stitch-cowe", rawr
    ],
)
