scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = [
        "bazel-compatible",
    ],
    dependencies = [
        "stitch/stitch-storehaus",
        "strato/src/main/scala/com/twitter/strato/fed",
        "topic-social-proof/server/src/main/scala/com/twitter/tsp/service",
        "topic-social-proof/server/src/main/thrift:thrift-scala",
    ],
)
