scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "image-fetchew-sewvice/thwift/swc/main/thwift:thwift-scawa", ( ͡o ω ͡o )
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", UwU
        "mediasewvices/mediainfo-sewvew/thwift/swc/main/thwift:thwift-scawa", rawr x3
        "tweetypie/sewvo/utiw", rawr
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:media-entity-scawa", σωσ
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa",
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", σωσ
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/backends", >_<
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/cowe", :3
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/media", (U ﹏ U)
        "usew-image-sewvice/thwift/swc/main/thwift:thwift-scawa", -.-
        "utiw/utiw-swf4j-api/swc/main/scawa/com/twittew/utiw/wogging", (ˆ ﻌ ˆ)♡
    ], (⑅˘꒳˘)
)
