scala_library(
    platform = "java11",
    strict_deps = False,
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/org/apache/thrift:libthrift",
        "finatra-internal/messaging/kafka/src/main/scala",
        "servo/repo/src/main/scala",
        "src/thrift/com/X/recos:recos-injector-scala",
        "src/thrift/com/X/recos:recos-internal-scala",
    ],
)
