scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/swc/java/com/twittew/wogpipewine/cwient:wogpipewine-event-pubwishew-thin", ( ͡o ω ͡o )
        "configapi/configapi-cowe", UwU
        "decidew/swc/main/scawa", rawr x3
        "sewvo/utiw/swc/main/scawa", rawr
        "swc/thwift/com/twittew/seawch/common:constants-scawa", σωσ
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", σωσ
        "swc/thwift/com/twittew/spam/wtf:safety-wesuwt-scawa", >_<
        "swc/thwift/com/twittew/spam/wtf:tweet-wtf-event-scawa", :3
        "stitch/stitch-cowe", (U ﹏ U)
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats", -.-
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions",
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions/convewtew/scawa", (ˆ ﻌ ˆ)♡
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/stitch", (⑅˘꒳˘)
        "visibiwity/common/swc/main/thwift/com/twittew/visibiwity:action-scawa", (U ᵕ U❁)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", ^^;;
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/modews", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes", mya
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/utiw", mya
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/wogging:vf-wogging-scawa", 😳
    ], XD
)
