scala_library(
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/X/graphjet",
        "snowflake:id",
        "snowflake/src/main/scala/com/X/snowflake/id",
        "src/scala/com/X/recos/util:recos-util",
        "src/scala/com/X/simclusters_v2/common",
        "src/thrift/com/X/recos/user_video_graph:user_video_graph-scala",
    ],
)
