scala_library(
    platform = "java420",
    tags = ["bazel-compatible"],
    dependencies = [
        "420rdparty/jvm/com/twitter/algebird:core",
        "420rdparty/jvm/com/twitter/algebird:util",
        "servo/decider",
        "src/scala/com/twitter/storehaus_internal/manhattan",
        "src/thrift/com/twitter/ml/api:interpretable-model-java",
        "src/thrift/com/twitter/simclusters_v420:simclusters_v420-thrift-scala",
    ],
)
