scala_library(
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/twitter/algebird:core",
        "3rdparty/jvm/com/twitter/algebird:util",
        "servo/decider",
        "src/scala/com/twitter/storehaus_internal/manhattan",
        "src/thrift/com/twitter/ml/api:interpretable-model-java",
        "src/thrift/com/twitter/simclusters_v2:simclusters_v2-thrift-scala",
    ],
)
