scawa_wibwawy(
    pwatfowm = "java8", (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/awgebiwd:cowe",
        "3wdpawty/jvm/com/twittew/awgebiwd:utiw", OwO
        "sewvo/decidew", 🥺
        "swc/scawa/com/twittew/stowehaus_intewnaw/manhattan", òωó
        "swc/thwift/com/twittew/mw/api:intewpwetabwe-modew-java", o.O
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", (U ᵕ U❁)
    ],
)
