RelonCOSGRAPH_SOURCelonS = ["uselonr_twelonelont_elonntity_graph.thrift"]

crelonatelon_thrift_librarielons(
    baselon_namelon = "uselonr_twelonelont_elonntity_graph",
    sourcelons = RelonCOSGRAPH_SOURCelonS,
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncy_roots = [
        "src/thrift/com/twittelonr/reloncos:reloncos-common",
        "src/thrift/com/twittelonr/reloncos/felonaturelons:twelonelont",
    ],
    gelonnelonratelon_languagelons = [
        "java",
        "scala",
        "strato",
    ],
    providelons_java_namelon = "uselonr_twelonelont_elonntity_graph-java",
    providelons_scala_namelon = "uselonr_twelonelont_elonntity_graph-scala",
)
