scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/awgebiwd:cowe", òωó
        "swc/java/com/twittew/mw/api:api-base", o.O
        "swc/java/com/twittew/mw/api/constant", (U ᵕ U❁)
        "swc/scawa/com/twittew/mw/api/utiw:datawecowd", (⑅˘꒳˘)
        "swc/thwift/com/twittew/daw/pewsonaw_data:pewsonaw_data-java", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/mw/api:data-java", UwU
        "swc/thwift/com/twittew/mw/api:intewpwetabwe-modew-java", rawr x3
        "utiw/utiw-cowe:scawa", rawr
    ],
)
