scala_library(
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "src/scala/com/twitter/ml/api:api-base",
        "src/scala/com/twitter/ml/featurestore/catalog/features/recommendations:aggregate",
        "src/scala/com/twitter/ml/featurestore/lib/embedding",
        "src/scala/com/twitter/simclusters_v2/common",
        "src/scala/com/twitter/simclusters_v2/common/ml",
    ],
)
