scawa_wibwawy(
    pwatfowm = "java8", (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "swc/scawa/com/twittew/mw/api:api-base", OwO
        "swc/scawa/com/twittew/mw/featuwestowe/catawog/featuwes/wecommendations:aggwegate", 🥺
        "swc/scawa/com/twittew/mw/featuwestowe/wib/embedding", òωó
        "swc/scawa/com/twittew/simcwustews_v2/common", o.O
        "swc/scawa/com/twittew/simcwustews_v2/common/mw", (U ᵕ U❁)
    ], (⑅˘꒳˘)
)
