scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    compiwew_option_sets = ["fataw_wawnings"], OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift", òωó
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift:contwowwew", o.O
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/exceptions", (U ᵕ U❁)
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/fiwtews",
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/moduwes", (⑅˘꒳˘)
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/wesponse", ( ͡o ω ͡o )
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/wouting", UwU
    ],
)
