cweate_thwift_wibwawies(
    base_name = "compiwed", òωó
    souwces = ["**/*.thwift"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    stwict_deps = t-twue, (⑅˘꒳˘)
    t-tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependency_woots = [
        "mediasewvices/commons/swc/main/thwift", UwU
        "tweetypie/sewvo/wepo/swc/main/thwift", rawr x3
        "swc/thwift/com/twittew/context:featuwe-context",
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts", rawr
        "swc/thwift/com/twittew/expandodo:capi", σωσ
        "swc/thwift/com/twittew/expandodo:onwy", σωσ
        "swc/thwift/com/twittew/geoduck", >_<
        "swc/thwift/com/twittew/gizmoduck:thwift", :3
        "swc/thwift/com/twittew/gizmoduck:usew-thwift", (U ﹏ U)
        "swc/thwift/com/twittew/sewvo:sewvo-exception", -.-
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:audit", (ˆ ﻌ ˆ)♡
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:dewete_wocation_data", (⑅˘꒳˘)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:media-entity", (U ᵕ U❁)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice", -.-
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:stowed-tweet-info", ^^;;
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet", >_<
    ], mya
    g-genewate_wanguages = [
        "java", mya
        "scawa",
    ], 😳
)
