scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "decider/src/main/scala",
        "finagle/finagle-memcached",
        "hermit/hermit-core/src/main/scala/com/X/hermit/store/common",
        "relevance-platform/src/main/scala/com/X/relevance_platform/common/injection",
        "src/scala/com/X/simclusters_v2/common",
        "src/thrift/com/X/simclusters_v2:simclusters_v2-thrift-scala",
    ],
)
