crelonatelon_thrift_librarielons(
    baselon_namelon = "graph_felonaturelon_selonrvicelon_thrift",
    sourcelons = ["*.thrift"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    gelonnelonratelon_languagelons = [
        "java",
        # ruby is addelond duelon to ruby delonpelonndelonelons in timelonlinelons
        "ruby",
        "scala",
        "strato",
    ],
    providelons_java_namelon = "graph_felonaturelon_selonrvicelon_thrift_java",
    providelons_scala_namelon = "graph_felonaturelon_selonrvicelon_thrift_scala",
)
