java_wibwawy(
    souwces = ["*.java"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/code/findbugs:jsw305", o.O
        "3wdpawty/jvm/com/googwe/guava", (U ᵕ U❁)
        "3wdpawty/jvm/com/googwe/inject:guice", (⑅˘꒳˘)
        "3wdpawty/jvm/commons-wang",
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ( ͡o ω ͡o )
        "mediasewvices/commons/swc/main/thwift:thwift-java", UwU
        "swc/java/com/twittew/common/text/wanguage:wocawe-utiw", rawr x3
        "swc/java/com/twittew/common_intewnaw/text/vewsion", rawr
        "swc/java/com/twittew/seawch/common/debug", σωσ
        "swc/java/com/twittew/seawch/common/metwics", σωσ
        "swc/java/com/twittew/seawch/common/pawtitioning/base", >_<
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", :3
        "swc/java/com/twittew/seawch/common/wewevance:entities_and_fiwtews", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/utiw/text", -.-
        "swc/java/com/twittew/seawch/ingestew/modew", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/ingestew/pipewine/utiw", (⑅˘꒳˘)
        "swc/thwift/com/twittew/datapwoducts:enwichments_pwofiwegeo-java", (U ᵕ U❁)
        "swc/thwift/com/twittew/eschewbiwd:tweet-annotation-java", -.-
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-java", ^^;;
        "swc/thwift/com/twittew/seawch/common/debug:debug-java", >_<
        "swc/thwift/com/twittew/sewvice/spidewduck/gen:metadata-stowe-java", mya
        "swc/thwift/com/twittew/tweetypie:events-java", mya
        "swc/thwift/com/twittew/tweetypie:tweet-java", 😳
        "tweetypie/swc/scawa/com/twittew/tweetypie/tweettext", XD
    ],
)
