jvm_binawy(
    name = "bin", rawr
    basename = "usew-signaw-sewvice", σωσ
    main = "com.twittew.usewsignawsewvice.usewsignawsewvicestwatofedsewvewmain", σωσ
    w-wuntime_pwatfowm = "java11", >_<
    t-tags = ["bazew-compatibwe"], :3
    d-dependencies = [
        "3wdpawty/jvm/ch/qos/wogback:wogback-cwassic", (U ﹏ U)
        "wogwens/wogwens-wogback/swc/main/scawa/com/twittew/wogwens/wogback", -.-
        "stwato/swc/main/scawa/com/twittew/stwato/wogging/wogback", (ˆ ﻌ ˆ)♡
        "usew-signaw-sewvice/sewvew/swc/main/wesouwces", (⑅˘꒳˘)
        "usew-signaw-sewvice/sewvew/swc/main/scawa/com/twittew/usewsignawsewvice", (U ᵕ U❁)
    ],
)

#  a-auwowa w-wowkfwows buiwd p-phase convention w-wequiwes a j-jvm_app nyamed with ${pwoject-name}-app
jvm_app(
    nyame = "usew-signaw-sewvice-app", -.-
    awchive = "zip", ^^;;
    binawy = ":bin", >_<
)
