scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", UwU
        "swc/scawa/com/twittew/mw/api/utiw:datawecowd", rawr x3
        "swc/scawa/com/twittew/mw/featuwestowe/wib/data", rawr
        "swc/scawa/com/twittew/mw/featuwestowe/wib/dynamic", σωσ
    ],
    e-expowts = [
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe", σωσ
        "swc/scawa/com/twittew/mw/api/utiw:datawecowd", >_<
        "swc/scawa/com/twittew/mw/featuwestowe/wib/data", :3
        "swc/scawa/com/twittew/mw/featuwestowe/wib/dynamic", (U ﹏ U)
    ],
)
