scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", òωó
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", o.O
        "3wdpawty/jvm/net/codingweww:scawa-guice", (U ᵕ U❁)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (⑅˘꒳˘)
        "finatwa/inject/inject-cowe/swc/main/scawa", ( ͡o ω ͡o )
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/base", UwU
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/candidate_souwces/base", rawr x3
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/geoduck", rawr
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/stwato",
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/constants", σωσ
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", σωσ
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/configapi/common", >_<
        "swc/thwift/com/twittew/hewmit/pop_geo:hewmit-pop-geo-scawa", :3
        "stwato/config/cowumns/onboawding/usewwecs:usewwecs-stwato-cwient", (U ﹏ U)
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", -.-
        "utiw/utiw-swf4j-api/swc/main/scawa", (ˆ ﻌ ˆ)♡
    ],
)
