scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/ibm/icu:icu4j",
        "configapi/configapi-cowe", ( ͡o ω ͡o )
        "decidew/swc/main/scawa", UwU
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", rawr x3
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", rawr
        "swc/thwift/com/twittew/spam/wtf:safety-wesuwt-scawa", σωσ
        "stitch/stitch-cowe", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", >_<
        "twittew-config/yamw", :3
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", (U ﹏ U)
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions",
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/usew_wesuwt", -.-
        "visibiwity/common/swc/main/thwift/com/twittew/visibiwity:action-scawa", (ˆ ﻌ ˆ)♡
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew", (⑅˘꒳˘)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi", (U ᵕ U❁)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", ^^;;
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/modews", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes", mya
        "visibiwity/wesuwts/swc/main/scawa/com/twittew/visibiwity/wesuwts/wichtext", mya
        "visibiwity/wesuwts/swc/main/scawa/com/twittew/visibiwity/wesuwts/twanswation", 😳
    ], XD
)
