targelont(
    namelon = "ingelonstelonr-lib",
    delonpelonndelonncielons = [
        "src/java/com/twittelonr/selonarch/common/convelonrtelonr/elonarlybird",
        "src/java/com/twittelonr/selonarch/ingelonstelonr/modelonl",
        "src/java/com/twittelonr/selonarch/ingelonstelonr/pipelonlinelon/app",
        "src/java/com/twittelonr/selonarch/ingelonstelonr/pipelonlinelon/twittelonr",
        "src/java/com/twittelonr/selonarch/ingelonstelonr/pipelonlinelon/twittelonr/elonngagelonmelonnts",
        "src/java/com/twittelonr/selonarch/ingelonstelonr/pipelonlinelon/twittelonr/filtelonrs",
        "src/java/com/twittelonr/selonarch/ingelonstelonr/pipelonlinelon/twittelonr/kafka",
        "src/java/com/twittelonr/selonarch/ingelonstelonr/pipelonlinelon/twittelonr/thriftparselon",
        "src/java/com/twittelonr/selonarch/ingelonstelonr/pipelonlinelon/twittelonr/uselonrupdatelons",
        "src/java/com/twittelonr/selonarch/ingelonstelonr/pipelonlinelon/util",
        "src/java/com/twittelonr/selonarch/ingelonstelonr/util/jndi",
    ],
)

jvm_binary(
    namelon = "ingelonstelonr-binary",
    baselonnamelon = "ingelonstelonr",
    main = "com.twittelonr.selonarch.ingelonstelonr.pipelonlinelon.app.IngelonstelonrPipelonlinelonApplication\\$Main",
    platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
    ],
    delonpelonndelonncielons = [
        ":ingelonstelonr-lib",
        "src/java/com/twittelonr/selonarch/common/logging:selonarch-log4j",
    ],
)
