scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/org/mapdb",
        "ann/src/main/java/com/twittelonr/ann/faiss",
        "ann/src/main/scala/com/twittelonr/ann/common",
        "ann/src/main/scala/com/twittelonr/ann/selonrialization",
        "ann/src/main/thrift/com/twittelonr/ann/common:ann-common-scala",
        "melondiaselonrvicelons/commons/src/main/scala:futurelontrackelonr",
        "src/java/com/twittelonr/common_intelonrnal/hadoop",
        "src/java/com/twittelonr/selonarch/common/filelon",
        "src/scala/com/twittelonr/ml/api/elonmbelondding",
    ],
    elonxports = [
        "ann/src/main/scala/com/twittelonr/ann/common",
        "src/java/com/twittelonr/common_intelonrnal/hadoop",
        "src/java/com/twittelonr/selonarch/common/filelon",
        "src/scala/com/twittelonr/ml/api/elonmbelondding",
    ],
)
