scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/bijection:scwooge", OwO
        "3wdpawty/jvm/javax/inject:javax.inject", 🥺
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", òωó
        "discovewy-ds/swc/main/thwift/com/twittew/dds/jobs/wepeated_pwofiwe_visits:pwofiwe_visit-scawa", o.O
        "fwock-cwient/swc/main/thwift:thwift-scawa", (U ᵕ U❁)
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/stowe/stwato", (⑅˘꒳˘)
        "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/pwedicate/sociawgwaph", ( ͡o ω ͡o )
        "swc/scawa/com/twittew/scawding_intewnaw/job", UwU
        "swc/scawa/com/twittew/simcwustews_v2/common", rawr x3
        "swc/scawa/com/twittew/stowehaus_intewnaw/manhattan", rawr
        "swc/scawa/com/twittew/stowehaus_intewnaw/manhattan/config", σωσ
        "swc/scawa/com/twittew/stowehaus_intewnaw/manhattan2", σωσ
        "swc/scawa/com/twittew/stowehaus_intewnaw/offwine", >_<
        "swc/scawa/com/twittew/stowehaus_intewnaw/utiw", :3
        "swc/scawa/com/twittew/twistwy/common", (U ﹏ U)
        "swc/thwift/com/twittew/expewiments/genewaw_metwics:genewaw_metwics-scawa", -.-
        "swc/thwift/com/twittew/fwigate/data_pipewine:fwigate-usew-histowy-thwift-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/onboawding/wewevance/tweet_engagement:tweet_engagement-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa",
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/twaffic_attwibution:twaffic_attwibution-scawa", -.-
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", ^^;;
        "usew-signaw-sewvice/sewvew/swc/main/scawa/com/twittew/usewsignawsewvice/base", >_<
        "usew-signaw-sewvice/sewvew/swc/main/scawa/com/twittew/usewsignawsewvice/signaws/common",
        "usew-signaw-sewvice/thwift/swc/main/thwift:thwift-scawa", mya
        "utiw/utiw-cowe:utiw-cowe-utiw", mya
        "utiw/utiw-cowe/swc/main/java/com/twittew/utiw", 😳
        "utiw/utiw-stats/swc/main/scawa/com/twittew/finagwe/stats", XD
    ],
)
