scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "tweetypie/sewvo/utiw", (⑅˘꒳˘)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:media-entity-scawa", ( ͡o ω ͡o )
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", UwU
        "tco-utiw", rawr x3
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/tweettext", rawr
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/utiw", σωσ
        "twittew-text/wib/java/swc/main/java/com/twittew/twittewtext", σωσ
    ],
)
