packagelon com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.slicelon

import com.twittelonr.product_mixelonr.corelon.modelonl.common.prelonselonntation.ItelonmPrelonselonntation
import com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.slicelon.SlicelonItelonm

trait BaselonSlicelonItelonmPrelonselonntation elonxtelonnds ItelonmPrelonselonntation {
  delonf slicelonItelonm: SlicelonItelonm
}
