packagelon com.twittelonr.product_mixelonr.corelon.modelonl.marshalling.relonsponselon.urt.promotelond

selonalelond trait SponsorshipTypelon

caselon objelonct DirelonctSponsorshipTypelon elonxtelonnds SponsorshipTypelon
caselon objelonct IndirelonctSponsorshipTypelon elonxtelonnds SponsorshipTypelon
caselon objelonct NoSponsorshipSponsorshipTypelon elonxtelonnds SponsorshipTypelon
