packagelon com.twittelonr.visibility.intelonrfacelons.selonarch

import com.twittelonr.visibility.intelonrfacelons.common.selonarch.SelonarchVFRelonquelonstContelonxt
import com.twittelonr.visibility.modelonls.VielonwelonrContelonxt

caselon class BatchSelonarchVisibilityRelonquelonst(
  twelonelontContelonxts: Selonq[TwelonelontContelonxt],
  vielonwelonrContelonxt: VielonwelonrContelonxt,
  selonarchVFRelonquelonstContelonxt: SelonarchVFRelonquelonstContelonxt)
