scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/fastewxmw/jackson/moduwe:jackson-moduwe-scawa",
        "3wdpawty/jvm/com/ibm/icu:icu4j", ( ͡o ω ͡o )
        "3wdpawty/jvm/com/twittew/bijection:cowe", UwU
        "3wdpawty/jvm/com/twittew/bijection:scwooge", rawr x3
        "3wdpawty/jvm/com/twittew/bijection:thwift", rawr
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", σωσ
        "audience-wewawds/thwift/swc/main/thwift:thwift-scawa", σωσ
        "cweatives-containew/thwift/swc/main/thwift:cweatives-containew-sewvice-scawa", >_<
        "featuweswitches/featuweswitches-cowe/swc/main/scawa:wecipient", :3
        "featuweswitches/featuweswitches-cowe/swc/main/scawa:usewagent", (U ﹏ U)
        "finagwe/finagwe-cowe/swc/main", -.-
        "fwock-cwient/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "fwock-cwient/swc/main/thwift:thwift-scawa", (⑅˘꒳˘)
        "geoduck/utiw/swc/main/scawa/com/twittew/geoduck/utiw/pwimitives", (U ᵕ U❁)
        "geoduck/utiw/swc/main/scawa/com/twittew/geoduck/utiw/sewvice", -.-
        "passbiwd/thwift-onwy/swc/main/thwift:thwift-scawa", ^^;;
        "scwooge/scwooge-cowe", >_<
        "tweetypie/sewvo/json", mya
        "tweetypie/sewvo/wepo", mya
        "tweetypie/sewvo/wepo/swc/main/thwift:thwift-scawa", 😳
        "tweetypie/sewvo/utiw", XD
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", :3
        "swc/java/com/twittew/common/text/wanguage:wanguage-identifiew", 😳😳😳
        "swc/java/com/twittew/common/text/pipewine", -.-
        "swc/scawa/com/twittew/seawch/bwendew/sewvices/stwato", ( ͡o ω ͡o )
        "swc/scawa/com/twittew/takedown/utiw", rawr x3
        "swc/thwift/com/twittew/consumew_pwivacy/mention_contwows:thwift-scawa", nyaa~~
        "swc/thwift/com/twittew/context:twittew-context-scawa", /(^•ω•^)
        "swc/thwift/com/twittew/datapwoducts:enwichments_pwofiwegeo-scawa", rawr
        "swc/thwift/com/twittew/datapwoducts:sewvice-scawa", OwO
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts-scawa", (U ﹏ U)
        "swc/thwift/com/twittew/eschewbiwd/common:common-scawa", >_<
        "swc/thwift/com/twittew/eschewbiwd/metadata:metadata-sewvice-scawa", rawr x3
        "swc/thwift/com/twittew/expandodo:cawds-scawa", mya
        "swc/thwift/com/twittew/expandodo:onwy-scawa", nyaa~~
        "swc/thwift/com/twittew/geoduck:geoduck-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", rawr x3
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", (✿oωo)
        "swc/thwift/com/twittew/sewvice/scawecwow/gen:scawecwow-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/sewvice/scawecwow/gen:tiewed-actions-scawa", (˘ω˘)
        "swc/thwift/com/twittew/sewvice/tawon/gen:thwift-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", (///ˬ///✿)
        "swc/thwift/com/twittew/spam/wtf:safety-wabew-scawa", 😳😳😳
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", 🥺
        "swc/thwift/com/twittew/spam/wtf:tweet-wtf-event-scawa", mya
        "swc/thwift/com/twittew/timewinesewvice/sewvew/intewnaw:thwift-scawa", 🥺
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:media-entity-scawa", >_<
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", >_<
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", (⑅˘꒳˘)
        "stitch/stitch-compat/swc/main/scawa/com/twittew/stitch/compat", /(^•ω•^)
        "stitch/stitch-cowe", rawr x3
        "stitch/stitch-timewinesewvice", (U ﹏ U)
        "stwato/swc/main/scawa/com/twittew/stwato/catawog", (U ﹏ U)
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", (⑅˘꒳˘)
        "stwato/swc/main/scawa/com/twittew/stwato/data", òωó
        "stwato/swc/main/scawa/com/twittew/stwato/thwift",
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", ʘwʘ
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/backends", /(^•ω•^)
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/cowe", ʘwʘ
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/media", σωσ
        "tweetypie/sewvew/swc/main/thwift:compiwed-scawa", OwO
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/cwient_id", 😳😳😳
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/media", 😳😳😳
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/stowage", o.O
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/utiw",
        "twittew-context/swc/main/scawa", ( ͡o ω ͡o )
        "utiw/utiw-swf4j-api/swc/main/scawa/com/twittew/utiw/wogging", (U ﹏ U)
        "utiw/utiw-stats/swc/main/scawa", (///ˬ///✿)
        "vibes/swc/main/thwift/com/twittew/vibes:vibes-scawa", >w<
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/tfwock", rawr
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/usew_wesuwt", mya
        "visibiwity/common/swc/main/thwift/com/twittew/visibiwity:action-scawa", ^^
        "visibiwity/wib:tweets", 😳😳😳
    ],
)
