scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "ann/swc/main/scawa/com/twittew/ann/common", òωó
        "utiw/utiw-wogging", o.O
    ],
)
