scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", òωó
        "configapi/configapi-cowe", o.O
        "configapi/configapi-decidew", (U ᵕ U❁)
    ], (⑅˘꒳˘)
)
