scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/awgebiwd:cowe", òωó
        "3wdpawty/jvm/com/twittew/awgebiwd:utiw", o.O
        "3wdpawty/jvm/com/twittew/stowehaus:awgebwa", (U ᵕ U❁)
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", (⑅˘꒳˘)
        "3wdpawty/swc/jvm/com/twittew/scawding:commons", ( ͡o ω ͡o )
        "3wdpawty/swc/jvm/com/twittew/scawding:cowe", UwU
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:batch", rawr x3
        "3wdpawty/swc/jvm/com/twittew/summingbiwd:cowe", rawr
        "swc/java/com/twittew/mw/api:api-base", σωσ
        "swc/thwift/com/twittew/mw/api:data-java", σωσ
        "swc/thwift/com/twittew/mw/api:intewpwetabwe-modew-java", >_<
        "timewines/data_pwocessing/mw_utiw/aggwegation_fwamewowk:common_types", :3
    ], (U ﹏ U)
)
