scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ( ͡o ω ͡o )
        "abdecidew", UwU
        "cowtex-tweet-annotate/sewvice/swc/main/thwift:thwift-scawa",
        "decidew", rawr x3
        "featuweswitches/featuweswitches-cowe/swc/main/scawa", rawr
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", σωσ
        "finagwe/finagwe-cowe/swc/main", σωσ
        "finagwe/finagwe-memcached/swc/main/scawa", >_<
        "finagwe/finagwe-stats", :3
        "finagwe/finagwe-thwift/swc/main/java", (U ﹏ U)
        "finagwe/finagwe-thwift/swc/main/scawa", -.-
        "finagwe/finagwe-thwiftmux/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "wogwens/wogwens-wogging/swc/main/scawa", (⑅˘꒳˘)
        "mewwin/utiw/swc/main/scawa", (U ᵕ U❁)
        "sewvo/decidew", -.-
        "sewvo/wequest/swc/main/scawa", ^^;;
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", >_<
        "swc/thwift/com/twittew/manhattan:v1-scawa", mya
        "swc/thwift/com/twittew/mewwin:thwift-scawa", mya
        "swc/thwift/com/twittew/wecos/usew_tweet_entity_gwaph:usew_tweet_entity_gwaph-scawa", 😳
        "swc/thwift/com/twittew/seawch:eawwybiwd-scawa", XD
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", :3
        "swc/thwift/com/twittew/timewinewankew:thwift-scawa", 😳😳😳
        "swc/thwift/com/twittew/timewinesewvice:thwift-scawa", -.-
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", rawr x3
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", nyaa~~
        "timewinewankew/sewvew/config", /(^•ω•^)
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/cwients", rawr
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/cwients/content_featuwes_cache", OwO
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/decidew", (U ﹏ U)
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/wecap/modew", >_<
        "timewines:authowization", rawr x3
        "timewines:config", mya
        "timewines:featuwes", nyaa~~
        "timewines:utiw", (⑅˘꒳˘)
        "timewines:visibiwity", rawr x3
        "timewines/swc/main/scawa/com/twittew/timewines/cwients/gizmoduck", (✿oωo)
        "timewines/swc/main/scawa/com/twittew/timewines/cwients/manhattan", (ˆ ﻌ ˆ)♡
        "timewines/swc/main/scawa/com/twittew/timewines/cwients/memcache_common", (˘ω˘)
        "timewines/swc/main/scawa/com/twittew/timewines/cwients/sociawgwaph", (⑅˘꒳˘)
        "timewines/swc/main/scawa/com/twittew/timewines/cwients/stwato/weawgwaph", (///ˬ///✿)
        "timewines/swc/main/scawa/com/twittew/timewines/cwients/tweetypie", 😳😳😳
        "timewines/swc/main/scawa/com/twittew/timewines/config/configapi", 🥺
        "timewines/swc/main/scawa/com/twittew/timewines/utiw", mya
        "timewines/swc/main/scawa/com/twittew/timewines/utiw/wogging", 🥺
        "timewines/swc/main/scawa/com/twittew/timewines/utiw/stats", >_<
        "timewinesewvice/common/swc/main/scawa/com/twittew/timewinesewvice/modew", >_<
        "twittew-sewvew-intewnaw", (⑅˘꒳˘)
        "utiw/utiw-app", /(^•ω•^)
        "utiw/utiw-cowe:utiw-cowe-utiw", rawr x3
        "utiw/utiw-cowe/swc/main/scawa/com/twittew/convewsions", (U ﹏ U)
        "utiw/utiw-stats/swc/main/scawa", (U ﹏ U)
    ], (⑅˘꒳˘)
    expowts = [
        "swc/thwift/com/twittew/wecos/usew_tweet_entity_gwaph:usew_tweet_entity_gwaph-scawa", òωó
    ],
)
