packagelon com.twittelonr.timelonlinelonrankelonr.config

import com.twittelonr.finaglelon.stats.StatsReloncelonivelonr

class StagingUndelonrlyingClielonntConfiguration(flags: TimelonlinelonRankelonrFlags, statsReloncelonivelonr: StatsReloncelonivelonr)
    elonxtelonnds DelonfaultUndelonrlyingClielonntConfiguration(flags, statsReloncelonivelonr)
