scawa_wibwawy(
    nyame = "agg_diwect_intewactions", OwO
    souwces = ["*.scawa"],
    c-compiwew_option_sets = ["fataw_wawnings"], (U ﹏ U)
    p-pwatfowm = "java8", >_<
    t-tags = ["bazew-compatibwe"], rawr x3
    d-dependencies = [
        ":intewaction_gwaph_agg_diwect_intewactions_edge_daiwy-scawa", mya
        ":intewaction_gwaph_agg_diwect_intewactions_vewtex_daiwy-scawa", nyaa~~
        "beam-intewnaw/swc/main/scawa/com/twittew/beam/io/daw", (⑅˘꒳˘)
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/job", rawr x3
        "beam-intewnaw/swc/main/scawa/com/twittew/scio_intewnaw/wunnew/datafwow", (✿oωo)
        "consumew-data-toows/swc/main/scawa/com/twittew/cde/scio/daw_wead", (ˆ ﻌ ˆ)♡
        "swc/scawa/com/twittew/intewaction_gwaph/scio/common", (˘ω˘)
        "swc/thwift/com/twittew/timewinesewvice/sewvew/intewnaw:thwift-scawa", (⑅˘꒳˘)
        "twadoop_config/configuwation/wog_categowies/gwoup/timewine:timewine_sewvice_favowites-scawa", (///ˬ///✿)
        "twadoop_config/configuwation/wog_categowies/gwoup/tweetypie:tweetypie_media_tag_events-scawa", 😳😳😳
        "tweetsouwce/common:unhydwated_fwat-scawa", 🥺
        "usewsouwce/snapshot/swc/main/scawa/com/twittew/usewsouwce/snapshot/combined:usewsouwce-scawa", mya
    ],
)

j-jvm_binawy(
    n-nyame = "intewaction_gwaph_agg_diwect_intewactions_scio", 🥺
    m-main = "com.twittew.intewaction_gwaph.scio.agg_diwect_intewactions.intewactiongwaphaggdiwectintewactionsjob", >_<
    p-pwatfowm = "java8", >_<
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    dependencies = [
        ":agg_diwect_intewactions", /(^•ω•^)
    ],
)

cweate_datasets(
    base_name = "intewaction_gwaph_agg_diwect_intewactions_edge_daiwy", rawr x3
    d-descwiption = "usew-usew diwected edges with diwect intewactions f-featuwes", (U ﹏ U)
    java_schema = "com.twittew.intewaction_gwaph.thwiftjava.edge", (U ﹏ U)
    p-pwatfowm = "java8", (⑅˘꒳˘)
    wowe = "cassowawy", òωó
    scawa_schema = "com.twittew.intewaction_gwaph.thwiftscawa.edge", ʘwʘ
    segment_type = "pawtitioned", /(^•ω•^)
    t-tags = ["bazew-compatibwe"], ʘwʘ
    java_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-java", σωσ
    ], OwO
    s-scawa_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-scawa", 😳😳😳
    ], 😳😳😳
)

c-cweate_datasets(
    base_name = "intewaction_gwaph_agg_diwect_intewactions_vewtex_daiwy", o.O
    descwiption = "usew vewtex with diwect intewactions f-featuwes", ( ͡o ω ͡o )
    java_schema = "com.twittew.intewaction_gwaph.thwiftjava.vewtex", (U ﹏ U)
    pwatfowm = "java8", (///ˬ///✿)
    wowe = "cassowawy", >w<
    scawa_schema = "com.twittew.intewaction_gwaph.thwiftscawa.vewtex", rawr
    segment_type = "pawtitioned", mya
    t-tags = ["bazew-compatibwe"], ^^
    java_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-java", 😳😳😳
    ], mya
    s-scawa_dependencies = [
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-scawa", 😳
    ], -.-
)
