wecosgwaph_souwces = ["usew_video_gwaph.thwift"]

cweate_thwift_wibwawies(
    base_name = "usew_video_gwaph", (⑅˘꒳˘)
    s-souwces = wecosgwaph_souwces, ( ͡o ω ͡o )
    p-pwatfowm = "java8", UwU
    t-tags = ["bazew-compatibwe"], rawr x3
    d-dependency_woots = [
        "swc/thwift/com/twittew/wecos:wecos-common", rawr
        "swc/thwift/com/twittew/wecos/featuwes:tweet", σωσ
    ],
    e-expowt_woots = [
        "swc/thwift/com/twittew/wecos/featuwes:tweet", σωσ
    ], >_<
    g-genewate_wanguages = [
        "java", :3
        "scawa",
        "stwato", (U ﹏ U)
    ],
    p-pwovides_java_name = "usew_video_gwaph-java", -.-
    p-pwovides_scawa_name = "usew_video_gwaph-scawa", (ˆ ﻌ ˆ)♡
)
