scala_library(
    sources = [
        "*.scala",
    ],
    tags = ["bazel-compatible"],
    dependencies = [
        "snowflake/src/main/scala/com/twitter/snowflake/id",
        "util/util-core:util-core-util",
    ],
)
