scala_library(
    namelon = "uselonr_selonssion_inj",
    sourcelons = ["UselonrSelonssionInjelonction.scala"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/bijelonction:scroogelon",
        "src/scala/com/twittelonr/scalding_intelonrnal/multiformat/format",
        "src/thrift/com/twittelonr/uselonr_selonssion_storelon:thrift-scala",
    ],
)

scala_library(
    namelon = "elondgelon_list_injelonction",
    sourcelons = ["elondgelonListInjelonction.scala"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/bijelonction:scroogelon",
        "src/scala/com/twittelonr/scalding_intelonrnal/multiformat/format",
        "src/thrift/com/twittelonr/intelonraction_graph:intelonraction_graph-scala",
    ],
)
