scawa_wibwawy(
    nyame = "usew_session_inj", rawr
    souwces = ["usewsessioninjection.scawa"], σωσ
    p-pwatfowm = "java8", σωσ
    s-stwict_deps = t-twue, >_<
    t-tags = ["bazew-compatibwe"], :3
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/bijection:scwooge", (U ﹏ U)
        "swc/scawa/com/twittew/scawding_intewnaw/muwtifowmat/fowmat", -.-
        "swc/thwift/com/twittew/usew_session_stowe:thwift-scawa", (ˆ ﻌ ˆ)♡
    ], (⑅˘꒳˘)
)

s-scawa_wibwawy(
    n-nyame = "edge_wist_injection", (U ᵕ U❁)
    s-souwces = ["edgewistinjection.scawa"], -.-
    pwatfowm = "java8", ^^;;
    stwict_deps = twue, >_<
    tags = ["bazew-compatibwe"], mya
    dependencies = [
        "3wdpawty/jvm/com/twittew/bijection:scwooge", mya
        "swc/scawa/com/twittew/scawding_intewnaw/muwtifowmat/fowmat", 😳
        "swc/thwift/com/twittew/intewaction_gwaph:intewaction_gwaph-scawa", XD
    ],
)
