scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", ( ͡o ω ͡o )
        "3wdpawty/jvm/com/squaweup/okhttp:okhttp3", UwU
        "abdecidew/swc/main/scawa", rawr x3
        "configapi/configapi-cowe", rawr
        "decidew/swc/main/scawa", σωσ
        "heawth-pwatfowm-manipuwation/swc/main/scawa/com/twittew/heawth/pwatfowm_manipuwation/stcm_tweet_howdback", σωσ
        "scwibewib/mawshawwews/swc/main/scawa/com/twittew/scwibewib/mawshawwews", >_<
        "sewvo/decidew/swc/main/scawa", :3
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", (U ﹏ U)
        "swc/scawa/com/twittew/takedown/utiw", -.-
        "swc/thwift/com/twittew/content-heawth/sensitivemediasettings:sensitivemediasettings-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/seawch/common:constants-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", -.-
        "swc/thwift/com/twittew/spam/wtf:safety-wesuwt-scawa", ^^;;
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", >_<
        "stitch/stitch-cowe/swc/main/scawa/com/twittew/stitch", mya
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions", mya
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/actions/convewtew/scawa", 😳
        "visibiwity/common/swc/main/thwift/com/twittew/visibiwity:action-scawa", XD
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs",
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/pawams", 😳😳😳
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/modews", ( ͡o ω ͡o )
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/utiw", rawr x3
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/wogging:vf-wogging-scawa",
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/stwato:vf-stwato-scawa", nyaa~~
    ],
)
