scala_library(
    compiler_option_sets = ["fatal_warnings"],
    tags = [
        "bazel-compatible",
    ],
    dependencies = [
        "3rdparty/jvm/org/lz4:lz4-java",
        "content-recommender/thrift/src/main/thrift:thrift-scala",
        "frigate/frigate-common/src/main/scala/com/twitter/frigate/common/store",
        "frigate/frigate-common/src/main/scala/com/twitter/frigate/common/store/health",
        "stitch/stitch-storehaus",
        "topic-social-proof/server/src/main/thrift:thrift-scala",
    ],
)
