create_thrift_libraries(
    base_name = "interaction_graph",
    sources = ["*.thrift"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependency_roots = [
    ],
    generate_languages = [
        "java",
        "scala",
        "strato",
    ],
    provides_java_name = "interaction_graph-thrift-java",
    provides_scala_name = "interaction_graph-thrift-scala",
)
