java_wibwawy(
    souwces = ["*.java"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", o.O
        "3wdpawty/jvm/com/googwe/inject:guice", (U ᵕ U❁)
        "3wdpawty/jvm/com/twittew/bijection:cowe", (⑅˘꒳˘)
        "3wdpawty/jvm/commons-wang", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/apache/thwift", UwU
        "ann/swc/main/scawa/com/twittew/ann/common", rawr x3
        "ann/swc/main/thwift/com/twittew/ann/common:ann-common-java",
        "mediasewvices/commons/swc/main/scawa:futuwetwackew", rawr
        "scwooge/scwooge-cowe", σωσ
        "swc/java/com/twittew/seawch/common/fiwe", σωσ
    ],
)
