#include <ultra64.h>
#include "sm64.h"
#include "geo_commands.h"

#include "game/level_geo.h"
#include "game/geo_misc.h"
#include "game/camera.h"
#include "game/moving_texture.h"
#include "game/screen_transition.h"
#include "game/paintings.h"

#include "make_const_nonconst.h"

#include "levels/bitfs/header.h"

#include "levels/bitfs/areas/1/2/geo.inc.c"
#include "levels/bitfs/areas/1/3/geo.inc.c"
#include "levels/bitfs/areas/1/4/geo.inc.c"
#include "levels/bitfs/areas/1/5/geo.inc.c"
#include "levels/bitfs/areas/1/6/geo.inc.c"
#include "levels/bitfs/areas/1/7/geo.inc.c"
#include "levels/bitfs/areas/1/8/geo.inc.c"
#include "levels/bitfs/areas/1/9/geo.inc.c"
#include "levels/bitfs/areas/1/10/geo.inc.c"
#include "levels/bitfs/areas/1/11/geo.inc.c"
#include "levels/bitfs/areas/1/12/geo.inc.c"
#include "levels/bitfs/areas/1/13/geo.inc.c"
#include "levels/bitfs/areas/1/14/geo.inc.c"
#include "levels/bitfs/areas/1/15/geo.inc.c"
#include "levels/bitfs/areas/1/16/geo.inc.c"
#include "levels/bitfs/areas/1/17/geo.inc.c"
#include "levels/bitfs/areas/1/18/geo.inc.c"
#include "levels/bitfs/areas/1/19/geo.inc.c"
#include "levels/bitfs/areas/1/20/geo.inc.c"
#include "levels/bitfs/elevator/geo.inc.c"
#include "levels/bitfs/sinking_cage_platform/geo.inc.c"
#include "levels/bitfs/sinking_cage_pole/geo.inc.c"
#include "levels/bitfs/tilting_square_platform/geo.inc.c"
#include "levels/bitfs/tumbling_platform_near/geo.inc.c"
#include "levels/bitfs/tumbling_platform_far/geo.inc.c"
#include "levels/bitfs/stretching_platform/geo.inc.c"
#include "levels/bitfs/moving_square_platform/geo.inc.c"
#include "levels/bitfs/sliding_platform/geo.inc.c"
#include "levels/bitfs/platform_on_track/geo.inc.c"
#include "levels/bitfs/sinking_platforms/geo.inc.c"
#include "levels/bitfs/seesaw_platform/geo.inc.c"
#include "levels/bitfs/areas/1/geo.inc.c"
