scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "decidew/swc/main/scawa", òωó
        "swc/scawa/com/twittew/simcwustews_v2/common", o.O
    ],
)
