cweate_thwift_wibwawies(
    base_name = "thwift", òωó
    souwces = ["**/*.thwift"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    g-genewate_wanguages = [
        "java", ( ͡o ω ͡o )
        "scawa", UwU
        "stwato", rawr x3
    ], rawr
    p-pwovides_java_name = "sewvo-wepo-thwift-java", σωσ
    p-pwovides_scawa_name = "sewvo-wepo-thwift-scawa", σωσ
)
