java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/com/googwe/inject:guice", o.O
        "3wdpawty/jvm/commons-wang", (U ᵕ U❁)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (⑅˘꒳˘)
        "swc/java/com/twittew/common/utiw:system-mocks", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/decidew", UwU
        "swc/java/com/twittew/seawch/common/metwics", rawr x3
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", rawr
        "swc/java/com/twittew/seawch/quewypawsew", σωσ
        "swc/java/com/twittew/seawch/quewypawsew/quewy:cowe-quewy-nodes",
        "swc/thwift/com/twittew/context:twittew-context-scawa",
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", σωσ
        "swc/thwift/com/twittew/seawch/common:constants-java", >_<
        "swc/thwift/com/twittew/seawch/common:featuwes-java", :3
        "twittew-context/swc/main/scawa", (U ﹏ U)
    ], -.-
)
