package com.twitter.product_mixer.core.model.marshalling.response.urt.color

sealed trait RosettaColor

case object WhiteRosettaColor extends RosettaColor
case object BlackRosettaColor extends RosettaColor
case object ClearRosettaColor extends RosettaColor

case object TextBlackRosettaColor extends RosettaColor
case object TextBlueRosettaColor extends RosettaColor

case object DeepGrayRosettaColor extends RosettaColor
case object MediumGrayRosettaColor extends RosettaColor
case object LightGrayRosettaColor extends RosettaColor
case object FadedGrayRosettaColor extends RosettaColor
case object FaintGrayRosettaColor extends RosettaColor

case object DeepOrangeRosettaColor extends RosettaColor
case object MediumOrangeRosettaColor extends RosettaColor
case object LightOrangeRosettaColor extends RosettaColor
case object FadedOrangeRosettaColor extends RosettaColor

case object DeepYellowRosettaColor extends RosettaColor
case object MediumYellowRosettaColor extends RosettaColor
case object LightYellowRosettaColor extends RosettaColor
case object FadedYellowRosettaColor extends RosettaColor

case object DeepGreenRosettaColor extends RosettaColor
case object MediumGreenRosettaColor extends RosettaColor
case object LightGreenRosettaColor extends RosettaColor
case object FadedGreenRosettaColor extends RosettaColor

case object DeepBlueRosettaColor extends RosettaColor
case object TwitterBlueRosettaColor extends RosettaColor
case object LightBlueRosettaColor extends RosettaColor
case object FadedBlueRosettaColor extends RosettaColor
case object FaintBlueRosettaColor extends RosettaColor

case object DeepPurpleRosettaColor extends RosettaColor
case object MediumPurpleRosettaColor extends RosettaColor
case object LightPurpleRosettaColor extends RosettaColor
case object FadedPurpleRosettaColor extends RosettaColor

case object DeepRedRosettaColor extends RosettaColor
case object MediumRedRosettaColor extends RosettaColor
case object LightRedRosettaColor extends RosettaColor
case object FadedRedRosettaColor extends RosettaColor
