java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/code/findbugs:jsw305", òωó
        "3wdpawty/jvm/com/googwe/guava", o.O
        "3wdpawty/jvm/owg/apache/commons:commons-wang3", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/swf4j:swf4j-api", UwU
        "3wdpawty/jvm/owg/yamw:snakeyamw", rawr x3
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", rawr
        "swc/java/com/twittew/common/base",
        "swc/java/com/twittew/common_intewnaw/text/vewsion", σωσ
        "swc/java/com/twittew/seawch/common/auwowa", σωσ
        "swc/java/com/twittew/seawch/common/config", >_<
        "swc/java/com/twittew/seawch/common/metwics", :3
        "swc/java/com/twittew/seawch/common/utiw/zookeepew", (U ﹏ U)
    ], -.-
)
