java_wibwawy(
    souwces = ["*.java"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/commons-wang", o.O
        "cuad/pwojects/new/thwift:thwift-java", (U ᵕ U❁)
        "pewiscope/api-pwoxy-thwift/thwift/swc/main/thwift:thwift-java", (⑅˘꒳˘)
        "scwooge/scwooge-cowe/swc/main/scawa", ( ͡o ω ͡o )
        "swc/java/com/twittew/common/cowwections", UwU
        "stitch/stitch-cowe", rawr x3
        "stwato/swc/main/scawa/com/twittew/stwato/catawog", rawr
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/thwift", σωσ
        "twittew-sewvew-intewnaw/swc/main/scawa", >_<
        "ubs/common/swc/main/thwift/com/twittew/ubs:bwoadcast-thwift-java", :3
        "utiw/utiw-cowe:utiw-cowe-utiw", (U ﹏ U)
    ],
)
