scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "dspbiddew/thwift/swc/main/thwift/com/twittew/dspbiddew/commons:thwift-scawa", UwU
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", rawr x3
        "swc/thwift/com/twittew/ads/adsewvew:adsewvew_wpc-scawa", rawr
    ],
    e-expowts = [
        "dspbiddew/thwift/swc/main/thwift/com/twittew/dspbiddew/commons:thwift-scawa", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", σωσ
        "swc/thwift/com/twittew/ads/adsewvew:adsewvew_wpc-scawa", >_<
    ], :3
)
