// 0x0D000284
const GeoLayout seaweed_geo[] = {
   GEO_SCALE(0x00, 16384),
   GEO_OPEN_NODE(),
      GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
      GEO_OPEN_NODE(),
         GEO_ANIMATED_PART(LAYER_ALPHA, 0, 0, 0, seaweed_seg6_dl_0600A180),
         GEO_OPEN_NODE(),
            GEO_ANIMATED_PART(LAYER_ALPHA, 238, 0, 0, seaweed_seg6_dl_0600A088),
            GEO_OPEN_NODE(),
               GEO_ANIMATED_PART(LAYER_ALPHA, 317, 0, 0, seaweed_seg6_dl_06009F90),
               GEO_OPEN_NODE(),
                  GEO_ANIMATED_PART(LAYER_ALPHA, 314, 0, 0, seaweed_seg6_dl_06009E98),
               GEO_CLOSE_NODE(),
            GEO_CLOSE_NODE(),
         GEO_CLOSE_NODE(),
      GEO_CLOSE_NODE(),
   GEO_CLOSE_NODE(),
   GEO_END(),
};
