scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "finagwe/finagwe-cowe/swc/main", (⑅˘꒳˘)
        "finatwa-intewnaw/tfe", ( ͡o ω ͡o )
        "passbiwd/bitfiewds-thwift/swc/main/thwift:thwift-scawa", UwU
        "swc/scawa/com/twittew/common/ip_addwess_utiws", rawr x3
        "swc/thwift/com/twittew/context:featuwe-context-scawa", rawr
        "swc/thwift/com/twittew/context:twittew-context-scawa", σωσ
        "swc/thwift/com/twittew/ip_addwess_utiws:ip-addwess-utiws-thwift-scawa", σωσ
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", >_<
        "stwato/swc/main/scawa/com/twittew/stwato/access", :3
        "stwato/swc/main/scawa/com/twittew/stwato/config", (U ﹏ U)
        "stwato/swc/main/scawa/com/twittew/stwato/context", -.-
        "stwato/swc/main/scawa/com/twittew/stwato/data", (ˆ ﻌ ˆ)♡
        "stwato/swc/main/scawa/com/twittew/stwato/opcontext", (⑅˘꒳˘)
        "stwato/swc/main/scawa/com/twittew/stwato/wesponse", (U ᵕ U❁)
        "stwato/swc/main/scawa/com/twittew/stwato/thwift", -.-
        "stwato/swc/main/thwift/com/twittew/stwato/context:thwift-scawa", ^^;;
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", >_<
        "twittew-context/swc/main/scawa", mya
        "weavewbiwd/common/swc/main/scawa/com/twittew/weavewbiwd/common", mya
    ],
)
