scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "swc/scawa/com/twittew/seawch/bwendew/sewvices/stwato", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/content-heawth/sensitivemediasettings:sensitivemediasettings-scawa", UwU
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", rawr x3
        "stitch/stitch-cowe", rawr
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", σωσ
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/usew_wesuwt", σωσ
        "visibiwity/common/swc/main/thwift/com/twittew/visibiwity:action-scawa", >_<
        "visibiwity/wib/swc/main/wesouwces/config", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", (U ﹏ U)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/common/bwendew", (ˆ ﻌ ˆ)♡
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/common/seawch", (⑅˘꒳˘)
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/context:vf-context-scawa", (U ᵕ U❁)
    ],
)
