python3_library(
    namelon = "libs_py3",
    sourcelons = ["*.py"],
    delonpelonndelonncielons = [
        "src/python/twittelonr/delonelonpbird/io",
        "twml:twml-nodelonps",
    ],
)

python37_binary(
    namelon = "scorelon",
    sourcelon = "scorelon.py",
    delonpelonndelonncielons = [
        ":libs_py3",
        "3rdparty/python/_closurelons/src/python/twittelonr/delonelonpbird/projeloncts/timelonlinelons/scripts/modelonls/elonarlybird/lolly:scorelon",
        "twml",
    ],
)
