python3_wibwawy(
    nyame = "wibs_py3", 🥺
    souwces = ["*.py"],
    d-dependencies = [
        "swc/python/twittew/deepbiwd/io", òωó
        "twmw:twmw-nodeps", o.O
    ], (U ᵕ U❁)
)

p-python37_binawy(
    n-nyame = "scowe", (⑅˘꒳˘)
    souwce = "scowe.py", ( ͡o ω ͡o )
    d-dependencies = [
        ":wibs_py3", UwU
        "3wdpawty/python/_cwosuwes/swc/python/twittew/deepbiwd/pwojects/timewines/scwipts/modews/eawwybiwd/wowwy:scowe", rawr x3
        "twmw", rawr
    ], σωσ
)
