scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "configapi/configapi-corelon/src/main/scala/com/twittelonr/timelonlinelons/configapi",
        "src/thrift/com/twittelonr/reloncos/uselonr_twelonelont_elonntity_graph:uselonr_twelonelont_elonntity_graph-scala",
        "src/thrift/com/twittelonr/selonarch:elonarlybird-scala",
        "src/thrift/com/twittelonr/selonarch/common:constants-scala",
        "src/thrift/com/twittelonr/selonarch/common:felonaturelons-scala",
        "timelonlinelonrankelonr/common:modelonl",
        "timelonlinelonrankelonr/selonrvelonr/src/main/scala/com/twittelonr/timelonlinelonrankelonr/reloncap/modelonl",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/clielonnts/gizmoduck",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/modelonl/twelonelont",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/util",
        "timelonlinelons/src/main/scala/com/twittelonr/timelonlinelons/visibility/modelonl",
        "util/util-corelon:util-corelon-util",
    ],
    elonxports = [
        "src/thrift/com/twittelonr/reloncos/uselonr_twelonelont_elonntity_graph:uselonr_twelonelont_elonntity_graph-scala",
    ],
)
