scawa_wibwawy(
    souwces = ["**/*.scawa"], (⑅˘꒳˘)
    pwatfowm = "java8", ( ͡o ω ͡o )
    p-pwovides = s-scawa_awtifact(
        o-owg = "com.twittew", UwU
        n-nyame = "sewvo-wepo", rawr x3
        w-wepo = awtifactowy, rawr
    ),
    s-stwict_deps = t-twue, σωσ
    tags = ["bazew-compatibwe"], σωσ
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", >_<
        "3wdpawty/jvm/com/googwe/inject:guice", :3
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (U ﹏ U)
        "finagwe/finagwe-cowe/swc/main", -.-
        "finagwe/finagwe-memcached/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "finagwe/finagwe-mux/swc/main/scawa", (⑅˘꒳˘)
        "finagwe/finagwe-thwift", (U ᵕ U❁)
        "scwooge/scwooge-cowe", -.-
        "scwooge/scwooge-sewiawizew/swc/main/scawa", ^^;;
        "tweetypie/sewvo/wepo/swc/main/thwift:thwift-scawa", >_<
        "tweetypie/sewvo/utiw", mya
        "utiw/utiw-codec/swc/main/scawa", mya
        "utiw/utiw-hashing/swc/main/scawa", 😳
        "utiw/utiw-wogging", XD
        "utiw/utiw-secuwity/swc/main/scawa/com/twittew/utiw/secuwity", :3
        "utiw/utiw-stats/swc/main/scawa", 😳😳😳
    ], -.-
)
