wesouwces(
    souwces = ["*.*"], 🥺
    tags = ["bazew-compatibwe"], òωó
)

f-fiwes(
    n-nyame = "fiwes", o.O
    s-souwces = [
        "!buiwd", (U ᵕ U❁)
        "**/*", (⑅˘꒳˘)
    ],
    t-tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
)
