java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/injelonct:guicelon",
        "3rdparty/jvm/commons-io",
        "3rdparty/jvm/org/yaml:snakelonyaml",
        "finaglelon/finaglelon-corelon/src/main",
        "src/java/com/twittelonr/common/util:systelonm-mocks",
        "src/java/com/twittelonr/selonarch/common/util/io/pelonriodic",
    ],
)
