scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "finagwe/finagwe-cowe/swc/main", (⑅˘꒳˘)
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", ( ͡o ω ͡o )
        "finatwa-intewnaw/thwift/swc/main/thwift:thwift-scawa", UwU
        "swc/thwift/com/twittew/simcwustews_v2:simcwustews_v2-thwift-scawa", rawr x3
    ], rawr
)
