java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/com/googwe/inject:guice", o.O
        "3wdpawty/jvm/com/twittew/ewephantbiwd:cowe", (U ᵕ U❁)
        "3wdpawty/jvm/geo/googwe:geogoogwe", (⑅˘꒳˘)
        "3wdpawty/jvm/joda-time", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", UwU
        "3wdpawty/jvm/owg/apache/httpcomponents:httpcowe", rawr x3
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", rawr
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", σωσ
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient", σωσ
        "3wdpawty/jvm/owg/swf4j:swf4j-api", >_<
        "cuad/pwojects/new/thwift/swc/main/thwift:thwift-java", :3
        "decidew/swc/main/scawa", (U ﹏ U)
        "swc/java/com/twittew/common/base", -.-
        "swc/java/com/twittew/common/cowwections", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/common/text/wanguage:wocawe-utiw", (⑅˘꒳˘)
        "swc/java/com/twittew/common/text/token", (U ᵕ U❁)
        "swc/java/com/twittew/common/text/utiw:token-utiw", -.-
        "swc/java/com/twittew/common_intewnaw/text:text-penguin7", ^^;;
        "swc/java/com/twittew/common_intewnaw/text/vewsion", >_<
        "swc/java/com/twittew/seawch/common/config", mya
        "swc/java/com/twittew/seawch/common/constants", mya
        "swc/java/com/twittew/seawch/common/debug", 😳
        "swc/java/com/twittew/seawch/common/decidew", XD
        "swc/java/com/twittew/seawch/common/encoding/docvawues", :3
        "swc/java/com/twittew/seawch/common/encoding/featuwes", 😳😳😳
        "swc/java/com/twittew/seawch/common/metwics", -.-
        "swc/java/com/twittew/seawch/common/pawtitioning/base", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", rawr x3
        "swc/java/com/twittew/seawch/common/wewevance:entities_and_fiwtews", nyaa~~
        "swc/java/com/twittew/seawch/common/wewevance:text", /(^•ω•^)
        "swc/java/com/twittew/seawch/common/wewevance/featuwes", rawr
        "swc/java/com/twittew/seawch/common/schema", OwO
        "swc/java/com/twittew/seawch/common/schema/base", (U ﹏ U)
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", >_<
        "swc/java/com/twittew/seawch/common/utiw:wongintconvewtew", rawr x3
        "swc/java/com/twittew/seawch/common/utiw/anawysis", mya
        "swc/java/com/twittew/seawch/common/utiw/wang",
        "swc/java/com/twittew/seawch/common/utiw/spatiaw", nyaa~~
        "swc/java/com/twittew/seawch/common/utiw/text", (⑅˘꒳˘)
        "swc/java/com/twittew/seawch/common/utiw/text/wegex", rawr x3
        "swc/java/com/twittew/seawch/common/utiw/thwift:thwift-utiws", (✿oωo)
        "swc/java/com/twittew/seawch/common/utiw/uww", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/seawch/ingestew/modew", (˘ω˘)
        "swc/thwift/com/twittew/seawch/common:constants-java", (⑅˘꒳˘)
        "swc/thwift/com/twittew/seawch/common:indexing-java", (///ˬ///✿)
        "swc/thwift/com/twittew/seawch/common:schema-java", 😳😳😳
        "swc/thwift/com/twittew/seawch/common/debug:debug-java", 🥺
        "swc/thwift/com/twittew/sewvice/spidewduck/gen:metadata-stowe-java", mya
        "swc/thwift/com/twittew/tweetypie:tweet-java", 🥺
    ],
)
