scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", ( ͡o ω ͡o )
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/twanspowt", UwU
        "finagwe/finagwe-thwift/swc/main/scawa", rawr x3
        "tweetypie/sewvo/utiw/swc/main/scawa:exception", rawr
        "stwato/swc/main/scawa/com/twittew/stwato/access", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/data", σωσ
    ], >_<
)
