scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "abdeloncidelonr/src/main/scala",
        "deloncidelonr",
        "felonaturelonswitchelons/felonaturelonswitchelons-corelon/src/main/scala",
        "felonaturelonswitchelons/felonaturelonswitchelons-corelon/src/main/scala/com/twittelonr/felonaturelonswitchelons/v2/buildelonr",
        "stitch/stitch-corelon",
        "twittelonr-config/yaml",
        "util-intelonrnal/scribelon",
        "util/util-logging/src/main/scala",
        "util/util-stats/src/main/scala",
    ],
)
