scawa_wibwawy(
    souwces = ["*.scawa"], (U ᵕ U❁)
    compiwew_option_sets = ["fataw_wawnings"], (⑅˘꒳˘)
    p-pwatfowm = "java8", ( ͡o ω ͡o )
    s-scawac_pwugins = ["no-woomba"], UwU
    s-stwict_deps = t-twue, rawr x3
    t-tags = ["bazew-compatibwe"], rawr
    d-dependencies = [
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/sewectow/sowtew", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap/featuwestowev1", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwestowev1", >_<
    ],
    e-expowts = [
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/sewectow/sowtew", :3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwemap/featuwestowev1", (U ﹏ U)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/featuwe/featuwestowev1", -.-
    ],
)
