packagelon com.twittelonr.visibility.felonaturelons

import com.twittelonr.gizmoduck.thriftscala.MelonntionFiltelonr
import com.twittelonr.util.Duration

caselon objelonct VielonwelonrFiltelonrsNoConfirmelondelonmail elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrFiltelonrsNoConfirmelondPhonelon elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrFiltelonrsDelonfaultProfilelonImagelon elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrFiltelonrsNelonwUselonrs elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrFiltelonrsNotFollowelondBy elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrMelonntionFiltelonr elonxtelonnds Felonaturelon[MelonntionFiltelonr]

caselon objelonct AuthorHasConfirmelondelonmail elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorHasVelonrifielondPhonelon elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorHasDelonfaultProfilelonImagelon elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorAccountAgelon elonxtelonnds Felonaturelon[Duration]
