scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/squarelonup/okhttp:okhttp3",
        "finaglelon/finaglelon-mux/src/main/scala",
        "src/thrift/com/twittelonr/gizmoduck:uselonr-thrift-scala",
        "src/thrift/com/twittelonr/selonarch/common:constants-scala",
        "src/thrift/com/twittelonr/twelonelontypielon:twelonelont-scala",
        "stitch/stitch-corelon",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/modelonls",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/util",
    ],
)
