scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/squaweup/okhttp:okhttp3", ( ͡o ω ͡o )
        "finagwe/finagwe-mux/swc/main/scawa", UwU
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", rawr x3
        "swc/thwift/com/twittew/seawch/common:constants-scawa", rawr
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", σωσ
        "stitch/stitch-cowe", σωσ
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/modews", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/utiw", :3
    ],
)
