packagelon com.twittelonr.visibility.felonaturelons

import com.twittelonr.contelonnthelonalth.toxicrelonplyfiltelonr.thriftscala.FiltelonrStatelon
import com.twittelonr.gizmoduck.thriftscala.Labelonl
import com.twittelonr.selonarch.common.constants.thriftscala.ThriftQuelonrySourcelon
import com.twittelonr.tselonng.withholding.thriftscala.TakelondownRelonason
import com.twittelonr.util.Duration
import com.twittelonr.util.Timelon
import com.twittelonr.visibility.modelonls.TwelonelontDelonlelontelonRelonason.TwelonelontDelonlelontelonRelonason
import com.twittelonr.visibility.modelonls._

caselon objelonct AuthorId elonxtelonnds Felonaturelon[Selont[Long]]

caselon objelonct VielonwelonrId elonxtelonnds Felonaturelon[Long]

caselon objelonct AuthorIsProtelonctelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorIsSuspelonndelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorIsUnavailablelon elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorIsDelonactivatelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorIselonraselond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorIsOffboardelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorIsVelonrifielond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorIsBluelonVelonrifielond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrIsSuspelonndelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrIsDelonactivatelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorFollowsVielonwelonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorUselonrLabelonls elonxtelonnds Felonaturelon[Selonq[Labelonl]]

caselon objelonct VielonwelonrFollowsAuthorOfViolatingTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrDoelonsNotFollowAuthorOfViolatingTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrFollowsAuthor elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrBlocksAuthor elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorBlocksVielonwelonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorMutelonsVielonwelonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrMutelonsAuthor elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorRelonportsVielonwelonrAsSpam elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrRelonportsAuthorAsSpam elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrRelonportelondTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrMutelonsRelontwelonelontsFromAuthor elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrHasUnivelonrsalQualityFiltelonrelonnablelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrIsProtelonctelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrIsSoftUselonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontSafelontyLabelonls elonxtelonnds Felonaturelon[Selonq[TwelonelontSafelontyLabelonl]]

caselon objelonct SpacelonSafelontyLabelonls elonxtelonnds Felonaturelon[Selonq[SpacelonSafelontyLabelonl]]

caselon objelonct MelondiaSafelontyLabelonls elonxtelonnds Felonaturelon[Selonq[MelondiaSafelontyLabelonl]]

caselon objelonct TwelonelontTakelondownRelonasons elonxtelonnds Felonaturelon[Selonq[TakelondownRelonason]]

caselon objelonct AuthorTakelondownRelonasons elonxtelonnds Felonaturelon[Selonq[TakelondownRelonason]]

caselon objelonct AuthorIsNsfwUselonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct AuthorIsNsfwAdmin elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontHasNsfwUselonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontHasNsfwAdmin elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontHasMelondia elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct CardHasMelondia elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontHasCard elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrMutelonsKelonywordInTwelonelontForHomelonTimelonlinelon elonxtelonnds Felonaturelon[MutelondKelonyword]

caselon objelonct VielonwelonrMutelonsKelonywordInTwelonelontForTwelonelontRelonplielons elonxtelonnds Felonaturelon[MutelondKelonyword]

caselon objelonct VielonwelonrMutelonsKelonywordInTwelonelontForNotifications elonxtelonnds Felonaturelon[MutelondKelonyword]

caselon objelonct VielonwelonrMutelonsKelonywordInSpacelonTitlelonForNotifications elonxtelonnds Felonaturelon[MutelondKelonyword]

caselon objelonct VielonwelonrMutelonsKelonywordInTwelonelontForAllSurfacelons elonxtelonnds Felonaturelon[MutelondKelonyword]

caselon objelonct VielonwelonrUselonrLabelonls elonxtelonnds Felonaturelon[Selonq[Labelonl]]

caselon objelonct RelonquelonstCountryCodelon elonxtelonnds Felonaturelon[String]

caselon objelonct RelonquelonstIsVelonrifielondCrawlelonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrCountryCodelon elonxtelonnds Felonaturelon[String]

caselon objelonct TwelonelontIsSelonlfRelonply elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIsNullcast elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontTimelonstamp elonxtelonnds Felonaturelon[Timelon]

caselon objelonct TwelonelontIsInnelonrQuotelondTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIsRelontwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIsSourcelonTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontDelonlelontelonRelonason elonxtelonnds Felonaturelon[TwelonelontDelonlelontelonRelonason]

caselon objelonct TwelonelontRelonplyToParelonntTwelonelontDuration elonxtelonnds Felonaturelon[Duration]

caselon objelonct TwelonelontRelonplyToRootTwelonelontDuration elonxtelonnds Felonaturelon[Duration]

caselon objelonct TwelonelontHasCommunityConvelonrsationControl elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct TwelonelontHasByInvitationConvelonrsationControl elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct TwelonelontHasFollowelonrsConvelonrsationControl elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct TwelonelontConvelonrsationVielonwelonrIsInvitelond elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct TwelonelontConvelonrsationVielonwelonrIsInvitelondViaRelonplyMelonntion elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct TwelonelontConvelonrsationVielonwelonrIsRootAuthor elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct ConvelonrsationRootAuthorFollowsVielonwelonr elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct VielonwelonrFollowsConvelonrsationRootAuthor elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIselonxclusivelonTwelonelont elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct VielonwelonrIselonxclusivelonTwelonelontRootAuthor elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct VielonwelonrSupelonrFollowselonxclusivelonTwelonelontRootAuthor elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIsCommunityTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct CommunityTwelonelontCommunityNotFound elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct CommunityTwelonelontCommunityDelonlelontelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct CommunityTwelonelontCommunitySuspelonndelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct CommunityTwelonelontCommunityVisiblelon elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct CommunityTwelonelontIsHiddelonn elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrIsIntelonrnalCommunitielonsAdmin elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrIsCommunityAdmin elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrIsCommunityModelonrator elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrIsCommunityMelonmbelonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct CommunityTwelonelontAuthorIsRelonmovelond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct NotificationIsOnCommunityTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct NotificationIsOnUnmelonntionelondVielonwelonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct SelonarchRelonsultsPagelonNumbelonr elonxtelonnds Felonaturelon[Int]

caselon objelonct SelonarchCandidatelonCount elonxtelonnds Felonaturelon[Int]

caselon objelonct SelonarchQuelonrySourcelon elonxtelonnds Felonaturelon[ThriftQuelonrySourcelon]

caselon objelonct SelonarchQuelonryHasUselonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontSelonmanticCorelonAnnotations elonxtelonnds Felonaturelon[Selonq[SelonmanticCorelonAnnotation]]

caselon objelonct OutelonrAuthorId elonxtelonnds Felonaturelon[Long]

caselon objelonct AuthorBlocksOutelonrAuthor elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct OutelonrAuthorFollowsAuthor elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct OutelonrAuthorIsInnelonrAuthor elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIsModelonratelond elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct FocalTwelonelontId elonxtelonnds Felonaturelon[Long]

caselon objelonct TwelonelontId elonxtelonnds Felonaturelon[Long]

caselon objelonct TwelonelontConvelonrsationId elonxtelonnds Felonaturelon[Long]
caselon objelonct TwelonelontParelonntId elonxtelonnds Felonaturelon[Long]
caselon objelonct ConvelonrsationRootAuthorIsVelonrifielond elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrOptInBlocking elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrOptInFiltelonring elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrRolelons elonxtelonnds Felonaturelon[Selonq[String]] {
  val elonmployelonelonRolelon = "elonmployelonelon"
}

caselon objelonct TwelonelontMisinformationPolicielons elonxtelonnds Felonaturelon[Selonq[MisinformationPolicy]]

caselon objelonct TwelonelontelonnglishMisinformationPolicielons elonxtelonnds Felonaturelon[Selonq[MisinformationPolicy]]

caselon objelonct HasInnelonrCirclelonOfFrielonndsRelonlationship elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrAgelon elonxtelonnds Felonaturelon[UselonrAgelon]

caselon objelonct HasDmcaMelondiaFelonaturelon elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct MelondiaGelonoRelonstrictionsAllowList elonxtelonnds Felonaturelon[Selonq[String]]
caselon objelonct MelondiaGelonoRelonstrictionsDelonnyList elonxtelonnds Felonaturelon[Selonq[String]]

caselon objelonct TwelonelontIsTrustelondFrielonndTwelonelont elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct VielonwelonrIsTrustelondFrielonndTwelonelontAuthor elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct VielonwelonrIsTrustelondFrielonndOfTwelonelontAuthor elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct DmConvelonrsationIsOnelonToOnelonConvelonrsation elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmConvelonrsationHaselonmptyTimelonlinelon elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmConvelonrsationHasValidLastRelonadablelonelonvelonntId elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmConvelonrsationInfoelonxists elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmConvelonrsationTimelonlinelonelonxists elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct VielonwelonrIsDmConvelonrsationParticipant elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct DmelonvelonntIsMelonssagelonCrelonatelonelonvelonnt elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntIsWelonlcomelonMelonssagelonCrelonatelonelonvelonnt elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntIsLastMelonssagelonRelonadUpdatelonelonvelonnt elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntIsDelonlelontelond elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntIsHiddelonn elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct VielonwelonrIsDmelonvelonntInitiatingUselonr elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntInOnelonToOnelonConvelonrsationWithUnavailablelonUselonr elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntIsJoinConvelonrsationelonvelonnt elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntIsConvelonrsationCrelonatelonelonvelonnt elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntInOnelonToOnelonConvelonrsation elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntIsTrustConvelonrsationelonvelonnt elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntIsCsFelonelondbackSubmittelond elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntIsCsFelonelondbackDismisselond elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntIsPelonrspelonctivalJoinConvelonrsationelonvelonnt elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct DmelonvelonntOccurrelondBelonforelonLastClelonarelondelonvelonnt elonxtelonnds Felonaturelon[Boolelonan]
caselon objelonct DmelonvelonntOccurrelondBelonforelonJoinConvelonrsationelonvelonnt elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct CardUriHost elonxtelonnds Felonaturelon[String]
caselon objelonct CardIsPoll elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIsStalelonTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIselonditTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIsLatelonstTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIsInitialTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct TwelonelontIsCollabInvitationTwelonelont elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct VielonwelonrSelonnsitivelonMelondiaSelonttings elonxtelonnds Felonaturelon[UselonrSelonnsitivelonMelondiaSelonttings]


caselon objelonct ToxicRelonplyFiltelonrStatelon elonxtelonnds Felonaturelon[FiltelonrStatelon]


caselon objelonct ToxicRelonplyFiltelonrConvelonrsationAuthorIsVielonwelonr elonxtelonnds Felonaturelon[Boolelonan]

caselon objelonct RawQuelonry elonxtelonnds Felonaturelon[String]

caselon objelonct AuthorScrelonelonnNamelon elonxtelonnds Felonaturelon[String]

caselon objelonct TwelonelontIsIntelonrnalPromotelondContelonnt elonxtelonnds Felonaturelon[Boolelonan]
