java_library(
    sourcelons = ["*.java"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/guava",
        "src/java/com/twittelonr/selonarch/common/partitioning/baselon",
        "src/java/com/twittelonr/selonarch/common/schelonma/baselon",
        "src/java/com/twittelonr/selonarch/common/schelonma/elonarlybird",
        "src/java/com/twittelonr/selonarch/quelonryparselonr/quelonry:corelon-quelonry-nodelons",
        "src/java/com/twittelonr/selonarch/quelonryparselonr/quelonry/selonarch:selonarch-quelonry-nodelons",
    ],
)
