java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/com/googwe/inject:guice", o.O
        "3wdpawty/jvm/com/twittew/ewephantbiwd:cowe", (U ᵕ U❁)
        "3wdpawty/jvm/geo/googwe:geogoogwe", (⑅˘꒳˘)
        "3wdpawty/jvm/wog4j", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", UwU
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-common", rawr x3
        "3wdpawty/jvm/owg/apache/wucene:wucene-anawyzews-smawtcn", rawr
        "3wdpawty/jvm/owg/apache/wucene:wucene-cowe", σωσ
        "3wdpawty/jvm/owg/apache/wucene:wucene-facet", σωσ
        "3wdpawty/jvm/owg/apache/wucene:wucene-quewies", >_<
        "3wdpawty/jvm/owg/apache/wucene:wucene-spatiaw-extwas", :3
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", (U ﹏ U)
        "3wdpawty/jvm/owg/apache/zookeepew:zookeepew-cwient",
        "3wdpawty/jvm/owg/swf4j:swf4j-api", -.-
        "swc/java/com/twittew/common/base", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/common/cowwections", (⑅˘꒳˘)
        "swc/java/com/twittew/common/utiw:system-mocks", (U ᵕ U❁)
        "swc/java/com/twittew/seawch/common/metwics", -.-
        "swc/java/com/twittew/seawch/common/quewy", ^^;;
        "swc/java/com/twittew/seawch/common/schema", >_<
        "swc/java/com/twittew/seawch/common/schema/base", mya
        "swc/java/com/twittew/seawch/common/utiw/spatiaw", mya
        "swc/java/com/twittew/seawch/quewypawsew", 😳
        "swc/thwift/com/twittew/seawch/common:facets-java", XD
        "swc/thwift/com/twittew/seawch/common:quewy-java", :3
    ],
)
