java_library(
    sources = ["*.java"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/google/guava",
        "src/java/com/twitter/search/common/partitioning/base",
        "src/java/com/twitter/search/common/schema/base",
        "src/java/com/twitter/search/common/schema/earlybird",
        "src/java/com/twitter/search/queryparser/query:core-query-nodes",
        "src/java/com/twitter/search/queryparser/query/search:search-query-nodes",
    ],
)
