scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-scawac_pwugins = ["no-woomba"], (U ᵕ U❁)
    s-stwict_deps = twue, (⑅˘꒳˘)
    t-tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", UwU
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/candidate_souwce/ads", rawr x3
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/decowatow/uwt", rawr
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate/ads", σωσ
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/quewy/ads", σωσ
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/candidate", >_<
    ],
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", :3
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/candidate_souwce/ads", (U ﹏ U)
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/candidate/ads", -.-
        "pwoduct-mixew/component-wibwawy/swc/main/scawa/com/twittew/pwoduct_mixew/component_wibwawy/modew/quewy/ads", (ˆ ﻌ ˆ)♡
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/candidate", (⑅˘꒳˘)
    ],
)
