scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", ( ͡o ω ͡o )
        "scwooge/scwooge-cowe/swc/main/scawa", UwU
        "tweetypie/sewvo/utiw/swc/main/scawa", rawr x3
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:media-entity-scawa", rawr
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", σωσ
        "tco-utiw", σωσ
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/utiw",
        "utiw/utiw-wogging/swc/main/scawa/com/twittew/wogging",
    ], >_<
)
