scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "ann/swc/main/scawa/com/twittew/ann/common", (U ᵕ U❁)
        "ann/swc/main/scawa/com/twittew/ann/sewiawization", (⑅˘꒳˘)
        "ann/swc/main/thwift/com/twittew/ann/sewiawization:sewiawization-scawa", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/fiwe", UwU
    ],
)
