scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "ann/src/main/scala/com/twittelonr/ann/common",
        "ann/src/main/scala/com/twittelonr/ann/selonrialization",
        "ann/src/main/thrift/com/twittelonr/ann/selonrialization:selonrialization-scala",
        "src/java/com/twittelonr/selonarch/common/filelon",
    ],
)
