scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/googlelon/injelonct:guicelon",
        "3rdparty/jvm/nelont/codingwelonll:scala-guicelon",
        "3rdparty/jvm/org/slf4j:slf4j-api",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/clielonnts/cachelon",
        "follow-reloncommelonndations-selonrvicelon/common/src/main/scala/com/twittelonr/follow_reloncommelonndations/common/clielonnts/strato",
        "follow-reloncommelonndations-selonrvicelon/selonrvelonr/src/main/scala/com/twittelonr/follow_reloncommelonndations/configapi/deloncidelonrs",
        "stitch/stitch-corelon",
        "strato/src/main/scala/com/twittelonr/strato/clielonnt",
        "uselonr-signal-selonrvicelon/thrift/src/main/thrift:thrift-scala",
    ],
)
