scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", (U ᵕ U❁)
        "3wdpawty/jvm/net/codingweww:scawa-guice", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/swf4j:swf4j-api", ( ͡o ω ͡o )
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/cache", UwU
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/stwato", rawr x3
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/configapi/decidews", rawr
        "stitch/stitch-cowe",
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", σωσ
        "usew-signaw-sewvice/thwift/swc/main/thwift:thwift-scawa", σωσ
    ], >_<
)
