scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", UwU
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common/pwesentation", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe", σωσ
        "stitch/stitch-cowe", σωσ
    ],
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", >_<
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/modew/common/pwesentation", :3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine", (U ﹏ U)
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/pipewine/pipewine_faiwuwe", -.-
        "stitch/stitch-cowe", (ˆ ﻌ ˆ)♡
    ],
)
