scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "finagle-internal/mtls/src/main/scala/com/twitter/finagle/mtls/authentication",
        "finagle/finagle-stats",
        "finatra/inject/inject-core/src/main/scala",
        "frigate/frigate-common/src/main/scala/com/twitter/frigate/common/util",
        "interests-service/thrift/src/main/thrift:thrift-scala",
        "representation-manager/server/src/main/scala/com/twitter/representation_manager/common",
        "servo/util",
        "src/scala/com/twitter/storehaus_internal/manhattan",
        "src/scala/com/twitter/storehaus_internal/memcache",
        "src/scala/com/twitter/storehaus_internal/util",
        "strato/src/main/scala/com/twitter/strato/client",
    ],
)
