scawa_wibwawy(
    souwces = ["*.scawa"], ^•ﻌ•^
    compiwew_option_sets = ["fataw_wawnings"], OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/bijection:cowe", òωó
        "3wdpawty/jvm/com/twittew/bijection:scwooge", o.O
        "ann/swc/main/scawa/com/twittew/ann/common",
        "swc/scawa/com/twittew/mw/api/embedding", (U ᵕ U❁)
        "stowage/cwients/manhattan", (⑅˘꒳˘)
    ],
)
