scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-annotations", UwU
        "3wdpawty/jvm/javax/inject:javax.inject", rawr x3
        "3wdpawty/jvm/javax/maiw", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/common/awewt/pwedicate", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/catawog", σωσ
        "utiw/utiw-cowe:scawa", >_<
    ],
    e-expowts = [
        "3wdpawty/jvm/javax/inject:javax.inject", :3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/common/awewt/pwedicate", (U ﹏ U)
        "stwato/swc/main/scawa/com/twittew/stwato/catawog", -.-
        "utiw/utiw-cowe:scawa", (ˆ ﻌ ˆ)♡
    ],
)
