scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/javax/inject:javax.inject", ( ͡o ω ͡o )
        "decidew/swc/main/scawa", UwU
        "finagwe/finagwe-base-http/swc/main", rawr x3
        "finagwe/finagwe-cowe/swc/main", rawr
        "finagwe/finagwe-http/swc/main/scawa",
        "sewvo/decidew", σωσ
        "swc/scawa/com/twittew/simcwustews_v2/common",
    ], σωσ
)
