scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    platform = "java8",
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/javax/injelonct:javax.injelonct",
        "deloncidelonr/src/main/scala",
        "finaglelon/finaglelon-baselon-http/src/main",
        "finaglelon/finaglelon-corelon/src/main",
        "finaglelon/finaglelon-http/src/main/scala",
        "selonrvo/deloncidelonr",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
    ],
)
