scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    p-pwatfowm = "java8", o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "swc/scawa/com/twittew/seawch/bwendew/sewvices/stwato", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/spam/wtf:safety-wabew-scawa", UwU
        "swc/thwift/com/twittew/spam/wtf:tweet-wtf-event-scawa", rawr x3
        "stitch/stitch-cowe", rawr
        "stwato/swc/main/scawa/com/twittew/stwato/catawog", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", σωσ
        "stwato/swc/main/scawa/com/twittew/stwato/data", >_<
        "stwato/swc/main/scawa/com/twittew/stwato/thwift", :3
    ], (U ﹏ U)
)
