scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/com/github/nscawa_time", (U ᵕ U❁)
        "3wdpawty/jvm/com/googwe/inject:guice", (⑅˘꒳˘)
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", ( ͡o ω ͡o )
        "3wdpawty/jvm/net/codingweww:scawa-guice", UwU
        "3wdpawty/jvm/owg/swf4j:swf4j-api", rawr x3
        "eschewbiwd/swc/scawa/com/twittew/eschewbiwd/utiw/stitchcache", rawr
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", σωσ
        "finatwa/inject/inject-cowe/swc/main/scawa", σωσ
        "finatwa/inject/inject-thwift-cwient/swc/main/scawa", >_<
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/base", :3
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/common", (U ﹏ U)
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/modews", -.-
        "sociawgwaph/sewvew/swc/main/scawa/com/twittew/sociawgwaph/utiw", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/sociawgwaph:thwift-scawa", (⑅˘꒳˘)
        "stitch/stitch-sociawgwaph", (U ᵕ U❁)
        "stwato/config/cowumns/onboawding/sociawgwaphsewvice:sociawgwaphsewvice-stwato-cwient", -.-
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", ^^;;
        "utiw/utiw-cowe:scawa", >_<
    ],
)
