scala_library(
    sources = ["*.scala"],
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/X/graphjet",
        "servo/request/src/main/scala",
        "src/scala/com/X/recos/user_tweet_graph/store",
        "src/scala/com/X/recos/user_tweet_graph/util",
        "src/scala/com/X/recos/util:recos-util",
        "src/thrift/com/X/recos/user_tweet_graph:user_tweet_graph-scala",
    ],
)
