scawa_wibwawy(
    nyame = "defauwt", rawr
    souwces = [
        "abstwacthydwatow.scawa", σωσ
        "defauwthydwatow.scawa", σωσ
    ],
    t-tags = ["bazew-compatibwe"], >_<
    d-dependencies = [
        ":base", :3
        "featuweswitches/dynmap/swc/main/scawa/com/twittew/dynmap:dynmap-cowe", (U ﹏ U)
        "unified_usew_actions/enwichew/swc/main/scawa/com/twittew/unified_usew_actions/enwichew", -.-
        "unified_usew_actions/enwichew/swc/main/scawa/com/twittew/unified_usew_actions/enwichew/gwaphqw", (ˆ ﻌ ˆ)♡
        "unified_usew_actions/enwichew/swc/main/scawa/com/twittew/unified_usew_actions/enwichew/hcache", (⑅˘꒳˘)
        "unified_usew_actions/enwichew/swc/main/thwift/com/twittew/unified_usew_actions/enwichew/intewnaw:intewnaw-scawa", (U ᵕ U❁)
    ], -.-
)

s-scawa_wibwawy(
    n-nyame = "noop", ^^;;
    s-souwces = ["noophydwatow.scawa"], >_<
    t-tags = ["bazew-compatibwe"], mya
    d-dependencies = [
        ":base", mya
        "unified_usew_actions/enwichew/swc/main/scawa/com/twittew/unified_usew_actions/enwichew",
        "unified_usew_actions/enwichew/swc/main/thwift/com/twittew/unified_usew_actions/enwichew/intewnaw:intewnaw-scawa", 😳
    ], XD
)

s-scawa_wibwawy(
    nyame = "base", :3
    souwces = ["hydwatow.scawa"], 😳😳😳
    tags = ["bazew-compatibwe"], -.-
    dependencies = [
        "unified_usew_actions/enwichew/swc/main/thwift/com/twittew/unified_usew_actions/enwichew/intewnaw:intewnaw-scawa", ( ͡o ω ͡o )
    ], rawr x3
)
