scawa_wibwawy(
    souwces = ["**/*.scawa"], UwU
    pwatfowm = "java8", rawr x3
    p-pwovides = s-scawa_awtifact(
        o-owg = "com.twittew", rawr
        n-nyame = "sewvo-wequest", σωσ
        w-wepo = a-awtifactowy, σωσ
    ),
    s-stwict_deps = t-twue, >_<
    tags = ["bazew-compatibwe"], :3
    dependencies = [
        "finagwe/finagwe-cowe/swc/main", (U ﹏ U)
        "tweetypie/sewvo/utiw", -.-
        "twittew-config/yamw", (ˆ ﻌ ˆ)♡
        "utiw/utiw-stats/swc/main/scawa", (⑅˘꒳˘)
    ],
    expowts = [
        "tweetypie/sewvo/utiw", (U ᵕ U❁)
    ], -.-
)
