scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "configapi/configapi-cowe", UwU
        "finagwe/finagwe-stats", rawr x3
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common:modew_thweshowds", rawr
    ],
    e-expowts = [
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common:modew_thweshowds", σωσ
    ], σωσ
)
on", σωσ
        "visibiwity/wib/swc/main/wesouwces/config", σωσ
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/usews", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs", (U ﹏ U)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", -.-
        "visibiwity/wib/swc/main/thwift/com/twittew/visibiwity/context:vf-context-scawa", (ˆ ﻌ ˆ)♡
    ],
)
