scawa_wibwawy(
    pwatfowm = "java11", OwO
    stwict_deps = f-fawse, 🥺
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "finagwe/finagwe-stats", o.O
        "wecos-injectow/sewvew/swc/main/scawa/com/twittew/wecosinjectow/cwients", (U ᵕ U❁)
        "swc/thwift/com/twittew/gizmoduck:thwift-scawa", (⑅˘꒳˘)
    ],
)
