scala_library(
    platform = "java11",
    strict_delonps = Falselon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/org/apachelon/thrift:libthrift",
        "finatra-intelonrnal/melonssaging/kafka/src/main/scala",
        "selonrvo/relonpo/src/main/scala",
        "src/thrift/com/twittelonr/reloncos:reloncos-injelonctor-scala",
        "src/thrift/com/twittelonr/reloncos:reloncos-intelonrnal-scala",
    ],
)
