scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    s-stwict_deps = t-twue, (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/swc/java/com/twittew/wogpipewine/cwient:wogpipewine-event-pubwishew-thin", ( ͡o ω ͡o )
        "abdecidew/swc/main/scawa:abdecidewutiws", UwU
        "decidew/swc/main/scawa",
        "finatwa-intewnaw/messaging/kafka/swc/main/scawa", rawr x3
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", rawr
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/side_effect", σωσ
        "scwibewib/mawshawwews/swc/main/scawa/com/twittew/scwibewib/mawshawwews", σωσ
        "scwibewib/vawidatows/swc/main/scawa/com/twittew/scwibewib/vawidatows", >_<
        "scwooge/scwooge-sewiawizew/swc/main/scawa", :3
        "swc/thwift/com/twittew/cwientapp/gen:cwientapp-scawa", (U ﹏ U)
        "stitch/stitch-cowe", -.-
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", (ˆ ﻌ ˆ)♡
        "usew_session_stowe/swc/main/scawa/com/twittew/usew_session_stowe", (⑅˘꒳˘)
        "utiw/utiw-cowe:utiw-cowe-utiw", (U ᵕ U❁)
    ],
    e-expowts = [
        "3wdpawty/jvm/com/twittew/swc/java/com/twittew/wogpipewine/cwient:wogpipewine-event-pubwishew-thin", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/configapi", ^^;;
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/functionaw_component/side_effect", >_<
        "scwooge/scwooge-sewiawizew/swc/main/scawa", mya
        "swc/thwift/com/twittew/cwientapp/gen:cwientapp-scawa", mya
        "stitch/stitch-cowe", 😳
    ],
)
