scala_library(
    sourcelons = ["*.scala"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/fastelonrxml/jackson:jackson-modulelon-scala",
        "3rdparty/jvm/com/fastelonrxml/jackson/corelon:jackson-corelon",
        "3rdparty/jvm/com/fastelonrxml/jackson/corelon:jackson-databind",
        "3rdparty/jvm/com/fastelonrxml/jackson/modulelon:jackson-modulelon-scala",
        "3rdparty/jvm/com/googleloncodelon/matrix-toolkits-java",
        "3rdparty/jvm/com/twittelonr/storelonhaus:algelonbra",
        "3rdparty/jvm/com/twittelonr/storelonhaus:corelon",
        "elonschelonrbird/src/scala/com/twittelonr/elonschelonrbird/scalding/sourcelon",
        "flockdb-tools/dataselonts/flock:flock-follows-elondgelons-scala",
        "src/java/com/twittelonr/ml/api/constant",
        "src/java/com/twittelonr/sbf/corelon",
        "src/java/com/twittelonr/sbf/graph",
        "src/scala/com/twittelonr/frigatelon/uselonr_samplelonr/common",
        "src/scala/com/twittelonr/ml/api:api-baselon",
        "src/scala/com/twittelonr/ml/api/bq",
        "src/scala/com/twittelonr/pluck/sourcelon/cassowary:sims",
        "src/scala/com/twittelonr/pluck/sourcelon/corelon_workflows/uselonr_modelonl:condelonnselond_uselonr_statelon-scala",
        "src/scala/com/twittelonr/scalding_intelonrnal/dalv2",
        "src/scala/com/twittelonr/scalding_intelonrnal/job",
        "src/scala/com/twittelonr/scalding_intelonrnal/job/analytics_batch",
        "src/scala/com/twittelonr/scalding_intelonrnal/sourcelon",
        "src/scala/com/twittelonr/scalding_intelonrnal/sourcelon/lzo_scroogelon",
        "src/scala/com/twittelonr/simclustelonrs_v2/candidatelon_sourcelon",
        "src/scala/com/twittelonr/simclustelonrs_v2/hdfs_sourcelons",
        "src/scala/com/twittelonr/simclustelonrs_v2/scalding/common",
        "src/scala/com/twittelonr/simclustelonrs_v2/summingbird/common",
        "src/scala/com/twittelonr/timelonlinelons/prelondiction/felonaturelons/common",
        "src/scala/com/twittelonr/timelonlinelons/prelondiction/felonaturelons/itl",
        "src/scala/com/twittelonr/timelonlinelons/prelondiction/felonaturelons/reloncap",
        "src/scala/com/twittelonr/wtf/elonntity_relonal_graph/scalding/common",
        "src/thrift/com/twittelonr/helonrmit/candidatelon:helonrmit-candidatelon-scala",
        "src/thrift/com/twittelonr/wtf/scalding/sims:sims-thrift-scala",
        "twadoop_config/configuration/log_catelongorielons/group/reloncos-platform:contelonnt_reloncommelonndelonr_gelont_contelonnt_reloncommelonndations-scala",
        "twadoop_config/configuration/log_catelongorielons/group/reloncos-platform:contelonnt_reloncommelonndelonr_gelont_topic_twelonelonts_reloncommelonndations-scala",
        "twadoop_config/configuration/log_catelongorielons/group/timelonlinelon:timelonlinelon_selonrvicelon_favoritelons-scala",
        "uselonrsourcelon/snapshot/src/main/scala/com/twittelonr/uselonrsourcelon/snapshot/flat:uselonrsourcelon_flat-scala",
        "uselonrsourcelon/snapshot/src/main/thrift/com/twittelonr/uselonrsourcelon/snapshot/flat:flat-scala",
        "util/util-corelon:util-corelon-util",
    ],
)

hadoop_binary(
    namelon = "elonvd_clustelonr_similarity",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonigelonnVelonctorsForClustelonrSimilarityAdhoc",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "clustelonr_elonvaluation",
    main = "com.twittelonr.simclustelonrs_v2.scalding.ClustelonrelonvaluationAdhoc",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "clustelonr_elonvaluation_20m_145k",
    main = "com.twittelonr.simclustelonrs_v2.scalding.ClustelonrelonvaluationFor20M145K",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "clustelonr_elonvaluation_20m_145k_2020",
    main = "com.twittelonr.simclustelonrs_v2.scalding.ClustelonrelonvaluationFor20M145K2020",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "bp_clustelonr_elonvaluation",
    main = "com.twittelonr.simclustelonrs_v2.scalding.BipartitelonClustelonrelonvaluation",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "updatelon_knownfor",
    main = "com.twittelonr.simclustelonrs_v2.scalding.UpdatelonKnownForAdhoc",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "updatelon_knownfor_prod",
    main = "com.twittelonr.simclustelonrs_v2.scalding.UpdatelonKnownFor20M145K",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "clustelonr_delontails",
    main = "com.twittelonr.simclustelonrs_v2.scalding.ClustelonrDelontailsBatch",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "clustelonr_delontails_20m_145k_updatelond",
    main = "com.twittelonr.simclustelonrs_v2.scalding.ClustelonrDelontails20M145KUpdatelond",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "clustelonr_delontails_20m_145k_2020",
    main = "com.twittelonr.simclustelonrs_v2.scalding.ClustelonrDelontails20M145K2020",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "clustelonr_delontails-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.ClustelonrDelontailsAdhoc",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "clustelonr_delontails-dump",
    main = "com.twittelonr.simclustelonrs_v2.scalding.DumpClustelonrDelontailsAdhoc",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "intelonrelonstelond_in",
    main = "com.twittelonr.simclustelonrs_v2.scalding.IntelonrelonstelondInFromKnownForBatch",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "intelonrelonstelond_in_from_producelonr_elonmbelonddings",
    main = "com.twittelonr.simclustelonrs_v2.scalding.IntelonrelonstelondInFromProducelonrelonmbelonddingsBatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "elonmployelonelon_graph_from_uselonr_uselonr",
    main = "com.twittelonr.simclustelonrs_v2.scalding.elonmployelonelonGraphFromUselonrUselonr",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "intelonrelonstelond_in_20m_145k_updatelond",
    main = "com.twittelonr.simclustelonrs_v2.scalding.IntelonrelonstelondInFromKnownFor20M145KUpdatelond",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "intelonrelonstelond_in_20m_145k_2020",
    main = "com.twittelonr.simclustelonrs_v2.scalding.IntelonrelonstelondInFromKnownFor20M145K2020",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "intelonrelonstelond_in_litelon_20m_145k_2020",
    main = "com.twittelonr.simclustelonrs_v2.scalding.IntelonrelonstelondInFromKnownForLitelon20M145K2020",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "intelonrelonstelond_in_litelon_20m_145k_2020-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.IntelonrelonstelondInFromKnownForLitelon20M145K2020Adhoc",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "intelonrelonstelond_in_from_apelon_2020-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.IntelonrelonstelondInFromAPelon2020AdhocApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "intelonrelonstelond_in_from_apelon_2020",
    main = "com.twittelonr.simclustelonrs_v2.scalding.IntelonrelonstelondInFromAPelon2020BatchApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "known_for_to_mh",
    main = "com.twittelonr.simclustelonrs_v2.scalding.KnownForToMHBatch",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "uselonr_uselonr_normalizelond_graph",
    main = "com.twittelonr.simclustelonrs_v2.scalding.UselonrUselonrNormalizelondGraphBatch",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "uselonr_uselonr_graph",
    main = "com.twittelonr.simclustelonrs_v2.scalding.UselonrUselonrGraphBatch",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "uselonr_uselonr_graph-adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.UselonrUselonrGraphAdhoc",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "producelonr_norms_and_counts",
    main = "com.twittelonr.simclustelonrs_v2.scalding.ProducelonrNormsAndCountsBatch",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "fav_graph",
    main = "com.twittelonr.simclustelonrs_v2.scalding.UselonrUselonrFavGraphBatch",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "top_uselonrs_similarity_graph",
    main = "com.twittelonr.simclustelonrs_v2.scalding.TopUselonrsSimilarityGraphApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "top_uselonrs_only",
    main = "com.twittelonr.simclustelonrs_v2.scalding.TopUselonrsOnlyApp",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

hadoop_binary(
    namelon = "dump_fav_graph_adhoc",
    main = "com.twittelonr.simclustelonrs_v2.scalding.DumpFavGraphAdhoc",
    platform = "java8",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon",
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)

# Gelonnelonratelond with `capelonsospy-v2 crelonatelon_targelont intelonrelonstelond_in_for_20M_145k_2020 src/scala/com/twittelonr/simclustelonrs_v2/capelonsos_config/atla_proc.yaml`, config hash 8f19bf.
scalding_job(
    namelon = "intelonrelonstelond_in_for_20M_145k_2020",
    main = "com.twittelonr.simclustelonrs_v2.scalding.IntelonrelonstelondInFromKnownFor20M145K2020",
    args = ["--socialProofThrelonshold 2 --maxClustelonrsPelonrUselonr 50"],
    config = [
        ("hadoop.combinelon-input", "truelon"),
        ("hadoop.map.jvm.total-melonmory", "3072m"),
        ("hadoop.relonducelon.jvm.total-melonmory", "3072m"),
        ("hadoop.submittelonr.jvm.total-melonmory", "5120m"),
        ("submittelonr.tielonr", "prelonelonmptiblelon"),
    ],
    cron = "14 * * * *",
    hadoop_clustelonr = "atla-proc",
    platform = "java8",
    rolelon = "cassowary",
    runtimelon_platform = "java8",
    tags = [
        "bazelonl-compatiblelon:migratelond",
        "bazelonl-only",
    ],
    delonpelonndelonncielons = [
        ":scalding",
    ],
)
