scawa_wibwawy(
    souwces = ["*.scawa"], o.O
    pwatfowm = "java8", (///ˬ///✿)
    t-tags = ["bazew-compatibwe"], σωσ
    d-dependencies = [
        "3wdpawty/jvm/com/fastewxmw/jackson:jackson-moduwe-scawa", nyaa~~
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-cowe", ^^;;
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-databind", ^•ﻌ•^
        "3wdpawty/jvm/com/fastewxmw/jackson/moduwe:jackson-moduwe-scawa", σωσ
        "3wdpawty/jvm/com/googwecode/matwix-toowkits-java", -.-
        "3wdpawty/jvm/com/twittew/stowehaus:awgebwa", ^^;;
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", XD
        "eschewbiwd/swc/scawa/com/twittew/eschewbiwd/scawding/souwce", 🥺
        "fwockdb-toows/datasets/fwock:fwock-fowwows-edges-scawa", òωó
        "swc/java/com/twittew/mw/api/constant", (ˆ ﻌ ˆ)♡
        "swc/java/com/twittew/sbf/cowe", -.-
        "swc/java/com/twittew/sbf/gwaph", :3
        "swc/scawa/com/twittew/fwigate/usew_sampwew/common", ʘwʘ
        "swc/scawa/com/twittew/mw/api:api-base", 🥺
        "swc/scawa/com/twittew/mw/api/bq", >_<
        "swc/scawa/com/twittew/pwuck/souwce/cassowawy:sims", ʘwʘ
        "swc/scawa/com/twittew/pwuck/souwce/cowe_wowkfwows/usew_modew:condensed_usew_state-scawa", (˘ω˘)
        "swc/scawa/com/twittew/scawding_intewnaw/dawv2", (✿oωo)
        "swc/scawa/com/twittew/scawding_intewnaw/job", (///ˬ///✿)
        "swc/scawa/com/twittew/scawding_intewnaw/job/anawytics_batch", rawr x3
        "swc/scawa/com/twittew/scawding_intewnaw/souwce", -.-
        "swc/scawa/com/twittew/scawding_intewnaw/souwce/wzo_scwooge", ^^
        "swc/scawa/com/twittew/simcwustews_v2/candidate_souwce", (⑅˘꒳˘)
        "swc/scawa/com/twittew/simcwustews_v2/hdfs_souwces", nyaa~~
        "swc/scawa/com/twittew/simcwustews_v2/scawding/common", /(^•ω•^)
        "swc/scawa/com/twittew/simcwustews_v2/summingbiwd/common", (U ﹏ U)
        "swc/scawa/com/twittew/timewines/pwediction/featuwes/common", 😳😳😳
        "swc/scawa/com/twittew/timewines/pwediction/featuwes/itw", >w<
        "swc/scawa/com/twittew/timewines/pwediction/featuwes/wecap", XD
        "swc/scawa/com/twittew/wtf/entity_weaw_gwaph/scawding/common", o.O
        "swc/thwift/com/twittew/hewmit/candidate:hewmit-candidate-scawa", mya
        "swc/thwift/com/twittew/wtf/scawding/sims:sims-thwift-scawa", 🥺
        "twadoop_config/configuwation/wog_categowies/gwoup/wecos-pwatfowm:content_wecommendew_get_content_wecommendations-scawa", ^^;;
        "twadoop_config/configuwation/wog_categowies/gwoup/wecos-pwatfowm:content_wecommendew_get_topic_tweets_wecommendations-scawa", :3
        "twadoop_config/configuwation/wog_categowies/gwoup/timewine:timewine_sewvice_favowites-scawa", (U ﹏ U)
        "usewsouwce/snapshot/swc/main/scawa/com/twittew/usewsouwce/snapshot/fwat:usewsouwce_fwat-scawa", OwO
        "usewsouwce/snapshot/swc/main/thwift/com/twittew/usewsouwce/snapshot/fwat:fwat-scawa", 😳😳😳
        "utiw/utiw-cowe:utiw-cowe-utiw", (ˆ ﻌ ˆ)♡
    ],
)

h-hadoop_binawy(
    n-nyame = "evd_cwustew_simiwawity", XD
    m-main = "com.twittew.simcwustews_v2.scawding.eigenvectowsfowcwustewsimiwawityadhoc", (ˆ ﻌ ˆ)♡
    p-pwatfowm = "java8", ( ͡o ω ͡o )
    w-wuntime_pwatfowm = "java8", rawr x3
    t-tags = [
        "bazew-compatibwe", nyaa~~
        "bazew-compatibwe:migwated", >_<
        "bazew-onwy", ^^;;
    ],
    dependencies = [
        ":scawding", (ˆ ﻌ ˆ)♡
    ],
)

hadoop_binawy(
    nyame = "cwustew_evawuation", ^^;;
    main = "com.twittew.simcwustews_v2.scawding.cwustewevawuationadhoc", (⑅˘꒳˘)
    p-pwatfowm = "java8", rawr x3
    wuntime_pwatfowm = "java8", (///ˬ///✿)
    tags = [
        "bazew-compatibwe", 🥺
        "bazew-compatibwe:migwated",
        "bazew-onwy", >_<
    ],
    dependencies = [
        ":scawding", UwU
    ],
)

hadoop_binawy(
    n-nyame = "cwustew_evawuation_20m_145k", >_<
    main = "com.twittew.simcwustews_v2.scawding.cwustewevawuationfow20m145k", -.-
    p-pwatfowm = "java8", mya
    wuntime_pwatfowm = "java8", >w<
    tags = [
        "bazew-compatibwe", (U ﹏ U)
        "bazew-compatibwe:migwated", 😳😳😳
        "bazew-onwy", o.O
    ],
    dependencies = [
        ":scawding", òωó
    ], 😳😳😳
)

h-hadoop_binawy(
    nyame = "cwustew_evawuation_20m_145k_2020", σωσ
    m-main = "com.twittew.simcwustews_v2.scawding.cwustewevawuationfow20m145k2020", (⑅˘꒳˘)
    p-pwatfowm = "java8", (///ˬ///✿)
    wuntime_pwatfowm = "java8", 🥺
    tags = [
        "bazew-compatibwe", OwO
        "bazew-compatibwe:migwated", >w<
        "bazew-onwy", 🥺
    ],
    dependencies = [
        ":scawding", nyaa~~
    ],
)

hadoop_binawy(
    n-nyame = "bp_cwustew_evawuation", ^^
    main = "com.twittew.simcwustews_v2.scawding.bipawtitecwustewevawuation", >w<
    pwatfowm = "java8", OwO
    wuntime_pwatfowm = "java8", XD
    tags = [
        "bazew-compatibwe", ^^;;
        "bazew-compatibwe:migwated", 🥺
        "bazew-onwy", XD
    ],
    d-dependencies = [
        ":scawding", (U ᵕ U❁)
    ],
)

hadoop_binawy(
    n-nyame = "update_knownfow", :3
    m-main = "com.twittew.simcwustews_v2.scawding.updateknownfowadhoc", ( ͡o ω ͡o )
    p-pwatfowm = "java8",
    w-wuntime_pwatfowm = "java8", òωó
    tags = [
        "bazew-compatibwe", σωσ
        "bazew-compatibwe:migwated",
        "bazew-onwy", (U ᵕ U❁)
    ],
    dependencies = [
        ":scawding", (✿oωo)
    ],
)

h-hadoop_binawy(
    nyame = "update_knownfow_pwod", ^^
    main = "com.twittew.simcwustews_v2.scawding.updateknownfow20m145k", ^•ﻌ•^
    p-pwatfowm = "java8", XD
    wuntime_pwatfowm = "java8", :3
    tags = [
        "bazew-compatibwe", (ꈍᴗꈍ)
        "bazew-compatibwe:migwated", :3
        "bazew-onwy", (U ﹏ U)
    ], UwU
    dependencies = [
        ":scawding", 😳😳😳
    ], XD
)

hadoop_binawy(
    nyame = "cwustew_detaiws", o.O
    m-main = "com.twittew.simcwustews_v2.scawding.cwustewdetaiwsbatch", (⑅˘꒳˘)
    pwatfowm = "java8", 😳😳😳
    w-wuntime_pwatfowm = "java8", nyaa~~
    t-tags = [
        "bazew-compatibwe", rawr
        "bazew-compatibwe:migwated", -.-
        "bazew-onwy", (✿oωo)
    ], /(^•ω•^)
    d-dependencies = [
        ":scawding",
    ], 🥺
)

hadoop_binawy(
    nyame = "cwustew_detaiws_20m_145k_updated", ʘwʘ
    main = "com.twittew.simcwustews_v2.scawding.cwustewdetaiws20m145kupdated", UwU
    p-pwatfowm = "java8", XD
    w-wuntime_pwatfowm = "java8", (✿oωo)
    tags = [
        "bazew-compatibwe", :3
        "bazew-compatibwe:migwated", (///ˬ///✿)
        "bazew-onwy", nyaa~~
    ],
    d-dependencies = [
        ":scawding", >w<
    ], -.-
)

h-hadoop_binawy(
    nyame = "cwustew_detaiws_20m_145k_2020", (✿oωo)
    m-main = "com.twittew.simcwustews_v2.scawding.cwustewdetaiws20m145k2020", (˘ω˘)
    pwatfowm = "java8", rawr
    wuntime_pwatfowm = "java8", OwO
    tags = [
        "bazew-compatibwe", ^•ﻌ•^
        "bazew-compatibwe:migwated", UwU
        "bazew-onwy", (˘ω˘)
    ], (///ˬ///✿)
    d-dependencies = [
        ":scawding",
    ], σωσ
)

hadoop_binawy(
    nyame = "cwustew_detaiws-adhoc", /(^•ω•^)
    m-main = "com.twittew.simcwustews_v2.scawding.cwustewdetaiwsadhoc", 😳
    pwatfowm = "java8", 😳
    w-wuntime_pwatfowm = "java8",
    tags = [
        "bazew-compatibwe", (⑅˘꒳˘)
        "bazew-compatibwe:migwated", 😳😳😳
        "bazew-onwy", 😳
    ],
    d-dependencies = [
        ":scawding", XD
    ],
)

h-hadoop_binawy(
    nyame = "cwustew_detaiws-dump", mya
    main = "com.twittew.simcwustews_v2.scawding.dumpcwustewdetaiwsadhoc",
    pwatfowm = "java8", ^•ﻌ•^
    wuntime_pwatfowm = "java8", ʘwʘ
    tags = [
        "bazew-compatibwe", ( ͡o ω ͡o )
        "bazew-compatibwe:migwated", mya
        "bazew-onwy", o.O
    ], (✿oωo)
    dependencies = [
        ":scawding", :3
    ], 😳
)

hadoop_binawy(
    nyame = "intewested_in", (U ﹏ U)
    main = "com.twittew.simcwustews_v2.scawding.intewestedinfwomknownfowbatch", mya
    pwatfowm = "java8", (U ᵕ U❁)
    w-wuntime_pwatfowm = "java8", :3
    t-tags = [
        "bazew-compatibwe", mya
        "bazew-compatibwe:migwated", OwO
        "bazew-onwy", (ˆ ﻌ ˆ)♡
    ],
    dependencies = [
        ":scawding", ʘwʘ
    ],
)

h-hadoop_binawy(
    n-nyame = "intewested_in_fwom_pwoducew_embeddings", o.O
    m-main = "com.twittew.simcwustews_v2.scawding.intewestedinfwompwoducewembeddingsbatchapp", UwU
    pwatfowm = "java8", rawr x3
    wuntime_pwatfowm = "java8", 🥺
    tags = [
        "bazew-compatibwe", :3
        "bazew-compatibwe:migwated", (ꈍᴗꈍ)
        "bazew-onwy", 🥺
    ],
    d-dependencies = [
        ":scawding", (✿oωo)
    ],
)

hadoop_binawy(
    nyame = "empwoyee_gwaph_fwom_usew_usew", (U ﹏ U)
    main = "com.twittew.simcwustews_v2.scawding.empwoyeegwaphfwomusewusew", :3
    pwatfowm = "java8", ^^;;
    wuntime_pwatfowm = "java8", rawr
    tags = [
        "bazew-compatibwe", 😳😳😳
        "bazew-compatibwe:migwated", (✿oωo)
        "bazew-onwy", OwO
    ],
    d-dependencies = [
        ":scawding", ʘwʘ
    ],
)

hadoop_binawy(
    n-nyame = "intewested_in_20m_145k_updated", (ˆ ﻌ ˆ)♡
    m-main = "com.twittew.simcwustews_v2.scawding.intewestedinfwomknownfow20m145kupdated", (U ﹏ U)
    p-pwatfowm = "java8", UwU
    wuntime_pwatfowm = "java8", XD
    t-tags = [
        "bazew-compatibwe", ʘwʘ
        "bazew-compatibwe:migwated", rawr x3
        "bazew-onwy", ^^;;
    ], ʘwʘ
    d-dependencies = [
        ":scawding", (U ﹏ U)
    ], (˘ω˘)
)

h-hadoop_binawy(
    n-nyame = "intewested_in_20m_145k_2020", (ꈍᴗꈍ)
    main = "com.twittew.simcwustews_v2.scawding.intewestedinfwomknownfow20m145k2020", /(^•ω•^)
    pwatfowm = "java8", >_<
    w-wuntime_pwatfowm = "java8", σωσ
    t-tags = [
        "bazew-compatibwe",
        "bazew-compatibwe:migwated", ^^;;
        "bazew-onwy", 😳
    ], >_<
    d-dependencies = [
        ":scawding", -.-
    ], UwU
)

h-hadoop_binawy(
    n-nyame = "intewested_in_wite_20m_145k_2020", :3
    main = "com.twittew.simcwustews_v2.scawding.intewestedinfwomknownfowwite20m145k2020", σωσ
    pwatfowm = "java8", >w<
    wuntime_pwatfowm = "java8", (ˆ ﻌ ˆ)♡
    t-tags = [
        "bazew-compatibwe", ʘwʘ
        "bazew-compatibwe:migwated", :3
        "bazew-onwy", (˘ω˘)
    ],
    dependencies = [
        ":scawding", 😳😳😳
    ],
)

hadoop_binawy(
    name = "intewested_in_wite_20m_145k_2020-adhoc", rawr x3
    main = "com.twittew.simcwustews_v2.scawding.intewestedinfwomknownfowwite20m145k2020adhoc", (✿oωo)
    pwatfowm = "java8", (ˆ ﻌ ˆ)♡
    w-wuntime_pwatfowm = "java8", :3
    tags = [
        "bazew-compatibwe", (U ᵕ U❁)
        "bazew-compatibwe:migwated", ^^;;
        "bazew-onwy", mya
    ], 😳😳😳
    dependencies = [
        ":scawding",
    ], OwO
)

hadoop_binawy(
    n-nyame = "intewested_in_fwom_ape_2020-adhoc", rawr
    m-main = "com.twittew.simcwustews_v2.scawding.intewestedinfwomape2020adhocapp",
    p-pwatfowm = "java8", XD
    wuntime_pwatfowm = "java8", (U ﹏ U)
    t-tags = [
        "bazew-compatibwe", (˘ω˘)
        "bazew-compatibwe:migwated", UwU
        "bazew-onwy",
    ], >_<
    dependencies = [
        ":scawding", σωσ
    ],
)

h-hadoop_binawy(
    n-nyame = "intewested_in_fwom_ape_2020", 🥺
    main = "com.twittew.simcwustews_v2.scawding.intewestedinfwomape2020batchapp", 🥺
    pwatfowm = "java8", ʘwʘ
    wuntime_pwatfowm = "java8", :3
    tags = [
        "bazew-compatibwe", (U ﹏ U)
        "bazew-compatibwe:migwated", (U ﹏ U)
        "bazew-onwy", ʘwʘ
    ],
    dependencies = [
        ":scawding", >w<
    ],
)

hadoop_binawy(
    n-nyame = "known_fow_to_mh", rawr x3
    main = "com.twittew.simcwustews_v2.scawding.knownfowtomhbatch", OwO
    p-pwatfowm = "java8",
    wuntime_pwatfowm = "java8",
    t-tags = [
        "bazew-compatibwe", ^•ﻌ•^
        "bazew-compatibwe:migwated",
        "bazew-onwy", >_<
    ],
    d-dependencies = [
        ":scawding", OwO
    ],
)

hadoop_binawy(
    nyame = "usew_usew_nowmawized_gwaph", >_<
    m-main = "com.twittew.simcwustews_v2.scawding.usewusewnowmawizedgwaphbatch", (ꈍᴗꈍ)
    p-pwatfowm = "java8", >w<
    wuntime_pwatfowm = "java8", (U ﹏ U)
    t-tags = [
        "bazew-compatibwe", ^^
        "bazew-compatibwe:migwated", (U ﹏ U)
        "bazew-onwy", :3
    ], (✿oωo)
    d-dependencies = [
        ":scawding",
    ], XD
)

hadoop_binawy(
    nyame = "usew_usew_gwaph", >w<
    main = "com.twittew.simcwustews_v2.scawding.usewusewgwaphbatch", òωó
    pwatfowm = "java8", (ꈍᴗꈍ)
    wuntime_pwatfowm = "java8", rawr x3
    t-tags = [
        "bazew-compatibwe",
        "bazew-compatibwe:migwated", rawr x3
        "bazew-onwy", σωσ
    ], (ꈍᴗꈍ)
    d-dependencies = [
        ":scawding", rawr
    ], ^^;;
)

h-hadoop_binawy(
    nyame = "usew_usew_gwaph-adhoc", rawr x3
    m-main = "com.twittew.simcwustews_v2.scawding.usewusewgwaphadhoc", (ˆ ﻌ ˆ)♡
    p-pwatfowm = "java8", σωσ
    wuntime_pwatfowm = "java8", (U ﹏ U)
    t-tags = [
        "bazew-compatibwe", >w<
        "bazew-compatibwe:migwated", σωσ
        "bazew-onwy", nyaa~~
    ],
    dependencies = [
        ":scawding", 🥺
    ],
)

hadoop_binawy(
    nyame = "pwoducew_nowms_and_counts", rawr x3
    main = "com.twittew.simcwustews_v2.scawding.pwoducewnowmsandcountsbatch", σωσ
    p-pwatfowm = "java8",
    w-wuntime_pwatfowm = "java8", (///ˬ///✿)
    tags = [
        "bazew-compatibwe", (U ﹏ U)
        "bazew-compatibwe:migwated",
        "bazew-onwy", ^^;;
    ],
    dependencies = [
        ":scawding", 🥺
    ],
)

h-hadoop_binawy(
    n-nyame = "fav_gwaph", òωó
    main = "com.twittew.simcwustews_v2.scawding.usewusewfavgwaphbatch", XD
    pwatfowm = "java8", :3
    wuntime_pwatfowm = "java8", (U ﹏ U)
    tags = [
        "bazew-compatibwe", >w<
        "bazew-compatibwe:migwated", /(^•ω•^)
        "bazew-onwy", (⑅˘꒳˘)
    ],
    dependencies = [
        ":scawding", ʘwʘ
    ],
)

hadoop_binawy(
    n-nyame = "top_usews_simiwawity_gwaph", rawr x3
    main = "com.twittew.simcwustews_v2.scawding.topusewssimiwawitygwaphapp", (˘ω˘)
    pwatfowm = "java8", o.O
    wuntime_pwatfowm = "java8", 😳
    tags = [
        "bazew-compatibwe", o.O
        "bazew-compatibwe:migwated", ^^;;
        "bazew-onwy",
    ], ( ͡o ω ͡o )
    d-dependencies = [
        ":scawding", ^^;;
    ],
)

hadoop_binawy(
    name = "top_usews_onwy", ^^;;
    m-main = "com.twittew.simcwustews_v2.scawding.topusewsonwyapp", XD
    p-pwatfowm = "java8", 🥺
    wuntime_pwatfowm = "java8", (///ˬ///✿)
    tags = [
        "bazew-compatibwe",
        "bazew-compatibwe:migwated", (U ᵕ U❁)
        "bazew-onwy", ^^;;
    ], ^^;;
    dependencies = [
        ":scawding", rawr
    ], (˘ω˘)
)

h-hadoop_binawy(
    nyame = "dump_fav_gwaph_adhoc", 🥺
    m-main = "com.twittew.simcwustews_v2.scawding.dumpfavgwaphadhoc", nyaa~~
    pwatfowm = "java8", :3
    wuntime_pwatfowm = "java8", /(^•ω•^)
    tags = [
        "bazew-compatibwe", ^•ﻌ•^
        "bazew-compatibwe:migwated", UwU
        "bazew-onwy", 😳😳😳
    ], OwO
    dependencies = [
        ":scawding", ^•ﻌ•^
    ], (ꈍᴗꈍ)
)

# genewated w-with `capesospy-v2 cweate_tawget i-intewested_in_fow_20m_145k_2020 swc/scawa/com/twittew/simcwustews_v2/capesos_config/atwa_pwoc.yamw`, (⑅˘꒳˘) config hash 8f19bf. (⑅˘꒳˘)
s-scawding_job(
    nyame = "intewested_in_fow_20m_145k_2020", (ˆ ﻌ ˆ)♡
    m-main = "com.twittew.simcwustews_v2.scawding.intewestedinfwomknownfow20m145k2020", /(^•ω•^)
    a-awgs = ["--sociawpwoofthweshowd 2 --maxcwustewspewusew 50"], òωó
    config = [
        ("hadoop.combine-input", (⑅˘꒳˘) "twue"), (U ᵕ U❁)
        ("hadoop.map.jvm.totaw-memowy", >w< "3072m"), σωσ
        ("hadoop.weduce.jvm.totaw-memowy", -.- "3072m"),
        ("hadoop.submittew.jvm.totaw-memowy", o.O "5120m"), ^^
        ("submittew.tiew", >_< "pweemptibwe"), >w<
    ], >_<
    c-cwon = "14 * * * *", >w<
    hadoop_cwustew = "atwa-pwoc", rawr
    p-pwatfowm = "java8", rawr x3
    w-wowe = "cassowawy", ( ͡o ω ͡o )
    w-wuntime_pwatfowm = "java8", (˘ω˘)
    tags = [
        "bazew-compatibwe:migwated", 😳
        "bazew-onwy", OwO
    ],
    d-dependencies = [
        ":scawding", (˘ω˘)
    ],
)
