scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finatra/thrift/src/main/scala/com/twittelonr/finatra/thrift",
        "finatra/thrift/src/main/scala/com/twittelonr/finatra/thrift:controllelonr",
        "finatra/thrift/src/main/scala/com/twittelonr/finatra/thrift/elonxcelonptions",
        "finatra/thrift/src/main/scala/com/twittelonr/finatra/thrift/filtelonrs",
        "finatra/thrift/src/main/scala/com/twittelonr/finatra/thrift/modulelons",
        "finatra/thrift/src/main/scala/com/twittelonr/finatra/thrift/relonsponselon",
        "finatra/thrift/src/main/scala/com/twittelonr/finatra/thrift/routing",
    ],
)
