scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", (U ᵕ U❁)
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", (⑅˘꒳˘)
        "3wdpawty/jvm/net/codingweww:scawa-guice", ( ͡o ω ͡o )
        "3wdpawty/jvm/owg/swf4j:swf4j-api", UwU
        "cowtex-deepbiwd/pwediction/swc/main/scawa/com/twittew/cowtex/deepbiwd/pwediction", rawr x3
        "cowtex-deepbiwd/thwift/swc/main/thwift:thwift-java", rawr
        "finatwa-intewnaw/mtws-thwiftmux/swc/main/scawa", σωσ
        "finatwa/inject/inject-cowe/swc/main/scawa", σωσ
        "finatwa/inject/inject-thwift-cwient/swc/main/scawa", >_<
        "fowwow-wecommendations-sewvice/common/swc/main/scawa/com/twittew/fowwow_wecommendations/common/cwients/common", :3
        "swc/scawa/com/twittew/mw/api/utiw", (U ﹏ U)
        "utiw/utiw-cowe:scawa", -.-
    ],
)
