java_wibwawy(
    souwces = ["*.java"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8",
    t-tags = ["bazew-compatibwe"], òωó
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/distwibutedwog:distwibutedwog-cowe", o.O
        "3wdpawty/jvm/commons-wogging", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/kafka:kafka-cwients",
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ( ͡o ω ͡o )
        "cuad/pwojects/new/cwient/swc/main/scawa/com/twittew/cuad/new/cwient", UwU
        "decidew/swc/main/scawa", rawr x3
        "eventbus/cwient/swc/main/scawa/com/twittew/eventbus/cwient", rawr
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", σωσ
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authowization", σωσ
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/cwient", >_<
        "finagwe/finagwe-cowe/swc/main", :3
        "finagwe/finagwe-thwift/swc/main/java", (U ﹏ U)
        "finagwe/finagwe-thwift/swc/main/scawa", -.-
        "finagwe/finagwe-thwiftmux/swc/main/scawa", (ˆ ﻌ ˆ)♡
        "kafka/finagwe-kafka/finatwa-kafka/swc/main/scawa", (⑅˘꒳˘)
        "sewvo/utiw/swc/main/scawa", (U ᵕ U❁)
        "swc/java/com/twittew/common/quantity", -.-
        "swc/java/com/twittew/common/utiw:system-mocks", ^^;;
        "swc/java/com/twittew/common_intewnaw/manhattan", >_<
        "swc/java/com/twittew/common_intewnaw/text/vewsion", mya
        "swc/java/com/twittew/common_intewnaw/zookeepew", mya
        "swc/java/com/twittew/metastowe/cwient_v2", 😳
        "swc/java/com/twittew/seawch/common/decidew", XD
        "swc/java/com/twittew/seawch/common/pawtitioning:timeswice-managew", :3
        "swc/java/com/twittew/seawch/common/pawtitioning/base", 😳😳😳
        "swc/java/com/twittew/seawch/common/wewevance:cwassifiews", -.-
        "swc/java/com/twittew/seawch/common/schema/eawwybiwd", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/utiw/io:dw-weadew-wwitew", rawr x3
        "swc/java/com/twittew/seawch/common/utiw/io:wecowd-weadew-api", nyaa~~
        "swc/java/com/twittew/seawch/common/utiw/io/kafka", /(^•ω•^)
        "swc/java/com/twittew/seawch/common/utiw/thwift:text-pwotocow",
        "swc/java/com/twittew/seawch/ingestew/pipewine/stwato_fetchews", rawr
        "swc/java/com/twittew/seawch/ingestew/pipewine/utiw", OwO
        "swc/thwift/com/twittew/gizmoduck:thwift-java", (U ﹏ U)
        "swc/thwift/com/twittew/manhattan:intewnaw-scawa", >_<
        "swc/thwift/com/twittew/manhattan:v1-java", rawr x3
        "swc/thwift/com/twittew/pink-fwoyd/thwift:thwift-java", mya
        "swc/thwift/com/twittew/tweetypie:sewvice-java", nyaa~~
        "stowage/cwients/manhattan/cwient/swc/main/scawa", (⑅˘꒳˘)
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", rawr x3
        "utiw/utiw-cowe:scawa", (✿oωo)
        "utiw/utiw-function/swc/main/java", (ˆ ﻌ ˆ)♡
        "utiw/utiw-stats/swc/main/scawa", (˘ω˘)
    ],
)
