scawa_wibwawy(
    nyame = "usew-video-gwaph", (⑅˘꒳˘)
    souwces = ["*.scawa"], ( ͡o ω ͡o )
    t-tags = [
        "bazew-compatibwe", UwU
        "bazew-onwy", rawr x3
    ], rawr
    d-dependencies = [
        "3wdpawty/jvm/cascading:cascading-wocaw", σωσ
        "3wdpawty/jvm/com/backtype:dfs-datastowes", σωσ
        "3wdpawty/jvm/com/fastewxmw/jackson/moduwe:jackson-moduwe-scawa", >_<
        "3wdpawty/jvm/com/googwe/inject:guice", :3
        "3wdpawty/jvm/com/netfwix/cuwatow:cuwatow-fwamewowk", (U ﹏ U)
        "3wdpawty/jvm/com/twittew/gwaphjet", -.-
        "3wdpawty/jvm/io/netty:netty4-tcnative-bowingssw-static", (ˆ ﻌ ˆ)♡
        "3wdpawty/jvm/it/unimi/dsi:fastutiw", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/hadoop:hadoop-cwient-defauwt", (U ᵕ U❁)
        "3wdpawty/jvm/owg/apache/kafka:wosette-kafka", -.-
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ^^;;
        "abdecidew/swc/main/scawa", >_<
        "decidew/swc/main/scawa", mya
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/authentication", mya
        "finagwe-intewnaw/mtws/swc/main/scawa/com/twittew/finagwe/mtws/sewvew", 😳
        "finagwe/finagwe-cowe/swc/main", XD
        "finagwe/finagwe-http/swc/main/scawa", :3
        "finagwe/finagwe-memcached/swc/main/scawa", 😳😳😳
        "finagwe/finagwe-stats/swc/main/scawa", -.-
        "finagwe/finagwe-thwiftmux/swc/main/scawa", ( ͡o ω ͡o )
        "fwigate/fwigate-common/swc/main/scawa/com/twittew/fwigate/common/utiw", rawr x3
        "scwooge/scwooge-cowe/swc/main/scawa", nyaa~~
        "sewvo/wepo/swc/main/scawa", /(^•ω•^)
        "sewvo/wequest/swc/main/scawa", rawr
        "sewvo/utiw/swc/main/scawa", OwO
        "swc/wesouwces/com/twittew/wecos:decidew", (U ﹏ U)
        "swc/scawa/com/twittew/wecos/decidew",
        "swc/scawa/com/twittew/wecos/gwaph_common", >_<
        "swc/scawa/com/twittew/wecos/hose/common", rawr x3
        "swc/scawa/com/twittew/wecos/modew:wecos-modew",
        "swc/scawa/com/twittew/wecos/sewviceapi", mya
        "swc/scawa/com/twittew/wecos/usew_video_gwaph/wewatedtweethandwews", nyaa~~
        "swc/scawa/com/twittew/wecos/usew_video_gwaph/stowe", (⑅˘꒳˘)
        "swc/scawa/com/twittew/wecos/utiw:wecos-utiw", rawr x3
        "swc/scawa/com/twittew/simcwustews_v2/common", (✿oωo)
        "swc/thwift/com/twittew/wecos:wecos-common-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/wecos:wecos-intewnaw-scawa", (˘ω˘)
        "swc/thwift/com/twittew/wecos/usew_video_gwaph:usew_video_gwaph-scawa", (⑅˘꒳˘)
        "thwift-web-fowms/swc/main/scawa/com/twittew/thwiftwebfowms", (///ˬ///✿)
        "thwift-web-fowms/swc/main/scawa/com/twittew/thwiftwebfowms/modew", 😳😳😳
        "twittew-sewvew-intewnaw/swc/main/scawa", 🥺
        "twittew-sewvew/sewvew/swc/main/scawa", mya
        "twittew-sewvew/swf4j-jdk14/swc/main/scawa/com/twittew/sewvew/wogging", 🥺
        "utiw/utiw-app/swc/main/scawa", >_<
        "utiw/utiw-hashing/swc/main/scawa", >_<
        "utiw/utiw-stats/swc/main/scawa", (⑅˘꒳˘)
    ],
)

j-jvm_binawy(
    n-nyame = "bin", /(^•ω•^)
    b-basename = "usew-video-gwaph-sewvew", rawr x3
    m-main = "com.twittew.wecos.usew_video_gwaph.main", (U ﹏ U)
    w-wuntime_pwatfowm = "java11", (U ﹏ U)
    tags = ["known-to-faiw-jiwa:sd-20771"], (⑅˘꒳˘)
    d-dependencies = [
        ":usew-video-gwaph", òωó
        "3wdpawty/jvm/owg/swf4j:swf4j-jdk14", ʘwʘ
        "twittew-sewvew/swf4j-jdk14/swc/main/scawa", /(^•ω•^)
    ], ʘwʘ
)
