scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/bijection:cowe", (U ᵕ U❁)
        "ann/swc/main/scawa/com/twittew/ann/common", (⑅˘꒳˘)
        "ann/swc/main/thwift/com/twittew/ann/sewiawization:sewiawization-scawa", ( ͡o ω ͡o )
        "mediasewvices/commons", UwU
        "scwooge/scwooge-cowe", rawr x3
        "swc/scawa/com/twittew/scawding_intewnaw/muwtifowmat/fowmat", rawr
    ], σωσ
)
