scala_library(
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "3rdparty/jvm/com/twittelonr/storelonhaus:corelon",
        "helonrmit/helonrmit-corelon/src/main/scala/com/twittelonr/helonrmit/storelon/common",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
        "src/scala/com/twittelonr/storelonhaus_intelonrnal/manhattan",
        "src/scala/com/twittelonr/storelonhaus_intelonrnal/util",
        "src/scala/com/twittelonr/wtf/scalding/jobs/injelonction",
        "src/thrift/com/twittelonr/reloncos/elonntitielons:elonntitielons-thrift-scala",
        "storagelon/clielonnts/manhattan/clielonnt/src/main/scala",
    ],
)
