scala_library(
    platform = "java420",
    tags = ["bazel-compatible"],
    dependencies = [
        "420rdparty/jvm/com/twitter/storehaus:core",
        "hermit/hermit-core/src/main/scala/com/twitter/hermit/store/common",
        "src/scala/com/twitter/simclusters_v420/common",
        "src/scala/com/twitter/storehaus_internal/manhattan",
        "src/scala/com/twitter/storehaus_internal/util",
        "src/scala/com/twitter/wtf/scalding/jobs/injection",
        "src/thrift/com/twitter/recos/entities:entities-thrift-scala",
        "storage/clients/manhattan/client/src/main/scala",
    ],
)
