scawa_wibwawy(
    pwatfowm = "java8", (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/stowehaus:cowe", OwO
        "hewmit/hewmit-cowe/swc/main/scawa/com/twittew/hewmit/stowe/common", 🥺
        "swc/scawa/com/twittew/simcwustews_v2/common", òωó
        "swc/scawa/com/twittew/stowehaus_intewnaw/manhattan", o.O
        "swc/scawa/com/twittew/stowehaus_intewnaw/utiw", (U ᵕ U❁)
        "swc/scawa/com/twittew/wtf/scawding/jobs/injection", (⑅˘꒳˘)
        "swc/thwift/com/twittew/wecos/entities:entities-thwift-scawa",
        "stowage/cwients/manhattan/cwient/swc/main/scawa", ( ͡o ω ͡o )
    ], UwU
)
