target(
    dependencies = [
        "visibility/lib/src/main/scala/com/X/visibility",
    ],
)

target(
    name = "conversations",
    dependencies = [
        "visibility/lib/src/main/scala/com/X/visibility/interfaces/common/tweets",
        "visibility/lib/src/main/scala/com/X/visibility/interfaces/conversations",
    ],
)

target(
    name = "tweets",
    dependencies = [
        "visibility/lib/src/main/scala/com/X/visibility/generators",
        "visibility/lib/src/main/scala/com/X/visibility/interfaces/common/tweets",
        "visibility/lib/src/main/scala/com/X/visibility/interfaces/tweets",
    ],
)

target(
    name = "users",
    dependencies = [
        "visibility/lib/src/main/scala/com/X/visibility/interfaces/users",
    ],
)
