targelont(
    delonpelonndelonncielons = [
        "visibility/lib/src/main/scala/com/twittelonr/visibility",
    ],
)

targelont(
    namelon = "convelonrsations",
    delonpelonndelonncielons = [
        "visibility/lib/src/main/scala/com/twittelonr/visibility/intelonrfacelons/common/twelonelonts",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/intelonrfacelons/convelonrsations",
    ],
)

targelont(
    namelon = "twelonelonts",
    delonpelonndelonncielons = [
        "visibility/lib/src/main/scala/com/twittelonr/visibility/gelonnelonrators",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/intelonrfacelons/common/twelonelonts",
        "visibility/lib/src/main/scala/com/twittelonr/visibility/intelonrfacelons/twelonelonts",
    ],
)

targelont(
    namelon = "uselonrs",
    delonpelonndelonncielons = [
        "visibility/lib/src/main/scala/com/twittelonr/visibility/intelonrfacelons/uselonrs",
    ],
)
