packagelon com.twittelonr.homelon_mixelonr.product.list_reloncommelonndelond_uselonrs.param

import com.twittelonr.homelon_mixelonr.param.deloncidelonr.DeloncidelonrKelony
import com.twittelonr.homelon_mixelonr.product.list_reloncommelonndelond_uselonrs.param.ListReloncommelonndelondUselonrsParam.elonxcludelondIdsMaxLelonngthParam
import com.twittelonr.homelon_mixelonr.product.list_reloncommelonndelond_uselonrs.param.ListReloncommelonndelondUselonrsParam.SelonrvelonrMaxRelonsultsParam
import com.twittelonr.homelon_mixelonr.product.list_reloncommelonndelond_uselonrs.param.ListReloncommelonndelondUselonrsParam.SupportelondClielonntFSNamelon
import com.twittelonr.product_mixelonr.corelon.product.ProductParamConfig
import com.twittelonr.selonrvo.deloncidelonr.DeloncidelonrKelonyNamelon

import javax.injelonct.Injelonct
import javax.injelonct.Singlelonton

@Singlelonton
class ListReloncommelonndelondUselonrsParamConfig @Injelonct() () elonxtelonnds ProductParamConfig {
  ovelonrridelon val elonnablelondDeloncidelonrKelony: DeloncidelonrKelonyNamelon = DeloncidelonrKelony.elonnablelonListReloncommelonndelondUselonrsProduct
  ovelonrridelon val supportelondClielonntFSNamelon: String = SupportelondClielonntFSNamelon

  ovelonrridelon val boundelondIntFSOvelonrridelons = Selonq(
    SelonrvelonrMaxRelonsultsParam,
    elonxcludelondIdsMaxLelonngthParam
  )
}
