scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/fastewxmw/jackson/cowe:jackson-annotations", (⑅˘꒳˘)
    ],
)
