scawa_wibwawy(
    souwces = ["*.scawa"], 🥺
    compiwew_option_sets = ["fataw_wawnings"], òωó
    s-stwict_deps = t-twue, o.O
    t-tags = ["bazew-compatibwe"], (U ᵕ U❁)
    d-dependencies = [
        "3wdpawty/jvm/com/twittew/bijection:scwooge", (⑅˘꒳˘)
        "3wdpawty/jvm/owg/apache/thwift:wibthwift", ( ͡o ω ͡o )
        "cowe-app-sewvices/faiwed_task:wwitew", UwU
        "cowe-app-sewvices/wib:cowesewvices", rawr x3
        "finagwe/finagwe-cowe/swc/main", rawr
        "finagwe/finagwe-mux/swc/main/scawa", σωσ
        "finagwe/finagwe-stats", σωσ
        "quiww/captuwe", >_<
        "quiww/cowe/swc/main/thwift:thwift-scawa", :3
        "scwooge/scwooge-cowe/swc/main/scawa", (U ﹏ U)
        "tweetypie/sewvo/wequest/swc/main/scawa", -.-
        "tweetypie/sewvo/utiw", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/sewvo:sewvo-exception-scawa", (⑅˘꒳˘)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:dewete_wocation_data-scawa", (U ᵕ U❁)
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:sewvice-scawa", -.-
        "tweetypie/common/swc/thwift/com/twittew/tweetypie:tweet-scawa", ^^;;
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie", >_<
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/cowe", mya
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/handwew", mya
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/sewvewutiw", 😳
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/sewvice/obsewvew", XD
        "tweetypie/sewvew/swc/main/scawa/com/twittew/tweetypie/stowe", :3
        "tweetypie/sewvew/swc/main/thwift:compiwed-scawa", 😳😳😳
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/additionawfiewds", -.-
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/cwient_id", ( ͡o ω ͡o )
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/context", rawr x3
        "tweetypie/common/swc/scawa/com/twittew/tweetypie/thwiftscawa", nyaa~~
        "twittew-sewvew-intewnaw", /(^•ω•^)
        "utiw/utiw-swf4j-api/swc/main/scawa/com/twittew/utiw/wogging", rawr
        "utiw/utiw-stats/swc/main/scawa", OwO
    ],
)
