cweate_thwift_wibwawies(
    owg = "com.twittew", o.O
    base_name = "unified_usew_actions", (U ᵕ U❁)
    s-souwces = ["*.thwift"], (⑅˘꒳˘)
    t-tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependency_woots = [
        "swc/thwift/com/twittew/cwientapp/gen:cwientapp", UwU
        "swc/thwift/com/twittew/gizmoduck:thwift", rawr x3
        "swc/thwift/com/twittew/gizmoduck:usew-thwift", rawr
        "swc/thwift/com/twittew/seawch/common:constants", σωσ
        "swc/thwift/com/twittew/sociawgwaph:thwift", σωσ
    ],
    g-genewate_wanguages = [
        "java", >_<
        "scawa", :3
        "stwato",
    ], (U ﹏ U)
    p-pwovides_java_name = "unified_usew_actions-thwift-java", -.-
    p-pwovides_scawa_name = "unified_usew_actions-thwift-scawa", (ˆ ﻌ ˆ)♡
)
