target(
    tags = ["bazel-compatible"],
    dependencies = [
        "tweetypie/server/src/main/scala/com/twitter/tweetypie",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/backends",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/config",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/core",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/handler",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/hydrator",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/media",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/repository",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/serverutil",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/service",
        "tweetypie/server/src/main/scala/com/twitter/tweetypie/store",
    ],
)