target(
    tags = ["bazel-compatible"],
    dependencies = [
        "tweetypie/server/src/main/scala/com/X/tweetypie",
        "tweetypie/server/src/main/scala/com/X/tweetypie/backends",
        "tweetypie/server/src/main/scala/com/X/tweetypie/config",
        "tweetypie/server/src/main/scala/com/X/tweetypie/core",
        "tweetypie/server/src/main/scala/com/X/tweetypie/handler",
        "tweetypie/server/src/main/scala/com/X/tweetypie/hydrator",
        "tweetypie/server/src/main/scala/com/X/tweetypie/media",
        "tweetypie/server/src/main/scala/com/X/tweetypie/repository",
        "tweetypie/server/src/main/scala/com/X/tweetypie/serverutil",
        "tweetypie/server/src/main/scala/com/X/tweetypie/service",
        "tweetypie/server/src/main/scala/com/X/tweetypie/store",
    ],
)