crelonatelon_thrift_librarielons(
    baselon_namelon = "ann-common",
    sourcelons = ["*.thrift"],
    platform = "java8",
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncy_roots = [
        "melondiaselonrvicelons/commons/src/main/thrift",
        "src/thrift/com/twittelonr/ml/api:elonmbelondding",
    ],
    gelonnelonratelon_languagelons = [
        "java",
        "python",
        "scala",
        "strato",
    ],
    providelons_java_namelon = "ann-common-thrift-java",
    providelons_scala_namelon = "ann-common-thrift-scala",
)
