cweate_thwift_wibwawies(
    base_name = "ann-common", òωó
    souwces = ["*.thwift"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    t-tags = ["bazew-compatibwe"], (⑅˘꒳˘)
    dependency_woots = [
        "mediasewvices/commons/swc/main/thwift", ( ͡o ω ͡o )
        "swc/thwift/com/twittew/mw/api:embedding", UwU
    ], rawr x3
    g-genewate_wanguages = [
        "java",
        "python", rawr
        "scawa", σωσ
        "stwato", σωσ
    ],
    p-pwovides_java_name = "ann-common-thwift-java", >_<
    p-pwovides_scawa_name = "ann-common-thwift-scawa", :3
)
