scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "configapi/configapi-corelon",
        "contelonnt-reloncommelonndelonr/thrift/src/main/thrift:thrift-scala",
        "cr-mixelonr/thrift/src/main/thrift:thrift-scala",
        "product-mixelonr/corelon/src/main/thrift/com/twittelonr/product_mixelonr/corelon:thrift-scala",
        "src/scala/com/twittelonr/simclustelonrs_v2/common",
        "src/thrift/com/twittelonr/corelon_workflows/uselonr_modelonl:uselonr_modelonl-scala",
        "src/thrift/com/twittelonr/reloncos:reloncos-common-scala",
        "src/thrift/com/twittelonr/simclustelonrs_v2:simclustelonrs_v2-thrift-scala",
    ],
)
