java_wibwawy(
    souwces = ["*.java"], ^•ﻌ•^
    pwatfowm = "java8", OwO
    t-tags = ["bazew-compatibwe"], 🥺
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/guava", òωó
        "3wdpawty/jvm/com/googwe/inject:guice", o.O
        "3wdpawty/jvm/owg/swf4j:swf4j-api", (U ᵕ U❁)
        "finatwa/inject/inject-cowe/swc/main/scawa", (⑅˘꒳˘)
        "swc/java/com/twittew/common/cowwections", ( ͡o ω ͡o )
        "swc/java/com/twittew/seawch/common/decidew", UwU
        "swc/java/com/twittew/seawch/common/futuwes", rawr x3
        "swc/java/com/twittew/seawch/common/metwics", rawr
        "swc/java/com/twittew/seawch/common/pawtitioning/snowfwakepawsew", σωσ
        "swc/java/com/twittew/seawch/common/utiw/eawwybiwd",
        "swc/java/com/twittew/seawch/eawwybiwd/common", σωσ
        "swc/java/com/twittew/seawch/eawwybiwd/config",
        "swc/java/com/twittew/seawch/eawwybiwd_woot/common", >_<
        "swc/java/com/twittew/seawch/eawwybiwd_woot/fiwtews", :3
        "swc/java/com/twittew/seawch/eawwybiwd_woot/mewgews", (U ﹏ U)
        "swc/java/com/twittew/seawch/quewypawsew", -.-
        "swc/java/com/twittew/seawch/quewypawsew/quewy:cowe-quewy-nodes", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/seawch:eawwybiwd-java", (⑅˘꒳˘)
    ], (U ᵕ U❁)
)
