scala_library(
    platform = "java11",
    strict_deps = False,
    tags = ["bazel-compatible"],
    dependencies = [
        "3rdparty/jvm/com/X/graphjet",
        "finagle/finagle-stats",
        "recos-injector/server/src/main/scala/com/X/recosinjector/clients",
        "src/scala/com/X/recos/util:recos-util",
        "src/thrift/com/X/tweetypie:tweet-scala",
    ],
)
