scawa_wibwawy(
    souwces = ["*.scawa"], òωó
    compiwew_option_sets = ["fataw_wawnings"], o.O
    p-pwatfowm = "java8", (U ᵕ U❁)
    s-stwict_deps = t-twue, (⑅˘꒳˘)
    tags = ["bazew-compatibwe"], ( ͡o ω ͡o )
    d-dependencies = [
        "decidew/swc/main/scawa", UwU
        "sewvo/decidew/swc/main/scawa",
        "swc/scawa/com/twittew/seawch/bwendew/sewvices/stwato",
        "swc/thwift/com/twittew/eschewbiwd:media-annotation-stwucts-scawa", rawr x3
        "swc/thwift/com/twittew/gizmoduck:usew-thwift-scawa", rawr
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", σωσ
        "swc/thwift/com/twittew/spam/wtf:tweet-wtf-event-scawa", σωσ
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", >_<
        "stitch/stitch-cowe", :3
        "stwato/swc/main/scawa/com/twittew/stwato/cwient", (U ﹏ U)
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", -.-
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common/stitch", (ˆ ﻌ ˆ)♡
        "visibiwity/wib/swc/main/wesouwces/config", (⑅˘꒳˘)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", (U ᵕ U❁)
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/common", -.-
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/spaces", ^^;;
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/tweets", >_<
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/buiwdew/usews", mya
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/configapi/configs", mya
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/featuwes", 😳
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/intewfaces/common/tweets", XD
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes/pwovidews", :3
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/wuwes/utiws", 😳😳😳
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity/utiw", -.-
    ],
    e-expowts = [
        "visibiwity/common/swc/main/scawa/com/twittew/visibiwity/common", ( ͡o ω ͡o )
        "visibiwity/wib/swc/main/scawa/com/twittew/visibiwity", rawr x3
    ], nyaa~~
)
