scawa_wibwawy(
    compiwew_option_sets = ["fataw_wawnings"], (ꈍᴗꈍ)
    tags = ["bazew-compatibwe"], ^•ﻌ•^
    d-dependencies = [
        "3wdpawty/jvm/com/googwe/inject:guice", OwO
        "3wdpawty/jvm/com/googwe/inject/extensions:guice-assistedinject", 🥺
        "3wdpawty/jvm/javax/inject:javax.inject", òωó
        "3wdpawty/jvm/net/codingweww:scawa-guice", o.O
        "3wdpawty/jvm/owg/swf4j:swf4j-api",
        "decidew/swc/main/scawa", (U ᵕ U❁)
        "finagwe/finagwe-cowe/swc/main", (⑅˘꒳˘)
        "finatwa/inject/inject-cowe/swc/main/scawa",
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift", ( ͡o ω ͡o )
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift:contwowwew", UwU
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/exceptions", rawr x3
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/fiwtews", rawr
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/moduwes", σωσ
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/wesponse", σωσ
        "finatwa/thwift/swc/main/scawa/com/twittew/finatwa/thwift/wouting", >_<
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/configapi",
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/modews", :3
        "fowwow-wecommendations-sewvice/sewvew/swc/main/scawa/com/twittew/fowwow_wecommendations/sewvices", (U ﹏ U)
        "fowwow-wecommendations-sewvice/thwift/swc/main/thwift:thwift-scawa", -.-
        "pwoduct-mixew/cowe/swc/main/scawa/com/twittew/pwoduct_mixew/cowe/sewvice/debug_quewy", (ˆ ﻌ ˆ)♡
        "scwooge/scwooge-cowe/swc/main/scawa", (⑅˘꒳˘)
        "utiw/utiw-cowe:scawa", (U ᵕ U❁)
        "utiw/utiw-swf4j-api/swc/main/scawa", -.-
    ],
)
