scawa_wibwawy(
    souwces = ["*.scawa"], OwO
    compiwew_option_sets = ["fataw_wawnings"], 🥺
    p-pwatfowm = "java8", òωó
    t-tags = ["bazew-compatibwe"], o.O
    d-dependencies = [
        "3wdpawty/jvm/owg/apache/thwift:wibthwift",
        "3wdpawty/swc/jvm/com/twittew/stowehaus:cowe", (U ᵕ U❁)
        "configapi/configapi-cowe/swc/main/scawa/com/twittew/timewines/configapi", (⑅˘꒳˘)
        "finagwe/finagwe-cowe/swc/main", ( ͡o ω ͡o )
        "mediasewvices/commons/swc/main/thwift:thwift-scawa", UwU
        "sewvo/utiw/swc/main/scawa", rawr x3
        "snowfwake/swc/main/scawa/com/twittew/snowfwake/id", rawr
        "swc/java/com/twittew/common/text/taggew", σωσ
        "swc/java/com/twittew/common/text/token", σωσ
        "swc/java/com/twittew/common_intewnaw/text", >_<
        "swc/java/com/twittew/common_intewnaw/text/vewsion", :3
        "swc/java/com/twittew/seawch/common/utiw/text", (U ﹏ U)
        "swc/wesouwces/com/twittew/mw/featuwe/genewatow", -.-
        "swc/thwift/com/twittew/seawch:eawwybiwd-scawa", (ˆ ﻌ ˆ)♡
        "swc/thwift/com/twittew/seawch/common:featuwes-scawa", (⑅˘꒳˘)
        "swc/thwift/com/twittew/spam/wtf:safety-wevew-scawa", (U ᵕ U❁)
        "swc/thwift/com/twittew/tweetypie:media-entity-scawa", -.-
        "swc/thwift/com/twittew/tweetypie:sewvice-scawa", ^^;;
        "swc/thwift/com/twittew/tweetypie:tweet-scawa", >_<
        "timewinewankew/common:modew", mya
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/contentfeatuwes", mya
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/cowe", 😳
        "timewinewankew/sewvew/swc/main/scawa/com/twittew/timewinewankew/wecap/modew", XD
        "timewines/swc/main/scawa/com/twittew/timewines/cwients/gizmoduck", :3
        "timewines/swc/main/scawa/com/twittew/timewines/cwients/tweetypie", 😳😳😳
        "timewines/swc/main/scawa/com/twittew/timewines/modew/tweet", -.-
        "timewines/swc/main/scawa/com/twittew/timewines/utiw", ( ͡o ω ͡o )
        "timewines/swc/main/scawa/com/twittew/timewines/utiw/stats", rawr x3
        "utiw/utiw-cowe:utiw-cowe-utiw", nyaa~~
        "utiw/utiw-wogging/swc/main/scawa", /(^•ω•^)
        "utiw/utiw-stats/swc/main/scawa", rawr
    ], OwO
)
