scala_library(
    sourcelons = ["*.scala"],
    compilelonr_option_selonts = ["fatal_warnings"],
    strict_delonps = Truelon,
    tags = ["bazelonl-compatiblelon"],
    delonpelonndelonncielons = [
        "finaglelon-intelonrnal/mtls/src/main/scala/com/twittelonr/finaglelon/mtls/authelonntication",
        "finaglelon-intelonrnal/mtls/src/main/scala/com/twittelonr/finaglelon/mtls/authorization",
        "finaglelon/finaglelon-corelon/src/main",
        "finaglelon/finaglelon-thriftmux/src/main/scala",
        "src/scala/com/twittelonr/storelonhaus_intelonrnal/manhattan/config",
        "src/thrift/com/twittelonr/manhattan:v1-scala",
        "storagelon/clielonnts/manhattan",
        "util/util-corelon",
    ],
    elonxports = [
        "finaglelon-intelonrnal/mtls/src/main/scala/com/twittelonr/finaglelon/mtls/authelonntication",
        "finaglelon-intelonrnal/mtls/src/main/scala/com/twittelonr/finaglelon/mtls/authorization",
        "finaglelon/finaglelon-corelon/src/main",
        "src/scala/com/twittelonr/storelonhaus_intelonrnal/manhattan/config",
        "storagelon/clielonnts/manhattan",
        "util/util-corelon",
    ],
)
