java_library(
    sources = ["*.java"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "src/java/com/X/search/common/schema/earlybird",
        "src/thrift/com/X/search:earlybird-java",
    ],
)
