scala_library(
    compiler_option_sets = ["fatal_warnings"],
    platform = "java8",
    tags = ["bazel-compatible"],
    dependencies = [
        "configapi/configapi-core",
        "follow-recommendations-service/common/src/main/scala/com/twitter/follow_recommendations/common/base",
        "follow-recommendations-service/common/src/main/scala/com/twitter/follow_recommendations/common/models",
        "follow-recommendations-service/server/src/main/scala/com/twitter/follow_recommendations/models",
        "follow-recommendations-service/thrift/src/main/thrift:thrift-scala",
    ],
)
